Repository sofa-framework/sofa, pull requests merged in 2018-03, with the labels that each got.

#594 [SofaDistanceGrid] ADD .scene-tests to ignore scene
  applications/plugins/SofaDistanceGrid/examples/.scene-tests
  examples/.scene-tests
  scripts/ci/configure.sh
Labels: location: plugins, pr: fast-merge, pr: fix, status: ready

#599 [runSofa] Fix compilation when SofaGuiQt is not activated
  applications/projects/runSofa/Main.cpp
  applications/sofa/gui/GuiDataRepository.cpp
  applications/sofa/gui/GuiDataRepository.h
  applications/sofa/gui/SofaGuiCommon/CMakeLists.txt
  applications/sofa/gui/qt/CMakeLists.txt
  applications/sofa/gui/qt/RealGUI.cpp
  applications/sofa/gui/qt/panels/QDocBrowser.cpp
Labels: pr: fix, status: ready

#538 [runSofa] Experimental : Headless recorder
  SofaGui/CMakeLists.txt
  SofaGui/SofaGuiConfig.cmake.in
  SofaGui/config.h.in
  applications/projects/runSofa/Main.cpp
  applications/sofa/gui/Main.cpp
  applications/sofa/gui/headlessRecorder/CMakeLists.txt
  applications/sofa/gui/headlessRecorder/HeadlessRecorder.cpp
  applications/sofa/gui/headlessRecorder/HeadlessRecorder.h
  applications/sofa/gui/headlessRecorder/README.md
  applications/sofa/gui/headlessRecorder/headlessRecorder_test
  cmake/Modules/FindFFMPEG.cmake
  examples/Demos/caduceus.scn
  scripts/ci/configure.sh
Labels: discussion, experimental, status: ready

#604 [extlibs/gtest] Update gtest & clean the CMakeLists.txt
  SofaKernel/framework/framework_test/CMakeLists.txt
  SofaKernel/framework/framework_test/testing/TestMessageHandler_test.cpp
  extlibs/gtest/CMakeLists.txt
  extlibs/gtest/GTestConfig.cmake.in
  extlibs/gtest/README.md
  extlibs/gtest/cmake/internal_utils.cmake
  extlibs/gtest/include/gtest/gtest-death-test.h
  extlibs/gtest/include/gtest/gtest-message.h
  extlibs/gtest/include/gtest/gtest-param-test.h
  extlibs/gtest/include/gtest/gtest-param-test.h.pump
  extlibs/gtest/include/gtest/gtest-printers.h
  extlibs/gtest/include/gtest/gtest-spi.h
  extlibs/gtest/include/gtest/gtest-typed-test.h
  extlibs/gtest/include/gtest/gtest.h
  extlibs/gtest/include/gtest/gtest_pred_impl.h
  extlibs/gtest/include/gtest/gtest_prod.h
  extlibs/gtest/include/gtest/internal/custom/gtest-port.h
  extlibs/gtest/include/gtest/internal/custom/gtest.h
  extlibs/gtest/include/gtest/internal/gtest-death-test-internal.h
  extlibs/gtest/include/gtest/internal/gtest-filepath.h
  extlibs/gtest/include/gtest/internal/gtest-internal.h
  extlibs/gtest/include/gtest/internal/gtest-param-util-generated.h
  extlibs/gtest/include/gtest/internal/gtest-param-util-generated.h.pump
  extlibs/gtest/include/gtest/internal/gtest-param-util.h
  extlibs/gtest/include/gtest/internal/gtest-port-arch.h
  extlibs/gtest/include/gtest/internal/gtest-port.h
  extlibs/gtest/include/gtest/internal/gtest-string.h
  extlibs/gtest/src/gtest-death-test.cc
  extlibs/gtest/src/gtest-filepath.cc
  extlibs/gtest/src/gtest-internal-inl.h
  extlibs/gtest/src/gtest-port.cc
  extlibs/gtest/src/gtest-printers.cc
  extlibs/gtest/src/gtest-test-part.cc
  extlibs/gtest/src/gtest-typed-test.cc
  extlibs/gtest/src/gtest.cc
  extlibs/gtest/src/gtest_main.cc
Labels: pr: fast-merge, pr: fix, status: ready

#595 [CImgPlugin] Export CImg_CFLAGS
  applications/plugins/CImgPlugin/CMakeLists.txt
Labels: location: plugins, pr: fix, status: ready

#608 [HeadlessRecorder] Handle errors in target config
  SofaGui/CMakeLists.txt
  applications/sofa/gui/headlessRecorder/CMakeLists.txt
  scripts/ci/configure.sh
Labels: location: plugins, pr: clean, status: ready

#607 [CImgPlugin] Less scary config warnings
  applications/plugins/CImgPlugin/CMakeLists.txt
Labels: location: plugins, pr: clean, pr: fast-merge, status: ready

#617 More robust method to test end of string
  SofaKernel/framework/sofa/helper/system/PluginManager.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#611 [CI] Ignore some scenes in scene tests
  applications/projects/CMakeLists.txt
  scripts/ci/configure.sh
  scripts/ci/scene-tests.sh
Labels: location: scripts, pr: clean, project: CI, status: ready
