Repository sofa-framework/sofa, pull requests merged in 2018-12, with the labels that each got.

#798 [SofaBaseMechanics] Optimize barycentric mapping initialization
  SofaKernel/modules/SofaBaseMechanics/BarycentricMappers/BarycentricMapperTopologyContainer.h
  SofaKernel/modules/SofaBaseMechanics/BarycentricMappers/BarycentricMapperTopologyContainer.inl
  SofaKernel/modules/SofaBaseMechanics/BarycentricMappers/BarycentricMapperTriangleSetTopology.h
  SofaKernel/modules/SofaBaseMechanics/BarycentricMappers/BarycentricMapperTriangleSetTopology.inl
  SofaKernel/modules/SofaBaseMechanics/BarycentricMapping.inl
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/BarycentricMapping_test.cpp
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/CMakeLists.txt
Labels: enhancement, status: ready

#839 [CollisionModel] TriangleModel optimization when topology changes occur
  SofaKernel/modules/SofaMeshCollision/TriangleModel.inl
Labels: enhancement, status: ready

#844 [SofaBaseLinearSolver] CLEAN GraphScatteredTypes
  SofaKernel/modules/SofaBaseLinearSolver/GraphScatteredTypes.cpp
  SofaKernel/modules/SofaBaseLinearSolver/GraphScatteredTypes.h
Labels: pr: clean, status: ready

#848 [DeformableOnRigidFrameMapping] Clean the component
  modules/SofaMiscMapping/DeformableOnRigidFrameMapping.h
  modules/SofaMiscMapping/DeformableOnRigidFrameMapping.inl
Labels: pr: clean, status: ready

#851 CLEAN: removing unused PS3 files
  SofaKernel/framework/sofa/core/ps3/cxa_demangle.cpp
  SofaKernel/framework/sofa/core/ps3/cxa_demangle.h
  SofaKernel/framework/sofa/core/ps3/cxxabi.h
  SofaKernel/framework/sofa/helper/gl/ps3gl_compat.cpp
  SofaKernel/framework/sofa/helper/gl/ps3gl_compat.h
Labels: pr: clean, pr: fast-merge, status: ready

#852 [SofaGeneralEngine] Fix to prepare automatic removal of SOFA_FLOAT
  modules/SofaGeneralEngine/SphereROI.inl
Labels: pr: fast-merge, status: ready

#846 [SofaGeneralSimpleFEM] Clean BeamFemForceField
  modules/SofaGeneralSimpleFem/BeamFEMForceField.cpp
  modules/SofaGeneralSimpleFem/BeamFEMForceField.h
  modules/SofaGeneralSimpleFem/BeamFEMForceField.inl
Labels: pr: clean, status: ready

#847 [SofaBaseCollision] CLEAN CylinderModel
  SofaKernel/modules/SofaBaseCollision/CylinderModel.cpp
  SofaKernel/modules/SofaBaseCollision/CylinderModel.h
  SofaKernel/modules/SofaBaseCollision/CylinderModel.inl
Labels: pr: clean, status: ready

#849 [All] Remove SOFA_SUPPORT_MOVING_FRAMES and SOFA_SUPPORT_MULTIRESOLUTION
  SofaKernel/framework/sofa/core/objectmodel/BaseContext.cpp
  SofaKernel/framework/sofa/core/objectmodel/BaseContext.h
  SofaKernel/framework/sofa/core/objectmodel/Context.cpp
  SofaKernel/framework/sofa/core/objectmodel/Context.h
  SofaKernel/framework/sofa/simulation/VisualVisitor.cpp
  SofaKernel/modules/SofaBaseMechanics/DiagonalMass.inl
  SofaKernel/modules/SofaBaseMechanics/UniformMass.inl
  applications/plugins/SofaMiscCollision/DefaultCollisionGroupManager.cpp
  applications/plugins/SofaMiscCollision/DefaultCollisionGroupManager.h
  applications/plugins/SofaSimpleGUI/VisualPickVisitor.cpp
  applications/sofa/gui/ColourPickingVisitor.cpp
  modules/SofaGeneralSimpleFem/HexahedronFEMForceFieldAndMass.inl
  modules/SofaMiscForceField/MatrixMass.inl
  modules/SofaMiscForceField/MeshMatrixMass.inl
Labels: pr: clean, status: ready

#854 [SofaConstraint] allow call of constraints' storeLambda()
  modules/SofaConstraint/ConstraintStoreLambdaVisitor.cpp
  modules/SofaConstraint/ConstraintStoreLambdaVisitor.h
Labels: enhancement, status: ready

#856 [SofaConstraint] CLEAN GenericConstraintSolver
  modules/SofaConstraint/GenericConstraintSolver.cpp
  modules/SofaConstraint/GenericConstraintSolver.h
Labels: pr: clean, status: to review

#870 [SofaFramework] Keep SOFA_EXTERN_TEMPLATE macro definition
  SofaKernel/SofaFramework/config.h.in
Labels: pr: fast-merge, pr: fix, status: to review

#855 [BaseTopology] SparseGrid and SparseGridRamification cleanup
  SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp
  SofaKernel/modules/SofaBaseTopology/SparseGridTopology.h
  examples/Components/engine/MergePoints.scn
  examples/Components/engine/SubsetTopology_refiningMesh.scn
  examples/Components/topology/SparseGridRamificationTopology.scn
  examples/Components/topology/SparseGridTopology.scn
  examples/RegressionStateScenes.regression-tests
  modules/SofaNonUniformFem/SparseGridMultipleTopology.cpp
  modules/SofaNonUniformFem/SparseGridRamificationTopology.cpp
Labels: pr: clean, status: ready

#862 [SofaKernel] use string in base object description.
  SofaKernel/framework/sofa/core/behavior/PairInteractionConstraint.h
  SofaKernel/framework/sofa/core/behavior/PairInteractionForceField.h
  SofaKernel/framework/sofa/core/behavior/PairInteractionProjectiveConstraintSet.h
  SofaKernel/framework/sofa/core/objectmodel/BaseObjectDescription.cpp
  SofaKernel/framework/sofa/core/objectmodel/BaseObjectDescription.h
  SofaKernel/framework/sofa/simulation/Node.cpp
  SofaKernel/modules/SofaSimulationCommon/xml/AttributeElement.cpp
  SofaKernel/modules/SofaSimulationCommon/xml/ObjectElement.cpp
  SofaKernel/modules/SofaSimulationGraph/SimpleApi.cpp
  applications/plugins/SofaPython/Binding_BaseContext.cpp
  applications/projects/Modeler/lib/GraphModeler.cpp
  applications/projects/Modeler/lib/SofaModeler.cpp
Labels: enhancement, status: ready

#859 [SofaMacros] ADD CMake macro to create pybind11 & cython targets and modules
  SofaKernel/SofaFramework/SofaMacros.cmake
Labels: pr: fast-merge, status: ready

#868 [Python_Binding] ADD binding python to getCategories
  applications/plugins/SofaPython/Binding_SofaModule.cpp
Labels: location: plugins, status: ready

#865 [all] cosmetic cleaning.
  SofaKernel/framework/sofa/core/BaseMapping.cpp
  SofaKernel/framework/sofa/core/BaseMapping.h
  SofaKernel/framework/sofa/core/MultiMapping.inl
  SofaKernel/framework/sofa/core/SofaLibrary.cpp
  SofaKernel/framework/sofa/helper/ComponentChange.h
  applications/plugins/ColladaSceneLoader/SceneColladaLoader.cpp
  applications/plugins/SofaTest/Elasticity_test.inl
Labels: pr: clean, status: ready
