Repository sofa-framework/sofa, pull requests merged in 2018-09, with the labels that each got.

#763 [SofaKernel] Fix: correct path writing in sofa_set_python_directory macro
  SofaKernel/SofaFramework/SofaMacros.cmake
Labels: pr: fast-merge, pr: fix, project: SofaPython, status: ready

#761 [Geomagic] Fix broken behavior
  applications/plugins/Geomagic/src/GeomagicDriver.cpp
  applications/plugins/Geomagic/src/GeomagicDriver.h
Labels: location: plugins, pr: fix, status: ready

#766 [SofaKernel][cmake] FIX: cyclic recursion in cmake configuration
  SofaKernel/SofaFramework/SofaMacros.cmake
Labels: pr: fix, status: ready

#764 [SofaKernel] Move ScriptEvent class from SofaPython to core/objectModel
  SofaKernel/framework/sofa/core/CMakeLists.txt
  SofaKernel/framework/sofa/core/objectmodel/ScriptEvent.cpp
  SofaKernel/framework/sofa/core/objectmodel/ScriptEvent.h
  applications/plugins/SofaPython/CMakeLists.txt
  applications/plugins/SofaPython/PythonScriptEvent.h
  applications/plugins/SofaPython/ScriptController.h
  applications/plugins/SofaPython/ScriptDataEngine.h
Labels: refactoring, status: ready

#762 [SofaPython] ADD a custom __dir__ method in Binding_Base.
  applications/plugins/SofaPython/Binding_Base.cpp
  applications/plugins/SofaPython/SofaPython_test/python/test_BindingBaseObject.py
Labels: enhancement, project: SofaPython, status: ready

#399 [SofaKernel] FIX bug in toEulerVector
  SofaKernel/framework/framework_test/helper/Quater_test.cpp
  SofaKernel/framework/sofa/helper/Quater.inl
Labels: pr: fix, status: ready

#722 [SofaGui] ADD option to enable VSync (default: OFF)
  SofaGui/CMakeLists.txt
  SofaGui/config.h.in
  applications/sofa/gui/qt/viewer/qgl/QtGLViewer.cpp
  applications/sofa/gui/qt/viewer/qt/QtViewer.cpp
Labels: pr: fix, status: ready

#738 [all] Fix some C4661 warnings
  SofaKernel/framework/sofa/core/Mapping.cpp
  SofaKernel/framework/sofa/core/Mapping.h
  SofaKernel/framework/sofa/core/MultiMapping.cpp
  SofaKernel/framework/sofa/core/MultiMapping.h
  SofaKernel/modules/SofaBaseTopology/EdgeSetGeometryAlgorithms.cpp
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyAlgorithms.cpp
  SofaKernel/modules/SofaBaseTopology/HexahedronSetGeometryAlgorithms.cpp
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyAlgorithms.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetGeometryAlgorithms.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyAlgorithms.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetGeometryAlgorithms.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyAlgorithms.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyAlgorithms.h
  applications/plugins/Compliant/compliance/DampingCompliance.cpp
  applications/plugins/Compliant/compliance/DampingCompliance.h
  applications/plugins/Compliant/compliance/DiagonalCompliance.cpp
  applications/plugins/Compliant/compliance/DiagonalCompliance.h
  applications/plugins/Compliant/compliance/FullCompliance.cpp
  applications/plugins/Compliant/compliance/FullCompliance.h
  applications/plugins/Compliant/compliance/LinearDiagonalCompliance.cpp
  applications/plugins/Compliant/compliance/LinearDiagonalCompliance.h
  applications/plugins/Compliant/compliance/UniformCompliance.cpp
  applications/plugins/Compliant/compliance/UniformCompliance.h
  applications/plugins/Compliant/mapping/ProjectionMapping.cpp
  applications/plugins/Compliant/mapping/ProjectionMapping.h
  applications/plugins/Compliant/mapping/RigidRestJointMapping.cpp
  applications/plugins/Compliant/mapping/RigidRestJointMapping.h
  modules/SofaBoundaryCondition/FixedConstraint.cpp
  modules/SofaBoundaryCondition/FixedConstraint.h
Labels: pr: clean, status: ready

#759 [SofaMacros] Improve external dirs fetching
  SofaKernel/SofaFramework/SofaMacros.cmake
Labels: enhancement, status: ready

#773 [Tutorials] FIX oneTetrahedron and chainHybrid
  applications/plugins/SceneCreator/SceneCreator.cpp
  applications/tutorials/CMakeLists.txt
  applications/tutorials/chainHybrid/CMakeLists.txt
  applications/tutorials/chainHybrid/chainHybrid.cpp
  applications/tutorials/oneTetrahedron/oneTetrahedron.cpp
Labels: pr: fix, status: ready

#778 [VisualModel] Improve the messages when loading mesh inside VisualModel
  SofaKernel/modules/SofaBaseVisual/VisualModelImpl.cpp
  modules/SofaExporter/SofaExporter_test/STLExporter_test.cpp
Labels: enhancement, pr: fast-merge, status: ready

#770 [MultiThreading] Add Image plugin Data types in DataExchange component
  applications/plugins/CMakeLists.txt
  applications/plugins/MultiThreading/CMakeLists.txt
  applications/plugins/MultiThreading/config.h.in
  applications/plugins/MultiThreading/src/DataExchange.cpp
  applications/plugins/image/CMakeLists.txt
  applications/plugins/image/ImageTypes.cpp
  applications/plugins/image/Kinect.h
  applications/plugins/image/config.h.in
  applications/plugins/image/examples/loadimage_mt.scn
Labels: enhancement, location: plugins, status: ready

#781 [SofaCarving] Modify the CMake config file to allow other plugins link to Sofa Carving
  applications/plugins/SofaCarving/CMakeLists.txt
  applications/plugins/SofaCarving/SofaCarvingConfig.cmake.in
Labels: pr: fix, status: ready
