Repository sofa-framework/sofa, pull requests merged in 2018-04, with the labels that each got.

#618 [SofaFramework] FIX Boost::program_options finding in install
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
Labels: pr: backport, pr: fix, status: ready

#613 [runSofa] ADD infinite iterations option to batch gui
  applications/sofa/gui/BatchGUI.cpp
  applications/sofa/gui/BatchGUI.h
Labels: location: project, pr: fix, status: ready

#621 [SofaHelper] PluginManager now checks for file existence instead of library extension match.
  SofaKernel/framework/framework_test/helper/system/FileSystem_test.cpp
  SofaKernel/framework/sofa/helper/system/FileSystem.cpp
  SofaKernel/framework/sofa/helper/system/FileSystem.h
  SofaKernel/framework/sofa/helper/system/PluginManager.cpp
Labels: enhancement, status: ready

#609 [CImgPlugin] FIX CMakeLists install fail since pluginization
  applications/plugins/CImgPlugin/CMakeLists.txt
  applications/plugins/SofaDistanceGrid/CMakeLists.txt
  applications/plugins/SofaDistanceGrid/config.h
  applications/plugins/SofaImplicitField/CMakeLists.txt
  applications/plugins/SofaImplicitField/config.h
Labels: pr: fix, status: ready

#622 [CImgPlugin] FIX malformed cflag append
  applications/plugins/CImgPlugin/CMakeLists.txt
Labels: location: plugins, pr: fast-merge, pr: fix, status: ready

#619 [scripts/ci] FIX ignore-scenes-with-deprecated-components triggering
  scripts/ci/scene-tests.sh
Labels: location: scripts, pr: fast-merge, pr: fix, status: ready

#615 [Headless Recorder] ADD frameskip option to headless recorder
  applications/sofa/gui/headlessRecorder/HeadlessRecorder.cpp
  applications/sofa/gui/headlessRecorder/HeadlessRecorder.h
Labels: enhancement, location: plugins, status: ready

#626 [MultiThreading] FIX: add createSubelements param in MeshGmshLoader
  applications/plugins/MultiThreading/examples/TriangularForceFieldComparison.scn
Labels: pr: fast-merge, pr: fix, status: ready

#628 [examples] FIX missing RequiredPlugin
  examples/Components/collision/SpatialGridPointModel.scn
  examples/Components/forcefield/ParticlesRepulsionForceField.scn
  examples/Components/forcefield/SPHFluidForceField.scn
  examples/Components/mapping/SPHFluidSurfaceMapping.scn
  examples/Components/visualmodel/PointSplatModel.scn
Labels: pr: fast-merge, pr: fix, status: ready

#630 [All] FIX VS2017 build (Windows)
  SofaKernel/modules/SofaBaseCollision/DiscreteIntersection.cpp
  SofaKernel/modules/SofaBaseCollision/MinProximityIntersection.cpp
  SofaKernel/modules/SofaBaseCollision/NewProximityIntersection.cpp
  applications/sofa/gui/qt/DataWidget.cpp
  applications/sofa/gui/qt/DataWidget.h
  modules/SofaConstraint/LocalMinDistance.cpp
  modules/SofaUserInteraction/ComponentMouseInteraction.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#634 [SofaComponent] Fix computeBBox()
  SofaKernel/modules/SofaEngine/BoxROI.inl
  modules/SofaBoundaryCondition/PlaneForceField.inl
  modules/SofaGeneralEngine/SubsetTopology.inl
Labels: pr: fix, status: ready

#627 [SofaKernel] FIX Bug in BoxROI that is not properly initialized
  SofaKernel/modules/SofaEngine/BoxROI.inl
Labels: pr: fix, status: ready

#644 [CI] ADD output on scene-test crash
  scripts/ci/scene-tests.sh
Labels: enhancement, pr: fast-merge, project: CI, status: ready

#645 [SofaFramework] Fix plugin list configuration
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/SofaFramework/SofaMacros.cmake
Labels: pr: fast-merge, pr: fix, status: ready
