Repository sofa-framework/sofa, pull requests merged in 2018-11, with the labels that each got.

#780 [SofaConstraint]: add a force data field in SlidingConstraint
  modules/SofaConstraint/SlidingConstraint.h
  modules/SofaConstraint/SlidingConstraint.inl
Labels: enhancement, status: ready

#817 clean handleTopologyChange
  modules/SofaMiscFem/BaseMaterial.h
Labels: pr: clean, status: ready

#831 [STC6] CLEAN
  SofaKernel/framework/sofa/core/objectmodel/BaseData.cpp
  SofaKernel/framework/sofa/core/objectmodel/BaseLink.cpp
  SofaKernel/framework/sofa/core/objectmodel/BaseObject.cpp
  SofaKernel/framework/sofa/simulation/AnimateVisitor.cpp
  SofaKernel/framework/sofa/simulation/MechanicalOperations.cpp
  SofaKernel/framework/sofa/simulation/MechanicalVisitor.cpp
  SofaKernel/framework/sofa/simulation/MechanicalVisitor.h
  SofaKernel/framework/sofa/simulation/ParallelMechanicalVisitor.cpp
  SofaKernel/framework/sofa/simulation/ParallelMechanicalVisitor.h
  SofaKernel/modules/SofaBaseMechanics/UniformMass.inl
  SofaKernel/modules/SofaSimpleFem/HexahedronFEMForceField.cpp
  SofaKernel/modules/SofaSimpleFem/HexahedronFEMForceField.h
  SofaKernel/modules/SofaSimpleFem/HexahedronFEMForceField.inl
  SofaKernel/modules/SofaSimpleFem/TetrahedronDiffusionFEMForceField.inl
  SofaKernel/modules/SofaSimpleFem/TetrahedronFEMForceField.h
  SofaKernel/modules/SofaSimpleFem/TetrahedronFEMForceField.inl
  SofaKernel/modules/SofaSimpleFem/initSimpleFEM.cpp
  SofaKernel/modules/SofaSimpleFem/initSimpleFEM.h
  modules/SofaGeneralEngine/CMakeLists.txt
  modules/SofaGeneralEngine/ComplementaryROI.cpp
  modules/SofaGeneralEngine/ComplementaryROI.h
  modules/SofaGeneralEngine/SofaGeneralEngine_test/CMakeLists.txt
Labels: STC#6, status: to review

#803 [SofaBoundaryCondition] Refactor FixedPlaneConstraint (breaking)
  applications/plugins/SofaTest/Elasticity_test.inl
  modules/SofaBoundaryCondition/FixedPlaneConstraint.cpp
  modules/SofaBoundaryCondition/FixedPlaneConstraint.h
  modules/SofaBoundaryCondition/FixedPlaneConstraint.inl
Labels: pr: breaking, pr: clean, pr: fix, refactoring, status: ready

#805 [Multithreading] Move TaskScheduler files from MultiThreading plugin to SofaKernel. TaskScheduler Tests included
  SofaKernel/framework/framework_test/CMakeLists.txt
  SofaKernel/framework/framework_test/simulation/TaskSchedulerTestTasks.cpp
  SofaKernel/framework/framework_test/simulation/TaskSchedulerTestTasks.h
  SofaKernel/framework/framework_test/simulation/TaskSchedulerTests.cpp
  SofaKernel/framework/sofa/simulation/CMakeLists.txt
  SofaKernel/framework/sofa/simulation/DefaultTaskScheduler.cpp
  SofaKernel/framework/sofa/simulation/DefaultTaskScheduler.h
  SofaKernel/framework/sofa/simulation/InitTasks.cpp
  SofaKernel/framework/sofa/simulation/InitTasks.h
  SofaKernel/framework/sofa/simulation/Locks.h
  SofaKernel/framework/sofa/simulation/Task.cpp
  SofaKernel/framework/sofa/simulation/Task.h
  SofaKernel/framework/sofa/simulation/TaskScheduler.cpp
  SofaKernel/framework/sofa/simulation/TaskScheduler.h
  SofaKernel/framework/sofa/simulation/VisitorAsync.h
  applications/plugins/MultiThreading/CMakeLists.txt
  applications/plugins/MultiThreading/src/AnimationLoopParallelScheduler.cpp
  applications/plugins/MultiThreading/src/AnimationLoopTasks.h
  applications/plugins/MultiThreading/src/BeamLinearMapping_mt.h
  applications/plugins/MultiThreading/src/BeamLinearMapping_mt.inl
  applications/plugins/MultiThreading/test/CMakeLists.txt
Labels: pr: clean, status: ready

#822 [DataUpdates][BREAKING] Rename: data tracker has changed
  SofaKernel/framework/framework_test/core/DataEngine_test.cpp
  SofaKernel/framework/sofa/core/DataTracker.cpp
  SofaKernel/framework/sofa/core/DataTracker.h
  SofaKernel/modules/SofaBaseMechanics/DiagonalMass.inl
  SofaKernel/modules/SofaBaseMechanics/UniformMass.inl
  SofaKernel/modules/sofa/frameworkextra/frameworkextra_test/core/TrackedData_test.cpp
  applications/plugins/image/CollisionToCarvingEngine.h
  applications/plugins/image/ImageFilter.h
  modules/SofaGeneralEngine/ShapeMatching.inl
  modules/SofaMiscForceField/MeshMatrixMass.inl
Labels: STC#6, enhancement, pr: breaking, status: ready

#830 [SofaHelper] EDIT FileSystem and FileRepository for regression tests
  SofaKernel/framework/sofa/helper/Utils.h
  SofaKernel/framework/sofa/helper/system/FileRepository.cpp
  SofaKernel/framework/sofa/helper/system/FileRepository.h
  SofaKernel/framework/sofa/helper/system/FileSystem.cpp
  SofaKernel/framework/sofa/helper/system/FileSystem.h
  SofaKernel/framework/sofa/helper/system/SetDirectory.h
  applications/plugins/SofaTest/SofaTest_test/CMakeLists.txt
  applications/plugins/SofaTest/SofaTest_test/Regression_test.cpp
  applications/plugins/SofaTest/SofaTest_test/Regression_test.h
  applications/plugins/SofaTest/SofaTest_test/regression/gravity.scn
  applications/plugins/SofaTest/SofaTest_test/regression/gravity.scn.reference
  applications/plugins/SofaTest/SofaTest_test/regression/gravity.scn.reference_0_dof_mstate.txt.gz
  applications/plugins/SofaTest/SofaTest_test/regression/list.txt
  applications/projects/Modeler/exec/Main.cpp
  applications/projects/runSofa/Main.cpp
  applications/projects/sofaVerification/CMakeLists.txt
  applications/projects/sofaVerification/README.txt
  applications/projects/sofaVerification/runVerification.sh
  applications/projects/sofaVerification/sofaVerification.cpp
  applications/projects/sofaVerification/verification.ini
  applications/sofa/gui/BaseViewer.cpp
  applications/sofa/gui/GUIManager.cpp
  applications/sofa/gui/GuiDataRepository.cpp
  examples/Components/collision/FFDDistanceGridCollisionModel.scn.view
  examples/Components/collision/RuleBasedContactManager.scn
  examples/Components/constraint/BilateralInteractionConstraint.scn
  examples/Components/constraint/FrictionContact.scn
  examples/Components/forcefield/BeamFEMForceField.scn
  examples/Components/topology/Tetra2TriangleTopologicalMapping.scn
  examples/Components/topology/TopologicalModifiers/RemovingTrianglesProcess.scn
  examples/Components/topology/TopologicalModifiers/RemovingTrianglesProcess.txt
  examples/Demos/TriangleSurfaceCutting.scn
  examples/Demos/caduceus.scn
  examples/Demos/collisionMultiple.scn
  examples/RegressionStateScenes.regression-tests
  examples/RegressionTopologyScenes.regression-tests
  tools/SofaGTestMain/SofaGTestMainConfig.cmake.in
Labels: STC#6, enhancement, status: ready

#824 [SofaBoundaryCondition] FIX AffineMovementConstraint orientation issue
  modules/SofaBoundaryCondition/AffineMovementConstraint.cpp
  modules/SofaBoundaryCondition/AffineMovementConstraint.h
  modules/SofaBoundaryCondition/AffineMovementConstraint.inl
Labels: STC#6, pr: fix, status: ready

#827 [SofaCore] FIX: enable ExtVecXf mappings with double floating type
  SofaKernel/framework/sofa/core/Mapping.cpp
  SofaKernel/framework/sofa/core/Mapping.h
  SofaKernel/framework/sofa/core/MultiMapping.h
Labels: pr: fast-merge, pr: fix, status: ready

#832 [SofaBaseMechanics] FIX DiagonalMass_test
  SofaKernel/modules/SofaBaseMechanics/DiagonalMass.inl
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/DiagonalMass_test.cpp
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/MechanicalObject_test.cpp
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/UniformMass_test.cpp
  SofaKernel/modules/SofaSimulationGraph/SimpleApi.cpp
  SofaKernel/modules/SofaSimulationGraph/SimpleApi.h
  applications/plugins/SofaTest/Sofa_test.cpp
  tools/SofaGTestMain/SofaGTestMain.cpp
Labels: pr: fix, status: ready

#838 [Topology] Topology change propagation to Mechanical State
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyModifier.cpp
Labels: enhancement, status: ready

#841 [SofaFramework] Various cleaning (non-breaking)
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/SofaFramework/build_option_bbox.h.in
  SofaKernel/SofaFramework/config.h.in
  SofaKernel/framework/sofa/simulation/DefaultAnimationLoop.cpp
  modules/SofaConstraint/ConstraintAnimationLoop.cpp
  modules/SofaConstraint/FreeMotionAnimationLoop.cpp
  modules/SofaGeneralAnimationLoop/MultiStepAnimationLoop.cpp
  modules/SofaGeneralAnimationLoop/MultiTagAnimationLoop.cpp
Labels: pr: clean, status: ready

#843 [SofaPython] add getLinkedBase to the binding of a link.
  applications/plugins/SofaPython/Binding_Link.cpp
Labels: enhancement, status: ready
