Repository sofa-framework/sofa, pull requests merged in 2018-07, with the labels that each got.

#693 [all] CLEAN topology classes
  SofaKernel/framework/sofa/core/topology/BaseMeshTopology.h
  SofaKernel/modules/SofaBaseMechanics/BarycentricMapping.inl
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/GridTopology.cpp
  SofaKernel/modules/SofaBaseTopology/GridTopology.h
  SofaKernel/modules/SofaBaseTopology/MeshTopology.cpp
  SofaKernel/modules/SofaBaseTopology/MeshTopology.h
  SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp
  SofaKernel/modules/SofaBaseTopology/SparseGridTopology.h
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyModifier.cpp
  SofaKernel/modules/SofaDeformable/MeshSpringForceField.inl
  SofaKernel/modules/SofaSimpleFem/HexahedronFEMForceField.h
  SofaKernel/modules/SofaSimpleFem/HexahedronFEMForceField.inl
  SofaKernel/modules/SofaSimpleFem/TetrahedronFEMForceField.inl
  applications/plugins/InvertibleFVM/InvertibleFVMForceField.inl
  applications/plugins/PersistentContact/PersistentContactBarycentricMapping.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping-3f.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping-3f1-3f.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping-3f1.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping.inl
  applications/plugins/SofaDistanceGrid/components/collision/DistanceGridCollisionModel.cpp
  modules/SofaGeneralEngine/MeshBarycentricMapperEngine.inl
  modules/SofaGeneralSimpleFem/HexahedralFEMForceFieldAndMass.inl
  modules/SofaGeneralSimpleFem/HexahedronFEMForceFieldAndMass.inl
  modules/SofaNonUniformFem/HexahedronCompositeFEMForceFieldAndMass.h
  modules/SofaNonUniformFem/NonUniformHexahedronFEMForceFieldAndMass.h
  modules/SofaNonUniformFem/NonUniformHexahedronFEMForceFieldAndMass.inl
  modules/SofaTopologyMapping/Hexa2TetraTopologicalMapping.cpp
Labels: STC#5, pr: clean, status: ready

#691 [SofaKernel] Remove unused function "renumberConstraintId"
  SofaKernel/framework/sofa/core/behavior/BaseMechanicalState.h
  SofaKernel/framework/sofa/simulation/MechanicalVisitor.h
  SofaKernel/modules/SofaBaseMechanics/MechanicalObject.h
  SofaKernel/modules/SofaBaseMechanics/MechanicalObject.inl
Labels: pr: clean, status: ready

#705 [MeshStepLoader] Fix: several bug due to changes in Sofa core api
  applications/plugins/MeshSTEPLoader/MeshSTEPLoader.cpp
  applications/plugins/MeshSTEPLoader/STEPShapeMapping.cpp
  applications/plugins/MeshSTEPLoader/STEPShapeMapping.h
Labels: bug, status: ready

#667 [SofaBaseLinearSolver] Add ability to activate printing of debug information at runtime
  SofaKernel/modules/SofaBaseLinearSolver/DefaultMultiMatrixAccessor.cpp
  SofaKernel/modules/SofaBaseLinearSolver/DefaultMultiMatrixAccessor.h
  SofaKernel/modules/SofaBaseLinearSolver/MatrixLinearSolver.inl
  examples/Components/linearsolver/FEMBAR-PCGLinearSolver.scn
  examples/Components/linearsolver/FEMBAR-SparseCholeskySolver.scn
  examples/Components/linearsolver/FEMBAR-SparseLDLSolver.scn
  examples/Components/linearsolver/FEMBAR-SparseLUSolver.scn
  modules/SofaSparseSolver/SparseLDLSolverImpl.h
Labels: enhancement, status: ready

#710 [SofaMiscMapping] Fix rigid barycentric mapping
  modules/SofaMiscMapping/BarycentricMappingRigid.inl
Labels: enhancement, pr: fast-merge, status: ready

#711 [SofaGraphComponent] FIX SceneChecker_test + ADD alias test
  CHANGELOG.md
  modules/SofaGraphComponent/SceneCheckUsingAlias.cpp
  modules/SofaGraphComponent/SofaGraphComponent_test/SceneChecker_test.cpp
Labels: pr: fast-merge, pr: fix

#692 [CMake] use ccache if available
  CMakeLists.txt
Labels: enhancement, status: ready

#715 [SofaSparseSolver] fix warning
  modules/SofaSparseSolver/SparseLDLSolver.inl
Labels: pr: fast-merge, status: ready

#661 [SofaKernel][SofaLoader] Merge duplicated loader codes
  SofaKernel/framework/framework_test/CMakeLists.txt
  SofaKernel/framework/sofa/core/loader/MeshLoader.cpp
  SofaKernel/framework/sofa/core/loader/MeshLoader.h
  SofaKernel/framework/sofa/helper/CMakeLists.txt
  SofaKernel/framework/sofa/helper/io/Mesh.cpp
  SofaKernel/framework/sofa/helper/io/Mesh.h
  SofaKernel/framework/sofa/helper/io/MeshGmsh.cpp
  SofaKernel/framework/sofa/helper/io/MeshGmsh.h
  SofaKernel/framework/sofa/helper/io/MeshOBJ.cpp
  SofaKernel/framework/sofa/helper/io/MeshSTL.cpp
  SofaKernel/framework/sofa/helper/io/MeshSTL.h
  SofaKernel/framework/sofa/helper/io/MeshTopologyLoader.cpp
  SofaKernel/framework/sofa/helper/io/MeshTopologyLoader.h
  SofaKernel/framework/sofa/helper/io/MeshTrian.cpp
  SofaKernel/framework/sofa/helper/io/MeshTrian.h
  SofaKernel/framework/sofa/helper/io/MeshVTK.cpp
  SofaKernel/modules/SofaBaseVisual/VisualModelImpl.cpp
  SofaKernel/modules/SofaLoader/MeshObjLoader.cpp
  SofaKernel/modules/SofaLoader/MeshObjLoader.h
  applications/plugins/Flexible/examples/shapeFunction/BezierTetrahedron.scn
  applications/plugins/Haption/exemple/haption1.scn
  applications/plugins/Haption/exemple/temp1.scn
  applications/plugins/ManifoldTopologies/examples/SimpleManifoldTesselatedTetraTopologicalMapping.scn
  applications/plugins/ManifoldTopologies/examples/SimpleTesselatedTetraTopologicalMapping.scn
  examples/Components/constraint/DOFBlockerLMConstraint.scn
  examples/Components/constraint/OscillatorConstraint.scn
  examples/Components/forcefield/FastTetrahedronCorotationalForceField_validation.scn
  examples/Components/forcefield/StandardTetrahedralFEMForceField.scn
  examples/Components/loader/MeshSTLLoader.scn
  examples/Components/loader/MeshSTLLoader_binary.scn
  examples/Components/mapping/BarycentricMappingTrussBeam.scn
  examples/Components/topology/Mesh2PointTopologicalMapping.scn
  examples/Components/topology/SimpleTesselatedTetraTopologicalMapping.scn
  examples/Tutorials/ForceFields/TutorialForceFieldLiverFEM.scn
  examples/Tutorials/ForceFields/TutorialForceFieldLiverSprings.scn
  examples/Tutorials/ForceFields/TutorialForceFieldLiverTriangleFEM.scn
  examples/Tutorials/StepByStep/FullObject/5_FullObject.scn
  examples/Tutorials/StepByStep/FullObject/6_FullObject.scn
  examples/Tutorials/StepByStep/FullObject/7_FullObject.scn
  examples/Tutorials/StepByStep/FullObject/8_FullObject.scn
  examples/Tutorials/Topologies/TopologyVolumeDifferentMesh.scn
  modules/SofaGeneralLoader/MeshGmshLoader.cpp
  modules/SofaGeneralLoader/MeshSTLLoader.cpp
  modules/SofaGeneralLoader/MeshXspLoader.cpp
  modules/SofaGeneralLoader/SofaGeneralLoader_test/MeshSTLLoader_test.cpp
Labels: enhancement, pr: clean, status: ready

#708 [SofaBaseTopology Test] Add battery of tests on topology containers
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/MeshTopology.cpp
  SofaKernel/modules/SofaBaseTopology/MeshTopology.h
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/CMakeLists.txt
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/EdgeSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/HexahedronSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/MeshTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/QuadSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/TetrahedronSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/TriangleSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/fake_TopologyScene.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/fake_TopologyScene.h
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.cpp
  examples/Components/topology/TopologicalModifiers/RemovingTetra2TriangleProcess.scn
  examples/Components/topology/TopologicalModifiers/RemovingTetra2TriangleProcess.txt
  examples/Components/topology/TopologicalModifiers/RemovingTetra2TriangleProcess_performanceTest.scn
  modules/SofaGeneralEngine/SofaGeneralEngine_test/MeshROI_test.cpp
  share/mesh/cube_low_res.msh
  share/mesh/square1_edges.mtl
  share/mesh/square1_edges.obj
  share/mesh/square1_quads.mtl
  share/mesh/square1_quads.obj
Labels: location: tests, pr: clean, status: ready

#720 [CImgPlugin] CMake/Mac: lower priority for XCode's libpng
  applications/plugins/CImgPlugin/CMakeLists.txt
Labels: pr: fast-merge, pr: fix, status: ready

#719 [SofaGraphComponent] FIX SceneCheck build on MacOS
  SofaKernel/extlibs/json/nlohmann_json.h
  modules/SofaGraphComponent/SceneCheck.h
Labels: pr: fast-merge, pr: fix, status: ready

#726 [Topology Test][Mass] Fix some recent compilation warnings
  SofaKernel/framework/sofa/helper/io/MeshTopologyLoader.cpp
  SofaKernel/modules/SofaBaseMechanics/DiagonalMass.h
  SofaKernel/modules/SofaBaseMechanics/DiagonalMass.inl
  SofaKernel/modules/SofaBaseMechanics/UniformMass.h
  SofaKernel/modules/SofaBaseMechanics/UniformMass.inl
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/EdgeSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/HexahedronSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/MeshTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/QuadSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/TetrahedronSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/TriangleSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/fake_TopologyScene.cpp
  SofaKernel/modules/SofaLoader/MeshObjLoader.cpp
  applications/plugins/SceneCreator/sceneCreatorExamples/SceneCreatorBenchmarks.cpp
  modules/SofaGeneralLoader/MeshGmshLoader.cpp
  modules/SofaMiscForceField/MeshMatrixMass.h
  modules/SofaMiscForceField/MeshMatrixMass.inl
Labels: pr: clean, status: ready

#728 [QtViewer (old gui) ] Change method to allow antialiased screenshots
  applications/sofa/gui/qt/viewer/qt/QtViewer.cpp
  applications/sofa/gui/qt/viewer/qt/QtViewer.h
Labels: pr: fast-merge, pr: fix, status: ready

#727 [Multithreading] FIX compiling error on Mac
  applications/plugins/MultiThreading/src/TaskScheduler.cpp
  applications/plugins/MultiThreading/src/TaskScheduler.h
  applications/plugins/MultiThreading/test/TaskSchedulerTests.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#734 [cmake] Add a findCython.cmake
  cmake/Modules/FindCython.cmake
Labels: enhancement, pr: fast-merge, status: ready

#737 [SofaPreconditioner] FIX ShewchukPCGLinearSolver
  modules/SofaPreconditioner/src/SofaPreconditioner/ShewchukPCGLinearSolver.cpp
  modules/SofaPreconditioner/src/SofaPreconditioner/ShewchukPCGLinearSolver.h
Labels: pr: fast-merge, pr: fix, status: ready
