Repository sofa-framework/sofa, pull requests merged in 2018-10, with the labels that each got.

#772 [SofaGeneralAnimationLoop] Improvement on MMMapper
  SofaKernel/framework/sofa/core/objectmodel/Link.h
  modules/SofaGeneralAnimationLoop/MechanicalMatrixMapper.h
  modules/SofaGeneralAnimationLoop/MechanicalMatrixMapper.inl
Labels: enhancement, status: ready

#776 [WriteState] minor fix with the time attribute, default values
  modules/SofaExporter/WriteState.inl
Labels: enhancement, status: ready

#786 [Geomagic] Fix dll export and some enhancements
  applications/plugins/Geomagic/CMakeLists.txt
  applications/plugins/Geomagic/src/GeomagicDriver.cpp
  applications/plugins/Geomagic/src/GeomagicDriver.h
  applications/plugins/Geomagic/src/config.h
Labels: enhancement, location: plugins, pr: fix, status: ready

#789 [CMake] Cleans for packaging
  CMakeLists.txt
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/framework/sofa/core/CMakeLists.txt
  SofaKernel/framework/sofa/defaulttype/CMakeLists.txt
  SofaKernel/framework/sofa/helper/CMakeLists.txt
  applications/projects/runSofa/CMakeLists.txt
  applications/sofa/gui/qt/CMakeLists.txt
  extlibs/libQGLViewer-2.7.1/QGLViewer/CMakeLists.txt
  package.cmake
Labels: pr: backport, pr: clean, status: ready

#782 [All] FIX a bunch of static-analysis errors (cppcheck)
  SofaKernel/framework/sofa/core/visual/DisplayFlags.cpp
  SofaKernel/framework/sofa/helper/LCPcalc.cpp
  SofaKernel/framework/sofa/helper/io/ImageDDS.cpp
  applications/sofa/gui/GUIManager.cpp
  applications/sofa/gui/qt/GenGraphForm.cpp
  applications/sofa/gui/qt/GenGraphForm.h
  applications/sofa/gui/qt/QSofaListView.cpp
  modules/SofaConstraint/LCPConstraintSolver.cpp
  modules/SofaExporter/STLExporter.cpp
  modules/SofaGeneralLoader/VoxelGridLoader.cpp
  modules/SofaGeneralSimpleFem/HexahedralFEMForceFieldAndMass.inl
  modules/SofaMiscFem/TriangularAnisotropicFEMForceField.h
Labels: pr: clean, status: ready

#791 [CMake] Backport fixes
  CHANGELOG.md
  SofaKernel/framework/sofa/core/CMakeLists.txt
  SofaKernel/framework/sofa/defaulttype/CMakeLists.txt
  SofaKernel/framework/sofa/helper/CMakeLists.txt
  applications/projects/runSofa/CMakeLists.txt
  applications/projects/runSofa/Main.cpp
  applications/projects/runSofa/cmake/bundle.cmake
  applications/sofa/gui/qt/CMakeLists.txt
  applications/sofa/gui/qt/RealGUI.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#760 [SofaCore] Add new (simpler) DataEngine implementation
  SofaKernel/framework/framework_test/core/DataEngine_test.cpp
  SofaKernel/framework/sofa/core/DataEngine.h
  applications/plugins/SofaTest/DataEngine_test.h
  modules/SofaGeneralEngine/TransformEngine.h
  modules/SofaGeneralEngine/TransformEngine.inl
Labels: enhancement, status: ready

#751 [SofaPython][PSDE] Update on demand as designed initially
  applications/plugins/SofaPython/Binding_PythonScriptDataEngine.cpp
  applications/plugins/SofaPython/PythonScriptDataEngine.cpp
  applications/plugins/SofaPython/PythonScriptDataEngine.h
  applications/plugins/SofaPython/ScriptDataEngine.cpp
  applications/plugins/SofaPython/ScriptDataEngine.h
Labels: enhancement, project: SofaPython, status: ready

#792 [MultiThreading] Fix Livers scenes crash
  SofaKernel/framework/sofa/helper/AdvancedTimer.cpp
  SofaKernel/framework/sofa/helper/AdvancedTimer.h
  applications/plugins/MultiThreading/src/DefaultTaskScheduler.cpp
  applications/plugins/MultiThreading/src/DefaultTaskScheduler.h
  applications/plugins/MultiThreading/src/TaskScheduler.cpp
  applications/plugins/MultiThreading/test/TaskSchedulerTests.cpp
Labels: pr: fix, status: ready

#793 [Compliant] update se3.h license to make it compatible with core
  applications/plugins/Compliant/utils/se3.h
Labels: status: to review

#790 [MechanicalObject] Check if Quaternion has norm 1
  SofaKernel/framework/sofa/defaulttype/RigidTypes.h
  SofaKernel/framework/sofa/helper/Quater.h
  SofaKernel/framework/sofa/helper/Quater.inl
Labels: pr: fix, status: ready

#796 [CMake] ADD QtIFW generator + improvements
  CMakeLists.txt
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/SofaFramework/SofaMacros.cmake
  applications/plugins/CImgPlugin/CMakeLists.txt
  applications/projects/runSofa/CMakeLists.txt
  applications/sofa/gui/qt/CMakeLists.txt
  extlibs/libQGLViewer-2.7.1/QGLViewer/CMakeLists.txt
  package.cmake
  scripts/qtifw/install.qs
Labels: enhancement, pr: clean, status: ready
