Repository sofa-framework/sofa, pull requests merged in 2018-05, with the labels that each got.

#646 [SofaOpenglVisual] FIX MacOS crash in batch mode
  applications/sofa/gui/BatchGUI.cpp
  examples/Components/visualmodel/LightMax.scn
  modules/SofaOpenglVisual/CompositingVisualLoop.h
  modules/SofaOpenglVisual/Light.cpp
  modules/SofaOpenglVisual/Light.h
  modules/SofaOpenglVisual/LightManager.cpp
  modules/SofaOpenglVisual/LightManager.h
  modules/SofaOpenglVisual/OglViewport.cpp
  modules/SofaOpenglVisual/OglViewport.h
  modules/SofaOpenglVisual/OrderIndependentTransparencyManager.h
  modules/SofaOpenglVisual/PostProcessManager.cpp
  modules/SofaOpenglVisual/PostProcessManager.h
  modules/SofaOpenglVisual/VisualManagerPass.cpp
  modules/SofaOpenglVisual/VisualManagerPass.h
  modules/SofaOpenglVisual/VisualManagerSecondaryPass.cpp
  modules/SofaOpenglVisual/VisualManagerSecondaryPass.h
Labels: pr: fix, status: ready

#655 [SofaSparseSolver] FIX SparseLDL crash and add proper SOFA_FLOAT/DOUBLE mangement
  modules/SofaSparseSolver/SparseLDLSolver.cpp
  modules/SofaSparseSolver/SparseLDLSolver.h
  modules/SofaSparseSolver/SparseLDLSolver.inl
Labels: pr: fast-merge, pr: fix, status: ready

#664 [CGALPlugin] FIX compilation issue with recent version of CGAL (4.11) & Ubunu 18.04 LTS
  applications/plugins/CGALPlugin/MeshGenerationFromPolyhedron.cpp
  applications/plugins/CGALPlugin/MeshGenerationFromPolyhedron.h
Labels: pr: fast-merge, pr: fix, status: ready

#659 [SofaPhysicsAPI] FIX: remove the include of glut
  applications/projects/SofaPhysicsAPI/SofaPhysicsSimulation.cpp
  scripts/ci/configure.sh
Labels: pr: clean, status: ready

#660 [all] Various small changes in error messages & bugfix from defrost branches
  SofaKernel/framework/sofa/core/behavior/BaseConstraintCorrection.h
  SofaKernel/framework/sofa/core/behavior/ConstraintCorrection.h
  SofaKernel/framework/sofa/core/objectmodel/BaseData.h
  SofaKernel/framework/sofa/helper/StringUtils.h
  SofaKernel/framework/sofa/helper/vectorData.h
  SofaKernel/framework/sofa/simulation/DefaultAnimationLoop.cpp
  SofaKernel/modules/SofaBaseLinearSolver/DefaultMultiMatrixAccessor.cpp
  SofaKernel/modules/SofaDeformable/RestShapeSpringsForceField.cpp
  applications/sofa/gui/qt/RealGUI.cpp
  modules/SofaConstraint/LinearSolverConstraintCorrection.h
  modules/SofaConstraint/LinearSolverConstraintCorrection.inl
  modules/SofaConstraint/PrecomputedConstraintCorrection.cpp
  modules/SofaConstraint/PrecomputedConstraintCorrection.h
  modules/SofaConstraint/UncoupledConstraintCorrection.cpp
  modules/SofaConstraint/UncoupledConstraintCorrection.h
  modules/SofaGeneralEngine/MergeMeshes.h
  modules/SofaGraphComponent/RequiredPlugin.cpp
Labels: pr: fix, status: ready
