Repository sofa-framework/sofa, pull requests merged in 2018-08, with the labels that each got.

#730 [SofaTest] ADD a PrintTo method so test failure shows human readable informations.
  applications/plugins/SofaTest/Python_test.cpp
  applications/plugins/SofaTest/Python_test.h
Labels: enhancement, pr: fast-merge, status: ready

#716 [examples] Fix TopologySurfaceDifferentMesh.scn
  examples/Tutorials/Topologies/TopologySurfaceDifferentMesh.scn
  examples/Tutorials/Topologies/TopologySurfaceDifferentMesh_01.png
  examples/Tutorials/Topologies/TopologySurfaceDifferentMesh_02.png
Labels: pr: fast-merge, pr: fix, status: ready

#732 [SofaKernel] Add a "sofa_add_module" in SofaMacro.cmake
  SofaKernel/SofaFramework/SofaMacros.cmake
  modules/CMakeLists.txt
Labels: enhancement, pr: fast-merge, project: Sofa NG, status: ready

#729 [All] replace some int/unit by size_t
  SofaKernel/framework/sofa/core/objectmodel/Link.h
  SofaKernel/framework/sofa/core/topology/BaseMeshTopology.h
  SofaKernel/framework/sofa/helper/logging/LoggingMessageHandler.cpp
  SofaKernel/framework/sofa/helper/logging/LoggingMessageHandler.h
  SofaKernel/framework/sofa/simulation/MechanicalMatrixVisitor.h
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/GridTopology.h
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/MeshTopology.cpp
  SofaKernel/modules/SofaBaseTopology/MeshTopology.h
  SofaKernel/modules/SofaBaseTopology/QuadSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/SparseGridTopology.h
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/TopologySparseDataHandler.inl
  SofaKernel/modules/SofaBaseTopology/TriangleSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.cpp
  SofaKernel/modules/SofaEigen2Solver/EigenSparseMatrix.h
  SofaKernel/modules/SofaRigid/SofaRigid_test/RigidRigidMapping_test.cpp
  applications/plugins/SofaTest/Mapping_test.h
Labels: pr: clean, status: ready

#731 [SofaPython] ADD forwarding of onMouseMove event into the script controller
  applications/plugins/SofaPython/Binding_PythonScriptController.cpp
  applications/plugins/SofaPython/PythonMainScriptController.cpp
  applications/plugins/SofaPython/PythonMainScriptController.h
  applications/plugins/SofaPython/PythonScriptController.cpp
  applications/plugins/SofaPython/PythonScriptController.h
  applications/plugins/SofaPython/ScriptController.cpp
  applications/plugins/SofaPython/ScriptController.h
  applications/plugins/SofaPython/examples/ExampleController.py
Labels: enhancement, pr: fast-merge, project: SofaPython, status: ready

#736 [SofaPython] ADD: Bindings for BoundingBox
  applications/plugins/SofaPython/Binding.cpp
  applications/plugins/SofaPython/Binding_BaseObject.cpp
  applications/plugins/SofaPython/Binding_BoundingBoxData.cpp
  applications/plugins/SofaPython/Binding_BoundingBoxData.h
  applications/plugins/SofaPython/CMakeLists.txt
  applications/plugins/SofaPython/examples/RegularGridFromMesh.py
Labels: enhancement, status: ready

#752 [Gui][HeadlessRecorder]Remove avcodec dependency in HeadlessRecorder.h
  applications/sofa/gui/headlessRecorder/HeadlessRecorder.cpp
  applications/sofa/gui/headlessRecorder/HeadlessRecorder.h
Labels: enhancement, pr: backport, status: ready

#740 [SofaPython][PSDE] ADD: Switching to cpp-style datatypes in the PSDE factory
  applications/plugins/SofaPython/Binding_Base.cpp
  applications/plugins/SofaPython/SofaPython_test/python/test_BindingBase.py
  applications/plugins/SofaPython/SofaPython_test/python/test_BindingData.py
  applications/plugins/SofaPython/examples/PSDEExamples/01-basic/DataEngine.py
Labels: status: ready

#748 [examples] Fix the examples missing a <RequiredPlugin name="SofaSparseSolver"/>
  examples/Components/constraint/InextensiblePendulum.scn
  examples/Components/forcefield/RestShapeSpringsForceField2.scn
  examples/Components/linearsolver/FEMBAR-PCGLinearSolver.scn
  examples/Components/linearsolver/FEMBAR-SparseCholeskySolver.scn
  examples/Components/linearsolver/FEMBAR-SparseLDLSolver.scn
  examples/Components/linearsolver/FEMBAR-SparseLUSolver.scn
Labels: pr: fast-merge, pr: fix, status: ready

#742 [SofaPython][PSDE] Psde derive io
  SofaKernel/framework/sofa/core/objectmodel/Base.cpp
  SofaKernel/framework/sofa/core/objectmodel/BaseData.h
  SofaKernel/framework/sofa/core/objectmodel/Data.h
  applications/plugins/SofaPython/Binding_Base.cpp
  applications/plugins/SofaPython/Binding_DataEngine.cpp
  applications/plugins/SofaPython/examples/PSDEExamples/01-basic/DataEngine.py
  applications/plugins/SofaPython/examples/PSDEExamples/01-basic/PSDEBasic.pyscn
  applications/plugins/SofaPython/examples/PSDEExamples/02-advanced/Compound.pyscn
  applications/plugins/SofaPython/examples/PSDEExamples/02-advanced/Controller.py
  applications/plugins/SofaPython/examples/PSDEExamples/02-advanced/DataEngineIntersection.py
  applications/plugins/SofaPython/examples/PSDEExamples/02-advanced/DataEngineROI1.py
  applications/plugins/SofaPython/examples/PSDEExamples/02-advanced/DataEngineROI2.py
  applications/plugins/SofaPython/examples/PSDEExamples/02-advanced/DataEngineROI3.py
  applications/plugins/SofaPython/examples/PSDEExamples/02-advanced/DataEngineROI4.py
  applications/plugins/SofaPython/examples/PSDEExamples/02-advanced/DataEngineUnion1.py
  applications/plugins/SofaPython/examples/PSDEExamples/02-advanced/DataEngineUnion2.py
  applications/plugins/SofaPython/examples/PSDEExamples/02-advanced/ROI.py
  applications/plugins/SofaPython/examples/PSDEExamples/02-advanced/VolumetricMeshGeneration.pyscn
  applications/plugins/SofaPython/examples/PSDEExamples/DataEngine.py
  applications/plugins/SofaPython/examples/PSDEExamples/DataEngine2.py
  applications/plugins/SofaPython/examples/PSDEExamples/PSDEAvgEngine.pyscn
  applications/plugins/SofaPython/examples/PSDEExamples/PSDEBasic.pyscn
Labels: enhancement, status: ready
