Repository sofa-framework/sofa, pull requests merged in 2019-11, with the labels that each got.

#1201 [SofaMeshCollision] Clean deprecated code
  SofaKernel/modules/SofaBaseCollision/CubeModel.cpp
  SofaKernel/modules/SofaBaseCollision/CubeModel.h
  SofaKernel/modules/SofaMeshCollision/TriangleModel.h
  SofaKernel/modules/SofaMeshCollision/TriangleModel.inl
Labels: pr: clean, pr: fast-merge, status: ready

#1208 [Geomagic] Reorder plugin files for better modularization
  applications/plugins/Geomagic/CMakeLists.txt
  applications/plugins/Geomagic/GeomagicConfig.cmake.in
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.cpp
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.h
  applications/plugins/Geomagic/src/Geomagic/config.h.in
  applications/plugins/Geomagic/src/Geomagic/initPlugin.cpp
  applications/plugins/Geomagic/src/initPlugin.cpp
Labels: location: plugins, pr: clean, status: ready

#1203 [SofaBaseMechanics] Add topological change in barycentric mapping
  SofaKernel/modules/SofaBaseMechanics/BarycentricMappers/BarycentricMapperTetrahedronSetTopology.h
  SofaKernel/modules/SofaBaseMechanics/BarycentricMappers/BarycentricMapperTetrahedronSetTopology.inl
  SofaKernel/modules/SofaBaseMechanics/BarycentricMappers/TopologyBarycentricMapper.h
  SofaKernel/modules/SofaBaseMechanics/BarycentricMapping.inl
  examples/Components/mapping/BarycentricTetraMapping.scn
Labels: enhancement, status: ready

#1202 [SofaKernel] Small Fix in CollisionModel
  SofaKernel/modules/SofaBaseCollision/CubeModel.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/CollisionModel.h
Labels: pr: fast-merge, pr: fix, status: ready

#1211 [Sofa v19.06] FIX installation for Windows
  CMakeLists.txt
  SofaKernel/SofaFramework/SofaMacros.cmake
Labels: pr: backport, pr: fast-merge, pr: fix, status: ready
