Repository sofa-framework/sofa, pull requests merged in 2019-07, with the labels that each got.

#1060 [CollisionGroupManager] Fix wrong search of deformable object node
  SofaKernel/modules/SofaSimulationGraph/DAGNode.cpp
  SofaKernel/modules/SofaSimulationGraph/DAGNode.h
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/CMakeLists.txt
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/DAGNode_test.cpp
  applications/plugins/SofaMiscCollision/DefaultCollisionGroupManager.cpp
  applications/plugins/SofaMiscCollision/DefaultCollisionGroupManager.h
  examples/Demos/chainHybrid.scn
Labels: STC#7, pr: fix, status: ready

#1094 [AdvanceTimer] Change several logs for a better tracking
  SofaKernel/framework/sofa/core/behavior/ConstraintSolver.cpp
  SofaKernel/framework/sofa/helper/AdvancedTimer.h
  SofaKernel/framework/sofa/simulation/DefaultVisualManagerLoop.cpp
  SofaKernel/framework/sofa/simulation/UpdateBoundingBoxVisitor.cpp
  SofaKernel/framework/sofa/simulation/UpdateMappingVisitor.cpp
  SofaKernel/framework/sofa/simulation/VisualVisitor.cpp
  SofaKernel/modules/SofaBaseCollision/BruteForceDetection.cpp
  SofaKernel/modules/SofaBaseCollision/DefaultPipeline.cpp
  SofaKernel/modules/SofaBaseVisual/VisualModelImpl.cpp
  applications/sofa/gui/qt/SofaWindowProfiler.cpp
Labels: enhancement, status: ready

#1095 [SofaExporter] Move bindings from SofaPython
  CMakeLists.txt
  applications/plugins/SofaPython/Binding.cpp
  applications/plugins/SofaPython/CMakeLists.txt
  modules/SofaExporter/CMakeLists.txt
  modules/SofaExporter/src/SofaExporter/bindings/Binding_OBJExporter.cpp
  modules/SofaExporter/src/SofaExporter/bindings/Binding_OBJExporter.h
  modules/SofaExporter/src/SofaExporter/bindings/Binding_STLExporter.cpp
  modules/SofaExporter/src/SofaExporter/bindings/Binding_STLExporter.h
  modules/SofaExporter/src/SofaExporter/initExporter.cpp
Labels: pr: fast-merge, pr: fix, status: to review

#1049 [all] Standardize epsilons in SOFA
  modules/SofaGeneralEngine/Vertex2Frame.inl
  modules/SofaMiscMapping/DistanceMapping.inl
  modules/SofaMiscTopology/TopologicalChangeProcessor.cpp
Labels: STC#7, pr: clean, pr: fast-merge, status: ready

#1097 [SofaTest] CLEAN msg in Multi2Mapping_test
  applications/plugins/SofaTest/Multi2Mapping_test.h
Labels: pr: clean, status: ready

#1063 [BaseLinearSolver] Remove virtual function BaseLinearSolver::isMultiGroup
  SofaKernel/framework/sofa/core/behavior/LinearSolver.h
  SofaKernel/modules/SofaBaseLinearSolver/CGLinearSolver.inl
  applications/plugins/SofaMiscCollision/DefaultCollisionGroupManager.cpp
  modules/SofaGeneralLinearSolver/MinResLinearSolver.inl
Labels: pr: clean, pr: fast-merge, status: ready

#1102 [Regression_test] Update regression test references for CollisionGroup
  applications/projects/Regression/ExternalProjectConfig.cmake.in
  examples/Demos/chainHybridNoGroup.scn
  examples/RegressionStateScenes.regression-tests
Labels: pr: fix, status: ready

#1108 [SofaGui] Prevent the GuiManager to store a pointer for the valid gui name
  applications/sofa/gui/GUIManager.cpp
  applications/sofa/gui/GUIManager.h
Labels: pr: fast-merge, pr: fix, status: to review

#1109 [SceneCreator] Pluginizing...
  applications/plugins/SceneCreator/CMakeLists.txt
  applications/plugins/SceneCreator/src/SceneCreator/GetAssembledSizeVisitor.cpp
  applications/plugins/SceneCreator/src/SceneCreator/GetAssembledSizeVisitor.h
  applications/plugins/SceneCreator/src/SceneCreator/GetVectorVisitor.cpp
  applications/plugins/SceneCreator/src/SceneCreator/GetVectorVisitor.h
  applications/plugins/SceneCreator/src/SceneCreator/SceneCreator.cpp
  applications/plugins/SceneCreator/src/SceneCreator/SceneCreator.h
  applications/plugins/SceneCreator/src/SceneCreator/SceneUtils.cpp
  applications/plugins/SceneCreator/src/SceneCreator/SceneUtils.h
  applications/plugins/SceneCreator/src/SceneCreator/initSceneCreator.cpp
  applications/projects/SofaPhysicsAPI/SofaPhysicsSimulation.cpp
Labels: pr: clean, refactoring, status: ready

#1104 [CGal plugin][CImgPlugin] Image data moved from Image/ to CImgPlugin/
  applications/plugins/CGALPlugin/CGALPlugin_test/MeshGenerationFromImage_test.cpp
  applications/plugins/CGALPlugin/CMakeLists.txt
  applications/plugins/CGALPlugin/MeshGenerationFromImage.h
  applications/plugins/CImgPlugin/CMakeLists.txt
  applications/plugins/CImgPlugin/src/CImgPlugin/CImgData.h
  applications/plugins/image/ImageTypes.h
Labels: location: plugins, refactoring, status: to review

#992 [SofaQtQuick] Pass extra command-line arguments for python scenes in a more high-level function call
  SofaKernel/framework/sofa/simulation/SceneLoaderFactory.h
  SofaKernel/framework/sofa/simulation/Simulation.cpp
  SofaKernel/framework/sofa/simulation/Simulation.h
  SofaKernel/modules/SofaSimulationCommon/SceneLoaderPHP.cpp
  SofaKernel/modules/SofaSimulationCommon/SceneLoaderPHP.h
  SofaKernel/modules/SofaSimulationCommon/SceneLoaderXML.cpp
  SofaKernel/modules/SofaSimulationCommon/SceneLoaderXML.h
  applications/plugins/PSL/SceneLoaderPSL.cpp
  applications/plugins/PSL/SceneLoaderPSL.h
  applications/plugins/SofaPython/Binding_SofaModule.cpp
  applications/plugins/SofaPython/SceneLoaderPY.cpp
  applications/plugins/SofaPython/SceneLoaderPY.h
  applications/plugins/SofaPython/SofaPython_test/PythonScriptController_test.cpp
  applications/plugins/SofaTest/Mapping_test.h
  applications/projects/runSofa/Main.cpp
  applications/sofa/gui/qt/RealGUI.cpp
Labels: enhancement, status: ready
