Repository sofa-framework/sofa, pull requests merged in 2019-06, with the labels that each got.

#1025 [SofaKernel] minor cleaning in mesh loader
  SofaKernel/framework/sofa/core/loader/MeshLoader.cpp
  SofaKernel/framework/sofa/core/loader/MeshLoader.h
  SofaKernel/framework/sofa/helper/types/RGBAColor.h
  SofaKernel/modules/SofaLoader/MeshObjLoader.cpp
  SofaKernel/modules/SofaLoader/MeshObjLoader.h
Labels: pr: clean, status: ready

#1069 [SofaOpenglVisual] Fix ogl perf problem
  modules/SofaOpenglVisual/OglModel.cpp
  modules/SofaOpenglVisual/OglModel.h
Labels: pr: breaking, pr: fix, status: ready

#1065 [Sofa] Remove bunch of warnings (again)
  SofaKernel/cmake/CompilerOptions.cmake
  SofaKernel/framework/sofa/core/DataTracker.h
  SofaKernel/framework/sofa/core/topology/TopologyChange.h
  SofaKernel/framework/sofa/core/topology/TopologyElementHandler.h
  SofaKernel/framework/sofa/core/topology/TopologyHandler.h
  SofaKernel/framework/sofa/core/visual/DrawToolGL.h
  SofaKernel/framework/sofa/helper/gl/BasicShapesGL.h
  SofaKernel/framework/sofa/helper/gl/BasicShapesGL.inl
  SofaKernel/framework/sofa/helper/io/FileAccess.h
  SofaKernel/framework/sofa/helper/system/FileMonitor_macosx.cpp
  SofaKernel/framework/sofa/simulation/CollisionVisitor.h
  SofaKernel/framework/sofa/simulation/DefaultTaskScheduler.cpp
  SofaKernel/framework/sofa/simulation/DefaultTaskScheduler.h
  SofaKernel/framework/sofa/simulation/Locks.h
  SofaKernel/framework/sofa/simulation/TopologyChangeVisitor.h
  SofaKernel/modules/SofaBaseCollision/BruteForceDetection.h
  SofaKernel/modules/SofaImplicitOdeSolver/StaticSolver.h
  SofaKernel/modules/SofaLoader/BaseVTKReader.h
  SofaKernel/modules/SofaSimulationCommon/FindByTypeVisitor.h
  SofaKernel/modules/SofaSimulationCommon/SceneLoaderPHP.h
  SofaKernel/modules/SofaSimulationCommon/SceneLoaderXML.h
  SofaKernel/modules/SofaSimulationCommon/xml/BaseElement.h
  SofaKernel/modules/SofaSimulationCommon/xml/XML.cpp
  SofaKernel/modules/SofaSimulationGraph/DAGNodeMultiMappingElement.h
  SofaKernel/modules/SofaSimulationTree/GNodeMultiMappingElement.h
  applications/plugins/SofaDistanceGrid/components/collision/DistanceGridCollisionModel.cpp
  applications/sofa/gui/BatchGUI.h
  applications/sofa/gui/FilesRecentlyOpenedManager.h
  applications/sofa/gui/MouseOperations.h
  applications/sofa/gui/OperationFactory.h
  applications/sofa/gui/qt/QMenuFilesRecentlyOpened.h
  applications/sofa/gui/qt/RealGUI.cpp
  applications/sofa/gui/qt/RealGUI.h
  applications/sofa/gui/qt/SofaWindowProfiler.cpp
  applications/sofa/gui/qt/SofaWindowProfiler.h
  applications/sofa/gui/qt/viewer/qgl/QtGLViewer.h
  applications/sofa/gui/qt/viewer/qt/QtViewer.h
  modules/SofaConstraint/ConstraintAnimationLoop.h
  modules/SofaConstraint/ConstraintSolverImpl.h
  modules/SofaConstraint/GenericConstraintSolver.h
  modules/SofaConstraint/LCPConstraintSolver.h
  modules/SofaConstraint/PrecomputedConstraintCorrection.inl
  modules/SofaGeneralAnimationLoop/MechanicalMatrixMapper.h
  modules/SofaGeneralDeformable/VectorSpringForceField.h
  modules/SofaGeneralDeformable/VectorSpringForceField.inl
  modules/SofaGeneralEngine/ExtrudeSurface.inl
  modules/SofaGeneralImplicitOdeSolver/VariationalSymplecticSolver.cpp
  modules/SofaGraphComponent/SceneCheck.h
  modules/SofaGraphComponent/SceneCheckerListener.h
  modules/SofaMiscTopology/TopologicalChangeProcessor.h
  modules/SofaOpenglVisual/OglLabel.cpp
  modules/SofaOpenglVisual/OglModel.cpp
  modules/SofaOpenglVisual/OglModel.h
  modules/SofaOpenglVisual/OglShader.h
Labels: pr: clean, status: ready

#1075 [all] Remove all #ifdef GLEW
  SofaKernel/framework/sofa/helper/gl/FrameBufferObject.h
  SofaKernel/framework/sofa/helper/gl/GLSLShader.h
  SofaKernel/framework/sofa/helper/gl/Texture.cpp
  SofaKernel/framework/sofa/helper/system/gl.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaDistanceGridCollisionModel.cpp
  applications/projects/SofaGuiGlut/MultithreadGUI.cpp
  applications/projects/SofaGuiGlut/SimpleGUI.cpp
  applications/projects/SofaPhysicsAPI/SofaPhysicsSimulation.cpp
  applications/sofa/gui/PickHandler.cpp
  applications/sofa/gui/PickHandler.h
  applications/sofa/gui/qt/viewer/qgl/QtGLViewer.cpp
  applications/sofa/gui/qt/viewer/qt/QtViewer.cpp
  modules/SofaOpenglVisual/CompositingVisualLoop.cpp
  modules/SofaOpenglVisual/CompositingVisualLoop.h
  modules/SofaOpenglVisual/Light.cpp
  modules/SofaOpenglVisual/Light.h
  modules/SofaOpenglVisual/LightManager.cpp
  modules/SofaOpenglVisual/LightManager.h
  modules/SofaOpenglVisual/OglColorMap.cpp
  modules/SofaOpenglVisual/SlicedVolumetricModel.cpp
  modules/SofaOpenglVisual/initOpenGLVisual.cpp
Labels: pr: clean, pr: fast-merge, status: to review

#1073 [SofaKernel] Refactor DataTrackerEngine so it match the DataCallback
  SofaKernel/framework/sofa/core/DataTracker.cpp
  SofaKernel/framework/sofa/core/DataTracker.h
  SofaKernel/modules/sofa/frameworkextra/frameworkextra_test/core/TrackedData_test.cpp
Labels: pr: fast-merge, refactoring, status: to review

#1077 [all] remove #ifdef SOFA_HAVE_GLEW
  SofaKernel/framework/sofa/helper/gl/FrameBufferObject.h
  SofaKernel/framework/sofa/helper/gl/GLSLShader.cpp
  SofaKernel/framework/sofa/helper/gl/GLSLShader.h
  SofaKernel/framework/sofa/helper/gl/Texture.cpp
  SofaKernel/framework/sofa/helper/system/gl.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaDistanceGridCollisionModel.cpp
  applications/projects/SofaGuiGlut/MultithreadGUI.cpp
  applications/projects/SofaGuiGlut/SimpleGUI.cpp
  applications/projects/SofaPhysicsAPI/SofaPhysicsSimulation.cpp
  applications/sofa/gui/PickHandler.cpp
  applications/sofa/gui/PickHandler.h
  applications/sofa/gui/qt/viewer/qgl/QtGLViewer.cpp
  applications/sofa/gui/qt/viewer/qt/QtViewer.cpp
  modules/SofaOpenglVisual/CompositingVisualLoop.cpp
  modules/SofaOpenglVisual/CompositingVisualLoop.h
  modules/SofaOpenglVisual/Light.cpp
  modules/SofaOpenglVisual/Light.h
  modules/SofaOpenglVisual/LightManager.cpp
  modules/SofaOpenglVisual/LightManager.h
  modules/SofaOpenglVisual/OglColorMap.cpp
  modules/SofaOpenglVisual/OglRenderingSRGB.cpp
  modules/SofaOpenglVisual/OglShader.cpp
  modules/SofaOpenglVisual/SlicedVolumetricModel.cpp
  modules/SofaOpenglVisual/initOpenGLVisual.cpp
Labels: pr: clean, pr: fast-merge, status: to review

#1061 [Tests] Add option in regression-test to check first and last iteration.
  applications/projects/Regression/ExternalProjectConfig.cmake.in
  examples/RegressionStateScenes.regression-tests
  modules/SofaExporter/src/SofaExporter/WriteState.cpp
  modules/SofaExporter/src/SofaExporter/WriteState.h
  modules/SofaExporter/src/SofaExporter/WriteState.inl
Labels: STC#7, enhancement, status: ready

#1078 [SofaTests] Fix small bugs in the Multi2Mapping_test
  applications/plugins/SofaTest/Multi2Mapping_test.h
Labels: bug (minor), pr: fast-merge, status: ready

#1082 Remove unjustified Assert in getSimulation()
  SofaKernel/framework/sofa/simulation/Simulation.cpp
Labels: pr: fast-merge, status: ready

#1084 ADD: static method to retrieve the count number of all Events
  SofaKernel/framework/sofa/core/objectmodel/Event.h
Labels: enhancement, pr: fast-merge, status: ready

#1085 ADD: method getCategories() returning all SOFA categories
  SofaKernel/framework/sofa/core/CategoryLibrary.cpp
  SofaKernel/framework/sofa/core/CategoryLibrary.h
Labels: enhancement, status: ready

#1083 Fix SetDirectory bug
  SofaKernel/framework/sofa/helper/system/SetDirectory.cpp
  SofaKernel/framework/sofa/helper/system/SetDirectory.h
Labels: pr: fix, status: to review

#1089 FIX: import of SofaExporter: #include <SofaExporter/headerFile.h>
  modules/SofaExporter/CMakeLists.txt
Labels: pr: fast-merge, pr: fix, status: ready

#1086 ADD: DataTypeInfo for Data type BoundingBox
  SofaKernel/framework/sofa/defaulttype/BoundingBox.h
Labels: pr: fast-merge, status: ready

#1088 [All] Cleans and fixes for v19.06
  CHANGELOG.md
  CMakeLists.txt
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/SofaFramework/SofaMacros.cmake
  SofaKernel/framework/sofa/helper/ComponentChange.cpp
  SofaKernel/framework/sofa/helper/ComponentChange.h
  SofaKernel/framework/sofa/helper/system/DynamicLibrary.cpp
  applications/packages/SofaAllCommonComponents/CMakeLists.txt
  applications/plugins/SofaPython/PythonEnvironment.cpp
  applications/projects/runSofa/CMakeLists.txt
  applications/projects/runSofa/runSofa.plist
  applications/sofa/gui/qt/CMakeLists.txt
  modules/CMakeLists.txt
  modules/SofaExporter/CMakeLists.txt
  modules/SofaExporter/SofaExporterConfig.cmake.in
  modules/SofaHaptics/CMakeLists.txt
  modules/SofaHaptics/SofaHapticsConfig.cmake.in
  modules/SofaOpenglVisual/CMakeLists.txt
  modules/SofaOpenglVisual/SofaOpenglVisualConfig.cmake.in
  modules/SofaOpenglVisual/src/SofaOpenglVisual/OglModel.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/initOpenGLVisual.cpp
  modules/SofaPreconditioner/CMakeLists.txt
  modules/SofaPreconditioner/SofaPreconditionerConfig.cmake.in
  modules/SofaSparseSolver/CMakeLists.txt
  modules/SofaSparseSolver/SofaSparseSolverConfig.cmake.in
  modules/tests/CMakeLists.txt
  package.cmake
  scripts/macos-postinstall-fixup.sh
Labels: pr: clean, pr: fix, status: ready

#1090 [SofaGuiQt] FIX tooltips segfault
  applications/sofa/gui/qt/QDisplayDataWidget.cpp
Labels: pr: fast-merge, pr: fix, status: ready
