Repository sofa-framework/sofa, pull requests merged in 2019-03, with the labels that each got.

#927 [CMake][SofaKernel] FIX: exporting options in SofaFrameworkConfig.cmake
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
Labels: pr: fix, status: ready

#939 [SofaKernel] FIX deprecation message related to template types.
  SofaKernel/framework/sofa/core/ObjectFactory.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#947 [SofaHelper] REMOVE PluginManager::m_searchPaths
  SofaKernel/framework/sofa/helper/system/PluginManager.cpp
  SofaKernel/framework/sofa/helper/system/PluginManager.h
  modules/SofaMisc/AddResourceRepository.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#942 [SofaDeformable] FIX issue928
  SofaKernel/modules/SofaDeformable/RestShapeSpringsForceField.h
  SofaKernel/modules/SofaDeformable/RestShapeSpringsForceField.inl
  SofaKernel/modules/SofaDeformable/SofaDeformable_test/CMakeLists.txt
  SofaKernel/modules/SofaDeformable/SofaDeformable_test/RestShapeSpringsForceField_test.cpp
Labels: pr: fix, status: ready

#952 [SofaKernel] Some small changes in debug topology drawing
  SofaKernel/framework/sofa/core/visual/DrawToolGL.cpp
  SofaKernel/framework/sofa/core/visual/DrawToolGL.h
  SofaKernel/modules/SofaBaseTopology/EdgeSetGeometryAlgorithms.h
  SofaKernel/modules/SofaBaseTopology/EdgeSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/HexahedronSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/QuadSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/TriangleSetGeometryAlgorithms.inl
Labels: enhancement, pr: fast-merge, status: ready

#962 fix collision visitor i.e. check if narrow phase is null before calli…
  SofaKernel/framework/sofa/simulation/CollisionVisitor.cpp
Labels: pr: fast-merge, pr: fix, status: to review

#951 [CMake] Rework sofa_generate_package
  SofaKernel/SofaFramework/SofaMacros.cmake
  SofaKernel/extlibs/newmat/CMakeLists.txt
  applications/packages/SofaAllCommonComponents/CMakeLists.txt
  applications/plugins/CImgPlugin/CMakeLists.txt
  applications/plugins/SceneCreator/CMakeLists.txt
  applications/plugins/SofaMiscCollision/CMakeLists.txt
  applications/plugins/SofaPython/CMakeLists.txt
  applications/plugins/SofaTest/CMakeLists.txt
  applications/projects/runSofa/CMakeLists.txt
  extlibs/gtest/CMakeLists.txt
  extlibs/libQGLViewer-2.7.1/QGLViewer/CMakeLists.txt
  modules/SofaPreconditioner/CMakeLists.txt
  modules/SofaSparseSolver/CMakeLists.txt
Labels: enhancement, status: ready

#959 [install] FIX Could not install plugin resources
  CMakeLists.txt
Labels: pr: fix, status: ready

#963 [SofaPython][SofaGuiQt] REMOVE: public export of target SofaExporter
  applications/plugins/SofaPython/CMakeLists.txt
  applications/sofa/gui/qt/CMakeLists.txt
Labels: pr: fix, status: ready

#964 [SofaPython2] Add Sofa.hasViewer function
  applications/plugins/SofaPython/Binding_SofaModule.cpp
Labels: enhancement, pr: fast-merge, status: ready

#953 [SofaKernel] several small fix
  SofaKernel/framework/sofa/core/collision/NarrowPhaseDetection.h
  SofaKernel/modules/SofaBaseMechanics/MechanicalObject.h
  SofaKernel/modules/SofaBaseMechanics/MechanicalObject.inl
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/MeshTopology.cpp
  SofaKernel/modules/SofaBaseTopology/MeshTopology.h
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.cpp
  SofaKernel/modules/SofaMeshCollision/PointLocalMinDistanceFilter.cpp
  SofaKernel/modules/SofaMeshCollision/PointModel.h
  SofaKernel/modules/SofaMeshCollision/TriangleLocalMinDistanceFilter.cpp
Labels: pr: fix, status: ready

#949 [SofaGeneralObjectInteraction] Fix AttachConstraint in case of FreeMotion (LM solving)
  modules/SofaGeneralObjectInteraction/AttachConstraint.cpp
  modules/SofaGeneralObjectInteraction/AttachConstraint.h
  modules/SofaGeneralObjectInteraction/AttachConstraint.inl
Labels: pr: fix, status: ready

#966 [SofaCuda] Fix windows compilation.
  SofaKernel/modules/SofaMeshCollision/SubsetContactMapper.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping-3f.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping-3f1-3f.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping-3f1-d.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping-3f1.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBeamLinearMapping.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBoxROI.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaCollision.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaExtraMonitor.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaFixedConstraint.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaFixedTranslationConstraint.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaIdentityMapping.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaIdentityMapping.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaIndexValueMapper.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLineModel.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLinearForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLinearMovementConstraint.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLinearVelocityConstraint.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMechanicalObject.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMechanicalObject.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMeshMatrixMass.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaRestShapeSpringsForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaRigidMapping.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSetTopology.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSphereROI.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSpringForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaStandardTetrahedralFEMForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSubsetMapping.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedralTensorMassForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedronFEMForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTriangleModel.cpp
  applications/plugins/SofaDistanceGrid/CMakeLists.txt
Labels: location: plugins, pr: fix, status: ready

#968 [SofaKernel] Remove warnings
  SofaKernel/framework/sofa/core/DataTracker.h
  SofaKernel/framework/sofa/core/ObjectFactory.h
  SofaKernel/framework/sofa/core/collision/Intersection.inl
  SofaKernel/framework/sofa/core/objectmodel/BaseData.h
  SofaKernel/framework/sofa/core/objectmodel/Data.h
  SofaKernel/framework/sofa/core/objectmodel/Event.h
  SofaKernel/framework/sofa/core/objectmodel/Link.h
  SofaKernel/framework/sofa/core/topology/TopologyElementHandler.h
  SofaKernel/framework/sofa/defaulttype/DataTypeInfo.h
  SofaKernel/framework/sofa/simulation/MechanicalComputeEnergyVisitor.h
  SofaKernel/framework/sofa/simulation/MechanicalVisitor.h
  SofaKernel/framework/sofa/simulation/PropagateEventVisitor.h
  SofaKernel/framework/sofa/simulation/VectorOperations.h
  SofaKernel/framework/sofa/simulation/VisualVisitor.h
  SofaKernel/modules/SofaBaseLinearSolver/CompressedRowSparseMatrix.h
  modules/SofaGeneralAnimationLoop/MechanicalMatrixMapper.inl
Labels: pr: clean, pr: fix, status: ready

#969 [SofaKernel] FIX: A few fix to compile on Mac OSX Xcode 9 and Linux gcc 7.3.0
  SofaKernel/framework/sofa/core/objectmodel/BaseClass.cpp
  SofaKernel/framework/sofa/helper/CMakeLists.txt
  SofaKernel/framework/sofa/simulation/CMakeLists.txt
  SofaKernel/framework/sofa/simulation/Locks.h
Labels: pr: fix, status: ready
