Repository sofa-framework/sofa, pull requests merged in 2019-01, with the labels that each got.

#873 [All] Fix some warnings
  SofaKernel/framework/sofa/core/loader/MeshLoader.cpp
  SofaKernel/framework/sofa/core/loader/MeshLoader.h
  SofaKernel/modules/SofaBaseMechanics/DiagonalMass.h
  SofaKernel/modules/SofaBaseMechanics/DiagonalMass.inl
  SofaKernel/modules/SofaBaseTopology/HexahedronSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/QuadSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseVisual/VisualModelImpl.cpp
  SofaKernel/modules/SofaMeshCollision/LineModel.inl
  SofaKernel/modules/SofaMeshCollision/PointModel.inl
  SofaKernel/modules/SofaMeshCollision/TriangleLocalMinDistanceFilter.cpp
  SofaKernel/modules/SofaMeshCollision/TriangleModel.h
  SofaKernel/modules/SofaMeshCollision/TriangleModel.inl
  SofaKernel/modules/SofaSimpleFem/HexahedronFEMForceField.inl
  SofaKernel/modules/SofaSimpleFem/TetrahedronDiffusionFEMForceField.inl
  applications/plugins/Flexible/deformationMapping/BaseDeformationImpl.inl
  modules/SofaBoundaryCondition/EdgePressureForceField.inl
  modules/SofaBoundaryCondition/OscillatingTorsionPressureForceField.inl
  modules/SofaBoundaryCondition/QuadPressureForceField.inl
  modules/SofaBoundaryCondition/TrianglePressureForceField.inl
  modules/SofaConstraint/GenericConstraintSolver.cpp
  modules/SofaExporter/MeshExporter.cpp
  modules/SofaExporter/VTKExporter.cpp
  modules/SofaGeneralEngine/MergeVectors.inl
  modules/SofaGeneralMeshCollision/TriangleOctree.cpp
  modules/SofaGeneralSimpleFem/HexahedralFEMForceField.inl
  modules/SofaGeneralSimpleFem/TetrahedralCorotationalFEMForceField.inl
  modules/SofaMiscFem/FastTetrahedralCorotationalForceField.inl
  modules/SofaMiscFem/StandardTetrahedralFEMForceField.inl
  modules/SofaMiscFem/TetrahedralTensorMassForceField.inl
  modules/SofaMiscFem/TetrahedronHyperelasticityFEMForceField.inl
  modules/SofaMiscFem/TriangularFEMForceField.inl
  modules/SofaNonUniformFem/HexahedronCompositeFEMMapping.inl
  modules/SofaNonUniformFem/NonUniformHexahedralFEMForceFieldAndMass.inl
  modules/SofaOpenglVisual/DataDisplay.cpp
  modules/SofaTopologyMapping/Edge2QuadTopologicalMapping.cpp
  modules/SofaTopologyMapping/Hexa2QuadTopologicalMapping.cpp
  modules/SofaTopologyMapping/Hexa2TetraTopologicalMapping.cpp
  modules/SofaTopologyMapping/Quad2TriangleTopologicalMapping.cpp
  modules/SofaTopologyMapping/Tetra2TriangleTopologicalMapping.cpp
  modules/SofaTopologyMapping/Triangle2EdgeTopologicalMapping.cpp
  modules/SofaUserInteraction/EdgeSetController.inl
  modules/SofaUserInteraction/TopologicalChangeManager.cpp
Labels: pr: fix, status: ready

#881 [Icons] EDIT Sofa icons
  share/icons/MODELER.ico
  share/icons/MODELER.png
  share/icons/SOFA.ico
  share/icons/SOFA.png
  share/icons/SOFACONFIGURATION.png
Labels: enhancement, pr: fast-merge, status: ready

#872 [NG][Sofa.Helper] Differentiate classic library from plugins
  modules/Sofa/Component/CMakeLists.txt
  modules/Sofa/Component/Utils/CMakeLists.txt
  modules/Sofa/Helper/Bvh/CMakeLists.txt
  modules/Sofa/Helper/Bvh/config/Sofa.Helper.Bvh.cpp
  modules/Sofa/Helper/CMakeLists.txt
  modules/Sofa/Helper/config/Sofa.Helper.cpp
Labels: enhancement, pr: fast-merge, status: ready

#866 [SofaKernel] Some Topology cleaning...
  SofaKernel/framework/sofa/core/topology/BaseMeshTopology.cpp
  SofaKernel/framework/sofa/core/topology/BaseMeshTopology.h
  SofaKernel/framework/sofa/core/topology/Topology.h
  SofaKernel/framework/sofa/defaulttype/CMakeLists.txt
  SofaKernel/framework/sofa/defaulttype/TopologyTypes.h
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/MeshTopology.cpp
  SofaKernel/modules/SofaBaseTopology/MeshTopology.h
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyModifier.cpp
  examples/Components/topology/TopologicalModifiers/RemovingTetra2TriangleProcess.txt
  examples/RegressionTopologyScenes.regression-tests
  modules/SofaGeneralDeformable/VectorSpringForceField.inl
  modules/SofaTopologyMapping/Tetra2TriangleTopologicalMapping.cpp
Labels: pr: breaking, pr: clean, status: ready

#877 [SofaBaseTopology][DrawTools] Some fix/update in topology internal draw methods.
  SofaKernel/framework/sofa/core/visual/DrawToolGL.cpp
  SofaKernel/framework/sofa/core/visual/DrawToolGL.h
  SofaKernel/modules/SofaBaseTopology/HexahedronSetGeometryAlgorithms.h
  SofaKernel/modules/SofaBaseTopology/HexahedronSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/PointSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/QuadSetGeometryAlgorithms.h
  SofaKernel/modules/SofaBaseTopology/QuadSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetGeometryAlgorithms.h
  SofaKernel/modules/SofaBaseTopology/TriangleSetGeometryAlgorithms.h
  SofaKernel/modules/SofaBaseTopology/TriangleSetGeometryAlgorithms.inl
Labels: pr: fix, status: ready

#874 [SofaBaseTopology] Clean Topology logs and add AdvanceTimer logs
  SofaKernel/framework/sofa/core/topology/TopologyHandler.cpp
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/TopologyEngine.inl
  SofaKernel/modules/SofaBaseTopology/TriangleSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyAlgorithms.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyModifier.cpp
Labels: enhancement, status: ready

#891 FIX: removing PythonLibs target from SofaPython
  applications/plugins/SofaPython/CMakeLists.txt
  applications/plugins/SofaPython/SofaPythonConfig.cmake.in
Labels: pr: fix, status: ready

#890 [SOFAGUI] Fix missing profiling timers for BatchGUI and HeadlessRecorder
  applications/sofa/gui/BatchGUI.cpp
  applications/sofa/gui/headlessRecorder/HeadlessRecorder.cpp
Labels: pr: fix, status: ready

#898 [Geomagic] FIX compilation error in Geomagic plugin with removal of SOFA_FLOAT/DOUBLE
  applications/plugins/Geomagic/src/GeomagicDriver.cpp
  applications/plugins/Geomagic/src/GeomagicDriver.h
Labels: pr: fast-merge, pr: fix, status: ready

#897 [CMAKE] Add check to prevent the inclusion of non-existant file in cmake 3.13
  CMakeLists.txt
Labels: pr: fix, status: ready

#889 [SofaBaseTopology] Fix right setDirty/clean topologyData
  SofaKernel/modules/SofaBaseMechanics/UniformMass.cpp
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyModifier.cpp
  examples/Components/topology/TopologicalModifiers/HexahedronForceFieldTopologyChangeHandling.scn
  examples/Components/topology/TopologicalModifiers/QuadForceFieldTopologyChangeHandling.scn
  modules/SofaGeneralDeformable/QuadularBendingSprings.inl
Labels: pr: fix, status: ready

#878 [SofaBaseTopology] Change triangles orientation in tetrahedron
  SofaKernel/modules/SofaBaseTopology/MeshTopology.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/TetrahedronSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
Labels: pr: breaking, pr: fix, status: ready

#901 [SofaKernel] Remove multigroup option in MatrixLinearSolver
  SofaKernel/modules/SofaBaseLinearSolver/MatrixLinearSolver.cpp
  SofaKernel/modules/SofaBaseLinearSolver/MatrixLinearSolver.h
  SofaKernel/modules/SofaBaseLinearSolver/MatrixLinearSolver.inl
  modules/SofaPreconditioner/src/SofaPreconditioner/WarpPreconditioner.inl
Labels: pr: clean, status: ready
