Repository sofa-framework/sofa, pull requests merged in 2019-08, with the labels that each got.

#1115 [SofaConstraint] Fix UncoupledConstraintCorrection topology change handling
  modules/SofaConstraint/UncoupledConstraintCorrection.cpp
  modules/SofaConstraint/UncoupledConstraintCorrection.h
  modules/SofaConstraint/UncoupledConstraintCorrection.inl
Labels: pr: fix, project: Topology, status: ready

#1114 [CMake] v19.06 changes
  CMakeLists.txt
  SofaKernel/SofaFramework/SofaMacros.cmake
  SofaKernel/extlibs/newmat/CMakeLists.txt
  SofaKernel/extlibs/tinyxml/CMakeLists.txt
  SofaKernel/framework/sofa/core/CMakeLists.txt
  applications/projects/runSofa/CMakeLists.txt
  applications/sofa/gui/qt/CMakeLists.txt
  extlibs/csparse/CMakeLists.txt
  extlibs/gtest/CMakeLists.txt
  extlibs/libQGLViewer-2.7.1/QGLViewer/CMakeLists.txt
  scripts/linux-postinstall-fixup.sh
  scripts/macos-postinstall-fixup.sh
Labels: enhancement, pr: fix, status: ready

#1119 [FixedRotationConstraint ] Fix FixedRotationConstraint when using more than one locked axis
  examples/Components/constraint/FixedRotationConstraint.scn
  modules/SofaBoundaryCondition/FixedRotationConstraint.inl
Labels: pr: fix, status: ready

#1112 [Examples] Add some mesh and PR1000 demo scene
  examples/Demos/sofa_1000PR.scn
  share/mesh/sofa_logo.mtl
  share/mesh/sofa_logo.obj
  share/mesh/sofa_logo_collision.mtl
  share/mesh/sofa_logo_collision.obj
  share/mesh/square_2594_triangles.mtl
  share/mesh/square_2594_triangles.obj
Labels: enhancement, status: ready

#1123 [SofaMacros] FIX default module version
  SofaKernel/SofaFramework/SofaMacros.cmake
Labels: pr: fix, status: ready

#1111 [SofaKernel] Several fix in draw methods and topology warnings
  SofaKernel/framework/sofa/core/visual/DrawTool.h
  SofaKernel/framework/sofa/core/visual/DrawToolGL.cpp
  SofaKernel/framework/sofa/core/visual/DrawToolGL.h
  SofaKernel/framework/sofa/simulation/Simulation.cpp
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyContainer.cpp
  modules/SofaConstraint/FreeMotionAnimationLoop.cpp
  modules/SofaGeneralDeformable/TriangularBendingSprings.inl
  modules/SofaTopologyMapping/Tetra2TriangleTopologicalMapping.cpp
Labels: pr: clean, pr: fix, status: ready

#1113 [SofaKernel] ADD: DataTypeInfo<vector<string>> & improved doc
  SofaKernel/framework/sofa/defaulttype/DataTypeInfo.h
Labels: enhancement, status: ready

#1124 [CGALPlugin] Some cleanups to CylinderMesh
  applications/plugins/CGALPlugin/CylinderMesh.inl
Labels: location: plugins, pr: clean, pr: fast-merge, status: ready

#1118 [SofaKernel] ADD: static method in events to retrieve the classname
  SofaKernel/framework/sofa/core/objectmodel/DetachNodeEvent.h
  SofaKernel/framework/sofa/core/objectmodel/Event.h
  SofaKernel/framework/sofa/core/objectmodel/GUIEvent.h
  SofaKernel/framework/sofa/core/objectmodel/HapticDeviceEvent.h
  SofaKernel/framework/sofa/core/objectmodel/IdleEvent.cpp
  SofaKernel/framework/sofa/core/objectmodel/IdleEvent.h
  SofaKernel/framework/sofa/core/objectmodel/JoystickEvent.h
  SofaKernel/framework/sofa/core/objectmodel/KeypressedEvent.h
  SofaKernel/framework/sofa/core/objectmodel/KeyreleasedEvent.h
  SofaKernel/framework/sofa/core/objectmodel/MouseEvent.h
  SofaKernel/framework/sofa/core/objectmodel/ScriptEvent.h
  SofaKernel/framework/sofa/simulation/AnimateBeginEvent.h
  SofaKernel/framework/sofa/simulation/AnimateEndEvent.h
  SofaKernel/framework/sofa/simulation/CollisionBeginEvent.h
  SofaKernel/framework/sofa/simulation/CollisionEndEvent.h
  SofaKernel/framework/sofa/simulation/IntegrateBeginEvent.h
  SofaKernel/framework/sofa/simulation/IntegrateEndEvent.h
  SofaKernel/framework/sofa/simulation/PauseEvent.h
  SofaKernel/framework/sofa/simulation/PositionEvent.h
  SofaKernel/framework/sofa/simulation/UpdateMappingEndEvent.h
  applications/plugins/ARTrack/ARTrackEvent.h
  applications/plugins/MultiThreading/src/DataExchange.h
  applications/plugins/SofaPython/PythonScriptEvent.h
Labels: enhancement, pr: breaking, status: ready

#1125 [SofaKernel] Use links for input and output topologies of the barycentric mapping
  SofaKernel/framework/sofa/core/topology/TopologicalMapping.h
  SofaKernel/modules/SofaBaseMechanics/BarycentricMapping.h
  SofaKernel/modules/SofaBaseMechanics/BarycentricMapping.inl
Labels: pr: fix, status: ready

#1110 [Carving plugin] Small fix at init.
  applications/plugins/SofaCarving/CarvingManager.cpp
  applications/plugins/SofaCarving/examples/CarvingTool.scn
Labels: location: plugins, pr: fix, status: ready
