Repository sofa-framework/sofa, pull requests merged in 2019-09, with the labels that each got.

#1127 [SofaKernel] Add a strict option to the BoxROI to prevent partially inside element to be in the box.
  SofaKernel/modules/SofaEngine/BoxROI.h
  SofaKernel/modules/SofaEngine/BoxROI.inl
  applications/plugins/Flexible/Flexible_test/Material_test.cpp
  applications/plugins/Flexible/Flexible_test/scenes/CylinderTraction.scn
  applications/plugins/Flexible/Flexible_test/scenes/CylinderTractionElaston.scn
  applications/plugins/SofaTest/Elasticity_test.inl
Labels: enhancement, status: ready

#1116 [All] Code cleaning of multiple classes
  SofaKernel/modules/SofaBaseCollision/RigidCapsuleModel.cpp
  SofaKernel/modules/SofaBaseCollision/RigidCapsuleModel.h
  SofaKernel/modules/SofaBaseCollision/RigidCapsuleModel.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaStandardTetrahedralFEMForceField.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTriangularFEMForceFieldOptim.inl
  modules/SofaBoundaryCondition/LinearVelocityConstraint.h
  modules/SofaBoundaryCondition/LinearVelocityConstraint.inl
  modules/SofaBoundaryCondition/PatchTestMovementConstraint.h
  modules/SofaBoundaryCondition/PatchTestMovementConstraint.inl
  modules/SofaConstraint/ConstraintAnimationLoop.cpp
  modules/SofaConstraint/ConstraintAnimationLoop.h
  modules/SofaGeneralDeformable/FastTriangularBendingSprings.h
  modules/SofaGeneralDeformable/FastTriangularBendingSprings.inl
  modules/SofaGeneralEngine/MergeROIs.cpp
  modules/SofaGeneralEngine/MergeROIs.h
  modules/SofaGeneralSimpleFem/HexahedronFEMForceFieldAndMass.h
  modules/SofaGeneralSimpleFem/HexahedronFEMForceFieldAndMass.inl
  modules/SofaGeneralSimpleFem/TriangularFEMForceFieldOptim.h
  modules/SofaGeneralSimpleFem/TriangularFEMForceFieldOptim.inl
  modules/SofaNonUniformFem/HexahedronCompositeFEMForceFieldAndMass.h
  modules/SofaNonUniformFem/HexahedronCompositeFEMForceFieldAndMass.inl
  modules/SofaNonUniformFem/HexahedronCompositeFEMMapping.inl
  modules/SofaNonUniformFem/NonUniformHexahedronFEMForceFieldAndMass.cpp
  modules/SofaNonUniformFem/NonUniformHexahedronFEMForceFieldAndMass.h
  modules/SofaNonUniformFem/NonUniformHexahedronFEMForceFieldAndMass.inl
Labels: pr: clean, status: ready

#1093 [SofaKernel] Add option in StiffSpringFF to track list of input springs
  SofaKernel/modules/SofaDeformable/StiffSpringForceField.h
  SofaKernel/modules/SofaDeformable/StiffSpringForceField.inl
Labels: discussion, enhancement, status: ready

#1140 [SofaDefaulttype] FIX too many ExtVec warnings with GCC
  SofaKernel/framework/sofa/defaulttype/VecTypes.h
Labels: pr: fix, status: ready

#958 [Cgal plugin] Fix windows cmake dll path and add a scene example
  applications/plugins/CGALPlugin/CMakeLists.txt
  applications/plugins/CGALPlugin/scenes/MeshGenerationFromPolyhedron.scn
Labels: location: plugins, pr: fix, status: ready

#1129 [SofaCore][ExecParams] Remove thread specific declaration
  SofaKernel/framework/sofa/core/ExecParams.cpp
  SofaKernel/framework/sofa/simulation/Node.cpp
Labels: enhancement, project: Multithreading, status: ready

#1141 [SofaGeneralEngine] Added Rigid to Euler orientation export
  modules/SofaGeneralEngine/RigidToQuatEngine.h
  modules/SofaGeneralEngine/RigidToQuatEngine.inl
Labels: enhancement, pr: fast-merge, status: ready

#1142 [SofaKernel] Fix alloc size
  SofaKernel/framework/sofa/helper/vector_device.h
Labels: pr: fast-merge, pr: fix, status: ready

#1143 [SofaKernel] Add bloc access in basematrix
  SofaKernel/framework/sofa/defaulttype/BaseMatrix.h
Labels: pr: fix, status: ready

#1144 [SofaKernel] Fix useless warnings
  SofaKernel/framework/sofa/core/MultiVecId.h
  SofaKernel/framework/sofa/simulation/UpdateBoundingBoxVisitor.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#1161 [SofaKernel] FIX regex in SofaMacros.cmake
  SofaKernel/SofaFramework/SofaMacros.cmake
Labels: pr: fast-merge, pr: fix, status: to review

#1158 [SofaKernel] Fix some AdvanceTimer log missing
  SofaKernel/framework/sofa/simulation/CollisionAnimationLoop.cpp
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyModifier.cpp
  modules/SofaConstraint/FreeMotionAnimationLoop.cpp
  modules/SofaConstraint/LCPConstraintSolver.cpp
Labels: pr: fix, status: ready
