Repository sofa-framework/sofa, pull requests merged in 2019-02, with the labels that each got.

#910 [modules] FIX Windows linkage
  modules/SofaConstraint/ConstraintStoreLambdaVisitor.h
  modules/SofaGeneralAnimationLoop/CMakeLists.txt
  modules/SofaGeneralAnimationLoop/MechanicalMatrixMapper.cpp
  modules/SofaGeneralAnimationLoop/MechanicalMatrixMapper.h
  modules/SofaGeneralSimpleFem/TetrahedralCorotationalFEMForceField.h
  modules/SofaMiscFem/TetrahedronHyperelasticityFEMForceField.h
Labels: pr: fix, status: ready

#908 [Sofa] Replace depreciated c++ standard binder component
  SofaKernel/extlibs/eigen-3.2.7/Eigen/src/Core/Functors.h
  SofaKernel/framework/sofa/simulation/MechanicalVisitor.h
Labels: enhancement, status: ready

#912 [SofaCUDA] Fix cuda with latest API
  SofaKernel/modules/SofaRigid/JointSpringForceField.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaCollision.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaDiagonalMass.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaIdentityMapping.cpp
Labels: enhancement, location: plugins, status: ready

#921 [CImgPlugin] FIX: messed up package prefix in CImg
  applications/plugins/CImgPlugin/extlibs/CImg/CImgConfig.cmake.in
Labels: pr: fast-merge, pr: fix, status: to review

#909 [CMake] SofaMacros.cmake: deprecating sofa_create_package
  SofaKernel/SofaFramework/SofaMacros.cmake
  SofaKernel/extlibs/newmat/CMakeLists.txt
  SofaKernel/extlibs/tinyxml/CMakeLists.txt
  applications/packages/SofaAllCommonComponents/CMakeLists.txt
  applications/plugins/CImgPlugin/CMakeLists.txt
  applications/plugins/SceneCreator/CMakeLists.txt
  applications/plugins/SofaMiscCollision/CMakeLists.txt
  applications/plugins/SofaPython/CMakeLists.txt
  applications/plugins/SofaTest/CMakeLists.txt
  applications/projects/runSofa/Main.cpp
  extlibs/csparse/CMakeLists.txt
  extlibs/gtest/CMakeLists.txt
  extlibs/libQGLViewer-2.7.1/QGLViewer/CMakeLists.txt
  extlibs/metis-5.1.0/CMakeLists.txt
  modules/SofaPreconditioner/CMakeLists.txt
  modules/SofaSparseSolver/CMakeLists.txt
  tools/SofaGTestMain/CMakeLists.txt
Labels: enhancement, status: ready

#924 Fix barycentric mapping again
  SofaKernel/modules/SofaBaseMechanics/BarycentricMappers/BarycentricMapperTopologyContainer.inl
Labels: pr: fast-merge, pr: fix

#922 [examples] Remove scenes about deprecated components
  CHANGELOG.md
  applications/plugins/Flexible/examples/.scene-tests
  applications/plugins/OptiTrackNatNet/examples/.scene-tests
  examples/.scene-tests
  examples/Components/controller/ArticulatedHierarchyBVHController.scn
  examples/Components/controller/ArticulatedHierarchyBVHController.scn.view
  examples/Components/controller/EdgeSetController.scn
  examples/Components/controller/NodeToggleController.scn
  examples/Components/forcefield/BuoyantForceField.scn
  examples/Components/forcefield/BuoyantForceField2Boxes.scn
  examples/Components/forcefield/ForceMaskOff.scn
  examples/Components/forcefield/WashingMachineForceField.scn
  examples/Components/forcefield/WashingMachineForceField.scn.view
  examples/Components/mapping/CatmullRomSplineMapping.scn
  examples/Components/mapping/ProjectionToTargetLineMapping.scn
  examples/Components/mapping/ProjectionToTargetPlaneMapping.scn
  examples/Components/topology/HexaCenterPointMapping.scn
  examples/Components/topology/HexaCenterPointMapping.scn.view
  examples/Demos/10000.scn
  examples/Demos/10000.scn.qglviewer.view
Labels: pr: backport, pr: fast-merge, pr: fix, status: to review

#920 [GenericConstraintSolver] Convert static sized arrays to dynamic ones
  modules/SofaConstraint/ConstraintAnimationLoop.cpp
  modules/SofaConstraint/GenericConstraintSolver.cpp
Labels: pr: fix, status: ready

#882 [SofaGeneralAnimationLoop] Improve MechanicalMatrixMapper
  SofaKernel/framework/sofa/core/behavior/MixedInteractionForceField.cpp
  modules/SofaGeneralAnimationLoop/MechanicalMatrixMapper.cpp
  modules/SofaGeneralAnimationLoop/MechanicalMatrixMapper.h
  modules/SofaGeneralAnimationLoop/MechanicalMatrixMapper.inl
Labels: enhancement, status: ready

#903 [SofaMeshCollision] Fix TriangleModel to handle topology changes
  SofaKernel/modules/SofaMeshCollision/TriangleModel.h
  SofaKernel/modules/SofaMeshCollision/TriangleModel.inl
  applications/plugins/SofaMiscCollision/TriangleModelInRegularGrid.cpp
  examples/Components/topology/TopologicalModifiers/AddingTrianglesProcess.scn
  examples/Components/topology/TopologicalModifiers/RemovingTrianglesProcess.scn
  modules/SofaConstraint/LocalMinDistance.cpp
  modules/SofaGeneralMeshCollision/TriangleOctreeModel.cpp
  modules/SofaGraphComponent/SofaGraphComponent_test/SceneChecker_test.cpp
Labels: pr: clean, pr: fix, status: ready

#915 [SofaExporter] Modularize (+minor dependency cleaning)
  CMakeLists.txt
  SofaGeneral/CMakeLists.txt
  SofaGeneral/config.h.in
  applications/plugins/Registration/config.h.in
  applications/plugins/SofaDistanceGrid/config.h
  applications/plugins/SofaPython/CMakeLists.txt
  applications/plugins/SofaVolumetricData/config.h.in
  modules/CMakeLists.txt
  modules/SofaComponentGeneral/CMakeLists.txt
  modules/SofaComponentGeneral/initComponentGeneral.cpp
  modules/SofaEditor/python/SofaEditor/SofaEditor.so
  modules/SofaExporter/CMakeLists.txt
  modules/SofaExporter/SofaExporterConfig.cmake.in
  modules/SofaExporter/SofaExporter_test/CMakeLists.txt
  modules/SofaExporter/src/SofaExporter/BlenderExporter.cpp
  modules/SofaExporter/src/SofaExporter/BlenderExporter.h
  modules/SofaExporter/src/SofaExporter/BlenderExporter.inl
  modules/SofaExporter/src/SofaExporter/Exporter.cpp
  modules/SofaExporter/src/SofaExporter/Exporter.h
  modules/SofaExporter/src/SofaExporter/MeshExporter.cpp
  modules/SofaExporter/src/SofaExporter/MeshExporter.h
  modules/SofaExporter/src/SofaExporter/OBJExporter.cpp
  modules/SofaExporter/src/SofaExporter/OBJExporter.h
  modules/SofaExporter/src/SofaExporter/STLExporter.cpp
  modules/SofaExporter/src/SofaExporter/STLExporter.h
  modules/SofaExporter/src/SofaExporter/VTKExporter.cpp
  modules/SofaExporter/src/SofaExporter/VTKExporter.h
  modules/SofaExporter/src/SofaExporter/WriteState.cpp
  modules/SofaExporter/src/SofaExporter/WriteState.h
  modules/SofaExporter/src/SofaExporter/WriteState.inl
  modules/SofaExporter/src/SofaExporter/WriteTopology.cpp
  modules/SofaExporter/src/SofaExporter/WriteTopology.h
  modules/SofaExporter/src/SofaExporter/WriteTopology.inl
  modules/SofaExporter/src/SofaExporter/config.h
  modules/SofaExporter/src/SofaExporter/initExporter.cpp
  modules/SofaExporter/src/SofaExporter/initExporter.h
Labels: pr: clean, status: ready

#907 [SofaGeneralLinearSolver] Clean BTDLinearSolver
  modules/SofaGeneralLinearSolver/BTDLinearSolver.h
  modules/SofaGeneralLinearSolver/BTDLinearSolver.inl
Labels: pr: clean, status: ready

#923 [SofaLoader] Fix positions when handleSeams is activated in MeshObjLoader
  SofaKernel/modules/SofaLoader/MeshObjLoader.cpp
Labels: pr: fix, status: ready

#931 Three small fixes in SofaBaseLinearSolver, SofaBoundaryCondition, runSofa
  SofaKernel/modules/SofaBaseLinearSolver/MatrixLinearSolver.inl
  applications/sofa/gui/qt/panels/QDocBrowser.cpp
  modules/SofaBoundaryCondition/FixedConstraint.inl
Labels: pr: fast-merge, pr: fix, status: ready

#935 FIX : for compilation on Visual Studio 2015 with QWT plugin
  SofaKernel/framework/sofa/helper/deque.h
Labels: pr: fast-merge, status: ready

#925 [Geomagic] Add some better check at init and method to free driver
  applications/plugins/Geomagic/src/GeomagicDriver.cpp
  applications/plugins/Geomagic/src/GeomagicDriver.h
Labels: enhancement, location: plugins, status: ready

#929 [BaseObject::draw()] call the draw function during the Transparent pass
  SofaKernel/framework/sofa/simulation/VisualVisitor.cpp
Labels: enhancement, status: ready

#933 [SofaBaseVisual] Add default texcoord in VisualModel
  SofaKernel/modules/SofaBaseVisual/VisualModelImpl.cpp
  SofaKernel/modules/SofaBaseVisual/VisualModelImpl.h
  share/textures/colorMap.png
Labels: enhancement, status: ready

#913 [All] Plugins finding and loading
  CMakeLists.txt
  SofaKernel/framework/sofa/helper/system/DynamicLibrary.cpp
  SofaKernel/framework/sofa/helper/system/FileRepository.cpp
  SofaKernel/framework/sofa/helper/system/FileRepository.h
  SofaKernel/framework/sofa/helper/system/FileSystem.cpp
  SofaKernel/framework/sofa/helper/system/FileSystem.h
  SofaKernel/framework/sofa/helper/system/PluginManager.cpp
  SofaKernel/framework/sofa/helper/system/PluginManager.h
  applications/plugins/SofaPython/PythonEnvironment.cpp
  applications/plugins/SofaPython/PythonEnvironment.h
  applications/projects/runSofa/Main.cpp
  examples/Components/misc/AddResourceRepository.scn
  modules/SofaGraphComponent/RequiredPlugin.cpp
  modules/SofaMisc/AddResourceRepository.cpp
  modules/SofaMisc/AddResourceRepository.h
  modules/SofaMisc/SofaMisc_test/AddResourceRepository_test.cpp
Labels: enhancement, status: ready

#916 [all] Replace serr with the new msg_error() API.
  SofaKernel/framework/sofa/core/behavior/ForceField.inl
  SofaKernel/framework/sofa/core/behavior/Mass.inl
  SofaKernel/framework/sofa/core/behavior/MixedInteractionForceField.inl
  SofaKernel/framework/sofa/core/behavior/PairInteractionProjectiveConstraintSet.inl
  SofaKernel/modules/SofaBaseCollision/CapsuleModel.inl
  SofaKernel/modules/SofaBaseCollision/DefaultContactManager.cpp
  SofaKernel/modules/SofaBaseCollision/OBBModel.inl
  SofaKernel/modules/SofaBaseMechanics/SubsetMapping.inl
  SofaKernel/modules/SofaBaseTopology/MeshTopology.cpp
  SofaKernel/modules/SofaMeshCollision/LineModel.inl
  SofaKernel/modules/SofaRigid/JointSpringForceField.inl
  examples/Components/topology/TopologicalModifiers/RemovingTriangle2EdgeProcess.scn
  modules/SofaBoundaryCondition/AffineMovementConstraint.inl
  modules/SofaBoundaryCondition/EdgePressureForceField.inl
  modules/SofaBoundaryCondition/EllipsoidForceField.inl
  modules/SofaBoundaryCondition/PositionBasedDynamicsConstraint.inl
  modules/SofaBoundaryCondition/TaitSurfacePressureForceField.inl
  modules/SofaGeneralDeformable/TriangularBendingSprings.inl
  modules/SofaGeneralEngine/ClusteringEngine.inl
  modules/SofaGeneralEngine/TransformPosition.inl
  modules/SofaGeneralEngine/ValuesFromIndices.inl
  modules/SofaHaptics/LCPForceFeedback.inl
  modules/SofaNonUniformFem/NonUniformHexahedronFEMForceFieldAndMass.inl
  modules/SofaSparseSolver/src/SofaSparseSolver/PrecomputedLinearSolver.inl
  modules/SofaTopologyMapping/IdentityTopologicalMapping.cpp
  modules/SofaTopologyMapping/Mesh2PointMechanicalMapping.inl
  modules/SofaValidation/EvalPointsDistance.inl
  modules/SofaValidation/EvalSurfaceDistance.inl
Labels: pr: clean, status: to review

#937 Add possibilities to draw lines on surfaces in DrawTool
  SofaKernel/framework/sofa/core/visual/DrawTool.h
  SofaKernel/framework/sofa/core/visual/DrawToolGL.cpp
  SofaKernel/framework/sofa/core/visual/DrawToolGL.h
Labels: pr: fast-merge, status: ready

#930 [CollisionVisitor] primitive tests count
  SofaKernel/framework/sofa/core/collision/NarrowPhaseDetection.h
  SofaKernel/framework/sofa/simulation/CollisionVisitor.cpp
  SofaKernel/framework/sofa/simulation/CollisionVisitor.h
Labels: enhancement, status: ready

#948 [SpringForceField] Merge 2 ctor into a templated one
  SofaKernel/modules/SofaDeformable/SpringForceField.h
Labels: enhancement, refactoring, status: ready
