Repository sofa-framework/sofa, pull requests merged in 2020-02, with the labels that each got.

#1247 [SofaMiscTopology] Fix bug in TopologicalChangeProcessor
  modules/SofaMiscTopology/TopologicalChangeProcessor.cpp
Labels: pr: fast-merge, pr: fix, project: Topology, status: ready

#1248 [SofaSimulationCore] Add a way to fill a multi vector from a base vector with a MechanicalOperations (mops).
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalMatrixVisitor.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalOperations.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalOperations.h
Labels: enhancement, pr: fast-merge, status: ready

#1251 [SofaDefaultType] Add a Ray type.
  SofaKernel/modules/SofaDefaultType/CMakeLists.txt
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/Ray.h
Labels: enhancement, status: ready

#1252 [SofaCore/Visual] Add new functions in drawTool (BREAKING)
  SofaKernel/modules/SofaCore/src/sofa/core/visual/DrawTool.h
  SofaKernel/modules/SofaCore/src/sofa/core/visual/DrawToolGL.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/visual/DrawToolGL.h
Labels: enhancement, pr: breaking, status: ready

#1254 [SofaKernel/SofaHelper] Add auto-friendly getWriteAccessors/getReadAcessor...
  SofaKernel/modules/SofaHelper/src/sofa/helper/accessor.h
Labels: enhancement, status: ready

#1256 [SofaHelper] Add the obj id to labels when available
  SofaKernel/modules/SofaHelper/src/sofa/helper/AdvancedTimer.cpp
Labels: enhancement, status: ready
