Repository sofa-framework/sofa, pull requests merged in 2020-07, with the labels that each got.

#1426 [SofaHelper] Fix fixed_array compilation with VS2019
  SofaKernel/modules/SofaHelper/src/sofa/helper/fixed_array.h
Labels: bug (major), pr: fast-merge, pr: fix, status: to review

#1434 [SofaHelper] ADD: singleton for ConsoleMessageHandler
  SofaKernel/modules/SofaHelper/src/sofa/helper/logging/ConsoleMessageHandler.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/logging/ConsoleMessageHandler.h
Labels: pr: fast-merge, status: ready

#1342 [SofaKernel] ADD: add polynomial springs force fields
  SofaKernel/modules/SofaDeformable/CMakeLists.txt
  SofaKernel/modules/SofaDeformable/PolynomialRestShapeSpringsForceField.cpp
  SofaKernel/modules/SofaDeformable/PolynomialRestShapeSpringsForceField.h
  SofaKernel/modules/SofaDeformable/PolynomialRestShapeSpringsForceField.inl
  SofaKernel/modules/SofaDeformable/PolynomialSpringsForceField.cpp
  SofaKernel/modules/SofaDeformable/PolynomialSpringsForceField.h
  SofaKernel/modules/SofaDeformable/PolynomialSpringsForceField.inl
  SofaKernel/modules/SofaDeformable/SofaDeformable_test/CMakeLists.txt
  SofaKernel/modules/SofaDeformable/SofaDeformable_test/PolynomialRestShapeSpringsForceField_test.cpp
  examples/Components/forcefield/PolynomialRestShapeSpringsForceField.scn
  examples/Components/forcefield/PolynomialSpringsForceField.scn
Labels: pr: new feature, status: ready

#1437 [SofaSparseSolver] FIX Metis and CSparse not found in install
  modules/SofaSparseSolver/SofaSparseSolverConfig.cmake.in
Labels: pr: backport, pr: fast-merge, pr: fix, status: ready

#1436 [SofaKernel] Add setLinkedBase method in BaseLink
  SofaKernel/modules/SofaCore/SofaCore_test/objectmodel/BaseLink_test.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseLink.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseLink.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Link.h
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/CMakeLists.txt
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/Link_test.cpp
Labels: pr: fast-merge, pr: new feature, status: ready

#1440 [SofaSparseSolver] FIX Metis and CSparse not found in install (redo)
  modules/SofaSparseSolver/CMakeLists.txt
  modules/SofaSparseSolver/SofaSparseSolverConfig.cmake.in
Labels: pr: fast-merge, pr: fix, status: ready
