Repository sofa-framework/sofa, pull requests merged in 2020-10, with the labels that each got.

#1490 [SofaKernel] Remove parentBaseData in BaseData.h
  SofaKernel/modules/SofaCore/SofaCore_test/objectmodel/DataLink_test.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Data.h
  SofaKernel/modules/SofaDeformable/MeshSpringForceField.h
  SofaKernel/modules/SofaDeformable/StiffSpringForceField.h
  modules/SofaGeneralDeformable/MeshSpringForceField.inl
  modules/SofaGeneralDeformable/RegularGridSpringForceField.h
Labels: pr: clean, pr: fast-merge, refactoring, status: to review

#1511 Use d_showColor for indices instead of arbitrary white
  SofaKernel/modules/SofaBaseMechanics/MechanicalObject.inl
Labels: pr: fast-merge, pr: fix, status: ready

#1516 [SofaGeneralEngine] Fix BarycentricMapperEngine parse() function
  modules/SofaGeneralEngine/MeshBarycentricMapperEngine.h
Labels: pr: fast-merge, pr: fix, status: ready

#1503 [SofaKernel] Remove support for BaseData in Link.h
  SofaKernel/modules/SofaCore/src/sofa/core/PathResolver.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/PathResolver.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseLink.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Data.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DataContentValue.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Link.h
  SofaKernel/modules/SofaDeformable/MeshSpringForceField.inl
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalVisitor.h
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/Link_test.cpp
Labels: pr: clean, refactoring, status: ready

#1508 [SofaQtGui] Restore GraphWidget for Momentum and Energy using QtCharts instead of Qwt
  modules/SofaGuiQt/CMakeLists.txt
  modules/SofaGuiQt/src/sofa/gui/qt/ModifyObject.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/ModifyObject.h
  modules/SofaGuiQt/src/sofa/gui/qt/QDisplayPropertyWidget.h
  modules/SofaGuiQt/src/sofa/gui/qt/QEnergyStatWidget.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/QEnergyStatWidget.h
  modules/SofaGuiQt/src/sofa/gui/qt/QGraphStatWidget.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/QGraphStatWidget.h
  modules/SofaGuiQt/src/sofa/gui/qt/QMomentumStatWidget.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/QMomentumStatWidget.h
Labels: enhancement, status: ready

#1519 [SofaKernel] Remove un-needed StringUtil.h in Base.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.h
Labels: pr: clean, pr: fast-merge, status: ready

#1542 [SofaSPHFluid] Fix compilation with std::execution
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidForceField.inl
Labels: pr: fast-merge, pr: fix, status: ready

#1514 [All] Change index_type from size_t to uint
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/TopologySubsetDataHandler.h
  SofaKernel/modules/SofaBaseTopology/TopologySubsetDataHandler.inl
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/BaseMechanicalState.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/MechanicalState.h
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseTopology.h
  SofaKernel/modules/SofaCore/src/sofa/core/topology/Topology.h
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologyHandler.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/TopologyTypes.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/MarchingCubeUtility.cpp
  SofaKernel/modules/SofaMeshCollision/BarycentricContactMapper.h
  SofaKernel/modules/SofaMeshCollision/TriangleModel.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping.inl
Labels: pr: breaking, pr: fix, status: ready

#1532 [SofaCarving] Fix method doCarve should be called at AnimateEndEvent
  applications/plugins/SofaCarving/CarvingManager.cpp
Labels: pr: fast-merge, pr: fix, status: to review

#1541 [SofaKernel] Remove un-needed class reflection system.
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.h
Labels: pr: clean, pr: fast-merge, status: ready

#1522 [CGALPlugin] Fix compilation for CGal version > 5
  applications/plugins/CGALPlugin/src/CGALPlugin/CylinderMesh.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.h
  applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/Refine2DMesh.inl
Labels: pr: fast-merge, pr: fix, status: ready

#1530 [SofaGeneral] Pluginize SofaGeneralVisual
  CMakeLists.txt
  SofaGeneral/CMakeLists.txt
  SofaGeneral/src/SofaGeneral/initSofaGeneral.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.cpp
  applications/plugins/image/CMakeLists.txt
  examples/Components/visualmodel/NavigationRecordedCamera.scn
  examples/Components/visualmodel/RecordedCamera.scn
  modules/SofaGeneralVisual/CMakeLists.txt
  modules/SofaGeneralVisual/README.md
  modules/SofaGeneralVisual/SofaGeneralVisualConfig.cmake.in
  modules/SofaGeneralVisual/VisualTransform.h
  modules/SofaGeneralVisual/src/SofaGeneralVisual/RecordedCamera.cpp
  modules/SofaGeneralVisual/src/SofaGeneralVisual/RecordedCamera.h
  modules/SofaGeneralVisual/src/SofaGeneralVisual/Visual3DText.cpp
  modules/SofaGeneralVisual/src/SofaGeneralVisual/Visual3DText.h
  modules/SofaGeneralVisual/src/SofaGeneralVisual/VisualTransform.cpp
  modules/SofaGeneralVisual/src/SofaGeneralVisual/VisualTransform.h
  modules/SofaGeneralVisual/src/SofaGeneralVisual/config.h.in
  modules/SofaGeneralVisual/src/SofaGeneralVisual/initSofaGeneralVisual.cpp
  modules/SofaGeneralVisual/src/SofaGeneralVisual/initSofaGeneralVisual.h
  modules/SofaUserInteraction/CMakeLists.txt
Labels: NG2: modularization, pr: clean, status: ready

#1533 [Geomagic] Update demo scenes to use direct solvers.
  applications/plugins/Geomagic/scenes/Geomagic-DeformableCubes.scn
  applications/plugins/Geomagic/scenes/Geomagic-FEMLiver.scn
  applications/plugins/Geomagic/scenes/Geomagic-RigidCubes.scn
  applications/plugins/Geomagic/scenes/Geomagic-RigidSkull-restShapeSpringForceField.scn
  applications/plugins/Geomagic/scenes/Geomagic-RigidSkull.scn
Labels: pr: clean, pr: fast-merge, status: ready

#1540 [SofaGeneral] Pluginize SofaGeneralMeshCollision
  CMakeLists.txt
  SofaGeneral/CMakeLists.txt
  SofaGeneral/src/SofaGeneral/initSofaGeneral.cpp
  examples/Components/collision/RayTraceCollision.scn
  examples/Objects/SMP/TorusFEMOctree.xml
  examples/Objects/SMP/TorusRigidOctree.xml
  modules/SofaGeneralMeshCollision/CMakeLists.txt
  modules/SofaGeneralMeshCollision/README.md
  modules/SofaGeneralMeshCollision/SofaGeneralMeshCollisionConfig.cmake.in
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/DirectSAP.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/DirectSAP.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/IncrSAP.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/IncrSAP.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshDiscreteIntersection.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshDiscreteIntersection.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshDiscreteIntersection.inl
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshMinProximityIntersection.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshMinProximityIntersection.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/TriangleOctree.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/TriangleOctree.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/TriangleOctreeModel.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/TriangleOctreeModel.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/config.h.in
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/initSofaGeneralMeshCollision.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/initSofaGeneralMeshCollision.h
Labels: NG2: pluginization, pr: clean, status: to review

#1554 [SofaGeneralLoader] fix GIDMeshLoader and add example
  SofaKernel/modules/SofaCore/src/sofa/core/loader/MeshLoader.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/loader/MeshLoader.h
  SofaKernel/modules/SofaLoader/MeshVTKLoader.cpp
  examples/Components/loader/GIDMeshLoader.scn
  modules/SofaGeneralLoader/GIDMeshLoader.cpp
  modules/SofaGeneralLoader/GIDMeshLoader.h
  modules/SofaGeneralLoader/MeshGmshLoader.cpp
  modules/SofaGeneralLoader/MeshOffLoader.cpp
  modules/SofaGeneralLoader/MeshSTLLoader.cpp
  modules/SofaGeneralLoader/MeshTrianLoader.cpp
  share/mesh/tripod.gidmsh
Labels: pr: fix, status: ready

#1510 [SofaImplicitField] Add new ImplicitFields and getHessian to ScalarField
  applications/plugins/SofaImplicitField/CMakeLists.txt
  applications/plugins/SofaImplicitField/components/geometry/BottleField.cpp
  applications/plugins/SofaImplicitField/components/geometry/BottleField.h
  applications/plugins/SofaImplicitField/components/geometry/ScalarField.cpp
  applications/plugins/SofaImplicitField/components/geometry/ScalarField.h
  applications/plugins/SofaImplicitField/components/geometry/StarShapedField.cpp
  applications/plugins/SofaImplicitField/components/geometry/StarShapedField.h
Labels: pr: new feature, status: ready

#1545 [SofaBaseTopology] Rework method getIntersectionPointWithPlane
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetGeometryAlgorithms.h
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetGeometryAlgorithms.inl
Labels: pr: clean, status: ready

#1574 [plugins] Reactivate SofaPython3
  applications/plugins/CMakeLists.txt
Labels: pr: clean, pr: fast-merge, status: to review

#1577 [SofaBaseTopology] Fix ambiguity causing compilation error with MSVC
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyModifier.cpp
Labels: pr: clean, pr: fast-merge, status: to review

#1570 [SofaGUI] Fix Cmake files for out-of-tree compilation
  SofaAdvanced/CMakeLists.txt
  SofaAdvanced/SofaAdvancedConfig.cmake.in
  SofaGeneral/SofaGeneralConfig.cmake.in
  SofaGui/SofaGuiConfig.cmake.in
  SofaKernel/SofaBase/SofaBaseConfig.cmake.in
  SofaKernel/SofaCommon/SofaCommonConfig.cmake.in
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
  SofaKernel/SofaFramework/SofaMacrosInstall.cmake
  SofaKernel/SofaSimulation/SofaSimulationConfig.cmake.in
  SofaMisc/CMakeLists.txt
  SofaMisc/SofaMiscConfig.cmake.in
  applications/collections/SofaComponentAll/SofaComponentAllConfig.cmake.in
  applications/projects/Modeler/lib/SofaModelerConfig.cmake.in
  applications/projects/SofaPhysicsAPI/SofaPhysicsAPIConfig.cmake.in
  modules/SofaDenseSolver/CMakeLists.txt
  modules/SofaDenseSolver/SofaDenseSolverConfig.cmake.in
  modules/SofaExporter/CMakeLists.txt
  modules/SofaExporter/SofaExporterConfig.cmake.in
  modules/SofaGeneralMeshCollision/CMakeLists.txt
  modules/SofaGeneralMeshCollision/SofaGeneralMeshCollisionConfig.cmake.in
  modules/SofaGeneralVisual/CMakeLists.txt
  modules/SofaGeneralVisual/SofaGeneralVisualConfig.cmake.in
  modules/SofaGraphComponent/CMakeLists.txt
  modules/SofaGraphComponent/SofaGraphComponentConfig.cmake.in
  modules/SofaGuiCommon/CMakeLists.txt
  modules/SofaGuiQt/CMakeLists.txt
  modules/SofaHaptics/CMakeLists.txt
  modules/SofaHaptics/SofaHapticsConfig.cmake.in
  modules/SofaMiscEngine/CMakeLists.txt
  modules/SofaMiscEngine/SofaMiscEngineConfig.cmake.in
  modules/SofaMiscExtra/CMakeLists.txt
  modules/SofaMiscExtra/SofaMiscExtraConfig.cmake.in
  modules/SofaMiscFem/CMakeLists.txt
  modules/SofaMiscFem/SofaMiscFemConfig.cmake.in
  modules/SofaMiscForceField/CMakeLists.txt
  modules/SofaMiscForceField/SofaMiscForceFieldConfig.cmake.in
  modules/SofaMiscMapping/CMakeLists.txt
  modules/SofaMiscMapping/SofaMiscMappingConfig.cmake.in
  modules/SofaMiscSolver/CMakeLists.txt
  modules/SofaMiscSolver/SofaMiscSolverConfig.cmake.in
  modules/SofaMiscTopology/CMakeLists.txt
  modules/SofaMiscTopology/SofaMiscTopologyConfig.cmake.in
  modules/SofaNonUniformFem/CMakeLists.txt
  modules/SofaNonUniformFem/SofaNonUniformFemConfig.cmake.in
  modules/SofaOpenglVisual/CMakeLists.txt
  modules/SofaOpenglVisual/SofaOpenglVisualConfig.cmake.in
  modules/SofaPreconditioner/CMakeLists.txt
  modules/SofaPreconditioner/SofaPreconditionerConfig.cmake.in
  modules/SofaSparseSolver/CMakeLists.txt
  modules/SofaSparseSolver/SofaSparseSolverConfig.cmake.in
  modules/SofaValidation/CMakeLists.txt
  modules/SofaValidation/SofaValidationConfig.cmake.in
  tools/SofaGTestMain/SofaGTestMainConfig.cmake.in
Labels: pr: fast-merge, pr: fix, status: ready

#1578 [SofaHelper] Link necessary Boost macro with SofaHelper (for Windows)
  CMakeLists.txt
  SofaKernel/modules/SofaHelper/CMakeLists.txt
Labels: pr: clean, pr: fast-merge, pr: fix, status: ready

#1537 [SofaHaptics] Small fix on LCPForceFeedback haptic rendering
  modules/SofaHaptics/src/SofaHaptics/LCPForceFeedback.inl
Labels: pr: clean, status: to review
