Repository sofa-framework/sofa, pull requests merged in 2020-12, with the labels that each got.

#1631 [SofaMacros] FIX RELOCATABLE_INSTALL_DIR target property
  SofaKernel/SofaFramework/SofaMacrosInstall.cmake
Labels: pr: fast-merge, pr: fix, status: ready

#1638 [SofaGraphComponent] Add a msgendl in scenechecker
  modules/SofaGraphComponent/src/SofaGraphComponent/SceneCheckMissingRequiredPlugin.cpp
Labels: pr: fast-merge, status: ready

#1612 [SofaKernel] Remove core::Plugin/core::PluginManager
  SofaKernel/modules/SofaCore/CMakeLists.txt
  SofaKernel/modules/SofaCore/SofaCore_test/PluginTest.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/Plugin.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/Plugin.h
  SofaKernel/modules/SofaCore/src/sofa/core/PluginManager.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/PluginManager.h
  applications/plugins/SofaEulerianFluid/EulerianFluid.cpp
  applications/plugins/SofaEulerianFluid/EulerianFluid.h
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/MiscCollision.cpp
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/MiscCollision.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SphFluid.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SphFluid.h
Labels: pr: clean, status: ready

#1641 [SofaKernel] Fix warning caused by unused arg in NoTypeInfo.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/typeinfo/NoTypeInfo.h
Labels: pr: fast-merge, status: ready

#1615 [SofaKernel] FIX PluginManager::pluginIsLoaded
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/PluginManager.cpp
Labels: bug (minor), status: ready

#1648 [runSofa] CLEAN unused dep to SofaGeneralLoader
  applications/projects/runSofa/Main.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#1646 [SofaHelper] Remove OpenGL dependency in vector_device
  SofaKernel/modules/SofaHelper/src/sofa/helper/MemoryManager.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/vector_device.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMemoryManager.h
  applications/plugins/SofaOpenCL/OpenCLMemoryManager.h
Labels: pr: clean, pr: fast-merge, status: ready

#1647 [SofaOpenCL] Fix Cmake configuration
  applications/plugins/SofaOpenCL/CMakeLists.txt
Labels: pr: fast-merge, pr: fix, status: ready

#1639 [all] Remove equality operator from Data
  SofaKernel/SofaFramework/src/sofa/config.h.in
  SofaKernel/modules/SofaBaseVisual/BaseCamera.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/loader/MeshLoader.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Data.h
  applications/plugins/SensableEmulation/OmniDriverEmu.cpp
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/SurfacePressureForceField.inl
  modules/SofaGeneralAnimationLoop/src/SofaGeneralAnimationLoop/MechanicalMatrixMapper.inl
  modules/SofaValidation/SofaValidation_test/Monitor_test.cpp
Labels: pr: fast-merge, status: ready

#1643 [all] Disable the very verbose -Wattribute warning and promote deprecation as error
  SofaKernel/SofaFramework/src/sofa/config.h.in
  SofaKernel/modules/SofaCore/src/sofa/core/ExecParams.h
  SofaKernel/modules/SofaCore/src/sofa/core/ObjectFactory.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseClass.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseLink.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DDGNode.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Data.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DataFileName.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Link.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/RGBAColor.h
Labels: pr: fast-merge, status: ready

#1652 [SofaKernel] Improve the object factory message for duplicated entries
  SofaKernel/modules/SofaCore/src/sofa/core/ObjectFactory.cpp
Labels: pr: fast-merge, status: ready

#1599 [SofaCommon] Pluginize SofaRigid
  CMakeLists.txt
  SofaKernel/SofaCommon/CMakeLists.txt
  SofaKernel/SofaCommon/SofaCommonConfig.cmake.in
  SofaKernel/SofaCommon/src/SofaCommon/initSofaCommon.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.cpp
  SofaKernel/modules/SofaRigid/CMakeLists.txt
  SofaKernel/modules/SofaRigid/README.md
  SofaKernel/modules/SofaRigid/SofaRigidConfig.cmake.in
  SofaKernel/modules/SofaRigid/SofaRigid_test/CMakeLists.txt
  SofaKernel/modules/SofaRigid/src/SofaRigid/JointSpring.cpp
  SofaKernel/modules/SofaRigid/src/SofaRigid/JointSpring.h
  SofaKernel/modules/SofaRigid/src/SofaRigid/JointSpring.inl
  SofaKernel/modules/SofaRigid/src/SofaRigid/JointSpringForceField.cpp
  SofaKernel/modules/SofaRigid/src/SofaRigid/JointSpringForceField.h
  SofaKernel/modules/SofaRigid/src/SofaRigid/JointSpringForceField.inl
  SofaKernel/modules/SofaRigid/src/SofaRigid/RigidMapping.cpp
  SofaKernel/modules/SofaRigid/src/SofaRigid/RigidMapping.h
  SofaKernel/modules/SofaRigid/src/SofaRigid/RigidMapping.inl
  SofaKernel/modules/SofaRigid/src/SofaRigid/RigidRigidMapping.cpp
  SofaKernel/modules/SofaRigid/src/SofaRigid/RigidRigidMapping.h
  SofaKernel/modules/SofaRigid/src/SofaRigid/RigidRigidMapping.inl
  SofaKernel/modules/SofaRigid/src/SofaRigid/config.h.in
  SofaKernel/modules/SofaRigid/src/SofaRigid/initSofaRigid.cpp
  SofaKernel/modules/SofaRigid/src/SofaRigid/initSofaRigid.h
  SofaKernel/modules/SofaSimpleFem/CMakeLists.txt
  modules/SofaGuiQt/src/sofa/gui/qt/StructDataWidget.h
  tests/CMakeLists.txt
Labels: NG2: pluginization, pr: clean, status: ready

#1600 [SofaCommon] Pluginize SofaDeformable
  CMakeLists.txt
  SofaKernel/SofaCommon/CMakeLists.txt
  SofaKernel/SofaCommon/src/SofaCommon/initSofaCommon.cpp
  SofaKernel/modules/SofaDeformable/CMakeLists.txt
  SofaKernel/modules/SofaDeformable/README.md
  SofaKernel/modules/SofaDeformable/SofaDeformableConfig.cmake.in
  SofaKernel/modules/SofaDeformable/SofaDeformable_test/CMakeLists.txt
  SofaKernel/modules/SofaDeformable/config.h
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/AngularSpringForceField.cpp
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/AngularSpringForceField.h
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/AngularSpringForceField.inl
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/MeshSpringForceField.cpp
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/MeshSpringForceField.h
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/MeshSpringForceField.inl
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/PolynomialRestShapeSpringsForceField.cpp
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/PolynomialRestShapeSpringsForceField.h
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/PolynomialRestShapeSpringsForceField.inl
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/PolynomialSpringsForceField.cpp
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/PolynomialSpringsForceField.h
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/PolynomialSpringsForceField.inl
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/RestShapeSpringsForceField.cpp
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/RestShapeSpringsForceField.h
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/RestShapeSpringsForceField.inl
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/SpringForceField.cpp
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/SpringForceField.h
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/SpringForceField.inl
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/StiffSpringForceField.cpp
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/StiffSpringForceField.h
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/StiffSpringForceField.inl
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/config.h.in
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/initSofaDeformable.cpp
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/initSofaDeformable.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/SofaImplicitOdeSolver_test/loadPlugins.cpp
  SofaKernel/modules/SofaRigid/src/SofaRigid/config.h.in
  modules/SofaGuiQt/src/sofa/gui/qt/StructDataWidget.h
  tests/CMakeLists.txt
Labels: NG2: pluginization, pr: clean, status: ready

#1658 [SofaFramework] Fix deprecated_as_error macro for MSVC
  SofaKernel/SofaFramework/src/sofa/config.h.in
Labels: pr: fast-merge, pr: fix, status: to review

#1601 [SofaCommon] Pluginize SofaObjectInteraction
  CMakeLists.txt
  SofaKernel/SofaCommon/CMakeLists.txt
  SofaKernel/SofaCommon/src/SofaCommon/initSofaCommon.cpp
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/RestShapeSpringsForceField.inl
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/config.h.in
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.cpp
  SofaKernel/modules/SofaObjectInteraction/CMakeLists.txt
  SofaKernel/modules/SofaObjectInteraction/README.md
  SofaKernel/modules/SofaObjectInteraction/SofaObjectInteractionConfig.cmake.in
  SofaKernel/modules/SofaObjectInteraction/src/SofaObjectInteraction/PenalityContactForceField.cpp
  SofaKernel/modules/SofaObjectInteraction/src/SofaObjectInteraction/PenalityContactForceField.h
  SofaKernel/modules/SofaObjectInteraction/src/SofaObjectInteraction/PenalityContactForceField.inl
  SofaKernel/modules/SofaObjectInteraction/src/SofaObjectInteraction/config.h.in
  SofaKernel/modules/SofaObjectInteraction/src/SofaObjectInteraction/initSofaObjectInteraction.cpp
  SofaKernel/modules/SofaObjectInteraction/src/SofaObjectInteraction/initSofaObjectInteraction.h
Labels: NG2: pluginization, pr: clean, status: ready

#1593 [All] Factorize and rename TopologyObjectType into TopologyElementType
  SofaKernel/modules/SofaBaseMechanics/DiagonalMass.h
  SofaKernel/modules/SofaBaseMechanics/DiagonalMass.inl
  SofaKernel/modules/SofaBaseTopology/EdgeSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/MeshTopology.cpp
  SofaKernel/modules/SofaBaseTopology/MeshTopology.h
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/EdgeSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/HexahedronSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/MeshTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/QuadSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/TetrahedronSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/TriangleSetTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/fake_TopologyScene.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/fake_TopologyScene.h
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/TriangleSetGeometryAlgorithms.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetGeometryAlgorithms.h
  SofaKernel/modules/SofaBaseTopology/TriangleSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.h
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseMeshTopology.h
  SofaKernel/modules/SofaCore/src/sofa/core/topology/Topology.h
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologyChange.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologyChange.h
  applications/plugins/ManifoldTopologies/ManifoldTriangleSetGeometryAlgorithms.h
  applications/plugins/ManifoldTopologies/ManifoldTriangleSetGeometryAlgorithms.inl
  applications/plugins/SofaPython/Binding_TopologyChange.cpp
  modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.h
  modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.inl
  modules/SofaMiscTopology/src/SofaMiscTopology/TopologicalChangeProcessor.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/InciseAlongPathPerformer.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/RemovePrimitivePerformer.h
  modules/SofaUserInteraction/src/SofaUserInteraction/RemovePrimitivePerformer.inl
  modules/SofaUserInteraction/src/SofaUserInteraction/TopologicalChangeManager.cpp
Labels: pr: breaking, pr: clean, status: ready

#1606 [SofaCommon] Pluginize SofaExplicitOdeSolver
  CMakeLists.txt
  SofaKernel/SofaCommon/CMakeLists.txt
  SofaKernel/SofaCommon/src/SofaCommon/initSofaCommon.cpp
  SofaKernel/modules/SofaExplicitOdeSolver/CMakeLists.txt
  SofaKernel/modules/SofaExplicitOdeSolver/README.md
  SofaKernel/modules/SofaExplicitOdeSolver/SofaExplicitOdeSolverConfig.cmake.in
  SofaKernel/modules/SofaExplicitOdeSolver/SofaExplicitOdeSolver_test/CMakeLists.txt
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/EulerSolver.cpp
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/EulerSolver.h
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/config.h.in
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/initSofaExplicitOdeSolver.cpp
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/initSofaExplicitOdeSolver.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.cpp
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/PointModel.cpp
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/initSofaMeshCollision.cpp
  tests/CMakeLists.txt
Labels: NG2: pluginization, pr: clean, status: to review

#1607 [SofaCommon] Pluginize SofaImplicitOdeSolver
  CMakeLists.txt
  SofaKernel/SofaCommon/CMakeLists.txt
  SofaKernel/SofaCommon/src/SofaCommon/initSofaCommon.cpp
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/initSofaExplicitOdeSolver.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/CMakeLists.txt
  SofaKernel/modules/SofaImplicitOdeSolver/README.md
  SofaKernel/modules/SofaImplicitOdeSolver/SofaImplicitOdeSolverConfig.cmake.in
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/EulerImplicitSolver.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/EulerImplicitSolver.h
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/StaticSolver.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/StaticSolver.h
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/config.h.in
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/initSofaImplicitOdeSolver.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/initSofaImplicitOdeSolver.h
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/BarycentricPenalityContact.h
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/PointModel.cpp
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/initSofaMeshCollision.cpp
  applications/plugins/SofaCarving/SofaCarving_test/SofaCarving_test.cpp
  applications/plugins/SofaCarving/examples/CarvingTool.scn
  applications/plugins/SofaCarving/examples/SimpleCarving.scn
  applications/plugins/SofaCarving/examples/SimpleCarving_withPenetration.scn
  examples/Demos/TriangleSurfaceCutting.scn
  examples/Demos/caduceus.scn
  examples/Demos/liver.scn
  modules/SofaHaptics/SofaHaptics_test/scenes/ToolvsFloorCollision_test.scn
  tests/CMakeLists.txt
Labels: NG2: pluginization, pr: clean, status: to review

#1609 [SofaCommon] Make SofaCommon a deprecated collection
  CMakeLists.txt
  SofaKernel/SofaBase/src/SofaBase/initSofaBase.cpp
  SofaKernel/SofaCommon/CMakeLists.txt
  SofaKernel/SofaCommon/SofaCommonConfig.cmake.in
  SofaKernel/SofaCommon/src/SofaCommon/initSofaCommon.cpp
  SofaKernel/modules/CMakeLists.txt
  applications/plugins/Flexible/CMakeLists.txt
  applications/plugins/SceneCreator/sceneCreatorExamples/SceneCreatorBenchmarks.cpp
  applications/projects/runSofa/Main.cpp
  applications/tutorials/oneTetrahedron/CMakeLists.txt
  applications/tutorials/oneTetrahedron/oneTetrahedron.cpp
  modules/SofaConstraint/CMakeLists.txt
  modules/SofaConstraint/SofaConstraintConfig.cmake.in
  modules/SofaExporter/SofaExporter_test/CMakeLists.txt
  modules/SofaExporter/SofaExporter_test/WriteState_test.cpp
  modules/SofaGeneralDeformable/CMakeLists.txt
  modules/SofaGeneralDeformable/SofaGeneralDeformableConfig.cmake.in
  modules/SofaGeneralEngine/CMakeLists.txt
  modules/SofaGeneralEngine/SofaGeneralEngineConfig.cmake.in
  modules/SofaGeneralMeshCollision/CMakeLists.txt
  modules/SofaGeneralMeshCollision/SofaGeneralMeshCollisionConfig.cmake.in
  modules/SofaGeneralObjectInteraction/CMakeLists.txt
  modules/SofaGeneralObjectInteraction/SofaGeneralObjectInteractionConfig.cmake.in
  modules/SofaGeneralSimpleFem/CMakeLists.txt
  modules/SofaGeneralSimpleFem/SofaGeneralSimpleFemConfig.cmake.in
  modules/SofaGuiCommon/CMakeLists.txt
  modules/SofaGuiCommon/src/sofa/gui/GUIManager.cpp
  modules/SofaHaptics/SofaHaptics_test/CMakeLists.txt
  modules/SofaHaptics/SofaHaptics_test/LCPForceFeedback_test.cpp
  modules/SofaMiscFem/CMakeLists.txt
  modules/SofaMiscFem/SofaMiscFemConfig.cmake.in
  modules/SofaMiscForceField/CMakeLists.txt
  modules/SofaMiscForceField/SofaMiscForceFieldConfig.cmake.in
  modules/SofaMiscMapping/CMakeLists.txt
  modules/SofaMiscMapping/SofaMiscMappingConfig.cmake.in
  modules/SofaMiscTopology/CMakeLists.txt
  modules/SofaMiscTopology/SofaMiscTopology_test/TopologicalChangeProcessor_test.cpp
  modules/SofaMiscTopology/SofaMiscTopology_test/scenes/IncisionTrianglesProcess.scn
  modules/SofaPreconditioner/CMakeLists.txt
  modules/SofaPreconditioner/SofaPreconditionerConfig.cmake.in
  modules/SofaSparseSolver/CMakeLists.txt
  modules/SofaSparseSolver/SofaSparseSolverConfig.cmake.in
  modules/SofaUserInteraction/CMakeLists.txt
  modules/SofaUserInteraction/SofaUserInteractionConfig.cmake.in
  modules/SofaValidation/CMakeLists.txt
  modules/SofaValidation/SofaValidationConfig.cmake.in
Labels: NG2: pluginization, pr: clean, status: to review

#1651 [CImgPlugin] CLEAN dependencies in CMakeLists
  SofaKernel/SofaFramework/SofaMacrosConfigure.cmake
  applications/plugins/CImgPlugin/CMakeLists.txt
Labels: pr: clean, pr: fix, status: ready

#1625 [Regression_test] Update ChainHybrid timestep
  applications/projects/Regression/ExternalProjectConfig.cmake.in
  examples/Demos/chainHybrid.scn
  examples/Demos/chainHybridNoGroup.scn
Labels: pr: fast-merge, status: ready

#1613 [Sofa] Remove SMP-related Code
  SofaKernel/modules/SofaCore/src/sofa/core/CallContext.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/CallContext.h
  SofaKernel/modules/SofaCore/src/sofa/core/ParallelCollisionModel.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/ParallelMultiVec.h
  SofaKernel/modules/SofaCore/src/sofa/core/collision/ParallelNarrowPhaseDetection.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObjectTasks.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObjectTasks_gen.m4
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/SharedTypes.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/ParallelMechanicalVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/ParallelMechanicalVisitor.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/ParallelSolverImpl.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/ParallelSolverImpl.h
  SofaKernel/modules/SofaSimulationTree/SMPSimulation.cpp
  SofaKernel/modules/SofaSimulationTree/SMPSimulation.h
  applications/plugins/Flexible/types/AffineTypes.h
  applications/plugins/Flexible/types/DeformationGradientTypes.h
  applications/plugins/Flexible/types/QuadraticTypes.h
  applications/plugins/Flexible/types/StrainTypes.h
  applications/plugins/SofaMiscCollision/CMakeLists.txt
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/ParallelCollisionPipeline.cpp
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/ParallelCollisionPipeline.h
  examples/Objects/SMP/GridFEM.xml
  examples/Objects/SMP/GridFEMSphere.xml
  examples/Objects/SMP/GridFEMSphereCPU.xml
  examples/Objects/SMP/GridFEMSphereCUDA.xml
  examples/Objects/SMP/GridFEMSphereTT.xml
  examples/Objects/SMP/GridSpring.xml
  examples/Objects/SMP/MeshFEM.xml
  examples/Objects/SMP/MeshSpring.xml
  examples/Objects/SMP/TorusFEM.xml
  examples/Objects/SMP/TorusFEMOctree.xml
  examples/Objects/SMP/TorusFFD.xml
  examples/Objects/SMP/TorusRigid.xml
  examples/Objects/SMP/TorusRigidOctree.xml
  examples/Objects/SMP/TorusSpring.xml
  examples/SMP/AllObjects.inc.php
  examples/SMP/ArmadilloFEM.inc.php
  examples/SMP/AttachConstraint.pscn
  examples/SMP/BasicTypes.inc.php
  examples/SMP/CowFEM.inc.php
  examples/SMP/DragonFEM.inc.php
  examples/SMP/DragonFFD.inc.php
  examples/SMP/FrogFEM.inc.php
  examples/SMP/FrogFFD.inc.php
  examples/SMP/TorusFFD.inc.php
  examples/SMP/TorusRigid.inc.php
  examples/SMP/TorusSpring.inc.php
  examples/SMP/mixedPyramidBowl.pscn
  examples/SMP/mixedPyramidBowlSimple.pscn
  examples/SMP/quadSpringSphere.pscn
  examples/SMP/quadSpringSphere2.pscn
Labels: pr: clean, status: to review

#1635 [SofaBase] Package SofaEigen2solver
  CMakeLists.txt
  SofaKernel/SofaBase/CMakeLists.txt
  SofaKernel/SofaBase/src/SofaBase/initSofaBase.cpp
  SofaKernel/modules/SofaEigen2Solver/CMakeLists.txt
  SofaKernel/modules/SofaEigen2Solver/EigenBaseSparseMatrix_MT.h
  SofaKernel/modules/SofaEigen2Solver/README.md
  SofaKernel/modules/SofaEigen2Solver/SofaEigen2SolverConfig.cmake.in
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/EigenBaseSparseMatrix.h
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/EigenBaseSparseMatrix_MT.h
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/EigenMatrixManipulator.cpp
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/EigenMatrixManipulator.h
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/EigenSparseMatrix.h
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/EigenVector.cpp
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/EigenVector.h
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/EigenVectorWrapper.h
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/SVDLinearSolver.cpp
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/SVDLinearSolver.h
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/config.h.in
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/initSofaEigen2Solver.cpp
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/initSofaEigen2Solver.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.cpp
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/BeamFEMForceField.h
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/BeamFEMForceField.inl
Labels: NG2: pluginization, pr: clean, status: to review

#1654 [SofaGeneralLoader] allow ReadState at init
  modules/SofaGeneralLoader/src/SofaGeneralLoader/ReadState.h
  modules/SofaGeneralLoader/src/SofaGeneralLoader/ReadState.inl
Labels: enhancement, status: ready

#1495 [SofaGeneralLoader] Add option for transform in SphereLoader to match other loaders API
  modules/SofaGeneralLoader/src/SofaGeneralLoader/SphereLoader.cpp
  modules/SofaGeneralLoader/src/SofaGeneralLoader/SphereLoader.h
Labels: enhancement, status: ready

#1622 [SofaGeneralEngine] Remove useless create() function in some components
  SofaKernel/modules/SofaEngine/src/SofaEngine/BoxROI.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MeshROI.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/PairBoxRoi.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/PlaneROI.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/QuatToRigidEngine.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/RigidToQuatEngine.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/SphereROI.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/SubsetTopology.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ValuesFromPositions.h
Labels: pr: clean, status: ready

#1626 [SofaHelper] DrawTool uses RGBAColor now (instead of Vec4f)
  SofaKernel/modules/SofaBaseMechanics/UniformMass.cpp
  SofaKernel/modules/SofaBaseMechanics/UniformMass.inl
  SofaKernel/modules/SofaBaseTopology/TriangleSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseVisual/BaseCamera.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/visual/DrawTool.h
  SofaKernel/modules/SofaCore/src/sofa/core/visual/DrawToolGL.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/visual/DrawToolGL.h
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/MeshSpringForceField.inl
  SofaKernel/modules/SofaRigid/src/SofaRigid/JointSpringForceField.inl
  SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
  applications/plugins/Flexible/deformationMapping/BaseDeformationMapping.inl
  applications/plugins/Flexible/deformationMapping/BaseDeformationMultiMapping.inl
  applications/plugins/SofaDistanceGrid/components/forcefield/DistanceGridForceField.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticlesRepulsionForceField.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidForceField.inl
  applications/plugins/image/DepthMapToMeshEngine.h
  applications/plugins/image/MarchingCubesEngine.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/FixedPlaneConstraint.inl
  modules/SofaConstraint/src/SofaConstraint/UnilateralInteractionConstraint.inl
  modules/SofaGeneralDeformable/src/SofaGeneralDeformable/FrameSpringForceField.inl
  modules/SofaGeneralDeformable/src/SofaGeneralDeformable/QuadularBendingSprings.inl
  modules/SofaGeneralDeformable/src/SofaGeneralDeformable/TriangularBendingSprings.inl
  modules/SofaGeneralDeformable/src/SofaGeneralDeformable/TriangularBiquadraticSpringsForceField.inl
  modules/SofaGeneralDeformable/src/SofaGeneralDeformable/TriangularQuadraticSpringsForceField.inl
  modules/SofaGeneralDeformable/src/SofaGeneralDeformable/TriangularTensorMassForceField.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ClusteringEngine.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/TextureInterpolation.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ValuesFromPositions.inl
  modules/SofaGeneralRigid/src/SofaGeneralRigid/LineSetSkinningMapping.inl
  modules/SofaGeneralRigid/src/SofaGeneralRigid/SkinningMapping.inl
  modules/SofaGeneralRigid/src/SofaGeneralRigid/bvh/BVHJoint.cpp
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/HexahedralFEMForceField.inl
  modules/SofaGuiCommon/src/sofa/gui/ColourPickingVisitor.cpp
  modules/SofaMiscFem/src/SofaMiscFem/TriangleFEMForceField.inl
  modules/SofaMiscFem/src/SofaMiscFem/TriangularFEMForceField.inl
Labels: STC#10, pr: clean, status: ready

#1627 [SofaLoader] Use references in Meshloader
  SofaKernel/modules/SofaCore/SofaCore_test/loader/MeshLoader_test.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/loader/MeshLoader.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/loader/MeshLoader.h
  SofaKernel/modules/SofaLoader/src/SofaLoader/MeshObjLoader.cpp
  SofaKernel/modules/SofaLoader/src/SofaLoader/MeshVTKLoader.cpp
  applications/plugins/MeshSTEPLoader/MeshSTEPLoader.cpp
  modules/SofaGeneralLoader/src/SofaGeneralLoader/MeshGmshLoader.cpp
  modules/SofaGeneralLoader/src/SofaGeneralLoader/MeshOffLoader.cpp
  modules/SofaGeneralLoader/src/SofaGeneralLoader/MeshSTLLoader.cpp
  modules/SofaGeneralLoader/src/SofaGeneralLoader/MeshTrianLoader.cpp
Labels: STC#10, pr: clean, status: ready

#1656 [SofaKernel] Data file repository now looks into the SOFA install directory
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/FileRepository.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#1665 [OmniDriverEmul] Fix thread behavior and replace boost/pthread by std::thread
  applications/plugins/SensableEmulation/OmniDriverEmu.cpp
  applications/plugins/SensableEmulation/OmniDriverEmu.h
  applications/plugins/SensableEmulation/examples/testOmniDriverEmu.scn
Labels: pr: fix, status: ready

#1640 [SofaBase] Package SofaBaseUtils
  SofaKernel/SofaBase/src/SofaBase/initSofaBase.cpp
  SofaKernel/modules/SofaBaseUtils/CMakeLists.txt
  SofaKernel/modules/SofaBaseUtils/README.md
  SofaKernel/modules/SofaBaseUtils/SofaBaseUtilsConfig.cmake.in
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/AddResourceRepository.cpp
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/AddResourceRepository.h
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/InfoComponent.cpp
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/InfoComponent.h
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/MakeAliasComponent.cpp
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/MakeAliasComponent.h
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/MakeDataAliasComponent.cpp
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/MakeDataAliasComponent.h
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/RequiredPlugin.cpp
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/RequiredPlugin.h
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/config.h.in
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/initSofaBaseUtils.cpp
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/initSofaBaseUtils.h
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/messageHandlerComponent.cpp
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/messageHandlerComponent.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.cpp
Labels: NG2: pluginization, pr: clean, status: ready

#1679 [Sofa] Fix CMake files due to SofaBase ongoing packaging
  SofaGui/SofaGuiConfig.cmake.in
  SofaKernel/SofaBase/SofaBaseConfig.cmake.in
  SofaKernel/modules/SofaObjectInteraction/CMakeLists.txt
  SofaKernel/modules/SofaObjectInteraction/SofaObjectInteractionConfig.cmake.in
Labels: NG2: pluginization, pr: fast-merge, pr: fix, status: ready

#1681 [SofaDefaulttype] Remove warnings from typeinfo files
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/typeinfo/TypeInfo_Vector.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/typeinfo/models/SetTypeInfo.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/typeinfo/models/VectorTypeInfo.h
Labels: pr: clean, pr: fast-merge, status: ready

#1668 [SofaKernel] Fix a broken that was introduced in pr #1605
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/AbstractTypeInfo.cpp
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/AbstractTypeInfo.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/typeinfo/DataTypeInfoDynamicWrapper.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/typeinfo/NameOnlyTypeInfo.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/typeinfo/NoTypeInfo.h
Labels: bug (major), pr: fix, status: ready

#1678 [SofaKernel] Exposing Data in ContactListener.
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/ContactListener.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/ContactListener.h
Labels: enhancement, status: ready

#1683 [Backport] Exposing Data in ContactListener
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/ContactListener.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/ContactListener.h
Labels: pr: fast-merge, status: ready

#1685 Minor cosmetic cleaning.
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/PluginManager.cpp
  examples/Demos/caduceus.scn
  modules/SofaGuiCommon/src/sofa/gui/BaseGUI.cpp
  modules/SofaGuiCommon/src/sofa/gui/GUIManager.cpp
Labels: pr: clean, pr: fast-merge, status: ready

#1684 [SofaSphFluid] Remove std::execution usage
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidForceField.inl
Labels: pr: fast-merge, pr: fix, status: to review
