Repository sofa-framework/sofa, pull requests merged in 2020-01, with the labels that each got.

#1240 [SofaHelper] FIX Eigen install path
  SofaKernel/modules/SofaHelper/CMakeLists.txt
Labels: pr: fast-merge, pr: fix, status: ready

#1237 [SofaKernel] replace all serr by msg_error/msg_warning
  SofaKernel/modules/SofaBaseCollision/DefaultContactManager.cpp
  SofaKernel/modules/SofaBaseLinearSolver/CompressedRowSparseMatrix.h
  SofaKernel/modules/SofaBaseLinearSolver/FullMatrix.h
  SofaKernel/modules/SofaBaseLinearSolver/SingleMatrixAccessor.cpp
  SofaKernel/modules/SofaBaseTopology/TopologyDataHandler.inl
  SofaKernel/modules/SofaBaseVisual/BaseCamera.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/Mapping.h
  SofaKernel/modules/SofaCore/src/sofa/core/Mapping.inl
  SofaKernel/modules/SofaCore/src/sofa/core/Multi2Mapping.h
  SofaKernel/modules/SofaCore/src/sofa/core/MultiMapping.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/BaseInteractionForceField.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/BaseMechanicalState.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/BaseProjectiveConstraintSet.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/LinearSolver.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/Mass.inl
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/OdeSolver.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/PairInteractionForceField.inl
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/ProjectiveConstraintSet.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/ProjectiveConstraintSet.inl
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Context.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseMeshTopology.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologicalMapping.h
  SofaKernel/modules/SofaCore/src/sofa/core/visual/VisualLoop.h
  SofaKernel/modules/SofaDeformable/AngularSpringForceField.h
  SofaKernel/modules/SofaDeformable/RestShapeSpringsForceField.h
  SofaKernel/modules/SofaEigen2Solver/EigenBaseSparseMatrix.h
  SofaKernel/modules/SofaEigen2Solver/EigenSparseMatrix.h
  SofaKernel/modules/SofaEigen2Solver/EigenVector.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/ArgumentParser.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/EulerImplicitSolver.cpp
  SofaKernel/modules/SofaLoader/MeshObjLoader.cpp
  SofaKernel/modules/SofaMeshCollision/LocalMinDistanceFilter.cpp
  SofaKernel/modules/SofaMeshCollision/MeshNewProximityIntersection.cpp
  SofaKernel/modules/SofaObjectInteraction/PenalityContactForceField.inl
  SofaKernel/modules/SofaRigid/RigidMapping.cpp
  SofaKernel/modules/SofaRigid/RigidMapping.inl
  SofaKernel/modules/SofaSimpleFem/HexahedronFEMForceField.inl
  SofaKernel/modules/SofaSimpleFem/TetrahedronDiffusionFEMForceField.inl
  SofaKernel/modules/SofaSimpleFem/TetrahedronFEMForceField.inl
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/AnimateVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/DefaultVisualManagerLoop.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalOperations.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Node.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/UpdateBoundingBoxVisitor.cpp
  SofaKernel/modules/SofaSimulationGraph/DAGNodeMultiMappingElement.cpp
Labels: pr: clean, status: ready

#1242 [SofaCUDA] Compilation without OpenGL
  applications/plugins/SofaCUDA/CMakeLists.txt
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaDistanceGridCollisionModel.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaFixedTranslationConstraint.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMemoryManager.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaPenalityContactForceField.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaPointModel.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSPHFluidForceField.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSpatialGridContainer.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaUniformMass.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaVisualModel.inl
Labels: enhancement, location: plugins, status: ready

#1244 [SofaHelper] AdvancedTimer wasn't using the good timer ids for the label assignments
  SofaKernel/modules/SofaHelper/src/sofa/helper/AdvancedTimer.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/AdvancedTimer.h
Labels: bug (minor), pr: fast-merge, pr: fix, status: ready
