Repository sofa-framework/sofa, pull requests merged in 2020-08, with the labels that each got.

#1438 [Geomagic] Fix include Dir of OpenHaptics
  applications/plugins/Geomagic/CMakeLists.txt
Labels: location: plugins, pr: backport, pr: fast-merge, pr: fix, status: ready

#1444 Micro PR to make a function virtual in FrictionContact.
  modules/SofaConstraint/FrictionContact.h
Labels: pr: fast-merge, status: ready

#1446 [SofaMacros] FIX deprecated macro sofa_generate_package
  SofaKernel/SofaFramework/SofaMacros.cmake
  modules/SofaSparseSolver/CMakeLists.txt
Labels: pr: backport, pr: fast-merge, pr: fix, status: to review

#1445 FIX: simu unload crashs caused by missing checks on slaves ptrs
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObject.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#1435 [Geomagic] Fix scenes ForceFeedBack behavior due to a change in UncoupledConstraintCorrection
  applications/plugins/Geomagic/scenes/Geomagic-FEMLiver.scn
  applications/plugins/Geomagic/scenes/Geomagic-RigidCubes.scn
  applications/plugins/Geomagic/scenes/Geomagic-RigidSkull-restShapeSpringForceField.scn
  applications/plugins/Geomagic/scenes/Geomagic-RigidSkull.scn
  applications/plugins/Geomagic/scenes/GeomagicEmulator-RigidCubes.scn
Labels: pr: backport, pr: fast-merge, pr: fix, status: to review

#1451 Remove Inria Foundation mention from CONTRIBUTING
  CONTRIBUTING.md
Labels: pr: clean, pr: fast-merge, status: to review

#1408 [SofaKernel][SofaCore][SofaLoader][SofaGeneralLoader] SOFA with callbacks
  SofaKernel/modules/SofaBaseUtils/AddResourceRepository.cpp
  SofaKernel/modules/SofaBaseUtils/AddResourceRepository.h
  SofaKernel/modules/SofaCore/SofaCore_test/TrackedData_test.cpp
  SofaKernel/modules/SofaCore/SofaCore_test/loader/MeshLoader_test.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/DataTracker.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/loader/MeshLoader.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/loader/MeshLoader.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.h
  SofaKernel/modules/SofaLoader/MeshObjLoader.cpp
  SofaKernel/modules/SofaLoader/MeshObjLoader.h
  SofaKernel/modules/SofaLoader/MeshVTKLoader.cpp
  SofaKernel/modules/SofaLoader/MeshVTKLoader.h
  applications/plugins/MeshSTEPLoader/MeshSTEPLoader.cpp
  applications/plugins/MeshSTEPLoader/MeshSTEPLoader.h
  applications/plugins/SofaAssimp/AssimpLoader.cpp
  applications/plugins/SofaAssimp/AssimpLoader.h
  modules/SofaGeneralLoader/GIDMeshLoader.cpp
  modules/SofaGeneralLoader/GIDMeshLoader.h
  modules/SofaGeneralLoader/GridMeshCreator.cpp
  modules/SofaGeneralLoader/GridMeshCreator.h
  modules/SofaGeneralLoader/MeshGmshLoader.cpp
  modules/SofaGeneralLoader/MeshGmshLoader.h
  modules/SofaGeneralLoader/MeshOffLoader.cpp
  modules/SofaGeneralLoader/MeshOffLoader.h
  modules/SofaGeneralLoader/MeshSTLLoader.cpp
  modules/SofaGeneralLoader/MeshSTLLoader.h
  modules/SofaGeneralLoader/MeshTrianLoader.cpp
  modules/SofaGeneralLoader/MeshTrianLoader.h
  modules/SofaGeneralLoader/MeshXspLoader.cpp
  modules/SofaGeneralLoader/MeshXspLoader.h
  modules/SofaGeneralLoader/SphereLoader.cpp
  modules/SofaGeneralLoader/SphereLoader.h
  modules/SofaGeneralLoader/StringMeshCreator.cpp
  modules/SofaGeneralLoader/StringMeshCreator.h
  modules/SofaGeneralLoader/VoxelGridLoader.h
Labels: pr: breaking, pr: new feature, status: ready

#1383 [SofaKernel] Filerepository gettemppath
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/FileRepository.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/FileRepository.h
Labels: enhancement, status: ready

#1452 [CMake] Fix Cmake configure step with SOFA_WITH_DEPRECATED_COMPONENTS
  CMakeLists.txt
Labels: pr: fast-merge, pr: fix, status: ready

#1457 [extlibs/gtest] Fix the broken sofa_create_package_with_targets in gtest
  extlibs/gtest/CMakeLists.txt
Labels: pr: fast-merge, pr: fix, status: ready

#1448 [SofaKernel][SofaGeneralRigid] Minor fixes in ArticulatedSystemMapping and JointSpringForceField
  SofaKernel/modules/SofaCore/src/sofa/core/visual/DrawToolGL.cpp
  SofaKernel/modules/SofaRigid/JointSpringForceField.inl
  modules/SofaGeneralRigid/ArticulatedHierarchyContainer.inl
  modules/SofaGeneralRigid/ArticulatedSystemMapping.inl
Labels: pr: fix, status: ready

#1449 [SofaBaseVisual][SofaDeformable] Clean some codes
  SofaKernel/modules/SofaBaseVisual/VisualModelImpl.cpp
  SofaKernel/modules/SofaDeformable/PolynomialRestShapeSpringsForceField.h
  SofaKernel/modules/SofaDeformable/PolynomialRestShapeSpringsForceField.inl
  SofaKernel/modules/SofaDeformable/PolynomialSpringsForceField.h
  SofaKernel/modules/SofaDeformable/PolynomialSpringsForceField.inl
  SofaKernel/modules/SofaEigen2Solver/EigenBaseSparseMatrix.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/Quater.inl
  SofaKernel/modules/SofaHelper/src/sofa/helper/vectorLinks.h
  modules/SofaOpenglVisual/src/SofaOpenglVisual/DataDisplay.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/DataDisplay.h
  modules/SofaOpenglVisual/src/SofaOpenglVisual/Light.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/Light.h
  modules/SofaOpenglVisual/src/SofaOpenglVisual/LightManager.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/MergeVisualModels.h
  modules/SofaOpenglVisual/src/SofaOpenglVisual/OglCylinderModel.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/OglShaderVisualModel.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/OglVariable.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/PointSplatModel.cpp
Labels: pr: clean, status: ready

#1455 [SofaCore] Add virtual getPathName function in Base
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseNode.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObject.h
Labels: enhancement, status: ready

#1459 [SofaKernel] Add updateOnTransformChange update callback on MeshLoader.
  SofaKernel/modules/SofaCore/src/sofa/core/loader/MeshLoader.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#1458 [SofaKernel] Implement an update mechanism on component: RequiredPlugin
  SofaKernel/modules/SofaBaseUtils/RequiredPlugin.cpp
  SofaKernel/modules/SofaBaseUtils/RequiredPlugin.h
  modules/SofaGraphComponent/SceneCheckMissingRequiredPlugin.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#1467 [SofaKernel] Switch to include_guard() instead of include_guard(GLOBAL)
  SofaKernel/SofaFramework/SofaMacros.cmake
Labels: pr: fast-merge, pr: fix, status: ready
