Repository sofa-framework/sofa, pull requests merged in 2020-05, with the labels that each got.

#1336 [SofaCUDA] Arch auto-detection for nvcc
  applications/plugins/SofaCUDA/CMakeLists.txt
  applications/plugins/SofaCUDA/SofaCUDANvccFlags.cmake
Labels: enhancement, pr: breaking, status: ready

#1365 [SofaKernel] Remove a #pragma in a config.h (shouldn't be there)
  SofaKernel/SofaFramework/config.h.in
Labels: pr: fast-merge, status: to review

#1315 [SofaGui] Pass QDocBrowser as an option
  SofaGui/SofaGuiConfig.cmake.in
  applications/sofa/gui/qt/CMakeLists.txt
  applications/sofa/gui/qt/RealGUI.cpp
  applications/sofa/gui/qt/RealGUI.h
  applications/sofa/gui/qt/SofaGuiQt.h.in
Labels: location: project, pr: clean, status: ready

#1351 [SofaKernel] Add Data bool d_checkTopology in Topology container to replace the use of CHECK_TOPOLOGY macro
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyModifier.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseMeshTopology.h
Labels: pr: clean, status: ready

#1368 [SofaFramework] Windows/VS: Remove warnings flags from definitions
  SofaKernel/cmake/CompilerOptions.cmake
Labels: pr: fast-merge, pr: fix, status: to review

#1354 [SofaMiscCollision] Fix topological changes in TetrahedronCollisionModel
  applications/plugins/SofaMiscCollision/TetrahedronModel.cpp
  applications/plugins/SofaMiscCollision/TetrahedronModel.h
  examples/Components/topology/Tetra2TriangleTopologicalMapping_with_TetrahedronModel.scn
  examples/Components/topology/TopologicalModifiers/RemovingTetraProcess_withCollisionModel.scn
  examples/Tutorials/Topologies/TopologyVolumeDifferentMesh.scn
Labels: pr: fix, status: ready

#1372 [SofaKernel] Refactor DDGNode
  SofaKernel/modules/SofaCore/SofaCore_simutest/CMakeLists.txt
  SofaKernel/modules/SofaCore/SofaCore_test/objectmodel/DDGNode_test.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/DataEngine.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/DataEngine.h
  SofaKernel/modules/SofaCore/src/sofa/core/DataTracker.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/DataTracker.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseContext.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseLink.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DDGNode.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DDGNode.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Data.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DataCallback.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DataCallback.h
Labels: pr: breaking, pr: clean, refactoring, status: to review

#1381 [SofaExporter] FIX Compilation of SofaExporter_test
  modules/SofaExporter/SofaExporter_test/CMakeLists.txt
Labels: pr: fast-merge, status: ready

#1361 [SofaOpenCL] Make it work with 20.06
  applications/plugins/SofaOpenCL/CMakeLists.txt
  applications/plugins/SofaOpenCL/OpenCLFixedConstraint.inl
  applications/plugins/SofaOpenCL/OpenCLIdentityMapping.cpp
  applications/plugins/SofaOpenCL/OpenCLSPHFluidForceField.h
  applications/plugins/SofaOpenCL/OpenCLSPHFluidForceField.inl
  applications/plugins/SofaOpenCL/OpenCLUniformMass.cpp
  applications/plugins/SofaOpenCL/OpenCLUniformMass.h
  applications/plugins/SofaOpenCL/OpenCLUniformMass.inl
  applications/plugins/SofaOpenCL/SofaOpenCLConfig.cmake.in
  applications/plugins/SofaOpenCL/examples/SPHFluidForceFieldOPENCL.scn
  applications/plugins/SofaOpenCL/examples/quadSpringSphereOPENCL.scn
  applications/plugins/SofaOpenCL/initSofaOpenCL.cpp
  applications/plugins/SofaOpenCL/kernels/OpenCLSpringForceField.cl
  applications/projects/CMakeLists.txt
Labels: location: plugins, pr: clean, pr: fix, status: ready

#1370 [SofaKernel] Remove X11 dependency when SOFA_NO_OPENGL is enabled.
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  SofaKernel/modules/SofaHelper/src/sofa/helper/gl/glfont.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/gl/glfont.h
  applications/projects/SofaGuiGlut/SimpleGUI.cpp
Labels: pr: clean, status: ready

#1384 [CMake] Add SofaNonUniformFem to the dependencies of SofaMisc
  CMakeLists.txt
  SofaAdvanced/src/SofaAdvanced/config.h.in
  SofaMisc/SofaMiscConfig.cmake.in
  modules/SofaMiscEngine/CMakeLists.txt
  modules/SofaNonUniformFem/CMakeLists.txt
  modules/SofaNonUniformFem/SofaNonUniformFemConfig.cmake.in
  modules/SofaNonUniformFem/src/SofaNonUniformFem/NonUniformFem.cpp
  modules/SofaNonUniformFem/src/SofaNonUniformFem/NonUniformFem.h
  modules/SofaNonUniformFem/src/SofaNonUniformFem/NonUniformHexahedronFEMForceFieldDensity.cpp
  modules/SofaNonUniformFem/src/SofaNonUniformFem/NonUniformHexahedronFEMForceFieldDensity.h
Labels: bug (minor), pr: fast-merge, pr: fix, pr: squashable, status: to review

#1366 [Geomagic Plugin] Move all code related to device model display in a dedicated class.
  applications/plugins/Geomagic/CMakeLists.txt
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.cpp
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.h
  applications/plugins/Geomagic/src/Geomagic/GeomagicVisualModel.cpp
  applications/plugins/Geomagic/src/Geomagic/GeomagicVisualModel.h
  share/mesh/BASEO.obj
  share/mesh/articulation1O.obj
  share/mesh/articulation2O.obj
  share/mesh/articulation4O.obj
Labels: location: plugins, pr: clean, status: ready

#1352 [SofaKernel] Clean occurrences of CHECK_TOPOLOGY macro in code
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/EdgeSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/HexahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/MeshTopology.cpp
  SofaKernel/modules/SofaBaseTopology/PointSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/QuadSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TopologyEngine.inl
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyModifier.cpp
  modules/SofaMiscForceField/MeshMatrixMass.h
  modules/SofaMiscForceField/MeshMatrixMass.inl
Labels: pr: clean, status: ready

#1377 [SofaKernel] Fixes a bug where the camera was not moving with the Qt viewer
  SofaKernel/modules/SofaBaseVisual/BaseCamera.cpp
  SofaKernel/modules/SofaBaseVisual/BaseCamera.h
  applications/sofa/gui/qt/viewer/qt/QtViewer.cpp
  examples/Demos/caduceus.scn
Labels: bug (minor), pr: fix, status: ready

#1378 [Geomagic] Fix several wrong behaviors in driver code
  applications/plugins/Geomagic/CMakeLists.txt
  applications/plugins/Geomagic/scenes/Geomagic-FEMLiver.scn
  applications/plugins/Geomagic/scenes/Geomagic-RigidCubes.scn
  applications/plugins/Geomagic/scenes/Geomagic-RigidSkull-restShapeSpringForceField.scn
  applications/plugins/Geomagic/scenes/Geomagic-RigidSkull.scn
  applications/plugins/Geomagic/scenes/GeomagicEmulator-RigidCubes.scn
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.cpp
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.h
  applications/plugins/Geomagic/src/Geomagic/GeomagicEmulator.cpp
  applications/plugins/Geomagic/src/Geomagic/GeomagicEmulator.h
  applications/plugins/Geomagic/src/Geomagic/GeomagicVisualModel.cpp
  applications/plugins/Geomagic/src/Geomagic/GeomagicVisualModel.h
Labels: location: plugins, pr: clean, pr: fix, status: ready

#1353 [ManifoldTopologies] Remove CHECK_TOPOLOGY macro occurrences
  applications/plugins/ManifoldTopologies/ManifoldEdgeSetTopologyContainer.cpp
  applications/plugins/ManifoldTopologies/ManifoldTetrahedronSetTopologyContainer.cpp
  applications/plugins/ManifoldTopologies/ManifoldTriangleSetTopologyContainer.cpp
  applications/plugins/ManifoldTopologies/ManifoldTriangleSetTopologyModifier.cpp
Labels: location: plugins, pr: clean, status: ready

#1373 [SofaKernel] Add DataTypeInfo for BoundingBox
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/BoundingBox.h
Labels: enhancement, status: ready

#1387 [SofaKernel] Remove the installation of external system libraries
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  applications/plugins/CImgPlugin/CMakeLists.txt
  applications/sofa/gui/qt/CMakeLists.txt
Labels: pr: fix, status: ready

#1359 [OpenCTM plugin] Fix compilation and clean before moving out
  applications/plugins/OpenCTMPlugin/CMakeLists.txt
  applications/plugins/OpenCTMPlugin/OpenCTMPluginConfig.cmake.in
  applications/plugins/OpenCTMPlugin/src/SofaOpenCTM/OpenCTMExporter.cpp
  applications/plugins/OpenCTMPlugin/src/SofaOpenCTM/OpenCTMExporter.h
  applications/plugins/OpenCTMPlugin/src/SofaOpenCTM/OpenCTMLoader.cpp
  applications/plugins/OpenCTMPlugin/src/SofaOpenCTM/OpenCTMLoader.h
  applications/plugins/OpenCTMPlugin/src/SofaOpenCTM/config.h.in
  applications/plugins/OpenCTMPlugin/src/SofaOpenCTM/initOpenCTMPlugin.cpp
Labels: location: plugins, pr: clean, status: ready

#1391 [SofaKernel] Fix minor bug in BoxROI and add warning message in RestShapeSpringsForceField
  SofaKernel/modules/SofaDeformable/RestShapeSpringsForceField.inl
  SofaKernel/modules/SofaEngine/BoxROI.inl
Labels: pr: fix, status: ready
