Repository sofa-framework/sofa, pull requests merged in 2020-09, with the labels that each got.

#1468 [SofaKernel] Add whole program optimization (aka link-time optimization) for msvc
  SofaKernel/cmake/CompilerOptions.cmake
Labels: enhancement, pr: fast-merge, status: ready

#1470 🐛 [SofaSimulationGraph] No reason to have moveChild in private
  SofaKernel/modules/SofaSimulationGraph/DAGNode.h
Labels: pr: fast-merge, pr: fix, status: ready

#1471 🚸 RGBAColor for MO's showColor
  SofaKernel/modules/SofaBaseMechanics/MechanicalObject.h
  SofaKernel/modules/SofaBaseMechanics/MechanicalObject.inl
Labels: pr: fast-merge, status: ready

#1475 [SofaHelper] swap lightgray / darkgray in RGBAColor
  SofaKernel/modules/SofaHelper/src/sofa/helper/types/RGBAColor.h
Labels: pr: fast-merge, status: ready

#1473 [SofaFramework] 🐛 Homogeneize SOFA_VERSION with APIVersion
  modules/SofaGraphComponent/APIVersion.cpp
  modules/SofaGraphComponent/SceneCheckAPIChange.h
Labels: pr: fast-merge, status: ready

#218 [all] issofa_bugfix: cleans and fixes
  SofaKernel/modules/SofaBaseMechanics/MechanicalObject.inl
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObject.cpp
  SofaKernel/modules/SofaDeformable/RestShapeSpringsForceField.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalMatrixVisitor.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalOperations.cpp
  applications/plugins/Compliant/compliance/UniformCompliance.cpp
  modules/SofaConstraint/GenericConstraintSolver.h
  modules/SofaGeneralRigid/SkinningMapping.inl
  modules/SofaSparseSolver/src/SofaSparseSolver/SparseLDLSolver.h
Labels: STC#9, pr: fix, status: ready

#1466 [SofaPython] Small fixes to import plugin and remove scene warnings
  applications/plugins/SofaPython/PythonEnvironment.cpp
  applications/plugins/SofaPython/examples/fountain.py
  applications/plugins/SofaPython/examples/fountain.scn
  applications/plugins/SofaPython/examples/houseOfCards.py
  applications/plugins/SofaPython/examples/keyboardControl.scn
  applications/plugins/SofaPython/initSofaPython.cpp
Labels: pr: fix, status: ready

#1465 [SofaKernel] In DataFileName, the name FILE used in the PathType enum could be ambigous
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DataFileName.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DataFileName.h
Labels: pr: fast-merge, pr: fix, pr: squashable, status: ready

#1477 [SofaMacros] Split SofaMacros.cmake into multiple files
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/SofaFramework/SofaMacros.cmake
  SofaKernel/SofaFramework/SofaMacrosConfigure.cmake
  SofaKernel/SofaFramework/SofaMacrosInstall.cmake
  SofaKernel/SofaFramework/SofaMacrosPython.cmake
  SofaKernel/SofaFramework/SofaMacrosUtils.cmake
Labels: pr: clean, pr: fast-merge, refactoring, status: ready

#1472 [SofaKernel] Improve check for already registered plugins
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/PluginManager.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/PluginManager.h
Labels: pr: fix, status: ready

#1479 [SofaKernel] 🐛 Break link when passing a nullptr to setLinkedBase
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseLink.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#1480 [SofaBaseMechanics] 🐛 FIX draw function in UniformMass
  SofaKernel/modules/SofaBaseMechanics/UniformMass.inl
Labels: pr: fast-merge, pr: fix, status: ready

#1487 [SofaGeneralEngine] Improve mesh barycentric mapper engine
  examples/Components/engine/MeshBarycentricMapperEngine.scn
  modules/SofaGeneralEngine/MeshBarycentricMapperEngine.h
  modules/SofaGeneralEngine/MeshBarycentricMapperEngine.inl
Labels: pr: fast-merge, refactoring, status: ready

#1484 [SofaMacros] Use IN_LIST (CMake >= 3.3)
  SofaKernel/SofaFramework/SofaMacrosConfigure.cmake
Labels: pr: clean, pr: fast-merge, status: ready

#1482 [SofaKernel] ♻️ FIX & CLEANUP BoxROI
  SofaKernel/modules/SofaEngine/BoxROI.h
  SofaKernel/modules/SofaEngine/BoxROI.inl
  SofaKernel/modules/SofaEngine/SofaEngine_test/BoxROI_test.cpp
Labels: pr: breaking, pr: clean, pr: fix, refactoring, status: ready

#1485 [SofaKernel] Add DataLink object & PathResolver.
  SofaKernel/modules/SofaCore/CMakeLists.txt
  SofaKernel/modules/SofaCore/SofaCore_test/CMakeLists.txt
  SofaKernel/modules/SofaCore/SofaCore_test/PathResolver_test.cpp
  SofaKernel/modules/SofaCore/SofaCore_test/objectmodel/DataLink_test.cpp
  SofaKernel/modules/SofaCore/SofaCore_test/objectmodel/Data_test.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/PathResolver.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/PathResolver.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/AbstractDataLink.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/AbstractDataLink.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DataLink.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DataLink.h
Labels: pr: fast-merge, pr: new feature, refactoring, status: ready

#1488 🐛 [SofaCore] FIX const correctness in DataTracker
  SofaKernel/modules/SofaCore/src/sofa/core/DataTracker.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/DataTracker.h
Labels: pr: fast-merge, pr: fix, status: ready

#1500 [SofaOpenglVisual] OglViewport: a fix for compatibility with modern OpenGL
  modules/SofaOpenglVisual/src/SofaOpenglVisual/OglViewport.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#1505 [SofaKernel] Remove un-needed includes
  SofaKernel/modules/SofaHelper/src/sofa/helper/StateMask.h
  modules/SofaGeneralAnimationLoop/MechanicalMatrixMapper.h
Labels: pr: fast-merge, status: ready
