Repository sofa-framework/sofa, pull requests merged in 2020-04, with the labels that each got.

#1310 [MeshSTEPLoader] FIX build with OCC >= 7.4
  applications/plugins/MeshSTEPLoader/MeshSTEPLoader.h
Labels: pr: fast-merge, pr: fix, status: to review

#1294 [Sofa] Overridden 'canCreate' methods should always log an error message when they fail
  SofaKernel/modules/SofaBaseCollision/CapsuleModel.h
  SofaKernel/modules/SofaBaseCollision/ContactListener.h
  SofaKernel/modules/SofaBaseCollision/OBBModel.h
  SofaKernel/modules/SofaBaseCollision/RigidCapsuleModel.h
  SofaKernel/modules/SofaBaseCollision/SphereModel.h
  SofaKernel/modules/SofaBaseTopology/PointSetGeometryAlgorithms.h
  SofaKernel/modules/SofaCore/src/sofa/core/Mapping.h
  SofaKernel/modules/SofaCore/src/sofa/core/MultiMapping.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/Constraint.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/ConstraintCorrection.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/LMConstraint.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/MixedInteractionConstraint.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/MixedInteractionForceField.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/PairInteractionConstraint.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/PairInteractionForceField.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/PairInteractionProjectiveConstraintSet.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/ProjectiveConstraintSet.h
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologicalMapping.h
  SofaKernel/modules/SofaEngine/BoxROI.h
  SofaKernel/modules/SofaLoader/MeshObjLoader.h
  SofaKernel/modules/SofaLoader/MeshVTKLoader.h
  SofaKernel/modules/SofaMeshCollision/LineModel.h
  SofaKernel/modules/SofaMeshCollision/PointModel.h
  SofaKernel/modules/SofaMeshCollision/TriangleModel.h
  applications/plugins/CImgPlugin/CImgPlugin_test/images/output_bw.png
  modules/SofaConstraint/GenericConstraintCorrection.h
  modules/SofaConstraint/LinearSolverConstraintCorrection.h
  modules/SofaExporter/src/SofaExporter/BlenderExporter.h
  modules/SofaExporter/src/SofaExporter/WriteState.h
  modules/SofaExporter/src/SofaExporter/WriteTopology.h
  modules/SofaGeneralEngine/GenerateRigidMass.h
  modules/SofaGeneralEngine/MeshROI.h
  modules/SofaGeneralEngine/PairBoxRoi.h
  modules/SofaGeneralEngine/PlaneROI.h
  modules/SofaGeneralEngine/PointsFromIndices.h
  modules/SofaGeneralEngine/ProximityROI.h
  modules/SofaGeneralEngine/SphereROI.h
  modules/SofaGeneralEngine/SubsetTopology.h
  modules/SofaGeneralEngine/TransformPosition.h
  modules/SofaGeneralEngine/ValuesFromPositions.h
  modules/SofaGeneralLoader/GIDMeshLoader.h
  modules/SofaGeneralLoader/GridMeshCreator.h
  modules/SofaGeneralLoader/MeshGmshLoader.h
  modules/SofaGeneralLoader/MeshOffLoader.h
  modules/SofaGeneralLoader/MeshSTLLoader.h
  modules/SofaGeneralLoader/MeshTrianLoader.h
  modules/SofaGeneralLoader/MeshXspLoader.h
  modules/SofaGeneralLoader/ReadState.h
  modules/SofaGeneralLoader/ReadTopology.h
  modules/SofaGeneralLoader/StringMeshCreator.h
  modules/SofaHaptics/src/SofaHaptics/LCPForceFeedback.h
  modules/SofaMiscTopology/TopologicalChangeProcessor.h
  modules/SofaPreconditioner/src/SofaPreconditioner/BlockJacobiPreconditioner.h
  modules/SofaPreconditioner/src/SofaPreconditioner/JacobiPreconditioner.h
  modules/SofaPreconditioner/src/SofaPreconditioner/PrecomputedWarpPreconditioner.h
  modules/SofaSparseSolver/src/SofaSparseSolver/PrecomputedLinearSolver.h
  modules/SofaValidation/CompareState.h
  modules/SofaValidation/DevTensionMonitor.h
  modules/SofaValidation/EvalPointsDistance.h
Labels: pr: clean, pr: fix, status: ready

#1296 [SphPlugin] Clean SofaFluid plugin compilation warning.
  applications/plugins/SofaSphFluid/src/SofaSphFluid/OglFluidModel.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/OglFluidModel.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSink.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSource.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSource.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticlesRepulsionForceField.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidForceField.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidSurfaceMapping.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidSurfaceMapping.inl
Labels: location: plugins, pr: clean, status: ready

#1312 [MeshSTEPLoader] FIX OCC version check
  applications/plugins/MeshSTEPLoader/MeshSTEPLoader.h
Labels: pr: fast-merge, pr: fix, status: ready

#1281 [cmake] Remove the use of an internal Eigen3 version and instead use the one installed on the system.
  CMakeLists.txt
  SofaKernel/SofaBase/SofaBaseConfig.cmake.in
  SofaKernel/SofaCommon/SofaCommonConfig.cmake.in
  SofaKernel/SofaCommon/config.h.in
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
  SofaKernel/cmake/Modules/FindSOFA.cmake
  SofaKernel/extlibs/eigen/ExternalProjectConfig.cmake.in
  SofaKernel/modules/SofaBaseTopology/CMakeLists.txt
  SofaKernel/modules/SofaBaseTopology/EdgeSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaDefaultType/CMakeLists.txt
  SofaKernel/modules/SofaEigen2Solver/CMakeLists.txt
  SofaKernel/modules/SofaEigen2Solver/EigenBaseSparseMatrix.h
  SofaKernel/modules/SofaEigen2Solver/EigenBaseSparseMatrix_MT.h
  SofaKernel/modules/SofaEigen2Solver/EigenSparseMatrix.h
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  SofaKernel/modules/SofaRigid/CMakeLists.txt
  SofaKernel/modules/SofaRigid/RigidMapping.inl
  applications/plugins/CGALPlugin/CMakeLists.txt
  applications/plugins/Compliant/CMakeLists.txt
  applications/plugins/Compliant/CompliantConfig.cmake.in
  applications/plugins/Compliant/assembly/AssembledSystem.h
  applications/plugins/Compliant/assembly/AssemblyHelper.h
  applications/plugins/Compliant/assembly/AssemblyVisitor.cpp
  applications/plugins/Compliant/initCompliant.cpp
  applications/plugins/Compliant/numericalsolver/PreconditionedSolver.h
  applications/plugins/Compliant/preconditioner/CompliantLDLTPreconditioner.cpp
  applications/plugins/Compliant/preconditioner/IncompleteCholeskyPreconditioner.cpp
  applications/plugins/Flexible/CMakeLists.txt
  applications/plugins/Flexible/FlexibleConfig.cmake.in
  applications/plugins/Flexible/deformationMapping/BaseDeformationMapping.inl
  applications/plugins/Registration/CMakeLists.txt
  applications/plugins/Registration/RegistrationConfig.cmake.in
  applications/plugins/SceneCreator/CMakeLists.txt
  applications/plugins/SceneCreator/SceneCreatorConfig.cmake.in
  applications/plugins/SofaPython/CMakeLists.txt
  applications/plugins/SofaPython/SofaPythonConfig.cmake.in
  applications/plugins/SofaSimpleGUI/CMakeLists.txt
  applications/plugins/SofaSimpleGUI/SofaSimpleGUIConfig.cmake.in
  cmake/Modules/FindEigen3.cmake
  extlibs/CMakeLists.txt
Labels: pr: breaking, pr: clean, status: ready

#1317 [SofaSphFluid] FIX .scene-tests
  applications/plugins/SofaSphFluid/examples/.scene-tests
Labels: pr: fast-merge, pr: fix, status: ready

#1325 [SofaCore] Remove warning in ExecParam
  SofaKernel/modules/SofaCore/src/sofa/core/ExecParams.h
Labels: enhancement, pr: fast-merge, status: to review

#1320 [CImgPlugin] Remove the test file output_bw.png and avoid its creation in the source directory
  applications/plugins/CImgPlugin/CImgPlugin_test/ImageCImg_test.cpp
  applications/plugins/CImgPlugin/CImgPlugin_test/images/output_bw.png
Labels: bug (minor), pr: fast-merge, status: to review

#1313 [All] Fix SOFA_LIBSUFFIX used in Debug by PluginManager
  SofaKernel/modules/SofaHelper/CMakeLists.txt
Labels: pr: fix, status: to review

#1253 [SofaBaseVisual] Add camera gizmo in base camera
  SofaKernel/modules/SofaBaseVisual/BaseCamera.cpp
  SofaKernel/modules/SofaBaseVisual/BaseCamera.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/Ray.h
Labels: enhancement, status: ready

#1319 [Topo] Fix Tetra2TriangleTopologicalMapping
  modules/SofaTopologyMapping/Tetra2TriangleTopologicalMapping.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#1332 [SofaKernel] Improve error message when a component cannot be created.
  SofaKernel/modules/SofaCore/src/sofa/core/ObjectFactory.cpp
Labels: bug (minor), pr: fast-merge, pr: fix, status: to review

#1323 [BaseTopology] Fix GridTopology edge computation
  SofaKernel/modules/SofaBaseTopology/GridTopology.cpp
  SofaKernel/modules/SofaBaseTopology/GridTopology.h
  SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.cpp
  examples/Components/topology/RegularGridTopology_TrianglesMesh.scn
  modules/SofaGeneralDeformable/TriangularBendingSprings.inl
Labels: pr: fix, status: ready

#1308 [CGALPlugin] Clean and pluginization
  applications/plugins/CGALPlugin/CGALPlugin.txt
  applications/plugins/CGALPlugin/CGALPluginConfig.cmake.in
  applications/plugins/CGALPlugin/CGALPlugin_test/CMakeLists.txt
  applications/plugins/CGALPlugin/CMakeLists.txt
  applications/plugins/CGALPlugin/FindCGAL.cmake
  applications/plugins/CGALPlugin/FindGMP.cmake
  applications/plugins/CGALPlugin/FindMPFR.cmake
  applications/plugins/CGALPlugin/scenes/MeshGenerationFromImage.scn
  applications/plugins/CGALPlugin/scenes/MeshGenerationFromImageWithFeatures.scn
  applications/plugins/CGALPlugin/scenes/MeshGenerationFromPolyhedron.scn
  applications/plugins/CGALPlugin/scenes/Refine2DMesh.scn
  applications/plugins/CGALPlugin/src/CGALPlugin/CuboidMesh.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/CuboidMesh.h
  applications/plugins/CGALPlugin/src/CGALPlugin/CuboidMesh.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/CylinderMesh.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/CylinderMesh.h
  applications/plugins/CGALPlugin/src/CGALPlugin/CylinderMesh.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.h
  applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/MeshGenerationFromImage.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/MeshGenerationFromImage.h
  applications/plugins/CGALPlugin/src/CGALPlugin/MeshGenerationFromImage.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/MeshGenerationFromPolyhedron.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/MeshGenerationFromPolyhedron.h
  applications/plugins/CGALPlugin/src/CGALPlugin/MeshGenerationFromPolyhedron.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/Refine2DMesh.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/Refine2DMesh.h
  applications/plugins/CGALPlugin/src/CGALPlugin/Refine2DMesh.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/TriangularConvexHull3D.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/TriangularConvexHull3D.h
  applications/plugins/CGALPlugin/src/CGALPlugin/TriangularConvexHull3D.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/config.h.in
  applications/plugins/CGALPlugin/src/CGALPlugin/initCGALPlugin.cpp
Labels: location: plugins, pr: clean, status: ready

#1346 [SofaKernel] Clean of Material.h/cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/types/Material.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/types/Material.h
Labels: pr: clean, pr: fast-merge, status: to review

#1347 [SofaFramework/CMake] Create configuration type dir before copying lib
  SofaKernel/SofaFramework/SofaMacros.cmake
Labels: pr: fast-merge, pr: fix, status: to review
