Repository sofa-framework/sofa, pull requests merged in 2021-02, with the labels that each got.

#1735 [SofaCore] Move definition of Link::updateLinks to BaseLink.h
  SofaKernel/modules/SofaCore/src/sofa/core/PathResolver.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/PathResolver.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseLink.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseLink.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Link.h
Labels: pr: breaking, refactoring, status: ready

#1766 [SofaSimpleFEM] Fix nasty bug in HexaFEMForceField' s draw()
  SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/HexahedronFEMForceField.inl
Labels: bug (minor), pr: fast-merge, pr: fix, status: to review

#1767 [cmake] Many fixes for compiling out-of-tree projects
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
  SofaKernel/modules/Sofa.Type/CMakeLists.txt
  SofaKernel/modules/SofaBaseCollision/SofaBaseCollisionConfig.cmake.in
  extlibs/gtest/CMakeLists.txt
  modules/SofaGuiCommon/CMakeLists.txt
  modules/SofaGuiQt/SofaGuiQtConfig.cmake.in
Labels: bug (major), pr: fast merge, status: ready

#1736 [SofaCore] Move definition Link::read() method to BaseLink::read()
  SofaKernel/modules/SofaCore/src/sofa/core/PathResolver.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseLink.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseLink.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Link.h
Labels: refactoring, status: ready

#1768 [SofaBaseCollision] Fix simulation dependency
  SofaKernel/modules/SofaBaseCollision/CMakeLists.txt
  SofaKernel/modules/SofaBaseCollision/SofaBaseCollisionConfig.cmake.in
  applications/plugins/MultiThreading/CMakeLists.txt
  applications/plugins/MultiThreading/MultiThreadingConfig.cmake.in
  modules/SofaGuiCommon/CMakeLists.txt
  modules/SofaGuiCommon/SofaGuiCommonConfig.cmake.in
  modules/SofaValidation/CMakeLists.txt
  modules/SofaValidation/SofaValidationConfig.cmake.in
Labels: pr: clean, pr: fast merge, status: ready

#1769 [SofaMacros] Shorter name for relocatable targets
  SofaKernel/SofaFramework/SofaMacrosInstall.cmake
Labels: pr: fast merge, pr: fix, status: ready

#1772 [SofaHelper] Move polygon cube intersection ad-hoc algorithm to SofaBaseTopology
  SofaKernel/modules/SofaBaseTopology/CMakeLists.txt
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/SparseGridTopology.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/polygon_cube_intersection/fast_polygon_cube_intersection.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/polygon_cube_intersection/polygon_cube_intersection.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/polygon_cube_intersection/polygon_cube_intersection.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/polygon_cube_intersection/vec.h
  SofaKernel/modules/SofaHelper/CMakeLists.txt
Labels: pr: breaking, pr: clean, status: ready

#1770 [SofaHelper] Remove SofaSimulationCore dependency from AdvancedTimer
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  SofaKernel/modules/SofaHelper/SofaHelper_simutest/AdvancedTimer_test.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/AdvancedTimer.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/AdvancedTimer.h
  applications/projects/runSofa/Main.cpp
  modules/SofaGuiCommon/src/sofa/gui/BatchGUI.cpp
Labels: pr: breaking, pr: clean, status: ready

#1751 [SofaCore] Move the streaming operator from .h to .cpp
  SofaKernel/modules/SofaBaseTopology/CMakeLists.txt
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/fwd.h
  SofaKernel/modules/SofaCore/src/sofa/core/fwd.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Tag.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Tag.h
  SofaKernel/modules/SofaCore/src/sofa/core/visual/DisplayFlags.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/visual/DisplayFlags.h
Labels: pr: fast merge, refactoring, status: ready

#1771 [cmake] Bump development SOFA version to 20.12.99
  CMakeLists.txt
Labels: pr: fast merge, status: ready

#1761 [MSVC] Some fixes (Debug+SofaCUDA)
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/typeinfo/models/IncompleteTypeInfo.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaStandardTetrahedralFEMForceField.cu
Labels: pr: backport me, pr: fast merge, pr: fix, status: ready

#1763 [SofaCore] Remove "depend" from Node
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Node.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Node.h
Labels: pr: breaking, refactoring, status: ready

#1733 [SofaGeneralLoader] adds translation and rotation to ReadState
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/MechanicalObject.inl
  modules/SofaGeneralLoader/src/SofaGeneralLoader/ReadState.h
  modules/SofaGeneralLoader/src/SofaGeneralLoader/ReadState.inl
Labels: enhancement, status: ready

#1753 [SofaCore] Merge TData in Data.
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Data.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Data.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DataFileName.h
  SofaKernel/modules/SofaHelper/SofaHelper_test/logging/logging_test.cpp
  applications/plugins/PluginExample/src/PluginExample/MyDataWidgetUnsigned.cpp
  applications/plugins/Registration/ClosestPointRegistrationForceField.inl
  applications/plugins/image/image_test/ImageEngine_test.cpp
  modules/SofaExporter/src/SofaExporter/VTKExporter.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/DataFilenameWidget.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/MaterialDataWidget.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/QDisplayDataWidget.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/RGBAColorDataWidget.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/SimpleDataWidget.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/SimpleDataWidget.h
Labels: refactoring, status: to review

#1776 [Geomagic] Fix GeomagicVisualModel compilation
  applications/plugins/Geomagic/src/Geomagic/GeomagicVisualModel.h
Labels: pr: fast merge, pr: fix, status: ready

#1774 [SofaHelper] Throw a compilation error if using AdvancedTimer end(Node*)
  SofaKernel/modules/SofaHelper/SofaHelper_simutest/AdvancedTimer_test.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/AdvancedTimer.h
  applications/plugins/SofaPython/Binding_SofaModule.cpp
Labels: pr: fast merge, status: ready

#1781 [SofaHelper] Fix AdvandedTimer test with end()
  SofaKernel/modules/SofaHelper/SofaHelper_simutest/AdvancedTimer_test.cpp
Labels: pr: fast merge, pr: fix, status: ready

#1782 [SofaExporter] Update OBJExporter example
  modules/SofaExporter/examples/OBJExporter.scn
Labels: pr: clean, pr: fast merge, status: ready

#1795 [SofaOpenCL] Fix compilation
  applications/plugins/SofaOpenCL/OpenCLFixedConstraint.inl
Labels: pr: fast merge, pr: fix, status: ready

#1775 [SofaKernel] Port Mat from Defaulttype to Sofa.Type
  SofaKernel/modules/Sofa.Type/CMakeLists.txt
  SofaKernel/modules/Sofa.Type/compat/sofa/defaulttype/Mat.h
  SofaKernel/modules/Sofa.Type/compat/sofa/defaulttype/MatSym.h
  SofaKernel/modules/Sofa.Type/compat/sofa/defaulttype/Mat_solve_Cholesky.h
  SofaKernel/modules/Sofa.Type/compat/sofa/defaulttype/Mat_solve_LU.h
  SofaKernel/modules/Sofa.Type/compat/sofa/defaulttype/Mat_solve_SVD.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/Mat.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/MatSym.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/Mat_solve_Cholesky.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/Mat_solve_LU.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/Mat_solve_SVD.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/CapsuleIntTool.inl
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/IntrUtility3.inl
  SofaKernel/modules/SofaDefaultType/CMakeLists.txt
  SofaKernel/modules/SofaDefaultType/SofaDefaultType_test/MatTypes_test.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/AdvancedTimer.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/GenerateRigid.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/Quater.h
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/MeshIntTool.cpp
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/MeshNewProximityIntersection.inl
  SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
  applications/plugins/Flexible/deformationMapping/ImageDeformation.h
  applications/plugins/Flexible/deformationMapping/LinearJacobianBlock_rigid.inl
  applications/plugins/Flexible/deformationMapping/MLSJacobianBlock_rigid.inl
  applications/plugins/Flexible/deformationMapping/TriangleDeformationMapping.inl
  applications/plugins/Flexible/material/HEMLStVKForceField.h
  applications/plugins/Flexible/strainMapping/CorotationalStrainJacobianBlock.inl
  applications/plugins/Flexible/strainMapping/InvariantJacobianBlock.inl
  applications/plugins/Flexible/types/AffineTypes.h
  applications/plugins/Flexible/types/QuadraticTypes.h
  applications/plugins/InvertibleFVM/ExternalProjectConfig.cmake.in
  applications/plugins/Registration/InertiaAlign.cpp
  applications/plugins/image/ImageToRigidMassEngine.h
  applications/plugins/image/MeshToImageEngine.h
  modules/SofaConstraint/src/SofaConstraint/LMDNewProximityIntersection.inl
  modules/SofaConstraint/src/SofaConstraint/LocalMinDistance.cpp
  modules/SofaGeneralDeformable/src/SofaGeneralDeformable/FrameSpringForceField.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/TransformMatrixEngine.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshMinProximityIntersection.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshMinProximityIntersection.h
Labels: NG1: include-graph, enhancement, pr: breaking, status: ready

#1798 [Scenes] Fix (new?) failing scenes on the CI
  examples/Components/constraint/OscillatorConstraint.scn
  examples/Components/solver/EulerExplicitSolver-diagonal.scn
  examples/Tutorials/Collision/AdvancedResponseConstraintBased.scn
Labels: pr: backport me, pr: clean, pr: fast merge, pr: fix, status: ready

#1787 [all] Remove warning: unused variable
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/FileSystem.cpp
Labels: pr: clean, status: ready

#1804 [CMake][tools] v20.12.00 changes
  CHANGELOG.md
  CMakeLists.txt
  applications/projects/runSofa/runSofa.plist
  modules/SofaGuiCommon/src/sofa/gui/BaseGUI.cpp
  modules/SofaGuiCommon/src/sofa/gui/GUIManager.cpp
  tools/postinstall-fixup/CMakeLists.txt
  tools/postinstall-fixup/linux-postinstall-fixup.sh
  tools/postinstall-fixup/macos-postinstall-fixup.sh
  tools/postinstall-fixup/windows-postinstall-fixup.sh
Labels: pr: do not squash, pr: fast merge, pr: fix, status: ready

#1813 [SofaRigid] fixes applyJT of RigidMapping
  SofaKernel/modules/SofaRigid/src/SofaRigid/RigidMapping.inl
Labels: pr: fix

#1780 [SofaCUDA] Fix CudaFixedConstraint when indices are not contiguous
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaFixedConstraint.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaFixedConstraint.inl
Labels: pr: backport me, pr: fix, status: to review

#1814 [SofaCore] adds template to Multi2Mapping
  SofaKernel/modules/SofaCore/src/sofa/core/Multi2Mapping.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/Multi2Mapping.h
Labels: pr: fast merge, status: ready

#1674 [SofaFramework] Create Sofa.Config module
  CMakeLists.txt
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
  SofaKernel/SofaFramework/src/SofaFramework/config.h.in
  SofaKernel/SofaFramework/src/SofaFramework/initSofaFramework.cpp
  SofaKernel/SofaFramework/src/SofaFramework/initSofaFramework.h
  SofaKernel/cmake/CompilerOptions.cmake
  SofaKernel/extlibs/newmat/CMakeLists.txt
  SofaKernel/extlibs/tinyxml/CMakeLists.txt
  SofaKernel/modules/Sofa.Config/CMakeLists.txt
  SofaKernel/modules/Sofa.Config/README.md
  SofaKernel/modules/Sofa.Config/Sofa.ConfigConfig.cmake.in
  SofaKernel/modules/Sofa.Config/cmake/CMakeParseLibraryList.cmake
  SofaKernel/modules/Sofa.Config/cmake/CompilerOptions.cmake
  SofaKernel/modules/Sofa.Config/cmake/Modules/FindJson.cmake
  SofaKernel/modules/Sofa.Config/cmake/Modules/FindPTHREAD.cmake
  SofaKernel/modules/Sofa.Config/cmake/Modules/FindPackageHandleStandardArgs.cmake
  SofaKernel/modules/Sofa.Config/cmake/Modules/FindSOFA.cmake
  SofaKernel/modules/Sofa.Config/cmake/Modules/FindSofaThreads.cmake
  SofaKernel/modules/Sofa.Config/cmake/Modules/find_lib.cmake
  SofaKernel/modules/Sofa.Config/cmake/SofaMacros.cmake
  SofaKernel/modules/Sofa.Config/cmake/SofaMacrosConfigure.cmake
  SofaKernel/modules/Sofa.Config/cmake/SofaMacrosInstall.cmake
  SofaKernel/modules/Sofa.Config/cmake/SofaMacrosPython.cmake
  SofaKernel/modules/Sofa.Config/cmake/SofaMacrosUtils.cmake
  SofaKernel/modules/Sofa.Config/etc/sofa.ini.in
  SofaKernel/modules/Sofa.Config/src/sofa/config.h.in
  SofaKernel/modules/Sofa.Config/src/sofa/config/build_option_bbox.h.in
  SofaKernel/modules/Sofa.Config/src/sofa/config/build_option_deprecated_components.h.in
  SofaKernel/modules/Sofa.Config/src/sofa/config/build_option_dump_visitor.h.in
  SofaKernel/modules/Sofa.Config/src/sofa/config/build_option_opengl.h.in
  SofaKernel/modules/Sofa.Config/src/sofa/config/build_option_threading.h.in
  SofaKernel/modules/Sofa.Config/src/sofa/config/sharedlibrary_defines.h.in
  SofaKernel/modules/Sofa.Config/src/sofa/initSofaConfig.cpp
  SofaKernel/modules/Sofa.Config/src/sofa/version.h.in
  SofaKernel/modules/Sofa.Type/CMakeLists.txt
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  applications/plugins/CImgPlugin/extlibs/CImg/CMakeLists.txt
  applications/plugins/SofaDistanceGrid/extlibs/miniFlowVR/CMakeLists.txt
  applications/projects/generateListDoxygen/CMakeLists.txt
  applications/projects/generateListDoxygen/Doxyfile.in
  applications/projects/generateListDoxygen/empty_sofa_modules_component_list.dox
  applications/projects/generateListDoxygen/generateComponentList.cpp
  applications/projects/generateListDoxygen/header.html
  applications/projects/generateListDoxygen/sofa_modules.dox.in
  applications/projects/generateListDoxygen/sofa_plugins.dox.in
  applications/projects/generateListDoxygen/stylesheet.css
  extlibs/gtest/CMakeLists.txt
  modules/SofaSparseSolver/extlibs/csparse/CMakeLists.txt
  modules/SofaSparseSolver/extlibs/metis-5.1.0/CMakeLists.txt
Labels: NG2: pluginization, pr: clean, pr: fix, status: to review

#1777 [SofaHelper][SofaPython] ADD PluginManager callback and use it in SofaPython
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/FileRepository.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/PluginManager.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/PluginManager.h
  applications/plugins/SofaPython/PythonEnvironment.cpp
  applications/plugins/SofaPython/PythonEnvironment.h
  applications/plugins/SofaPython/initSofaPython.cpp
Labels: pr: backport me, pr: new feature, status: ready

#1819 [LMConstraint] Fix collision model
  applications/plugins/LMConstraint/CMakeLists.txt
  applications/plugins/LMConstraint/src/LMConstraint/BaseLMConstraint.h
Labels: pr: fast merge, pr: fix, status: ready

#1823 [PluginManager] FIX "name vs path" issue + FIX test
  SofaKernel/modules/SofaHelper/SofaHelper_test/system/PluginManager_test.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/PluginManager.cpp
Labels: pr: backport me, pr: fast merge, pr: fix, status: ready

#1808 [SofaHelper] remove stream operator<< in accessor
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaDeformable/SofaDeformable_test/StiffSpringForceField_test.cpp
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/PolynomialRestShapeSpringsForceField.inl
  SofaKernel/modules/SofaHelper/src/sofa/helper/accessor.h
  applications/plugins/PluginExample/PluginExample_test/MyBehaviorModel_test.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSource.inl
  applications/plugins/SofaTest/ForceField_test.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ComplementaryROI.inl
Labels: pr: breaking, pr: fast merge, refactoring, status: ready

#1825 [SofaHelper] FIX "name vs path" issue in PluginManager + FIX PluginManager_test (2)
  SofaKernel/modules/SofaHelper/SofaHelper_test/system/PluginManager_test.cpp
Labels: pr: fast merge, pr: fix, status: to review

#1826 [SofaGuiCommon] fix BackgroundSetting
  modules/SofaGuiCommon/src/sofa/gui/BaseViewer.cpp
Labels: pr: fast merge, pr: fix, status: ready

#1779 [SofaMiscFEM] Minor changes in TrianglePressureFF and TriangularFEMFF
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/TrianglePressureForceField.inl
  modules/SofaMiscFem/src/SofaMiscFem/TriangularFEMForceField.h
  modules/SofaMiscFem/src/SofaMiscFem/TriangularFEMForceField.inl
Labels: pr: fix, status: ready

#1788 [SofaCUDA] Renaming cudaMatrix methods to use rowSize and colSize
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMatrix.h
Labels: pr: backport me, pr: breaking, pr: fix, status: ready

#1558 [SofaBoundaryCondition] Add projectVelocity in FixedConstraint and PartialFixedConstraint
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/FixedConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/FixedConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/PartialFixedConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/PartialFixedConstraint.inl
Labels: enhancement, pr: clean, status: to review

#1835 [SofaPython] CLEAN PythonEnvironment info messages
  applications/plugins/SofaPython/PythonEnvironment.cpp
Labels: pr: backport me, pr: clean, pr: fast merge, status: ready

#1839 [SofaMeshCollision] Fix: windows debug linkage of class EmptyFilter
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/EmptyFilter.h
Labels: pr: fast merge, pr: fix, status: ready

#1829 [All] FIX build without SofaPython soft dependencies
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/CMakeLists.txt
  applications/plugins/Flexible/Flexible_test/CMakeLists.txt
  applications/plugins/Flexible/Flexible_test/stdafx.h
  applications/plugins/SofaImplicitField/CMakeLists.txt
  applications/plugins/SofaTest/CMakeLists.txt
  applications/plugins/SofaTest/SofaTestConfig.cmake.in
Labels: pr: backport me, pr: fast merge, pr: fix, status: ready

#1831 [LMConstraint] Fix unload
  applications/plugins/LMConstraint/examples/DistanceLMContactConstraint.scn
  applications/plugins/LMConstraint/src/LMConstraint/BarycentricDistanceLMConstraintContact_DistanceGrid.cpp
  applications/plugins/LMConstraint/src/LMConstraint/BaseLMConstraint.h
Labels: pr: fix, status: ready

#1824 [SofaHelper] Add two search paths for every prefixes of the plugin manager
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/PluginManager.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/PluginManager.h
Labels: enhancement, pr: breaking, status: to review

#1849 [all] Fix invalid Memory access in MechanicalObject and Compliant_test
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/MechanicalObject.inl
  applications/plugins/Compliant/Compliant_test/Assembly_test.cpp
Labels: bug (minor), pr: fast merge, status: ready

#1815 [SofaBaseMechanics] fixes reinit of BarycentricMapping
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/BarycentricMapping.h
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/BarycentricMapping.inl
Labels: pr: backport me, pr: fix, status: ready

#1810 [SofaHelper] Remove some SofaCore dependencies
  SofaKernel/modules/SofaCore/CMakeLists.txt
  SofaKernel/modules/SofaCore/compat/sofa/helper/vectorData.h
  SofaKernel/modules/SofaCore/compat/sofa/helper/vectorLinks.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/vectorData.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/vectorLinks.h
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  SofaKernel/modules/SofaHelper/src/sofa/helper/io/XspLoader.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/visual/DrawTool.h
Labels: NG1: include-graph, pr: clean, status: ready

#1820 [SofaGuiQt] ADD qt.conf.h for custom qt.conf loading at runtime
  modules/SofaGuiQt/CMakeLists.txt
  modules/SofaGuiQt/src/sofa/gui/qt/qt.conf.h
  tools/postinstall-fixup/CMakeLists.txt
Labels: pr: backport me, pr: fix, status: ready

#1846 [SofaBaseVisual] Move #include<Mat.h> from BaseCamera.h to BaseCamera.cpp
  SofaKernel/modules/SofaBaseVisual/src/SofaBaseVisual/BaseCamera.cpp
  SofaKernel/modules/SofaBaseVisual/src/SofaBaseVisual/BaseCamera.h
Labels: pr: clean, pr: fast merge, status: ready

#1793 [all] use =deleted for deprecation
  SofaKernel/modules/Sofa.Config/src/sofa/config.h.in
  SofaKernel/modules/SofaCore/SofaCore_simutest/objectmodel/BaseLink_simutest.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/ExecParams.h
  SofaKernel/modules/SofaCore/src/sofa/core/Multi2Mapping.h
  SofaKernel/modules/SofaCore/src/sofa/core/MultiMapping.h
  SofaKernel/modules/SofaCore/src/sofa/core/ObjectFactory.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseClass.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseLink.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DDGNode.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Data.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Link.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/RGBAColor.h
  applications/plugins/PluginExample/src/PluginExample/MyDataWidgetUnsigned.cpp
  applications/plugins/PluginExample/src/PluginExample/MyMappingPendulumInPlane.inl
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/SolverMerger.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/QMouseOperations.cpp
  modules/SofaValidation/src/SofaValidation/EvalPointsDistance.h
Labels: pr: clean, status: ready

#1863 [CMake] FIX header include tree
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
  SofaKernel/modules/Sofa.Config/CMakeLists.txt
  SofaKernel/modules/Sofa.Config/cmake/SofaMacrosInstall.cmake
  SofaKernel/modules/Sofa.GL/CMakeLists.txt
  modules/SofaGuiCommon/CMakeLists.txt
Labels: bug (minor), pr: fast merge, pr: fix, status: to review

#1843 [SofaCUDA] change the setTopology method signature
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping.h
Labels: pr: fast merge, pr: fix, status: ready

#1866 [SofaCore] FIX Issue #1865
  SofaKernel/modules/SofaCore/src/sofa/core/MultiMapping.h
Labels: pr: fast merge, pr: fix, status: ready
