Repository sofa-framework/sofa, pull requests merged in 2021-06, with the labels that each got.

#2116 [all] Update code to use sofa::InvalidID instead of topology::InvalidID
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologySparseData.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologySparseData.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseMeshTopology.cpp
  modules/SofaMiscTopology/src/SofaMiscTopology/TopologicalChangeProcessor.cpp
  modules/SofaMiscTopology/src/SofaMiscTopology/TopologyChecker.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Hexa2TetraTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Mesh2PointTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/SubsetTopologicalMapping.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/TopologicalChangeManager.cpp
Labels: pr: clean, pr: status ready

#2144 [SofaBaseMechanics_test] Update tests to use Sofa.Testing instead of Sofa_Test
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/BarycentricMapping_test.cpp
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/CMakeLists.txt
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/DiagonalMass_test.cpp
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/MechanicalObject_test.cpp
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/UniformMass_test.cpp
Labels: pr: clean, pr: fast merge, pr: status ready

#2139 [SofaGuiQt] Tooltips
  modules/SofaGuiQt/src/sofa/gui/qt/SofaWindowProfiler.cpp
Labels: enhancement, pr: fast merge, pr: status ready

#2152 [SofaBaseTopology] Improve TopologyDataHandler message
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.inl
Labels: pr: clean, pr: fast merge, pr: status ready

#2147 [CImgPlugin] Fix unit test
  applications/plugins/CImgPlugin/CImgPlugin_test/ImageCImg_test.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#2121 [SofaCore] FIX buffer overflow when using AddressSanitizer
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.cpp
Labels: pr: fix, pr: status ready

#2109 [Collision] Build collision tree only if required
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceBroadPhase.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceDetection.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/DefaultPipeline.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/collision/BroadPhaseDetection.h
  SofaKernel/modules/SofaCore/src/sofa/core/collision/Detection.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/DirectSAP.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/DirectSAPNarrowPhase.h
Labels: pr: status ready

#2127 [SofaMiscCollision] Move back to modules (instead of applications/plugins)
  applications/collections/SofaComponentAll/CMakeLists.txt
  applications/plugins/CMakeLists.txt
  modules/CMakeLists.txt
  modules/SofaMiscCollision/CMakeLists.txt
  modules/SofaMiscCollision/SofaMiscCollisionConfig.cmake.in
  modules/SofaMiscCollision/SofaMiscCollision_test/CMakeLists.txt
  modules/SofaMiscCollision/SofaMiscCollision_test/DefaultCollisionGroupManager_test.cpp
  modules/SofaMiscCollision/SofaMiscCollision_test/scenes/DefaultCollisionGroupManager_singleObject_test.scn
  modules/SofaMiscCollision/src/SofaMiscCollision/BarycentricStickContact.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/BarycentricStickContact.h
  modules/SofaMiscCollision/src/SofaMiscCollision/BarycentricStickContact.inl
  modules/SofaMiscCollision/src/SofaMiscCollision/CapsuleContact.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/CapsuleContactMapper.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/CapsuleContactMapper.h
  modules/SofaMiscCollision/src/SofaMiscCollision/CapsuleIntersection.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/CapsuleIntersection.h
  modules/SofaMiscCollision/src/SofaMiscCollision/DefaultCollisionGroupManager.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/DefaultCollisionGroupManager.h
  modules/SofaMiscCollision/src/SofaMiscCollision/FrictionContact_DistanceGrid.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/OBBContact.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/OBBContactMapper.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/OBBContactMapper.h
  modules/SofaMiscCollision/src/SofaMiscCollision/OBBIntersection.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/OBBIntersection.h
  modules/SofaMiscCollision/src/SofaMiscCollision/README.md
  modules/SofaMiscCollision/src/SofaMiscCollision/RayTriangleVisitor.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/RayTriangleVisitor.h
  modules/SofaMiscCollision/src/SofaMiscCollision/RuleBasedContactManager.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/RuleBasedContactManager.h
  modules/SofaMiscCollision/src/SofaMiscCollision/SolverMerger.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/SolverMerger.h
  modules/SofaMiscCollision/src/SofaMiscCollision/SpatialGridPointModel.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/SpatialGridPointModel.h
  modules/SofaMiscCollision/src/SofaMiscCollision/TetrahedronBarycentricPenalityContact.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/TetrahedronDiscreteIntersection.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/TetrahedronDiscreteIntersection.h
  modules/SofaMiscCollision/src/SofaMiscCollision/TetrahedronFrictionContact.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/TetrahedronModel.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/TetrahedronModel.h
  modules/SofaMiscCollision/src/SofaMiscCollision/TetrahedronRayContact.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/TriangleModelInRegularGrid.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/TriangleModelInRegularGrid.h
  modules/SofaMiscCollision/src/SofaMiscCollision/config.h.in
  modules/SofaMiscCollision/src/SofaMiscCollision/initSofaMiscCollision.cpp
  modules/SofaMiscCollision/src/SofaMiscCollision/initSofaMiscCollision.h
Labels: pr: clean, pr: fast merge, pr: status ready

#2151 [SofaGuiQt] FIX "show grid" (G) shortcut for QGLViewer
  modules/SofaGuiQt/src/sofa/gui/qt/viewer/qgl/QtGLViewer.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#2164 [sofaBaseMechanics] Fix bug when deleting point. Mass vector was not well recomputed.
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/DiagonalMass.inl
Labels: pr: fast merge, pr: fix, pr: status ready

#2146 [SofaBase] Convert tests to Sofa.Testing
  SofaKernel/modules/SofaBaseCollision/SofaBaseCollision_test/BroadPhase_test.cpp
  SofaKernel/modules/SofaBaseCollision/SofaBaseCollision_test/BroadPhase_test.h
  SofaKernel/modules/SofaBaseCollision/SofaBaseCollision_test/CMakeLists.txt
  SofaKernel/modules/SofaBaseCollision/SofaBaseCollision_test/DefaultPipeline_test.cpp
  SofaKernel/modules/SofaBaseCollision/SofaBaseCollision_test/SpherePrimitiveCreator.h
  SofaKernel/modules/SofaBaseCollision/SofaBaseCollision_test/Sphere_test.cpp
  SofaKernel/modules/SofaBaseLinearSolver/SofaBaseLinearSolver_test/CMakeLists.txt
  SofaKernel/modules/SofaBaseLinearSolver/SofaBaseLinearSolver_test/Matrix_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/CMakeLists.txt
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/RegularGridTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/SparseGridTopology_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/TetrahedronNumericalIntegration_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/TriangleNumericalIntegration_test.cpp
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/fake_TopologyScene.cpp
  SofaKernel/modules/SofaBaseUtils/SofaBaseUtils_test/AddResourceRepository_test.cpp
  SofaKernel/modules/SofaBaseUtils/SofaBaseUtils_test/CMakeLists.txt
  SofaKernel/modules/SofaBaseUtils/SofaBaseUtils_test/MakeAliasComponent_test.cpp
  SofaKernel/modules/SofaBaseUtils/SofaBaseUtils_test/MakeDataAliasComponent_test.cpp
  SofaKernel/modules/SofaBaseUtils/SofaBaseUtils_test/MessageHandlerComponent_test.cpp
  SofaKernel/modules/SofaBaseUtils/SofaBaseUtils_test/RequiredPlugin_test.cpp
  SofaKernel/modules/SofaBaseVisual/SofaBaseVisual_test/CMakeLists.txt
  SofaKernel/modules/SofaMeshCollision/SofaMeshCollision_test/BaryMapper_test.cpp
  SofaKernel/modules/SofaMeshCollision/SofaMeshCollision_test/CMakeLists.txt
  SofaKernel/modules/SofaMeshCollision/SofaMeshCollision_test/MeshNewProximityIntersection_test.cpp
  SofaKernel/modules/SofaMeshCollision/SofaMeshCollision_test/MeshPrimitiveCreator.h
  SofaKernel/modules/SofaMeshCollision/SofaMeshCollision_test/Triangle_test.cpp
  modules/SofaMiscCollision/SofaMiscCollision_test/CMakeLists.txt
  modules/SofaMiscCollision/SofaMiscCollision_test/DefaultCollisionGroupManager_test.cpp
  modules/SofaMiscCollision/SofaMiscCollision_test/OBBCapsPrimitiveCreator.h
  modules/SofaMiscCollision/SofaMiscCollision_test/OBB_test.cpp
Labels: pr: clean, pr: status ready

#2115 [Geomagic] Add macro HAS_OPENHAPTICS to know if library is present
  applications/plugins/Geomagic/CMakeLists.txt
  applications/plugins/Geomagic/scenes/.scene-tests
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.cpp
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.h
  applications/plugins/Geomagic/src/Geomagic/GeomagicVisualModel.cpp
  applications/plugins/Geomagic/src/Geomagic/GeomagicVisualModel.h
  applications/plugins/Geomagic/src/Geomagic/config.h.in
Labels: pr: status ready, refactoring

#2105 [SofaHelper] Optimize use of map_ptr_stable_compare
  SofaKernel/modules/SofaCore/src/sofa/core/collision/NarrowPhaseDetection.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/map_ptr_stable_compare.h
  modules/SofaHaptics/SofaHaptics_test/LCPForceFeedback_test.cpp
  modules/SofaHaptics/SofaHaptics_test/scenes/ToolvsFloorCollision_test.scn
Labels: enhancement, pr: status ready

#2124 [CGALPlugin] new features
  applications/plugins/CGALPlugin/CMakeLists.txt
  applications/plugins/CGALPlugin/scenes/BooleanOperations.scn
  applications/plugins/CGALPlugin/scenes/FrontSurfaceReconstruction.scn
  applications/plugins/CGALPlugin/scenes/PoissonSurfaceReconstruction.scn
  applications/plugins/CGALPlugin/scenes/UpsamplePointCloud.scn
  applications/plugins/CGALPlugin/src/CGALPlugin/BooleanOperations.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/BooleanOperations.h
  applications/plugins/CGALPlugin/src/CGALPlugin/CylinderMesh.h
  applications/plugins/CGALPlugin/src/CGALPlugin/CylinderMesh.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.h
  applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/FrontSurfaceReconstruction.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/FrontSurfaceReconstruction.h
  applications/plugins/CGALPlugin/src/CGALPlugin/PoissonSurfaceReconstruction.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/PoissonSurfaceReconstruction.h
  applications/plugins/CGALPlugin/src/CGALPlugin/UpsamplePointCloud.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/UpsamplePointCloud.h
Labels: pr: breaking, pr: new feature, pr: status ready

#2160 [Sofa.Helper] Remove atomic.h (and fix compilation on Silicon M1)
  SofaKernel/modules/Sofa.Compat/CMakeLists.txt
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/system/atomic.h
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  SofaKernel/modules/SofaHelper/SofaHelper_test/CMakeLists.txt
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/atomic.h
  applications/plugins/MultiThreading/src/MultiThreading/AnimationLoopParallelScheduler.cpp
  applications/plugins/MultiThreading/src/MultiThreading/AnimationLoopTasks.cpp
  applications/projects/SofaGuiGlut/Main.cpp
Labels: pr: breaking, pr: fix, pr: status ready

#2131 [Topology] add intersection methods
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetGeometryAlgorithms.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetGeometryAlgorithms.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetGeometryAlgorithms.inl
  modules/SofaGuiQt/src/sofa/gui/qt/viewer/SofaViewer.cpp
Labels: pr: new feature, pr: status ready

#2153 [SofaCommon] Convert tests to Sofa.Testing
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/CMakeLists.txt
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/MappingTestCreation.h
  SofaKernel/modules/SofaDeformable/SofaDeformable_test/CMakeLists.txt
  SofaKernel/modules/SofaDeformable/SofaDeformable_test/RestShapeSpringsForceField_test.cpp
  SofaKernel/modules/SofaDeformable/SofaDeformable_test/StiffSpringForceField_test.cpp
  SofaKernel/modules/SofaEngine/SofaEngine_test/CMakeLists.txt
  SofaKernel/modules/SofaExplicitOdeSolver/SofaExplicitOdeSolver_test/CMakeLists.txt
  SofaKernel/modules/SofaExplicitOdeSolver/SofaExplicitOdeSolver_test/EulerExplicitSolverDynamic_test.cpp
  SofaKernel/modules/SofaExplicitOdeSolver/SofaExplicitOdeSolver_test/MassSpringSystemCreation.h
  SofaKernel/modules/SofaImplicitOdeSolver/SofaImplicitOdeSolver_test/CMakeLists.txt
  SofaKernel/modules/SofaImplicitOdeSolver/SofaImplicitOdeSolver_test/EulerImplicitSolverDynamic_test.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/SofaImplicitOdeSolver_test/EulerImplicitSolverStatic_test.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/SofaImplicitOdeSolver_test/SpringSolverDynamic_test.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/SofaImplicitOdeSolver_test/StaticSolver_test.cpp
  SofaKernel/modules/SofaLoader/SofaLoader_test/CMakeLists.txt
  SofaKernel/modules/SofaLoader/SofaLoader_test/MeshObjLoader_test.cpp
  SofaKernel/modules/SofaRigid/SofaRigid_test/CMakeLists.txt
  SofaKernel/modules/SofaRigid/SofaRigid_test/QuaternionIntegration_test.cpp
  SofaKernel/modules/SofaRigid/SofaRigid_test/RigidMapping_test.cpp
  SofaKernel/modules/SofaRigid/SofaRigid_test/RigidRigidMapping_test.cpp
  SofaKernel/modules/SofaSimpleFem/SofaSimpleFem_test/CMakeLists.txt
  SofaKernel/modules/SofaSimpleFem/SofaSimpleFem_test/ForceFieldTestCreation.h
  SofaKernel/modules/SofaSimpleFem/SofaSimpleFem_test/HexahedronFEMForceField_test.cpp
  SofaKernel/modules/SofaSimpleFem/SofaSimpleFem_test/TetrahedronDiffusionFEMForceField_test.cpp
  SofaKernel/modules/SofaSimpleFem/SofaSimpleFem_test/TetrahedronFEMForceField_test.cpp
Labels: pr: clean, pr: status ready

#2169 [Sofa.Helper] Add new MOVED status to ComponentChange
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.h
Labels: pr: fast merge, pr: status to review

#2112 [MultiThreading] ADD scene showing the perf improvements
  applications/plugins/MultiThreading/examples/ParallelCollisionDetection.scn
Labels: pr: fast merge, pr: status ready

#2167 [SofaCore] Deprecate operator=
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/MultiMatrix.h
Labels: pr: clean, pr: fast merge, pr: status ready

#2181 [GTest] Fix with GCC11
  SofaKernel/modules/Sofa.Testing/extlibs/gtest/src/gtest-death-test.cc
Labels: pr: fast merge, pr: fix, pr: status ready

#2175 [CMake] FIX SofaFramework aliases
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
  SofaKernel/modules/SofaCore/CMakeLists.txt
  SofaKernel/modules/SofaCore/Sofa.CoreConfig.cmake.in
  SofaKernel/modules/SofaDefaultType/CMakeLists.txt
  SofaKernel/modules/SofaDefaultType/Sofa.DefaultTypeConfig.cmake.in
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  SofaKernel/modules/SofaHelper/Sofa.HelperConfig.cmake.in
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/Sofa.SimulationCoreConfig.cmake.in
  modules/SofaGeneralAnimationLoop/SofaGeneralAnimationLoopConfig.cmake.in
Labels: pr: fast merge, pr: fix, pr: status ready

#2154 [SofaSimulation] Convert tests to Sofa.Testing
  SofaKernel/modules/SofaSimulationCommon/SofaSimulationCommon_test/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCommon/SofaSimulationCommon_test/LoadScene_test.cpp
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/CMakeLists.txt
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/DAGNode_test.cpp
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/Link_test.cpp
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/MutationListener_test.cpp
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/Node_test.h
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/SimpleApi_test.cpp
Labels: pr: clean, pr: status ready

#2125 [SofaSimulationCore] Simplify repetitive code in BaseMechanicalVisitor
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/BaseMechanicalVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/BaseMechanicalVisitor.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Visitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Visitor.h
Labels: pr: breaking, pr: clean, pr: status ready

#2171 [All] remove method applyTestCreateFunction in TopologyDataHandler
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologySubsetData.inl
  applications/plugins/LMConstraint/src/LMConstraint/DOFBlockerLMConstraint.h
  applications/plugins/LMConstraint/src/LMConstraint/DOFBlockerLMConstraint.inl
  applications/plugins/LMConstraint/src/LMConstraint/FixedLMConstraint.h
  applications/plugins/LMConstraint/src/LMConstraint/FixedLMConstraint.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSource.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/AffineMovementConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/AffineMovementConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/FixedConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/FixedConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/FixedPlaneConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/FixedTranslationConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/FixedTranslationConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/LinearMovementConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/LinearMovementConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/LinearVelocityConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/LinearVelocityConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/PartialLinearMovementConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/PartialLinearMovementConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/PatchTestMovementConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/PatchTestMovementConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/ProjectDirectionConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/ProjectDirectionConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/ProjectToLineConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/ProjectToLineConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/ProjectToPlaneConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/ProjectToPlaneConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/ProjectToPointConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/ProjectToPointConstraint.inl
Labels: pr: clean, pr: fast merge, pr: status ready

#2170 [SofaMiscCollision] Clean options
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.h
  applications/plugins/SofaSphFluid/CMakeLists.txt
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SpatialGridPointModel.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SpatialGridPointModel.h
  examples/Components/collision/SpatialGridPointModel.scn
  examples/Components/visualmodel/PointSplatModel.scn
  modules/SofaMiscCollision/CMakeLists.txt
  modules/SofaMiscCollision/SofaMiscCollisionConfig.cmake.in
  modules/SofaMiscCollision/src/SofaMiscCollision/FrictionContact_DistanceGrid.cpp
Labels: pr: breaking, pr: clean, pr: fast merge, pr: status ready

#2184 [Topology] correct the logic issue in computeEdgeSegmentIntersection
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetGeometryAlgorithms.inl
Labels: pr: fast merge, pr: fix, pr: status ready

#2136 [SofaBoundaryCondition_test] Add TopologicalChanges unit test for FixedConstraint
  modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp
Labels: pr: new feature, pr: status ready

#2183 [SofaBaseMechanics_test] Add more checks in DiagonalMass_test
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/DiagonalMass_test.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#2138 [SofaCore] Minor cleaning in constraints
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/ConstraintSolver.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/ConstraintSolver.h
  examples/Demos/sofa_1000PR.scn
Labels: pr: clean, pr: status ready

#2190 [IDE] Regroup targets related to test
  CMakeLists.txt
  SofaKernel/modules/Sofa.Config/cmake/SofaMacrosUtils.cmake
Labels: pr: fast merge, pr: status ready

#2137 [Sofa.Core] Move eq,peq utilities functions to a standalone file
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/IdentityMapping.h
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/IdentityMapping.inl
  SofaKernel/modules/SofaCore/CMakeLists.txt
  SofaKernel/modules/SofaCore/src/sofa/core/MappingHelper.h
  modules/SofaMiscMapping/src/SofaMiscMapping/IdentityMultiMapping.inl
  modules/SofaMiscMapping/src/SofaMiscMapping/SubsetMultiMapping.inl
Labels: pr: clean, pr: status ready

#2176 [SofaBaseMechanics_test] Add TopologicalChanges unit tests for DiagonalMass
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/DiagonalMass_test.cpp
Labels: pr: new feature, pr: status ready

#2161 [Scenes] Add scenes to test several components during mesh removal
  examples/.scene-tests
  examples/Benchmark/TopologicalChanges/AffineMovementConstraint__RemovingMeshTest.scn
  examples/Benchmark/TopologicalChanges/FixedConstraint_RemovingMeshTest.scn
  examples/Benchmark/TopologicalChanges/FixedPlaneConstraint_RemovingMeshTest.scn
  examples/Benchmark/TopologicalChanges/LinearMovementConstraint_RemovingMeshTest.scn
  examples/Benchmark/TopologicalChanges/ProjectDirectionConstraint_RemovingMeshTest.scn
  examples/Benchmark/TopologicalChanges/ProjectToLineConstraint_RemovingMeshTest.scn
  examples/Benchmark/TopologicalChanges/ProjectToPlaneConstraint_RemovingMeshTest.scn
  examples/Benchmark/TopologicalChanges/ProjectToPointConstraint_RemovingMeshTest.scn
  examples/Benchmark/TopologicalChanges/RemovingTrianglesProcess_constraint.txt
  examples/Benchmark/TopologicalChanges/TriangularBendingSprings_RemovingMeshTest.scn
  examples/Benchmark/TopologicalChanges/TriangularFEMForceField_RemovingMeshTest.scn
Labels: pr: new feature, pr: status ready

#2197 [All] Disable Drawtool functions using Vec4f
  SofaKernel/modules/SofaHelper/src/sofa/helper/visual/DrawTool.h
  applications/plugins/Compliant/mapping/DifferenceFromTargetMapping.h
  applications/plugins/Compliant/mapping/SafeDistanceMapping.h
  applications/plugins/Flexible/deformationMapping/BaseDeformationMapping.inl
  applications/plugins/Flexible/deformationMapping/BaseDeformationMultiMapping.inl
  applications/plugins/Flexible/deformationMapping/TriangleDeformationMapping.inl
  applications/plugins/Flexible/quadrature/BaseGaussPointSampler.h
  applications/plugins/Flexible/types/ComponentSpecializations.cpp.inl
  applications/plugins/Flexible/types/RigidConstraint.h
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.cpp
  applications/plugins/OptiTrackNatNet/OptiTrackNatNetClient.cpp
  applications/plugins/OptiTrackNatNet/OptiTrackNatNetClient.h
  applications/plugins/OptiTrackNatNet/OptiTrackNatNetDevice.cpp
  applications/plugins/OptiTrackNatNet/OptiTrackNatNetDevice.h
  applications/plugins/PluginExample/src/PluginExample/MyMappingPendulumInPlane.inl
  applications/plugins/Registration/ClosestPointRegistrationForceField.inl
  applications/plugins/Registration/RegistrationContactForceField.inl
  applications/plugins/image/ImageSampler.h
  applications/plugins/image/ImageViewer.h
  modules/SofaUserInteraction/src/SofaUserInteraction/MouseInteractor.cpp
Labels: pr: clean, pr: fast merge, pr: status ready

#2200 [SofaLoaders] Fix MeshObjLoader material parsing by using the proper locale.
  SofaKernel/modules/SofaLoader/src/SofaLoader/MeshObjLoader.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#2202 [CGAL] Remove #pragma once in .cpp files
  applications/plugins/CGALPlugin/src/CGALPlugin/BooleanOperations.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/FrontSurfaceReconstruction.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/PoissonSurfaceReconstruction.cpp
  applications/plugins/CGALPlugin/src/CGALPlugin/UpsamplePointCloud.cpp
Labels: pr: clean, pr: fast merge, pr: status ready

#2186 [SofaBaseMechanics] Clean DiagonalMass init
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/DiagonalMass.h
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/DiagonalMass.inl
Labels: pr: fix, pr: status ready

#2172 [scenes] Update tetrahedron and tetrahedralCorotational FEM scenes
  examples/Components/forcefield/TetrahedralCorotationalFEMForceField.scn
  examples/Components/forcefield/TetrahedronFEMForceField.scn
  examples/Components/forcefield/TetrahedronFEMForceField_Chain.scn
Labels: pr: clean, pr: status ready

#2204 [SofaCore] Remove empty file
  SofaKernel/modules/SofaCore/CMakeLists.txt
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/MultiMatrix.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/MultiMatrix.h
Labels: pr: clean, pr: fast merge, pr: status ready

#2205 [SofaImplicitOdeSolver] Fix Latex format for doxygen
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/EulerImplicitSolver.h
Labels: pr: clean, pr: fast merge, pr: status ready

#2206 [CGALPlugin] Fix cgal drawings
  applications/plugins/CGALPlugin/src/CGALPlugin/MeshGenerationFromImage.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/MeshGenerationFromPolyhedron.inl
Labels: pr: fast merge, pr: fix, pr: status to review

#2163 [SofaSimulationCore] Add tons of details in Euler solver
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/BaseMechanicalState.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/BaseMechanicalState.h
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/EulerSolver.cpp
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/EulerSolver.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalOperations.cpp
Labels: pr: clean, pr: status ready

#2201 [SofaLoader] FIX Circular dependency in the update of MeshObjLoader
  SofaKernel/modules/SofaLoader/src/SofaLoader/MeshObjLoader.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#2165 [SofaExplicitOdelSolver] Introduce visitor to know the number of non-diagonal mass matrices
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/EulerSolver.cpp
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/EulerSolver.h
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/mechanicalvisitor/MechanicalGetNonDiagonalMassesCountVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/mechanicalvisitor/MechanicalGetNonDiagonalMassesCountVisitor.h
Labels: enhancement, pr: breaking, pr: status ready

#2166 [SofaSimulationGraph] Reading links fail when owner is invalid
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseLink.cpp
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/Link_test.cpp
Labels: pr: fix, pr: status ready

#2210 [All] Remove deprecated calls and warnings
  SofaKernel/modules/Sofa.Config/src/sofa/config.h.in
  SofaKernel/modules/Sofa.Type/src/sofa/type/Mat.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/MinProximityIntersection.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/NewProximityIntersection.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseVisual/src/SofaBaseVisual/VisualModelImpl.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/MultiMapping.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/RigidTypes.h
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/EulerSolver.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/EulerImplicitSolver.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/StaticSolver.cpp
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/MeshNewProximityIntersection.cpp
  modules/SofaConstraint/src/SofaConstraint/UncoupledConstraintCorrection.inl
  modules/SofaGeneralImplicitOdeSolver/src/SofaGeneralImplicitOdeSolver/VariationalSymplecticSolver.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/QDisplayDataWidget.cpp
  modules/SofaHeadlessRecorder/src/SofaHeadlessRecorder/HeadlessRecorder.cpp
  modules/SofaMiscEngine/src/SofaMiscEngine/DisplacementMatrixEngine.cpp
  modules/SofaMiscEngine/src/SofaMiscEngine/DisplacementMatrixEngine.inl
  modules/SofaMiscSolver/src/SofaMiscSolver/NewmarkImplicitSolver.cpp
Labels: pr: clean, pr: do not squash, pr: fast merge, pr: status ready

#2208 [Benchmark] Introduce benchmark on matrix assembly
  examples/Benchmark/Performance/MatrixAssembly/MatrixAssembly_assembledCG.scn
  examples/Benchmark/Performance/MatrixAssembly/MatrixAssembly_assembledCG_blocs.scn
  examples/Benchmark/Performance/MatrixAssembly/MatrixAssembly_direct.scn
  examples/Benchmark/Performance/MatrixAssembly/MatrixAssembly_direct_blocs.scn
  examples/Benchmark/Performance/MatrixAssembly/MatrixAssembly_matrixfreeCG.scn
  examples/Benchmark/Performance/MatrixAssembly/run.sh
Labels: pr: status to review

#2213 [SofaBaseLinearSolver] Important comment in the CG
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
Labels: pr: fast merge, pr: status ready

#2178 [Collision] Clean code related to intersection methods
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BaseProximityIntersection.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/DiscreteIntersection.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/DiscreteIntersection.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/MinProximityIntersection.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/MinProximityIntersection.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/NewProximityIntersection.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/NewProximityIntersection.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/NewProximityIntersection.inl
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/MeshNewProximityIntersection.cpp
  modules/SofaConstraint/CMakeLists.txt
  modules/SofaConstraint/src/SofaConstraint/LMDNewProximityIntersection.h
  modules/SofaConstraint/src/SofaConstraint/LocalMinDistance.cpp
  modules/SofaConstraint/src/SofaConstraint/LocalMinDistance.h
  modules/SofaConstraint/src/SofaConstraint/LocalMinDistance.inl
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshMinProximityIntersection.cpp
Labels: pr: clean, pr: fix, pr: status ready

#2191 [MeshMatrixMass_test] Clean and add more tests
  modules/SofaMiscForceField/SofaMiscForceField_test/MeshMatrixMass_test.cpp
Labels: pr: clean, pr: fix, pr: status ready

#2194 [SofaSimulationCore] Clean AnimateVisitor
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/AnimateVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/AnimateVisitor.h
Labels: pr: clean, pr: status ready

#2212 [SofaUserInteraction] Deprecate RayTraceDetection
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceDetection.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.cpp
  examples/Components/collision/RayTraceCollision.scn
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/DirectSAP.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/RayTraceDetection.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/RayTraceDetection.h
Labels: pr: clean, pr: fast merge, pr: status ready

#2207 [SofaKernel] Write template list in error message
  SofaKernel/modules/SofaCore/src/sofa/core/ObjectFactory.cpp
Labels: enhancement, pr: status ready

#2218 [SofaExplicitOdeSolver] Mark Data as disabled
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/EulerSolver.h
Labels: pr: fast merge, pr: status ready

#2195 [SofaBaseLinearSolver] Clean MatrixLinearSolver
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/MatrixLinearSolver.cpp
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/MatrixLinearSolver.h
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/MatrixLinearSolver.inl
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/mechanicalvisitor/MechanicalGetDimensionVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/mechanicalvisitor/MechanicalGetDimensionVisitor.h
  modules/SofaDenseSolver/src/SofaDenseSolver/LULinearSolver.cpp
  modules/SofaGeneralLinearSolver/src/SofaGeneralLinearSolver/BTDLinearSolver.inl
  modules/SofaPreconditioner/src/SofaPreconditioner/PrecomputedWarpPreconditioner.inl
  modules/SofaPreconditioner/src/SofaPreconditioner/WarpPreconditioner.inl
  modules/SofaSparseSolver/examples/FEM_SparseLDLSolver.scn
  modules/SofaSparseSolver/src/SofaSparseSolver/PrecomputedLinearSolver.inl
Labels: pr: breaking, pr: clean, pr: status ready
