Repository sofa-framework/sofa, pull requests merged in 2021-04, with the labels that each got.

#1917 [SofaBaseCollision] Speedup direct SAP
  SofaKernel/modules/SofaBaseCollision/CMakeLists.txt
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceDetection.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceDetection.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/CubeModel.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/MirrorIntersector.h
  SofaKernel/modules/SofaCore/src/sofa/core/collision/BroadPhaseDetection.h
  SofaKernel/modules/SofaCore/src/sofa/core/collision/CollisionAlgorithm.h
  SofaKernel/modules/SofaCore/src/sofa/core/collision/Detection.h
  SofaKernel/modules/SofaCore/src/sofa/core/collision/NarrowPhaseDetection.h
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/EndPoint.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/DirectSAP.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/DirectSAP.h
  modules/SofaUserInteraction/src/SofaUserInteraction/RayTraceDetection.cpp
Labels: enhancement, pr: clean, pr: highlighted in next release, pr: status ready

#1969 [Sofa.Topology] remove unnecessary pragma
  SofaKernel/modules/Sofa.Topology/src/sofa/topology/Point.cpp
Labels: pr: clean, pr: fast merge, pr: status to review

#1919 [examples] Fix or disable scene tests
  applications/plugins/Compliant/examples/.scene-tests
  applications/plugins/Flexible/examples/.scene-tests
  applications/plugins/RigidScale/examples/.scene-tests
  applications/plugins/RigidScale/examples/skinning/minimal_skin.obj
  applications/plugins/RigidScale/python/RigidScale/API.py
  applications/plugins/SofaPython/examples/.scene-tests
  applications/plugins/SofaPython/examples/PSDEExamples/PSDEAvgEngine.pyscn
  applications/plugins/SofaPython/examples/PSDEExamples/PSDEBasic.pyscn
  applications/plugins/SofaPython/examples/PythonScene.pyscn
  applications/plugins/SofaPython3/ExternalProjectConfig.cmake.in
  applications/plugins/image/examples/.scene-tests
Labels: pr: fix, pr: status ready

#1594 [SofaMiscTopology] Add component TopologyChecker
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/QuadSetTopologyContainer.h
  modules/SofaMiscTopology/CMakeLists.txt
  modules/SofaMiscTopology/SofaMiscTopology_test/CMakeLists.txt
  modules/SofaMiscTopology/SofaMiscTopology_test/TopologicalChangeProcessor_test.cpp
  modules/SofaMiscTopology/SofaMiscTopology_test/TopologyChecker_test.cpp
  modules/SofaMiscTopology/src/SofaMiscTopology/TopologyChecker.cpp
  modules/SofaMiscTopology/src/SofaMiscTopology/TopologyChecker.h
Labels: enhancement, pr: new feature, pr: status ready

#1930 [SofaSimulationCore] Clean free motion animation loop
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
  applications/plugins/SofaCarving/CarvingManager.cpp
  modules/SofaConstraint/src/SofaConstraint/ConstraintAnimationLoop.cpp
  modules/SofaConstraint/src/SofaConstraint/FreeMotionAnimationLoop.cpp
  modules/SofaConstraint/src/SofaConstraint/FreeMotionAnimationLoop.h
  modules/SofaGeneralAnimationLoop/src/SofaGeneralAnimationLoop/MultiStepAnimationLoop.cpp
  modules/SofaGeneralAnimationLoop/src/SofaGeneralAnimationLoop/MultiTagAnimationLoop.cpp
Labels: pr: clean, pr: status ready

#1932 [Sofa.Type] Remove MIN_DETERMINANT preprocessor value
  SofaKernel/modules/Sofa.Type/src/sofa/type/Mat.h
Labels: pr: clean, pr: status ready

#1941 [Sofa.GL] Relocate the module (again) + clarify module vs plugin definitions
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
  SofaKernel/modules/CMakeLists.txt
  SofaKernel/modules/Sofa.Config/cmake/SofaMacrosConfigure.cmake
  modules/CMakeLists.txt
Labels: pr: clean, pr: status ready

#1944 [SofaKernel] Regroup all compatibility files in a Sofa.Compat module
  CMakeLists.txt
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
  SofaKernel/modules/Sofa.Compat/CMakeLists.txt
  SofaKernel/modules/Sofa.Compat/README.md
  SofaKernel/modules/Sofa.Compat/Sofa.CompatConfig.cmake.in
  SofaKernel/modules/Sofa.Compat/src/sofa/core/visual/DrawTool.h
  SofaKernel/modules/Sofa.Compat/src/sofa/core/visual/DrawToolGL.h
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/BoundingBox.h
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/Color.h
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/Frame.h
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/Mat.h
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/MatSym.h
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/Mat_solve_Cholesky.h
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/Mat_solve_LU.h
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/Mat_solve_SVD.h
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/Quat.h
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/Quat.inl
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/RGBAColor.h
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/Ray.h
  SofaKernel/modules/Sofa.Compat/src/sofa/defaulttype/Vec.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/DualQuat.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/DualQuat.inl
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/Quater.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/Quater.inl
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/SVector.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/fixed_array.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/fixed_array_algorithms.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/Axis.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/BasicShapes.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/Capture.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/Color.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/Cylinder.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/FrameBufferObject.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/GLSLShader.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/RAII.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/Texture.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/Trackball.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/Transformation.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/VideoRecorderFFMPEG.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/glText.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/glText.inl
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/gl/template.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/stable_vector.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/system/gl.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/system/glu.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/types/Material.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/types/PrimitiveGroup.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/types/RGBAColor.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/types/RGBAColor_fwd.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/vector.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/vectorData.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/vectorLinks.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/vector_algebra.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/vector_algorithm.h
  SofaKernel/modules/Sofa.Compat/src/sofa/helper/vector_device.h
  SofaKernel/modules/Sofa.Compat/src/sofa/initSofaCompat.cpp
  SofaKernel/modules/Sofa.Type/CMakeLists.txt
  SofaKernel/modules/SofaCore/CMakeLists.txt
  SofaKernel/modules/SofaDefaultType/CMakeLists.txt
  SofaKernel/modules/SofaHelper/CMakeLists.txt
Labels: NG1: include-graph, pr: clean, pr: status ready

#1951 [Sofa.GL] static variable belongs to the class
  SofaKernel/modules/Sofa.GL/src/sofa/gl/Axis.cpp
  SofaKernel/modules/Sofa.GL/src/sofa/gl/Axis.h
  SofaKernel/modules/Sofa.GL/src/sofa/gl/Cylinder.cpp
  SofaKernel/modules/Sofa.GL/src/sofa/gl/Cylinder.h
Labels: pr: clean, pr: status ready

#1952 [Sofa.Type] add operator* for RGBAColor
  SofaKernel/modules/Sofa.Type/src/sofa/type/RGBAColor.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/RGBAColor.h
Labels: pr: clean, pr: fast merge, pr: status ready

#1955 [SofaBaseTopology] Remove definition of real
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/polygon_cube_intersection/fast_polygon_cube_intersection.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/polygon_cube_intersection/polygon_cube_intersection.h
Labels: pr: clean, pr: fast merge, pr: status ready

#1947 [SofaBaseTopology] Remove getter to some Data in Topology container and put them public
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/QuadSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetTopologyContainer.h
Labels: pr: breaking, pr: clean, pr: fast merge, pr: status ready

#1981 [SofaCore] Remove duplicated explicit instanciation
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologyHandler.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologyHandler.h
Labels: pr: fast merge, pr: fix, pr: status ready

#1970 [SofaUserInteraction] Remove AddFramePerformer as it is not compiled
  modules/SofaUserInteraction/CMakeLists.txt
  modules/SofaUserInteraction/src/SofaUserInteraction/AddFramePerformer.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/AddFramePerformer.h
  modules/SofaUserInteraction/src/SofaUserInteraction/AddFramePerformer.inl
Labels: pr: clean, pr: fast merge, pr: status to review

#1982 [SofaCore] Fix explicit instantiations with MultiMapping
  SofaKernel/modules/SofaCore/src/sofa/core/MultiMapping.h
Labels: pr: fast merge, pr: fix, pr: status ready

#1984 [SofaHelper][SofaBoundaryCondition] Fix export keywords
  SofaKernel/modules/SofaHelper/src/sofa/helper/AdvancedTimer.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/TrianglePressureForceField.h
Labels: pr: fast merge, pr: fix, pr: status ready

#1986 Modules: Update variable name
  modules/SofaGuiQt/src/sofa/gui/qt/QModelViewTableDataContainer.h
Labels: pr: fast merge, pr: status ready

#1987 [SofaSimulation/Tests] Fix init/cleanup in SofaSimulation modules
  SofaKernel/modules/SofaSimulationCommon/src/SofaSimulationCommon/init.cpp
  SofaKernel/modules/SofaSimulationGraph/src/SofaSimulationGraph/init.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#1983 [SofaHelper] Remove unused UnitTest class + clean FnDispatcher includes
  SofaKernel/modules/SofaCore/src/sofa/core/collision/Intersection.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/collision/Intersection.h
  SofaKernel/modules/SofaCore/src/sofa/core/collision/IntersectorFactory.h
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  SofaKernel/modules/SofaHelper/src/sofa/helper/UnitTest.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/UnitTest.h
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/MeshIntTool.h
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/FFDDistanceGridDiscreteIntersection.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/FFDDistanceGridDiscreteIntersection.h
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/RigidDistanceGridDiscreteIntersection.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/RigidDistanceGridDiscreteIntersection.h
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/TetrahedronDiscreteIntersection.cpp
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/TetrahedronDiscreteIntersection.h
  applications/tutorials/anatomyModelling/anatomyModelling.cpp
  applications/tutorials/compositeObject/compositeObject.cpp
  modules/SofaConstraint/src/SofaConstraint/LMDNewProximityIntersection.h
  modules/SofaConstraint/src/SofaConstraint/LocalMinDistance.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/DirectSAP.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshDiscreteIntersection.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshDiscreteIntersection.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshMinProximityIntersection.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshMinProximityIntersection.h
  modules/SofaUserInteraction/src/SofaUserInteraction/RayDiscreteIntersection.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/RayDiscreteIntersection.h
  modules/SofaUserInteraction/src/SofaUserInteraction/RayNewProximityIntersection.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/RayNewProximityIntersection.h
Labels: pr: clean, pr: fast merge, pr: status ready

#1971 [SofaBaseTopology] Remove warning when a Data is directly linked to a topoogy Data container
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyContainer.cpp
Labels: pr: clean, pr: fast merge, pr: status ready

#1973 [SofaUserInteraction] Fix Bug of removing topological element when a Hexa2TetraTopologicalMapping is in the scene
  modules/SofaUserInteraction/src/SofaUserInteraction/TopologicalChangeManager.cpp
Labels: pr: fix, pr: status ready

#1988 [SofaSimulationGraph] Restore tests
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationGraph/CMakeLists.txt
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/CMakeLists.txt
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/DAG_test.cpp
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/Link_test.cpp
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/Node_test.cpp
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/Node_test.h
Labels: pr: clean, pr: fast merge, pr: fix, pr: status to review

#1878 [Sofa.Type] Clean Quat
  SofaKernel/modules/Sofa.Config/src/sofa/config.h.in
  SofaKernel/modules/Sofa.Type/src/sofa/type/Quat.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/Quat.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/Quat.inl
  SofaKernel/modules/Sofa.Type/src/sofa/type/RGBAColor.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/Vec.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/fixed_array.h
  SofaKernel/modules/SofaDefaultType/CMakeLists.txt
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/DataTypeInfo.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/GenerateRigid.h
  SofaKernel/modules/SofaRigid/src/SofaRigid/RigidMapping.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Node.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Node.h
  applications/plugins/Registration/RegistrationExporter.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaRigidMapping.inl
  applications/plugins/SofaPython3/ExternalProjectConfig.cmake.in
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/PointConstraint.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/PointConstraint.inl
  modules/SofaMiscEngine/src/SofaMiscEngine/DisplacementMatrixEngine.cpp
  modules/SofaMiscEngine/src/SofaMiscEngine/DisplacementMatrixEngine.h
Labels: pr: breaking, pr: clean, pr: status ready

#1927 [SofaSimulationCore] FIX Task scheduler memory leak
  SofaKernel/modules/SofaSimulationCore/SofaSimulationCore_test/TaskSchedulerTestTasks.cpp
  SofaKernel/modules/SofaSimulationCore/SofaSimulationCore_test/TaskSchedulerTestTasks.h
  SofaKernel/modules/SofaSimulationCore/SofaSimulationCore_test/TaskSchedulerTests.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/DefaultTaskScheduler.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/DefaultTaskScheduler.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/TaskScheduler.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/TaskScheduler.h
Labels: pr: fix, pr: status ready

#2006 [Sofa.Type] Add missing header in fixed_array
  SofaKernel/modules/Sofa.Type/src/sofa/type/fixed_array.h
Labels: pr: fast merge, pr: fix, pr: status ready

#1978 [SofaGeneralEngine] Add option in NearestPointROI to use restPosition or position
  modules/SofaGeneralEngine/src/SofaGeneralEngine/NearestPointROI.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/NearestPointROI.inl
Labels: pr: clean, pr: do not squash, pr: status ready

#2004 [SofaPython3] Fix ExternalProjectConfig.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/BoundingBox.cpp
  applications/plugins/SofaPython3/ExternalProjectConfig.cmake.in
Labels: pr: fast merge, pr: status ready

#2007 [THMPGSpatialHashing] Add a readme file and basic information
  applications/plugins/THMPGSpatialHashing/README.md
Labels: pr: clean, pr: fast merge, pr: status ready

#2011 [SofaSimulationCore] Broken URL
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/PipelineImpl.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#1989 [all] Move BaseMechanicalVisitor in its own files
  SofaKernel/modules/SofaCore/src/sofa/core/fwd.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/map.h
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/BaseMechanicalVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/BaseMechanicalVisitor.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalComputeEnergyVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalVisitor.h
  applications/plugins/Compliant/assembly/AssemblyHelper.h
  applications/plugins/LMConstraint/src/LMConstraint/LMConstraintSolver.h
  applications/plugins/SofaPython/Binding_Node.cpp
  applications/plugins/SofaTest/ForceField_test.h
  modules/SofaConstraint/src/SofaConstraint/ConstraintAnimationLoop.h
  modules/SofaConstraint/src/SofaConstraint/GenericConstraintSolver.h
  modules/SofaConstraint/src/SofaConstraint/UncoupledConstraintCorrection.inl
Labels: pr: breaking, pr: clean, pr: status ready

#2002 [SofaSimulationCore] Move WorkerThread class into its own file
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/DefaultTaskScheduler.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/DefaultTaskScheduler.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/WorkerThread.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/WorkerThread.h
Labels: pr: clean, pr: fast merge, pr: status ready

#1985 [Sofa.Type] Modernize fixed_array
  SofaKernel/modules/Sofa.Type/src/sofa/type/fixed_array.h
Labels: pr: clean, pr: status ready

#2009 [SofaUserInteraction] Minor cleaning of RayTraceDetection
  modules/SofaUserInteraction/src/SofaUserInteraction/RayTraceDetection.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/RayTraceDetection.h
Labels: pr: clean, pr: fast merge, pr: status ready

#2020 [SofaGui] Fix GenericWidget closing brackets
  modules/SofaGuiQt/src/sofa/gui/qt/GenericWidget.h
Labels: pr: fast merge, pr: status ready

#2022 [SofaCUDA] Quick fix for SofaCUDA NVCC flags include not found during CMake setup
  applications/plugins/SofaCUDA/CMakeLists.txt
Labels: pr: fast merge, pr: fix, pr: status ready

#1950 [SofaBaseTopology] Single definition of global variables
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/MeshTopology.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetGeometryAlgorithms.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseMeshTopology.h
  SofaKernel/modules/SofaCore/src/sofa/core/topology/Topology.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/Topology.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/GenerateCylinder.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/GenerateSphere.inl
  modules/SofaMiscFem/src/SofaMiscFem/FastTetrahedralCorotationalForceField.inl
Labels: pr: clean, pr: status ready

#1997 [SofaSimulationCore] Set default TaskScheduler worker threads to idle state
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/DefaultTaskScheduler.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/WorkerThread.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#1862 [SofaConstraint] GenericConstraintSolver: compute compliances concurrently
  modules/SofaConstraint/src/SofaConstraint/GenericConstraintSolver.cpp
  modules/SofaConstraint/src/SofaConstraint/GenericConstraintSolver.h
Labels: pr: highlighted in next release, pr: new feature, pr: status ready

#1979 [SofaDeformable] Fix test in StiffSpringForceField doUpdateInternal
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/StiffSpringForceField.h
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/StiffSpringForceField.inl
Labels: pr: fix, pr: status ready

#1998 [Tests] Move tests in their (new) correct locations
  SofaKernel/modules/Sofa.Testing/CMakeLists.txt
  SofaKernel/modules/Sofa.Testing/Sofa.Testing_test/CMakeLists.txt
  SofaKernel/modules/Sofa.Testing/Sofa.Testing_test/TestMessageHandler_test.cpp
  SofaKernel/modules/Sofa.Type/CMakeLists.txt
  SofaKernel/modules/Sofa.Type/Sofa.Type_test/CMakeLists.txt
  SofaKernel/modules/Sofa.Type/Sofa.Type_test/Color_test.cpp
  SofaKernel/modules/Sofa.Type/Sofa.Type_test/MatTypes_test.cpp
  SofaKernel/modules/Sofa.Type/Sofa.Type_test/Material_test.cpp
  SofaKernel/modules/Sofa.Type/Sofa.Type_test/Quater_test.cpp
  SofaKernel/modules/Sofa.Type/Sofa.Type_test/SVector_test.cpp
  SofaKernel/modules/Sofa.Type/Sofa.Type_test/VecTypes_test.cpp
  SofaKernel/modules/Sofa.Type/Sofa.Type_test/vector_test.cpp
  SofaKernel/modules/SofaDefaultType/SofaDefaultType_test/CMakeLists.txt
  SofaKernel/modules/SofaHelper/SofaHelper_test/CMakeLists.txt
Labels: pr: clean, pr: status ready

#1999 [SofaBaseCollision] REFACTOR BruteForceDetection
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceDetection.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceDetection.h
  SofaKernel/modules/SofaCore/src/sofa/core/CollisionElement.h
  SofaKernel/modules/SofaCore/src/sofa/core/collision/BroadPhaseDetection.h
Labels: pr: breaking, pr: clean, pr: status ready

#2000 [SofaFramework/Sofa.Testing] remove macro and move testing resources from SofaFramework
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/modules/Sofa.GL/Sofa.GL_test/src/GLSLShader_test.cpp
  SofaKernel/modules/Sofa.Testing/CMakeLists.txt
  SofaKernel/modules/Sofa.Testing/resources/UtilsTest.ini
  SofaKernel/modules/Sofa.Testing/resources/dir with spaces/file.txt
  SofaKernel/modules/Sofa.Testing/resources/dir_é_with_è_accents_à/file.txt
  SofaKernel/modules/Sofa.Testing/resources/file with spaces.txt
  SofaKernel/modules/Sofa.Testing/resources/file è with é accents à.txt
  SofaKernel/modules/Sofa.Testing/resources/image/imagetest_blackwhite.png
  SofaKernel/modules/Sofa.Testing/resources/image/imagetest_noimage.png
  SofaKernel/modules/Sofa.Testing/resources/mesh/dragon.OBJ
  SofaKernel/modules/Sofa.Testing/resources/mesh/meshtest_nomesh.obj
  SofaKernel/modules/Sofa.Testing/resources/mesh/meshtest_nomesh.stl
  SofaKernel/modules/Sofa.Testing/resources/mesh/meshtest_uv_n_mtl.mtl
  SofaKernel/modules/Sofa.Testing/resources/mesh/meshtest_uv_n_mtl.obj
  SofaKernel/modules/Sofa.Testing/resources/mesh/suzanne.stl
  SofaKernel/modules/Sofa.Testing/resources/mesh/test.xs3
  SofaKernel/modules/Sofa.Testing/resources/mesh/test.xs4
  SofaKernel/modules/Sofa.Testing/resources/non-empty-directory/fileA.txt
  SofaKernel/modules/Sofa.Testing/resources/non-empty-directory/fileB.txt
  SofaKernel/modules/Sofa.Testing/resources/non-empty-directory/fileC.so
  SofaKernel/modules/Sofa.Testing/resources/shader/test.fs
  SofaKernel/modules/Sofa.Testing/resources/shader/test.gs
  SofaKernel/modules/Sofa.Testing/resources/shader/test.tcs
  SofaKernel/modules/Sofa.Testing/resources/shader/test.tes
  SofaKernel/modules/Sofa.Testing/resources/shader/test.vs
  SofaKernel/modules/Sofa.Testing/src/sofa/testing/config.h.in
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/SparseGridTopology_test.cpp
  SofaKernel/modules/SofaCore/SofaCore_test/objectmodel/DataFileName_test.cpp
  SofaKernel/modules/SofaCore/SofaCore_test/objectmodel/Data_test.cpp
  SofaKernel/modules/SofaHelper/SofaHelper_test/Utils_test.cpp
  SofaKernel/modules/SofaHelper/SofaHelper_test/io/MeshOBJ_test.cpp
  SofaKernel/modules/SofaHelper/SofaHelper_test/io/XspLoader_test.cpp
  SofaKernel/modules/SofaHelper/SofaHelper_test/system/FileMonitor_test.cpp
  SofaKernel/modules/SofaHelper/SofaHelper_test/system/FileRepository_test.cpp
  SofaKernel/modules/SofaHelper/SofaHelper_test/system/FileSystem_test.cpp
Labels: pr: clean, pr: status ready

#2012 [SofaSparseSolver] Clean useless dependencies
  modules/SofaSparseSolver/CMakeLists.txt
  modules/SofaSparseSolver/src/SofaSparseSolver/PrecomputedLinearSolver.cpp
  modules/SofaSparseSolver/src/SofaSparseSolver/PrecomputedLinearSolver.inl
Labels: pr: clean, pr: fast merge, pr: status ready

#2010 [SofaBaseCollision] Introduce brute force broad phase
  SofaKernel/modules/SofaBaseCollision/CMakeLists.txt
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceBroadPhase.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceBroadPhase.h
  modules/SofaUserInteraction/src/SofaUserInteraction/RayTraceDetection.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/RayTraceDetection.h
Labels: pr: new feature, pr: status ready

#2016 [SofaCUDA] Add more examples for liver scene and squareTissue
  applications/plugins/SofaCUDA/examples/SquareTissue-cpu.scn
  applications/plugins/SofaCUDA/examples/SquareTissue-cuda.scn
  applications/plugins/SofaCUDA/examples/liver-CUDA.scn
Labels: enhancement, pr: fast merge, pr: status ready

#2017 [SofaSimulationCore] Revert changes in #1927
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/DefaultTaskScheduler.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/TaskScheduler.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/TaskScheduler.h
Labels: pr: fast merge, pr: fix, pr: status ready

#2025 [plugins] Disable old python2 examples
  applications/plugins/RigidScale/examples/.scene-tests
  applications/plugins/SofaAssimp/examples/.scene-tests
  applications/plugins/SofaAssimp/examples/character_clothes.py
  applications/plugins/SofaPython/examples/.scene-tests
Labels: pr: fix, pr: status ready

#2024 [Tutorials] Resurrect tutorials projects
  applications/tutorials/CMakeLists.txt
  applications/tutorials/chainHybrid/CMakeLists.txt
  applications/tutorials/chainHybrid/chainHybrid.cpp
  applications/tutorials/compositeObject/CMakeLists.txt
  applications/tutorials/compositeObject/compositeObject.cpp
  applications/tutorials/mixedPendulum/CMakeLists.txt
  applications/tutorials/mixedPendulum/mixedPendulum.cpp
  applications/tutorials/oneParticle/CMakeLists.txt
  applications/tutorials/oneParticle/oneParticle.cpp
  applications/tutorials/oneTetrahedron/CMakeLists.txt
  applications/tutorials/oneTetrahedron/oneTetrahedron.cpp
Labels: pr: clean, pr: fix, pr: status ready

#2029 [SofaOpenglVisual] Fix typo
  modules/SofaOpenglVisual/src/SofaOpenglVisual/OglLabel.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#2034 [SofaSimulationCore] Reorder according to definition
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Node.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#2035 [SofaBaseTopology] Missing override keyword
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.inl
Labels: pr: fast merge, pr: fix, pr: status ready

#2027 [SofaBaseTopology] Add security in TopologyData to check input Topology pointer
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyData.inl
Labels: pr: fast merge, pr: fix, pr: status ready

#2026 [SofaSphFluid] Fix ParticleSink init and refresh all examples.
  applications/plugins/SofaSphFluid/examples/OglFluidModel_SPH.scn
  applications/plugins/SofaSphFluid/examples/OglFluidModel_SPHParticles.scn
  applications/plugins/SofaSphFluid/examples/ParticleSink.scn
  applications/plugins/SofaSphFluid/examples/ParticleSource.scn
  applications/plugins/SofaSphFluid/examples/ParticlesRepulsionForceField.scn
  applications/plugins/SofaSphFluid/examples/SPHDemo.scn
  applications/plugins/SofaSphFluid/examples/SPHFluidForceField.scn
  applications/plugins/SofaSphFluid/examples/SPHFluidForceField_benchmarks.scn
  applications/plugins/SofaSphFluid/examples/SPHFluidSurfaceMapping.scn
  applications/plugins/SofaSphFluid/examples/SPHParticleSink_obstacle.scn
  applications/plugins/SofaSphFluid/examples/SPHParticleSource.scn
  applications/plugins/SofaSphFluid/examples/SpatialGridContainer.scn
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSink.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSink.inl
  examples/Components/collision/SpatialGridPointModel.scn
  examples/Components/visualmodel/PointSplatModel.scn
Labels: pr: do not squash, pr: fix, pr: status ready

#2033 [Geomagic] Fix Geomagic plugin compilation
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.cpp
Labels: pr: backport todo, pr: fast merge, pr: fix, pr: status ready

#2031 [SofaConstraint] Fix symbol export of BilateralInteractionConstraint on RigidTypes
  modules/SofaConstraint/src/SofaConstraint/BilateralInteractionConstraint.cpp
  modules/SofaConstraint/src/SofaConstraint/BilateralInteractionConstraint.h
Labels: pr: fast merge, pr: fix, pr: status ready

#2037 [CMake] Set CMake install default component
  CMakeLists.txt
  SofaKernel/modules/Sofa.Config/CMakeLists.txt
Labels: pr: backport todo, pr: fast merge, pr: fix, pr: status ready

#2039 [SofaExporter] Remove SofaBaseVisual dependency
  modules/SofaExporter/CMakeLists.txt
  modules/SofaExporter/src/SofaExporter/STLExporter.cpp
Labels: pr: clean, pr: fast merge, pr: status ready

#2018 [SofaGuiCommon] Write json file
  modules/SofaGuiCommon/src/sofa/gui/BatchGUI.cpp
  modules/SofaGuiCommon/src/sofa/gui/BatchGUI.h
Labels: pr: fix, pr: status ready

#2038 [MultiThreading] Parallel brute force broad phase
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceBroadPhase.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceBroadPhase.h
  applications/plugins/MultiThreading/CMakeLists.txt
  applications/plugins/MultiThreading/examples/ParallelBruteForceBroadPhase.scn
  applications/plugins/MultiThreading/src/MultiThreading/ParallelBruteForceBroadPhase.cpp
  applications/plugins/MultiThreading/src/MultiThreading/ParallelBruteForceBroadPhase.h
Labels: pr: new feature, pr: status ready

#2001 [SofaFramework] Rename modules (cmake)
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
  SofaKernel/modules/SofaCore/CMakeLists.txt
  SofaKernel/modules/SofaCore/Sofa.CoreConfig.cmake.in
  SofaKernel/modules/SofaCore/src/sofa/core/config.h.in
  SofaKernel/modules/SofaDefaultType/CMakeLists.txt
  SofaKernel/modules/SofaDefaultType/Sofa.DefaultTypeConfig.cmake.in
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/config.h.in
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  SofaKernel/modules/SofaHelper/Sofa.HelperConfig.cmake.in
  SofaKernel/modules/SofaHelper/src/sofa/helper/config.h.in
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/Sofa.SimulationCoreConfig.cmake.in
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/config.h.in
Labels: NG1: include-graph, pr: clean, pr: highlighted in next release, pr: status ready

#2040 [SofaConstraint] Parallel free motion and collision detection
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/CollisionAnimationLoop.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/CollisionAnimationLoop.h
  examples/Benchmark/Performance/benchmark_cubes.pscn
  examples/Benchmark/Performance/benchmark_cubes.scn
  modules/SofaConstraint/CMakeLists.txt
  modules/SofaConstraint/src/SofaConstraint/FreeMotionAnimationLoop.cpp
  modules/SofaConstraint/src/SofaConstraint/FreeMotionAnimationLoop.h
  modules/SofaConstraint/src/SofaConstraint/FreeMotionTask.cpp
  modules/SofaConstraint/src/SofaConstraint/FreeMotionTask.h
Labels: pr: new feature, pr: status ready

#2044 [SofaGuiQt] Fix compat file SofaGuiQt.h
  modules/SofaGuiQt/src/sofa/gui/qt/SofaGuiQt.h
Labels: pr: fast merge, pr: fix, pr: status ready

#2046 [SofaBaseTopology] Remove warnings
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyData.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologySparseData.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologySubsetData.inl
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseTopologyData.h
Labels: pr: clean, pr: fast merge, pr: status ready
