Repository sofa-framework/sofa, pull requests merged in 2021-05, with the labels that each got.

#2052 [SofaMiscCollision] Fix config.in cmake file for export
  applications/plugins/SofaMiscCollision/CMakeLists.txt
  applications/plugins/SofaMiscCollision/SofaMiscCollisionConfig.cmake.in
Labels: pr: backport todo, pr: fast merge, pr: fix, pr: status ready

#2043 [SofaBaseCollision] BVH narrow phase
  SofaKernel/modules/SofaBaseCollision/CMakeLists.txt
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BVHNarrowPhase.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BVHNarrowPhase.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceBroadPhase.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceDetection.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BruteForceDetection.h
Labels: enhancement, pr: status ready

#2047 [SofaKernel] Switch from map_ptr_stable_compare to std::unordered_map
  SofaKernel/modules/SofaCore/SofaCore_test/CMakeLists.txt
  SofaKernel/modules/SofaCore/SofaCore_test/collision/NarrowPhaseDetection_test.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/collision/NarrowPhaseDetection.h
Labels: issue: discussion, pr: experimental, pr: status ready

#2067 [SofaCore] Revert #2047 for deterministic contacts
  SofaKernel/modules/SofaCore/src/sofa/core/collision/NarrowPhaseDetection.h
Labels: pr: fast merge, pr: status ready

#2072 [Geomagic] Duplicated includes #2070
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.cpp
Labels: pr: clean, pr: fast merge, pr: status ready

#2058 [HeadlessRecorder] CLEAN Headless recorder
  modules/SofaHeadlessRecorder/src/SofaHeadlessRecorder/HeadlessRecorder.cpp
  modules/SofaHeadlessRecorder/src/SofaHeadlessRecorder/HeadlessRecorder.h
Labels: pr: clean, pr: status ready

#2065 [CGAL] Fix compilation errors related to SOFA.GL and types converted to DataTypes
  applications/plugins/CGALPlugin/src/CGALPlugin/CuboidMesh.h
  applications/plugins/CGALPlugin/src/CGALPlugin/CuboidMesh.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.inl
  applications/plugins/CGALPlugin/src/CGALPlugin/MeshGenerationFromImage.h
Labels: pr: fast merge, pr: fix, pr: status ready

#2061 [SofaFramework] Restore IDE folder
  SofaKernel/SofaFramework/CMakeLists.txt
Labels: pr: fast merge, pr: status ready

#2068 [SofaOpenGLVisual] Fix unreachable code in VisualManagerSecondaryPass
  modules/SofaOpenglVisual/src/SofaOpenglVisual/VisualManagerSecondaryPass.cpp
Labels: pr: clean, pr: fast merge, pr: fix, pr: status ready

#2064 [SofaGuiCommon] Clean includes
  applications/plugins/SceneCreator/sceneCreatorExamples/SceneCreatorBenchmarks.cpp
  applications/projects/runSofa/Main.cpp
  applications/tutorials/chainHybrid/chainHybrid.cpp
  applications/tutorials/oneTetrahedron/oneTetrahedron.cpp
  modules/SofaGuiCommon/src/sofa/gui/BaseGUI.cpp
  modules/SofaGuiCommon/src/sofa/gui/BaseGUI.h
  modules/SofaGuiCommon/src/sofa/gui/BaseViewer.cpp
  modules/SofaGuiCommon/src/sofa/gui/BaseViewer.h
  modules/SofaGuiCommon/src/sofa/gui/BatchGUI.cpp
  modules/SofaGuiCommon/src/sofa/gui/BatchGUI.h
  modules/SofaGuiCommon/src/sofa/gui/ColourPickingVisitor.cpp
  modules/SofaGuiCommon/src/sofa/gui/FilesRecentlyOpenedManager.h
  modules/SofaGuiCommon/src/sofa/gui/GUIManager.cpp
  modules/SofaGuiCommon/src/sofa/gui/GUIManager.h
  modules/SofaGuiCommon/src/sofa/gui/GuiDataRepository.h
  modules/SofaGuiCommon/src/sofa/gui/MouseOperations.h
  modules/SofaGuiCommon/src/sofa/gui/PickHandler.cpp
  modules/SofaGuiCommon/src/sofa/gui/ViewerFactory.h
  modules/SofaGuiQt/src/sofa/gui/qt/RealGUI.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/SofaPluginManager.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/viewer/SofaViewer.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/viewer/qgl/QtGLViewer.cpp
  modules/SofaHeadlessRecorder/src/SofaHeadlessRecorder/HeadlessRecorder.cpp
Labels: pr: clean, pr: fast merge, pr: status ready

#2091 Update GraphListenerQListView.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/GraphListenerQListView.cpp
Labels: pr: clean, pr: fast merge, pr: status ready

#2083 [image] Fix wrong condition
  applications/plugins/image/ImageFilter.h
Labels: pr: fast merge, pr: fix, pr: status ready

#2042 [SofaCUDA] Ignore example scenes using SofaCUDA on CI
  applications/plugins/SofaCUDA/examples/.scene-tests
  applications/plugins/SofaCUDA/examples/SquareTissue-cpu.scn
  applications/plugins/SofaCUDA/examples/SquareTissue-cuda.scn
Labels: issue: discussion, pr: fast merge, pr: fix, pr: status ready

#2089 [examples] Benchmark the effects of DefaultCollisionGroupManager
  examples/Benchmark/Performance/CollisionGroupManager/1system_without_CollisionGroupManager.scn
  examples/Benchmark/Performance/CollisionGroupManager/2systems_with_CollisionGroupManager.scn
  examples/Benchmark/Performance/CollisionGroupManager/2systems_without_CollisionGroupManager.scn
Labels: issue: discussion, pr: fast merge, pr: status to review

#2102 [all] Avoid redundant printLog check
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/DiagonalMass.inl
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/PolynomialRestShapeSpringsForceField.inl
  modules/SofaMiscFem/src/SofaMiscFem/TetrahedronHyperelasticityFEMForceField.inl
Labels: pr: clean, pr: fast merge, pr: status ready

#1961 [All] ADD option to fetch pull-request commits in ExternalProject
  applications/plugins/InvertibleFVM/ExternalProjectConfig.cmake.in
  applications/plugins/SofaHighOrder/ExternalProjectConfig.cmake.in
  applications/plugins/SofaPython3/ExternalProjectConfig.cmake.in
  applications/projects/Regression/ExternalProjectConfig.cmake.in
Labels: enhancement, pr: status ready

#2081 [SofaBaseCollision] Remove dependencies on BaseIntTool
  SofaKernel/modules/SofaBaseCollision/SofaBaseCollision_test/BroadPhase_test.h
  SofaKernel/modules/SofaBaseCollision/SofaBaseCollision_test/Sphere_test.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BaseProximityIntersection.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BaseProximityIntersection.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/DiscreteIntersection.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/DiscreteIntersection.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/MinProximityIntersection.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/MinProximityIntersection.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/NewProximityIntersection.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/NewProximityIntersection.h
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/NewProximityIntersection.inl
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/MeshNewProximityIntersection.cpp
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/MeshNewProximityIntersection.h
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/MeshNewProximityIntersection.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaCollision.cpp
  applications/plugins/SofaMiscCollision/CMakeLists.txt
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/CapsuleContactMapper.cpp
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/CapsuleIntersection.cpp
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/CapsuleIntersection.h
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/OBBContact.cpp
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/OBBIntersection.h
  applications/plugins/SofaTest/BroadPhase_test.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshDiscreteIntersection.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshDiscreteIntersection.h
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshDiscreteIntersection.inl
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshMinProximityIntersection.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/MeshMinProximityIntersection.h
Labels: NG3: new-archi, pr: clean, pr: status ready

#2062 [Plugins] Add SofaGLFW GUI
  applications/projects/CMakeLists.txt
  applications/projects/SofaGLFW/ExternalProjectConfig.cmake.in
Labels: pr: highlighted in next release, pr: new feature, pr: status ready

#2104 [SofaBaseMechanics] Restore tests commented by mistake
  SofaKernel/modules/SofaBaseMechanics/CMakeLists.txt
Labels: pr: fast merge, pr: fix, pr: status ready

#2050 [SofaImplicitOdeSolver] Rewrite of the static Newton-Raphson ODE solver
  SofaKernel/modules/SofaImplicitOdeSolver/SofaImplicitOdeSolver_test/CMakeLists.txt
  SofaKernel/modules/SofaImplicitOdeSolver/SofaImplicitOdeSolver_test/StaticSolver_test.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/StaticSolver.cpp
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/StaticSolver.h
Labels: enhancement, pr: status ready

#2082 [SofaBaseTopology] Remove unnecessary code in BaseTopologyData
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyData.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyData.inl
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseTopologyData.h
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/LineLocalMinDistanceFilter.cpp
  SofaKernel/modules/SofaMeshCollision/src/SofaMeshCollision/TriangleLocalMinDistanceFilter.cpp
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/EdgePressureForceField.inl
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/TriangularFEMForceFieldOptim.inl
Labels: pr: breaking, pr: clean, pr: do not squash, pr: status ready

#2090 [SofaGeneralEngine] Remove dep on IdentityMapping (because of helper::eq)
  modules/SofaGeneralEngine/src/SofaGeneralEngine/GenerateGrid.inl
Labels: pr: clean, pr: fast merge, pr: status ready

#2084 [SofaUserInteraction] Refactor PickParticlePerformer
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaCollision.cpp
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/CapsuleIntersection.cpp
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/OBBIntersection.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/FixParticlePerformer.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/FixParticlePerformer.h
  modules/SofaUserInteraction/src/SofaUserInteraction/FixParticlePerformer.inl
  modules/SofaUserInteraction/src/SofaUserInteraction/RayContact.cpp
Labels: NG3: new-archi, pr: clean, pr: status ready

#2085 [SofaBaseTopology] Register TopologyHandler directly in each TopologyContainer
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/QuadSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/QuadSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyContainer.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyData.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyData.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetTopologyContainer.h
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseMeshTopology.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseMeshTopology.h
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseTopology.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseTopology.h
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologyHandler.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologyHandler.h
Labels: pr: breaking, pr: clean, pr: do not squash, pr: status ready

#2099 [SofaGeneralSimpleFem] Remove *Containers
  SofaKernel/modules/SofaHelper/src/sofa/helper/ComponentChange.cpp
  modules/SofaGeneralSimpleFem/CMakeLists.txt
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/BeamFEMForceField.h
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/BeamFEMForceField.inl
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/LengthContainer.h
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/PoissonContainer.h
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/RadiusContainer.h
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/StiffnessContainer.h
  modules/SofaMiscMapping/src/SofaMiscMapping/TubularMapping.h
  modules/SofaMiscMapping/src/SofaMiscMapping/TubularMapping.inl
  modules/SofaTopologyMapping/CMakeLists.txt
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Edge2QuadTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Edge2QuadTopologicalMapping.h
Labels: pr: breaking, pr: clean, pr: status ready

#2103 [SofaGraphComponent] Fix a typo in the warning emited by the APIVersion component and add missing allowed versions.
  CMakeLists.txt
  modules/SofaGraphComponent/src/SofaGraphComponent/APIVersion.cpp
Labels: pr: fix, pr: status ready

#2113 [Geomagic] Fix compilation of GeomagicVisualModel due to change in MechanicalVisitor
  applications/plugins/Geomagic/src/Geomagic/GeomagicVisualModel.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#2111 [SofaGraphComponent] Clean format of RequiredPlugin message
  modules/SofaGraphComponent/src/SofaGraphComponent/SceneCheckMissingRequiredPlugin.cpp
Labels: pr: clean, pr: fast merge, pr: fix, pr: status ready

#2120 [tools] CLEAN logs for macos-postinstall-fixup
  tools/postinstall-fixup/macos-postinstall-fixup.sh
Labels: pr: clean, pr: fast merge, pr: status ready

#2132 [SofaBaseCollision] Fix pipeline warning test
  SofaKernel/modules/SofaBaseCollision/SofaBaseCollision_test/DefaultPipeline_test.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/DefaultPipeline.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/DefaultPipeline.h
Labels: pr: fast merge, pr: fix, pr: status ready

#2126 [SofaTopologyMapping] Fix Edge2Quad condition
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Edge2QuadTopologicalMapping.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#2134 [SofaMiscCollision] Contact response order
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/DefaultCollisionGroupManager.cpp
  applications/plugins/SofaMiscCollision/src/SofaMiscCollision/DefaultCollisionGroupManager.h
Labels: pr: fast merge, pr: fix, pr: status ready
