Repository sofa-framework/sofa, pull requests merged in 2021-03, with the labels that each got.

#1868 [SofaKernel] fix #1857 out of bounds
  SofaKernel/modules/SofaHelper/src/sofa/helper/types/RGBAColor.cpp
Labels: pr: fast merge, pr: fix, status: ready

#1874 [SofaNonUniformFem] Remove shadow variable
  modules/SofaNonUniformFem/src/SofaNonUniformFem/SparseGridMultipleTopology.cpp
Labels: pr: clean, pr: fast merge, status: ready

#1876 [SofaFramework] Remove warnings (a lot)
  SofaKernel/modules/Sofa.Config/src/sofa/config.h.in
Labels: pr: clean, pr: fast merge, status: ready

#1879 [SofaCore] Use references in range loop with non trivial types in BaseObject
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObject.cpp
Labels: pr: fast merge, status: ready

#1880 [SofaOpenCL] Remove use of deleted functions
  applications/plugins/SofaOpenCL/OpenCLIdentityMapping.inl
  applications/plugins/SofaOpenCL/OpenCLTypes.h
Labels: pr: fast merge, pr: fix, status: ready

#1807 [all] Refactor Read/Write Accessor.
  SofaKernel/modules/Sofa.Type/CMakeLists.txt
  SofaKernel/modules/Sofa.Type/src/sofa/type/trait/is_container.h
  SofaKernel/modules/SofaBaseVisual/src/SofaBaseVisual/VisualStyle.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/Constraint.inl
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/PairInteractionConstraint.inl
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Data.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/VecTypes.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/accessor.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/vector.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTypes.h
  applications/projects/Modeler/lib/TutorialSelector.cpp
  modules/SofaConstraint/src/SofaConstraint/LinearSolverConstraintCorrection.inl
  modules/SofaConstraint/src/SofaConstraint/PrecomputedConstraintCorrection.inl
  modules/SofaConstraint/src/SofaConstraint/UncoupledConstraintCorrection.inl
  modules/SofaConstraint/src/SofaConstraint/UniformConstraint.inl
  modules/SofaMiscMapping/src/SofaMiscMapping/DistanceMapping.inl
Labels: refactoring, status: ready

#1881 [examples] FIX scene name for Regression_test
  applications/plugins/RegressionStateScenes.regression-tests
  examples/Components/solver/EulerExplicitSolver_diagonal.scn
  examples/RegressionStateScenes.regression-tests
  examples/RegressionTopologyScenes.regression-tests
Labels: pr: fast merge, pr: fix, status: to review

#1832 [SofaSimulationCore] Launch a new event when textures have been initialized.
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Simulation.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/events/SimulationInitTexturesDoneEvent.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/events/SimulationInitTexturesDoneEvent.h
Labels: enhancement, status: ready

#1756 [SofaGuiQt] Qt6 support
  SofaKernel/modules/Sofa.Config/cmake/SofaMacrosConfigure.cmake
  cmake/Modules/windeployqt.cmake
  cmake/Modules/windeployqt5.cmake
  cmake/Modules/windeployqt6.cmake
  modules/SofaGuiQt/CMakeLists.txt
  modules/SofaGuiQt/SofaGuiQtConfig.cmake.in
  modules/SofaGuiQt/libQGLViewer-2.7.1/QGLViewer/CMakeLists.txt
  modules/SofaGuiQt/src/sofa/gui/qt/BaseGenGraphForm.ui
  modules/SofaGuiQt/src/sofa/gui/qt/DialogAddObject.ui
  modules/SofaGuiQt/src/sofa/gui/qt/DisplayFlagsDataWidget.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/GUI.ui
  modules/SofaGuiQt/src/sofa/gui/qt/ModifyObject.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/QDataDescriptionWidget.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/QSofaListView.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/QTabulationModifyObject.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/RealGUI.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/VideoRecorderManager.ui
  modules/SofaGuiQt/src/sofa/gui/qt/viewer/qt/QtViewer.h
Labels: pr: new feature, status: ready

#1818 [SofaKernel] Port a bunch of types from Helper and Defaulttype to Sofa.Type
  SofaKernel/modules/Sofa.Type/CMakeLists.txt
  SofaKernel/modules/Sofa.Type/src/sofa/type/BoundingBox.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/BoundingBox.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/Color.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/Color.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/DualQuat.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/Frame.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/Frame.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/Material.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/Material.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/PrimitiveGroup.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/PrimitiveGroup.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/RGBAColor.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/RGBAColor.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/RGBAColor_fwd.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/Ray.h
  SofaKernel/modules/SofaDefaultType/CMakeLists.txt
  SofaKernel/modules/SofaDefaultType/compat/sofa/defaulttype/BoundingBox.h
  SofaKernel/modules/SofaDefaultType/compat/sofa/defaulttype/Color.h
  SofaKernel/modules/SofaDefaultType/compat/sofa/defaulttype/Frame.h
  SofaKernel/modules/SofaDefaultType/compat/sofa/defaulttype/RGBAColor.h
  SofaKernel/modules/SofaDefaultType/compat/sofa/defaulttype/Ray.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/Ray.h
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  SofaKernel/modules/SofaHelper/SofaHelper_test/types/Color_test.cpp
  SofaKernel/modules/SofaHelper/compat/sofa/helper/types/Material.h
  SofaKernel/modules/SofaHelper/compat/sofa/helper/types/PrimitiveGroup.h
  SofaKernel/modules/SofaHelper/compat/sofa/helper/types/RGBAColor.h
  SofaKernel/modules/SofaHelper/compat/sofa/helper/types/RGBAColor_fwd.h
  modules/SofaOpenglVisual/src/SofaOpenglVisual/OglLabel.cpp
Labels: NG1: include-graph, enhancement, pr: status ready

#1840 [SofaBaseTopology] Clean RenumberPoints methods
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/QuadSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/QuadSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetTopologyModifier.h
  applications/plugins/ManifoldTopologies/ManifoldEdgeSetTopologyModifier.cpp
  applications/plugins/ManifoldTopologies/ManifoldEdgeSetTopologyModifier.h
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Edge2QuadTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Hexa2QuadTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/IdentityTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Quad2TriangleTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/SubsetTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Tetra2TriangleTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Triangle2EdgeTopologicalMapping.cpp
Labels: pr: breaking, pr: clean, pr: do not squash, pr: fix, pr: status ready

#1844 [SofaSimulationCore] Remove ClassSystem.h
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/ClassSystem.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/LocalStorage.h
Labels: pr: clean, pr: status ready

#1845 [SofaSimulationGraph] Remove dead-end experiment in SimpleApi.h
  SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/fake_TopologyScene.cpp
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraph_test/SimpleApi_test.cpp
  SofaKernel/modules/SofaSimulationGraph/src/SofaSimulationGraph/SimpleApi.h
  applications/plugins/SofaCarving/SofaCarving_test/SofaCarving_test.cpp
Labels: pr: breaking, pr: clean, pr: status ready

#1848 [SofaKernel][SofaGui] Move Boost::program_option and remove Boost::system dependencies
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  applications/plugins/SofaTest/Mapping_test.h
  modules/SofaGuiCommon/CMakeLists.txt
  modules/SofaGuiCommon/SofaGuiCommonConfig.cmake.in
  modules/SofaGuiCommon/compat/sofa/helper/ArgumentParser.h
  modules/SofaGuiCommon/src/sofa/gui/ArgumentParser.cpp
  modules/SofaGuiCommon/src/sofa/gui/ArgumentParser.h
Labels: pr: clean, pr: status ready

#1854 [SofaSimpleFEM] Fix TetrahedronFEMForceField Von Mises stress drawing
  SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.h
  SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
Labels: pr: clean, pr: fix, pr: status ready

#1861 [SofaTopologyMapping] adds ellipse feature to Edge2QuadTopologyMapping
  applications/plugins/SofaPython/examples/Components/topology/Edge2QuadTopologyMapping.py
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Edge2QuadTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Edge2QuadTopologicalMapping.h
Labels: pr: breaking, pr: clean, pr: new feature, pr: status ready

#1889 [SofaGuiQt] Fix compilation
  modules/SofaGuiQt/CMakeLists.txt
  modules/SofaGuiQt/libQGLViewer-2.7.1/QGLViewer/CMakeLists.txt
Labels: pr: fast merge, pr: fix, pr: status to review

#1892 [SofaGuiCommon] Fix include path for compat files when installing
  modules/SofaGuiCommon/CMakeLists.txt
Labels: pr: fast merge, pr: fix, pr: status to review

#1894 [CentralDifferenceSolver] Fixed typo error in description
  modules/SofaGeneralExplicitOdeSolver/src/SofaGeneralExplicitOdeSolver/CentralDifferenceSolver.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#1891 [CMake] FIX Debug build + more cleaning
  SofaKernel/modules/Sofa.Config/cmake/SofaMacrosConfigure.cmake
  SofaKernel/modules/SofaHelper/src/sofa/helper/config.h.in
  applications/plugins/CImgPlugin/CMakeLists.txt
  cmake/Modules/windeployqt.cmake
  modules/SofaGeneralEngine/SofaGeneralEngineConfig.cmake.in
  modules/SofaGeneralEngine/src/SofaGeneralEngine/config.h.in
  modules/SofaGeneralVisual/SofaGeneralVisualConfig.cmake.in
  modules/SofaGuiCommon/CMakeLists.txt
  modules/SofaGuiCommon/SofaGuiCommonConfig.cmake.in
  modules/SofaGuiCommon/src/sofa/gui/config.h.in
Labels: pr: clean, pr: fast merge, pr: fix, pr: status ready

#1899 [SofaBaseUtils] Clean RequiredPlugin
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/RequiredPlugin.cpp
  SofaKernel/modules/SofaBaseUtils/src/SofaBaseUtils/RequiredPlugin.h
Labels: pr: clean, pr: status to review

#1842 [All] Removes search & searchAll from BaseObject
  SofaKernel/modules/Sofa.Config/src/sofa/config.h.in
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObject.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Context.h
  applications/plugins/Compliant/Compliant_gui/CompliantAttachPerformer.inl
  applications/plugins/Flexible/deformationMapping/TriangleStrainAverageMapping.inl
  applications/plugins/image/ImageTypes.h
  modules/SofaExporter/src/SofaExporter/BlenderExporter.inl
Labels: pr: breaking, pr: status ready, refactoring

#1858 [SofaBaseTopology] Secure PointSetTopologyModifier API
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/QuadSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetTopologyModifier.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSink.inl
  modules/SofaTopologyMapping/src/SofaTopologyMapping/CenterPointTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Edge2QuadTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Hexa2QuadTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/IdentityTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Mesh2PointTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Quad2TriangleTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/SubsetTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Tetra2TriangleTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Triangle2EdgeTopologicalMapping.cpp
Labels: pr: breaking, pr: clean, pr: do not squash, pr: status ready

#1911 [SofaFramework] Fix config files for Sofa.GL, for out-of-tree
  SofaKernel/modules/Sofa.GL/Sofa.GLConfig.cmake.in
Labels: pr: fast merge, pr: fix, pr: status to review

#1902 [SofaHelper] Moves operator>> specialisation for int from set.h to set.cpp
  SofaKernel/modules/SofaCore/CMakeLists.txt
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  SofaKernel/modules/SofaHelper/src/sofa/helper/set.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/set.h
Labels: pr: clean, pr: fast merge, pr: status ready

#1886 [All] CLEAN tests, use CMake weak dependencies
  CMakeLists.txt
  SofaKernel/modules/SofaBaseMechanics/SofaBaseMechanics_test/CMakeLists.txt
  SofaKernel/modules/SofaBaseUtils/CMakeLists.txt
  SofaKernel/modules/SofaBaseUtils/SofaBaseUtils_test/CMakeLists.txt
  SofaKernel/modules/SofaCore/CMakeLists.txt
  SofaKernel/modules/SofaCore/SofaCore_simutest/CMakeLists.txt
  SofaKernel/modules/SofaDefaultType/CMakeLists.txt
  SofaKernel/modules/SofaDefaultType/SofaDefaultType_simutest/CMakeLists.txt
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  SofaKernel/modules/SofaHelper/SofaHelper_simutest/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCommon/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCommon/SofaSimulationCommon_test/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/SofaSimulationCore_simutest/CMakeLists.txt
  modules/SofaGeneralMeshCollision/CMakeLists.txt
  modules/SofaGeneralMeshCollision/SofaGeneralMeshCollision_test/CMakeLists.txt
  modules/SofaGeneralSimpleFem/CMakeLists.txt
  modules/SofaGeneralSimpleFem/SofaGeneralSimpleFem_test/CMakeLists.txt
  modules/SofaGeneralSimpleFem/SofaGeneralSimpleFem_test/scenes/LinearElasticity.scn
  modules/SofaGeneralVisual/CMakeLists.txt
  modules/SofaGeneralVisual/SofaGeneralVisual_test/CMakeLists.txt
  tests/CMakeLists.txt
Labels: pr: clean, pr: status ready

#1904 [RealGUI] Fix: QDesktopWidget header missing for Qt < 5.11
  modules/SofaGuiQt/src/sofa/gui/qt/RealGUI.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#1872 [SofaBaseTopology] Rename TopologyEngine and TopologyData classes to match file names
  SofaKernel/modules/SofaBaseTopology/CMakeLists.txt
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/QuadSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/QuadSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyData.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyData.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataEngine.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataEngine.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologySparseData.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologySparseData.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologySparseDataHandler.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologySubsetData.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologySubsetData.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetTopologyContainer.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseVisual/src/SofaBaseVisual/VisualModelImpl.cpp
  SofaKernel/modules/SofaCore/CMakeLists.txt
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseTopology.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologyEngine.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologyEngine.h
Labels: pr: breaking, pr: clean, pr: do not squash, pr: status ready

#1914 [SofaGuiQt] Fix compilation when SOFA_DUMP_VISITOR is enabled
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Visitor.h
  applications/plugins/SofaDistanceGrid/extlibs/miniFlowVR/src/librender/mesh_io_mesh.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/GraphVisitor.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/GraphVisitor.h
  modules/SofaGuiQt/src/sofa/gui/qt/PieWidget.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/WindowVisitor.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/WindowVisitor.h
Labels: pr: fast merge, pr: fix, pr: status ready

#1913 [All] Rename SOFA_NO_OPENGL + Relocate Sofa.GL + Improve sofa_add_* macros
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
  SofaKernel/modules/CMakeLists.txt
  SofaKernel/modules/Sofa.Config/CMakeLists.txt
  SofaKernel/modules/Sofa.Config/Sofa.ConfigConfig.cmake.in
  SofaKernel/modules/Sofa.Config/cmake/SofaMacrosConfigure.cmake
  applications/collections/SofaComponentAll/CMakeLists.txt
  applications/collections/SofaComponentAll/SofaComponentAllConfig.cmake.in
  applications/plugins/Compliant/CMakeLists.txt
  applications/plugins/Compliant/CompliantConfig.cmake.in
  applications/plugins/Compliant/config.h.in
  applications/plugins/Compliant/mapping/AdditionMapping.h
  applications/plugins/Compliant/mapping/DifferenceMapping.h
  applications/plugins/Compliant/mapping/SafeDistanceMapping.h
  applications/plugins/Flexible/CMakeLists.txt
  applications/plugins/Flexible/FlexibleConfig.cmake.in
  applications/plugins/Flexible/config.h.in
  applications/plugins/Flexible/deformationMapping/BaseDeformationImpl.inl
  applications/plugins/Flexible/deformationMapping/BaseDeformationMapping.inl
  applications/plugins/Flexible/deformationMapping/BaseDeformationMultiMapping.inl
  applications/plugins/Flexible/types/ComponentSpecializations.cpp.inl
  applications/projects/SofaGuiGlut/CMakeLists.txt
  applications/projects/SofaGuiGlut/glut.h
  modules/CMakeLists.txt
Labels: pr: clean, pr: fast merge, pr: status ready

#1918 [SofaGuiQt] Use opaque API instead
  modules/SofaGuiQt/src/sofa/gui/qt/ModifyObject.cpp
Labels: pr: fast merge, pr: fix, pr: status ready

#1920 [SofaFramework] Put back Sofa.GL in Framework
  SofaKernel/SofaFramework/CMakeLists.txt
  SofaKernel/SofaFramework/SofaFrameworkConfig.cmake.in
  SofaKernel/modules/CMakeLists.txt
Labels: pr: fast merge, pr: fix, pr: revert(ed), pr: status ready

#1929 Remove pragma guard in cpp files
  SofaKernel/modules/SofaHelper/src/sofa/helper/fwd.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/AddFramePerformer.cpp
Labels: pr: clean, pr: fast merge, pr: status ready

#1744 [SofaCore] Reduce the needs for include in Node.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Node.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Node.h
  SofaKernel/modules/SofaSimulationGraph/src/SofaSimulationGraph/DAGNode.cpp
  applications/plugins/MultiThreading/src/MultiThreading/AnimationLoopParallelScheduler.cpp
  applications/plugins/SofaSimpleGUI/VisualPickVisitor.cpp
  modules/SofaGeneralObjectInteraction/src/SofaGeneralObjectInteraction/AttachConstraint.inl
  modules/SofaGuiQt/src/sofa/gui/qt/GraphListenerQListView.cpp
Labels: pr: clean, pr: do not squash, pr: status ready

#1859 [SofaBaseTopology] Secure All Topology modifiers API
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/QuadSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetTopologyModifier.h
  applications/plugins/ManifoldTopologies/ManifoldEdgeSetTopologyModifier.h
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Edge2QuadTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Hexa2QuadTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/IdentityTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Mesh2PointTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Quad2TriangleTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/SubsetTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Triangle2EdgeTopologicalMapping.cpp
Labels: pr: breaking, pr: clean, pr: do not squash, pr: status ready

#1890 [SofaKernel] Removes the method BaseData::getOwnerClass()
  SofaKernel/modules/Sofa.Config/src/sofa/config.h.in
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.h
Labels: pr: status ready, refactoring

#1860 [SofaBaseTopology] Remove public access to propagateTopologyChanges
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/HexahedronSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyModifier.cpp
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/PointSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/QuadSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TetrahedronSetTopologyModifier.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetTopologyModifier.h
  modules/SofaMiscTopology/src/SofaMiscTopology/TopologicalChangeProcessor.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Edge2QuadTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Hexa2QuadTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/IdentityTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Mesh2PointTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Quad2TriangleTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/SimpleTesselatedTetraTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/SubsetTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Tetra2TriangleTopologicalMapping.cpp
  modules/SofaTopologyMapping/src/SofaTopologyMapping/Triangle2EdgeTopologicalMapping.cpp
  modules/SofaUserInteraction/src/SofaUserInteraction/TopologicalChangeManager.cpp
Labels: pr: breaking, pr: clean, pr: status ready

#1901 [SofaHelper] Replace boost::shared_ptr for std::shared_ptr
  SofaKernel/modules/SofaHelper/src/sofa/helper/logging/ComponentInfo.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/logging/FileInfo.h
Labels: pr: breaking, pr: clean, pr: status ready

#1905 [SofaSimulationCore] Moves code from TopologyChangeVisitor.h into .cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/TopologyChangeVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/TopologyChangeVisitor.h
Labels: pr: clean, pr: fast merge, pr: status ready

#1906 [MultiThreading] Removes useless classid in AnimationLoopParalleleScheduler.cpp
  applications/plugins/MultiThreading/src/MultiThreading/AnimationLoopParallelScheduler.cpp
Labels: pr: clean, pr: status ready

#1907 [Sofa.Type & DefaultType] Adds forward declaration for Vec and StdRigidTypes.
  SofaKernel/modules/Sofa.Type/src/sofa/type/Vec.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/fwd.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/RigidTypes.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/VecTypes.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/fwd.h
Labels: pr: clean, pr: status ready

#1937 [Sofa.Type] Add forgotten function declaration, used in Debug
  SofaKernel/modules/Sofa.Type/src/sofa/type/stdtype/vector_T.h
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/FullVector.inl
Labels: pr: fast merge, pr: fix, pr: status ready

#1909 [SofaMiscTopology_test] Replace inheritence of SofaTest by BaseSimulation_test and fix test
  SofaKernel/modules/Sofa.Testing/src/sofa/testing/BaseSimulationTest.cpp
  SofaKernel/modules/Sofa.Testing/src/sofa/testing/BaseSimulationTest.h
  modules/SofaMiscTopology/SofaMiscTopology_test/CMakeLists.txt
  modules/SofaMiscTopology/SofaMiscTopology_test/TopologicalChangeProcessor_test.cpp
  modules/SofaMiscTopology/SofaMiscTopology_test/scenes/IncisionTrianglesProcess.scn
  modules/SofaMiscTopology/SofaMiscTopology_test/scenes/IncisionTrianglesProcess.txt
Labels: pr: fix, pr: status ready

#1933 [SofaKernel] Correct licence citations
  SofaKernel/modules/Sofa.Testing/compat/SofaSimulationGraph/testing/BaseSimulationTest.h
  SofaKernel/modules/Sofa.Testing/compat/sofa/helper/testing/BaseTest.h
  SofaKernel/modules/Sofa.Testing/compat/sofa/helper/testing/NumericTest.h
  SofaKernel/modules/Sofa.Testing/compat/sofa/helper/testing/TestMessageHandler.h
  SofaKernel/modules/Sofa.Testing/src/sofa/testing/BaseSimulationTest.h
  SofaKernel/modules/Sofa.Testing/src/sofa/testing/BaseTest.h
  SofaKernel/modules/Sofa.Testing/src/sofa/testing/NumericTest.h
  SofaKernel/modules/SofaCore/src/sofa/core/fwd.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/fwd.h
Labels: pr: fast merge, pr: status to review

#1938 [SofaSimpleFem] FIX wrong initialization order
  SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
Labels: pr: clean, pr: fast merge, pr: status ready

#1942 [SofaHelper] Fix compilation in kdtree
  SofaKernel/modules/SofaHelper/src/sofa/helper/kdTree.h
Labels: pr: fast merge, pr: fix, pr: status to review

#1940 [SofaComponentAll] FIX build with disabled dependencies
  applications/collections/SofaComponentAll/CMakeLists.txt
Labels: pr: fast merge, pr: fix, pr: status ready

#1928 [SofaCore] Clean dependencies to SimulationCore
  SofaKernel/modules/SofaCore/src/sofa/core/collision/Pipeline.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseContext.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseContext.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Context.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/GUIEvent.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/HapticDeviceEvent.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/JoystickEvent.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/MouseEvent.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/ScriptEvent.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/ScriptEvent.h
Labels: NG1: include-graph, pr: clean, pr: fast merge, pr: status to review

#1939 [SofaBaseMechanics] Restore useRestPos Data initialization for BarycentricMapping
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/BarycentricMapping.h
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/BarycentricMapping.inl
Labels: pr: fast merge, pr: fix, pr: status ready

#1903 [SofaCore] isDiagonal is const
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/DiagonalMass.h
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/UniformMass.h
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/BaseMass.h
  applications/plugins/Compliant/misc/RigidMass.h
  applications/plugins/ExternalBehaviorModel/FEMGridBehaviorModel.h
  applications/plugins/Flexible/mass/AffineMass.h
  applications/plugins/Flexible/mass/ImageDensityMass.h
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/HexahedralFEMForceFieldAndMass.h
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/HexahedronFEMForceFieldAndMass.h
  modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.h
Labels: pr: breaking, pr: fix, pr: status ready

#1946 [Sofa.Type] Remove stdtype subdirectory
  SofaKernel/modules/Sofa.Type/CMakeLists.txt
  SofaKernel/modules/Sofa.Type/src/sofa/type/Mat.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/RGBAColor.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/RGBAColor.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/SVector.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/SVector.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/Vec.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/fixed_array.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/fixed_array.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/fixed_array_algorithms.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/stable_vector.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector_Integral.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector_Integral.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector_Real.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector_Real.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector_String.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector_String.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector_T.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector_T.inl
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector_algebra.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector_algorithm.h
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector_device.h
  SofaKernel/modules/SofaHelper/compat/sofa/helper/SVector.h
  SofaKernel/modules/SofaHelper/compat/sofa/helper/fixed_array.h
  SofaKernel/modules/SofaHelper/compat/sofa/helper/fixed_array_algorithms.h
  SofaKernel/modules/SofaHelper/compat/sofa/helper/stable_vector.h
  SofaKernel/modules/SofaHelper/compat/sofa/helper/vector.h
  SofaKernel/modules/SofaHelper/compat/sofa/helper/vector_algebra.h
  SofaKernel/modules/SofaHelper/compat/sofa/helper/vector_algorithm.h
  SofaKernel/modules/SofaHelper/compat/sofa/helper/vector_device.h
Labels: NG1: include-graph, pr: fast merge, pr: status ready

#1953 [SofaHelper] Clarify with global namespace
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/PipeProcess.cpp
Labels: pr: clean, pr: fast merge, pr: status ready

#1956 [SofaMiscMapping] Remove unused global variable
  modules/SofaMiscMapping/src/SofaMiscMapping/SquareDistanceMapping.inl
Labels: pr: clean, pr: fast merge, pr: status ready

#1957 [SofaMiscMapping] Factorize code to remove duplicated struct
  modules/SofaMiscMapping/CMakeLists.txt
  modules/SofaMiscMapping/src/SofaMiscMapping/CenterOfMassMappingOperation.h
  modules/SofaMiscMapping/src/SofaMiscMapping/CenterOfMassMulti2Mapping.inl
  modules/SofaMiscMapping/src/SofaMiscMapping/CenterOfMassMultiMapping.inl
Labels: pr: clean, pr: status ready

#1958 [SofaBoundaryCondition] Avoid ambiguity
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/LinearMovementConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/PartialLinearMovementConstraint.inl
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/PatchTestMovementConstraint.inl
  modules/SofaConstraint/src/SofaConstraint/BilateralConstraintResolution.h
Labels: pr: clean, pr: fast merge, pr: status ready

#1948 [SofaGuiQt] FIX segfault due to qFatal in GenGraphForm
  modules/SofaGuiQt/src/sofa/gui/qt/GenGraphForm.cpp
Labels: pr: backport todo, pr: fast merge, pr: fix, pr: status ready

#1959 [SofaSimulation*] Fix confusion between namespaces
  SofaKernel/modules/SofaSimulationCommon/src/SofaSimulationCommon/xml/BaseElement.h
  SofaKernel/modules/SofaSimulationCommon/src/SofaSimulationCommon/xml/Element.h
  SofaKernel/modules/SofaSimulationCommon/src/SofaSimulationCommon/xml/Element.inl
  SofaKernel/modules/SofaSimulationCommon/src/SofaSimulationCommon/xml/NodeElement.h
  SofaKernel/modules/SofaSimulationCommon/src/SofaSimulationCommon/xml/ObjectElement.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/BaseSimulationExporter.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/InitTasks.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalComputeEnergyVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalComputeEnergyVisitor.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalVisitor.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/SolveVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/SolveVisitor.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/StateChangeVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/StateChangeVisitor.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/TopologyChangeVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/TopologyChangeVisitor.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Visitor.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/XMLPrintVisitor.h
  SofaKernel/modules/SofaSimulationGraph/src/SofaSimulationGraph/DAGNode.cpp
  SofaKernel/modules/SofaSimulationGraph/src/SofaSimulationGraph/DAGNode.h
Labels: pr: clean, pr: fast merge, pr: status ready

#1949 [CMake] FIX resources and translations install on Windows
  cmake/Modules/windeployqt.cmake
Labels: pr: backport todo, pr: fast merge, pr: fix
