Repository sofa-framework/sofa, pull requests merged in 2021-09, with the labels that each got.

#2292 [Sofa.Core] Deprecate officially the usage of SofaOStream (sout, serr, sendl in Base)
  SofaKernel/modules/Sofa.Config/src/sofa/config.h.in
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/BVHNarrowPhase.cpp
  SofaKernel/modules/SofaBaseVisual/src/SofaBaseVisual/VisualModelImpl.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/DataFileName.cpp
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/PolynomialRestShapeSpringsForceField.h
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/SVDLinearSolver.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/SofaOStream.h
  SofaKernel/modules/SofaLoader/src/SofaLoader/MeshVTKLoader.cpp
  SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/HexahedronFEMForceField.inl
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Simulation.cpp
  applications/plugins/LMConstraint/src/LMConstraint/PrecomputedLMConstraintCorrection.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaHexahedronTLEDForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLinearForceField.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaPenalityContactForceField.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaPointModel.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedronTLEDForceField.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/DistanceGridCollisionModel.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/FFDDistanceGridDiscreteIntersection.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/FFDDistanceGridDiscreteIntersection.inl
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/RigidDistanceGridDiscreteIntersection.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/RigidDistanceGridDiscreteIntersection.inl
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/forcefield/DistanceGridForceField.h
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/forcefield/DistanceGridForceField.inl
  applications/plugins/SofaEulerianFluid/Fluid2D.h
  applications/plugins/SofaEulerianFluid/Fluid3D.h
  applications/plugins/SofaImplicitField/components/mapping/ImplicitSurfaceMapping.h
  applications/plugins/SofaImplicitField/components/mapping/ImplicitSurfaceMapping.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSource.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticlesRepulsionForceField.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticlesRepulsionForceField.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidForceField.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SpatialGridPointModel.cpp
  applications/plugins/VolumetricRendering/src/VolumetricRendering/OglVolumetricModel.cpp
  applications/plugins/image/ImageContainer.h
  applications/plugins/image/ImageCoordValuesFromPositions.h
  applications/plugins/image/ImageExporter.h
  applications/plugins/image/ImageSampler.h
  applications/plugins/image/ImageTransform.h
  applications/plugins/image/MeshToImageEngine.h
  applications/plugins/image/imagetoolbox/contour/contourimagetoolbox.h
  modules/SofaConstraint/src/SofaConstraint/ConstraintAnimationLoop.cpp
  modules/SofaConstraint/src/SofaConstraint/PrecomputedConstraintCorrection.inl
  modules/SofaExporter/src/SofaExporter/MeshExporter.cpp
  modules/SofaExporter/src/SofaExporter/VTKExporter.cpp
  modules/SofaGeneralAnimationLoop/src/SofaGeneralAnimationLoop/MechanicalMatrixMapper.inl
  modules/SofaGeneralAnimationLoop/src/SofaGeneralAnimationLoop/MultiTagAnimationLoop.cpp
  modules/SofaGeneralEngine/src/SofaGeneralEngine/TransformPosition.inl
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/TriangularFEMForceFieldOptim.inl
  modules/SofaMiscExtra/src/SofaMiscExtra/MeshTetraStuffing.cpp
  modules/SofaMiscSolver/src/SofaMiscSolver/NewmarkImplicitSolver.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/OglCylinderModel.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/OglShader.cpp
  modules/SofaPreconditioner/src/SofaPreconditioner/PrecomputedWarpPreconditioner.inl
Labels: pr: breaking, pr: status ready, pr: clean, deprecated

#2310 [SofaDenseSolver][SofaBaseLinearSolver] CLEAN macros *_CHECK and *_VERBOSE
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CompressedRowSparseMatrix.h
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CompressedRowSparseMatrix.inl
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/FullMatrix.inl
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/MatrixExpr.h
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/SparseMatrix.h
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/config.h.in
  modules/SofaDenseSolver/src/SofaDenseSolver/NewMatMatrix.h
  modules/SofaDenseSolver/src/SofaDenseSolver/config.h.in
Labels: pr: fast merge, pr: status ready, pr: clean

#2306 [SofaBaseLinearSolver] CRS explicit instantiation
  SofaKernel/modules/SofaBaseLinearSolver/CMakeLists.txt
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CompressedRowSparseMatrix.cpp
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CompressedRowSparseMatrix.h
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CompressedRowSparseMatrix.inl
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/MatrixExpr.h
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/MatrixLinearSolver.cpp
  applications/plugins/SofaPardisoSolver/SparsePARDISOSolver.cpp
  modules/SofaSparseSolver/src/SofaSparseSolver/SparseLDLSolver.inl
Labels: pr: fix, pr: status to review, pr: clean

#2317 [Sofa.DefaultType] Fix declaration of global variables
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/MatrixExporter.cpp
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/MatrixExporter.h
Labels: pr: fix, pr: fast merge, pr: status ready

#2318 [CImgPlugin] Minimize plugin dependencies
  applications/plugins/CImgPlugin/CMakeLists.txt
Labels: pr: fast merge, pr: status ready, pr: clean

#2311 [SofaDenseSolver] Introduce NewMat unit tests
  modules/SofaDenseSolver/CMakeLists.txt
  modules/SofaDenseSolver/SofaDenseSolver_test/CMakeLists.txt
  modules/SofaDenseSolver/SofaDenseSolver_test/NewMatMatrix_test.cpp
  modules/SofaDenseSolver/src/SofaDenseSolver/LULinearSolver.cpp
  modules/SofaDenseSolver/src/SofaDenseSolver/NewMatMatrix.h
Labels: pr: status ready

#2313 [SofaBaseLinearSolver] Remove FullMatrix<bool> and FullVector<bool>
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/FullMatrix.cpp
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/FullMatrix.h
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/FullVector.cpp
  SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/FullVector.h
Labels: pr: status ready, pr: clean

#2307 [CImgPlugin/image] Move file and clean headers
  applications/plugins/CImgPlugin/CMakeLists.txt
  applications/plugins/image/CImgData.h
  applications/plugins/image/CMakeLists.txt
  applications/plugins/image/ImageCoordValuesFromPositions.h
  applications/plugins/image/ImageToRigidMassEngine.h
  applications/plugins/image/ImageTypes.h
  applications/plugins/image/ImageValuesFromPositions.h
  applications/plugins/image/ImageViewer.h
Labels: pr: breaking, pr: status ready, pr: clean

#2299 [SofaBaseVisual] Split VisualModelImpl init method in several methods for more clarity
  SofaKernel/modules/SofaBaseVisual/src/SofaBaseVisual/VisualModelImpl.cpp
  SofaKernel/modules/SofaBaseVisual/src/SofaBaseVisual/VisualModelImpl.h
Labels: pr: status ready, pr: clean, pr: do not squash

#2324 [SofaGeneralEngine] Fix a typo in the PairBoxRoi.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/PairBoxRoi.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#2285 [SofaKernel] change data content copy on write condition
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Data.h
Labels: pr: status ready, refactoring

#2325 [examples] Introduce example of a mapped force field
  examples/Demos/rigidifiedSectionsInBeam.scn
Labels: pr: fast merge, pr: status ready

#2308 [image] Remove useless DiffusionSolver dependency
  applications/plugins/image/CMakeLists.txt
  applications/plugins/image/config.h.in
Labels: pr: status ready, pr: clean

#2328 [examples] Limit GlobalSystemMatrixExporter.scn to 1 iteration
  examples/.scene-tests
Labels: enhancement, pr: fast merge, pr: status ready

#2326 [SofaCore_simutest] Fix getobjects and testcomponentstate unit tests
  SofaKernel/modules/SofaCore/SofaCore_simutest/objectmodel/BaseContext_test.cpp
  SofaKernel/modules/SofaCore/SofaCore_simutest/objectmodel/Base_test.cpp
Labels: pr: fix, pr: fast merge, pr: status to review, pr: clean

#2332 FIX createFromRotationVEctor, the inequality was wrong
  SofaKernel/modules/Sofa.Type/Sofa.Type_test/Quater_test.cpp
  SofaKernel/modules/Sofa.Type/src/sofa/type/Quat.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#2320 [Sofa.Helper_test] "fix" wstring unittest
  SofaKernel/modules/SofaHelper/SofaHelper_test/Utils_test.cpp
Labels: pr: fix, pr: status ready

#2337 [Sofa.LinearAlgebra] Fix installation (fwd.h)
  SofaKernel/modules/Sofa.LinearAlgebra/CMakeLists.txt
Labels: pr: fix, pr: fast merge, pr: status ready

#2322 [SofaGuiQt] Introduce expand/collapse buttons
  modules/SofaGuiQt/CMakeLists.txt
  modules/SofaGuiQt/src/sofa/gui/qt/GUI.ui
  modules/SofaGuiQt/src/sofa/gui/qt/QSofaListView.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/QSofaListView.h
  modules/SofaGuiQt/src/sofa/gui/qt/RealGUI.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/resources/RealGUI.qrc
  modules/SofaGuiQt/src/sofa/gui/qt/resources/icons/collapseAll.svg
  modules/SofaGuiQt/src/sofa/gui/qt/resources/icons/expandAll.svg
Labels: enhancement, pr: status ready

#2319 [SofaGeneralEngine] Cleaning of MeshBoundaryROI
  examples/Components/engine/MeshBoundaryROI.scn
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MeshBoundaryROI.cpp
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MeshBoundaryROI.h
Labels: pr: status ready, pr: clean

#2331 [SofaBaseLinearSolver] Fix mulTranspose for scalar types
  SofaKernel/modules/Sofa.LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrix.h
  SofaKernel/modules/SofaBaseLinearSolver/SofaBaseLinearSolver_test/Matrix_test.cpp
Labels: pr: fix, pr: status ready

#2343 [Sofa.Type] Check return value + add more tests
  SofaKernel/modules/Sofa.Type/Sofa.Type_test/MatTypes_test.cpp
Labels: pr: fast merge, pr: status ready

#2341 [SofaHelper] Add a method getTrace() to BackTrace class.
  SofaKernel/modules/SofaHelper/src/sofa/helper/BackTrace.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/BackTrace.h
Labels: pr: fast merge, pr: status ready, pr: new feature

#2347 [Sofa.LinearAlgebra] Fix assert in CompressedRowSparseMatrix
  SofaKernel/modules/Sofa.LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrix.h
Labels: pr: fix, pr: fast merge, pr: status ready

#2323 [SofaSimpleFem] Remove branches based on type of matrix
  SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.h
  SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
  examples/Benchmark/Performance/MatrixAssembly/run.bat
Labels: pr: status ready, pr: clean

#2327 [SofaScenes] Introduce option to add scenes as a project of the build
  CMakeLists.txt
  examples/CMakeLists.txt
Labels: enhancement, pr: status ready

#2349 [Sofa.Helper] Fix and micro-optimize AdvancedTimer
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/ConstraintSolver.cpp
  SofaKernel/modules/SofaExplicitOdeSolver/src/SofaExplicitOdeSolver/EulerSolver.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/AdvancedTimer.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/ScopedAdvancedTimer.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/ScopedAdvancedTimer.h
  SofaKernel/modules/SofaImplicitOdeSolver/src/SofaImplicitOdeSolver/StaticSolver.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/SolveVisitor.cpp
  modules/SofaConstraint/src/SofaConstraint/ConstraintAnimationLoop.cpp
  modules/SofaGeneralAnimationLoop/src/SofaGeneralAnimationLoop/MultiStepAnimationLoop.cpp
  modules/SofaGeneralAnimationLoop/src/SofaGeneralAnimationLoop/MultiTagAnimationLoop.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/DirectSAPNarrowPhase.cpp
Labels: pr: fix, pr: fast merge, pr: status ready, pr: clean

#2333 [all] Clean unreferenced files
  SofaKernel/modules/Sofa.Type/src/sofa/type/Color.cpp
  SofaKernel/modules/SofaCore/CMakeLists.txt
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/InertiaForce.h
  SofaKernel/modules/SofaCore/src/sofa/core/collision/ParallelPipeline.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/collision/ParallelPipeline.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObjectTasks.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObjectTasks_epilogue.m4
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObjectTasks_macros.m4
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseObjectTasks_prologue.m4
  SofaKernel/modules/SofaHelper/src/sofa/helper/FnDispatcher.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/io/MassSpringLoader.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/io/bvh/BVHChannels.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/io/bvh/BVHJoint.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/io/bvh/BVHLoader.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/io/bvh/BVHMotion.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/io/bvh/BVHOffset.h
  SofaKernel/modules/SofaHelper/src/sofa/helper/logging/LoggerMessageHandler.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/logging/LoggerMessageHandler.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/ChangeListener.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/ChangeListener.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/MechanicalMatrixVisitor.h
  modules/SofaGeneralDeformable/src/SofaGeneralDeformable/MeshSpringForceField.inl
  modules/SofaGeneralEngine/CMakeLists.txt
  modules/SofaGeneralRigid/src/SofaGeneralRigid/LaparoscopicRigidMapping.cpp
  modules/SofaGeneralRigid/src/SofaGeneralRigid/LaparoscopicRigidMapping.h
  modules/SofaGeneralRigid/src/SofaGeneralRigid/LaparoscopicRigidMapping.inl
  modules/SofaNonUniformFem/CMakeLists.txt
  modules/SofaNonUniformFem/src/SofaNonUniformFem/NonUniformHexahedronFEMForceFieldDensity.cpp
  modules/SofaNonUniformFem/src/SofaNonUniformFem/NonUniformHexahedronFEMForceFieldDensity.h
  modules/SofaNonUniformFem/src/SofaNonUniformFem/NonUniformHexahedronFEMForceFieldDensity.inl
Labels: pr: status ready, pr: clean

#2336 [SofaEigen2Solver] Description + timers + support of any BaseMatrix
  SofaKernel/modules/SofaEigen2Solver/src/SofaEigen2Solver/SVDLinearSolver.cpp
Labels: pr: status ready, pr: clean

#2351 [SofaGuiQt] Introduce expand/collapse buttons in profiler
  modules/SofaGuiQt/src/sofa/gui/qt/SofaWindowProfiler.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/SofaWindowProfiler.h
  modules/SofaGuiQt/src/sofa/gui/qt/WindowProfiler.ui
Labels: pr: fast merge, pr: status ready, pr: new feature

#2340 [image] Restore ability to select a subset of instanciations
  applications/plugins/image/CMakeLists.txt
  applications/plugins/image/CollisionToCarvingEngine.cpp
  applications/plugins/image/DepthMapToMeshEngine.cpp
  applications/plugins/image/GenerateImage.cpp
  applications/plugins/image/ImageAccumulator.cpp
  applications/plugins/image/ImageContainer.cpp
  applications/plugins/image/ImageExporter.cpp
  applications/plugins/image/ImageFilter.cpp
  applications/plugins/image/ImageOperation.cpp
  applications/plugins/image/ImageSampler.cpp
  applications/plugins/image/ImageToRigidMassEngine.cpp
  applications/plugins/image/ImageTransform.cpp
  applications/plugins/image/ImageValuesFromPositions.cpp
  applications/plugins/image/ImageViewer.cpp
  applications/plugins/image/MarchingCubesEngine.cpp
  applications/plugins/image/MergeImages.cpp
  applications/plugins/image/TransferFunction.cpp
  applications/plugins/image/VoronoiToMeshEngine.cpp
  applications/plugins/image/config.h.in
  applications/plugins/image/image_gui/HistogramWidget.cpp
  applications/plugins/image/image_gui/ImagePlaneWidget.cpp
  applications/plugins/image/imagetoolbox/contour/contourimagetoolbox.cpp
  applications/plugins/image/imagetoolbox/imagetoolbox.cpp
  applications/plugins/image/imagetoolbox/imagetoolboxwidget.cpp
  applications/plugins/image/imagetoolbox/labelgrid/labelgridimagetoolbox.cpp
  applications/plugins/image/imagetoolbox/zonegenerator/distancezoneimagetoolbox.cpp
  applications/plugins/image/imagetoolbox/zonegenerator/zonegeneratorimagetoolbox.cpp
Labels: pr: fast merge, pr: status ready, pr: new feature

#2342 [Sofa.Helper] Remove usage of boost::filesystem
  SofaKernel/modules/SofaHelper/CMakeLists.txt
  SofaKernel/modules/SofaHelper/Sofa.HelperConfig.cmake.in
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/FileMonitor_linux.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/FileRepository.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/FileSystem.cpp
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/PluginManager.cpp
  applications/plugins/OptiTrackNatNet/CMakeLists.txt
  modules/SofaExporter/SofaExporter_test/MeshExporter_test.cpp
  modules/SofaExporter/SofaExporter_test/OBJExporter_test.cpp
  modules/SofaExporter/SofaExporter_test/STLExporter_test.cpp
Labels: pr: status ready, pr: clean

#2354 [SofaCore] FIX BaseData::getLinkPath()
  SofaKernel/modules/SofaCore/SofaCore_test/CMakeLists.txt
  SofaKernel/modules/SofaCore/SofaCore_test/objectmodel/BaseData_test.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/BaseData.h
  modules/SofaGuiQt/src/sofa/gui/qt/DataWidget.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#2360 [Sofa.Compat] Fix install
  SofaKernel/modules/Sofa.Compat/CMakeLists.txt
Labels: pr: fix, pr: fast merge, pr: status ready

#2361 [examples] Make scene resolution independent + doc
  examples/Components/animationloop/MechanicalMatrixMapper.pyscn
Labels: pr: fast merge, pr: status ready, pr: clean

#2356 [SofaGuiQt] UX: graph is easier to read
  modules/SofaGuiQt/src/sofa/gui/qt/GraphListenerQListView.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/GraphListenerQListView.h
  modules/SofaGuiQt/src/sofa/gui/qt/QSofaListView.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/RealGUI.cpp
Labels: enhancement, pr: status ready

#2359 [SofaBaseTopology] Fix Last element index update in TopologyData
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyData.h
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyData.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologySubsetData.inl
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologySubsetIndices.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/topology/BaseTopologyData.h
Labels: pr: breaking, pr: fix, pr: status ready

#2362 [SofaGeneralAnimationLoop] MechanicalMatrixMapper timers
  examples/Components/animationloop/MechanicalMatrixMapper.pyscn
  modules/SofaGeneralAnimationLoop/src/SofaGeneralAnimationLoop/MechanicalMatrixMapper.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#2352 [Sofa.Helper] PluginManager: check if a plugin is already loaded with a different path
  SofaKernel/modules/SofaHelper/src/sofa/helper/system/PluginManager.cpp
Labels: pr: fix, pr: status ready

#2369 [Sofa.Compat] Fix Matrixexpr alias
  SofaKernel/modules/Sofa.Compat/src/SofaBaseLinearSolver/MatrixExpr.h
Labels: pr: fix, pr: fast merge, pr: status ready
