Repository sofa-framework/sofa, pull requests merged in 2022-05, with the labels that each got.

#2911 [FEM.Elastic] Fix typo on Poisson's ratio
  Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/BeamFEMForceField.h
  Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/BeamFEMForceField.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#2910 [applications] remove shadow variable
  applications/plugins/image/imagetoolbox/depth/depthimagetoolbox.h
Labels: pr: fix, pr: status ready

#2909 [S.C.Engine] Remove previous engine files and fix some cmake.in
  Component/Engine/Analyze/Sofa.Component.Engine.AnalyzeConfig.cmake.in
  Component/Engine/Data/CMakeLists.txt
  Component/Engine/Data/Sofa.Component.Engine.DataConfig.cmake.in
  Component/Engine/Data/src/sofa/component/engine/data/config.h.in
  Component/Engine/Data/src/sofa/component/engine/data/init.cpp
  Component/Engine/Data/src/sofa/component/engine/data/init.h
  Component/Engine/Generate/Sofa.Component.Engine.GenerateConfig.cmake.in
  Component/Engine/Geometry/CMakeLists.txt
  Component/Engine/Geometry/Sofa.Component.Engine.GeometryConfig.cmake.in
  Component/Engine/Geometry/src/sofa/component/engine/geometry/config.h.in
  Component/Engine/Geometry/src/sofa/component/engine/geometry/init.cpp
  Component/Engine/Geometry/src/sofa/component/engine/geometry/init.h
  Component/Engine/Mesh/CMakeLists.txt
  Component/Engine/Mesh/Sofa.Component.Engine.MeshConfig.cmake.in
  Component/Engine/Mesh/src/sofa/component/engine/mesh/config.h.in
  Component/Engine/Mesh/src/sofa/component/engine/mesh/init.cpp
  Component/Engine/Mesh/src/sofa/component/engine/mesh/init.h
  Component/Engine/ROI/CMakeLists.txt
  Component/Engine/ROI/Sofa.Component.Engine.ROIConfig.cmake.in
  Component/Engine/ROI/src/sofa/component/engine/roi/config.h.in
  Component/Engine/ROI/src/sofa/component/engine/roi/init.cpp
  Component/Engine/ROI/src/sofa/component/engine/roi/init.h
  Component/Engine/Rigid/CMakeLists.txt
  Component/Engine/Rigid/Sofa.Component.Engine.RigidConfig.cmake.in
  Component/Engine/Rigid/src/sofa/component/engine/rigid/config.h.in
  Component/Engine/Rigid/src/sofa/component/engine/rigid/init.cpp
  Component/Engine/Rigid/src/sofa/component/engine/rigid/init.h
  SofaKernel/modules/Sofa.Testing/SofaGTestMain/SofaGTestMain.cpp
Labels: pr: fix, pr: fast merge, pr: status to review

#2856 [Sofa.GL.Component] OglModel: Uniformize floating point type
  Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
  Component/Visual/src/sofa/component/visual/VisualModelImpl.h
  SofaKernel/modules/Sofa.GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglModel.cpp
  SofaKernel/modules/Sofa.GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglModel.h
Labels: pr: status ready, pr: clean

#2921 [applications] remove shadow variables
  applications/plugins/image/imagetoolbox/depth/depthimagetoolbox.h
Labels: pr: fast merge, pr: status ready

#2922 [Constraint.Lagrangian.Solver] Convert double to SReal
  Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/ConstraintSolverImpl.h
  Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.cpp
  Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.h
  Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/LCPConstraintSolver.cpp
  Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/LCPConstraintSolver.h
Labels: pr: fast merge, pr: status ready, pr: clean

#2923 [SofaCuda] Forward declaration in wrong namespace
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaCollision.cpp
Labels: pr: fix, pr: fast merge, pr: status to review

#2928 [applications] remove shadow variable
  applications/plugins/image/imagetoolbox/depth/depthimagetoolbox.h
  applications/plugins/image/imagetoolbox/labelgrid/labelgridimagetoolbox.h
Labels: pr: fast merge, pr: status to review, pr: clean

#2908 [SolidMechanics] TetrahedronFEMForceField: adds error message for Poisson's ratio
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#2940 [CMake] FIX out-of-tree build
  SofaKernel/modules/SofaCore/SofaCoreConfig.cmake.in
  SofaKernel/modules/SofaDefaultType/SofaDefaultTypeConfig.cmake.in
  SofaKernel/modules/SofaHelper/SofaHelperConfig.cmake.in
  SofaKernel/modules/SofaSimulationCommon/SofaSimulationCommonConfig.cmake.in
  SofaKernel/modules/SofaSimulationCore/Sofa.SimulationCoreConfig.cmake.in
  SofaKernel/modules/SofaSimulationGraph/SofaSimulationGraphConfig.cmake.in
  modules/SofaGeneralEngine/SofaGeneralEngineConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status ready

#2936 [Image Plugin] remove shadow variables
  applications/plugins/image/imagetoolbox/zonegenerator/zonegeneratorimagetoolbox.h
Labels: pr: fast merge, pr: status ready, pr: clean

#2939 [LinearSolver] Remove explicit template instantiation for floating point types different from SReal
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/MatrixLinearSolver.cpp
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/MatrixLinearSolver.h
Labels: pr: fast merge, pr: status ready, pr: clean

#2947 [SofaRigid][SofaGeneralSimpleFem] Fix typos
  SofaKernel/modules/SofaRigid/src/SofaRigid/initSofaRigid.cpp
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/initSofaGeneralSimpleFem.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#2870 [SofaCore] Inf fix topo subset indices
  Sofa/framework/Core/src/sofa/core/topology/BaseTopologyData.h
  Sofa/framework/Core/src/sofa/core/topology/TopologyData.inl
  Sofa/framework/Core/src/sofa/core/topology/TopologySubsetData.h
  Sofa/framework/Core/src/sofa/core/topology/TopologySubsetData.inl
  Sofa/framework/Core/src/sofa/core/topology/TopologySubsetIndices.cpp
  Sofa/framework/Core/src/sofa/core/topology/TopologySubsetIndices.h
Labels: pr: fix, pr: status ready, pr: do not squash

#2944 [SofaGuiQt] Rename attributes to follow SOFA guidelines.
  modules/SofaGuiQt/src/sofa/gui/qt/RealGUI.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/RealGUI.h
Labels: pr: fast merge, pr: status ready, pr: clean

#2949 [helper.system] Fix crash when module does not provide a version
  Sofa/framework/Helper/src/sofa/helper/system/PluginManager.cpp
Labels: pr: fix, pr: fast merge, pr: status to review

#2896 [SofaNG] Dispatch useful SofaMiscCollision components into S.C.Collision
  Sofa/Component/Collision/Detection/Intersection/CMakeLists.txt
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/TetrahedronDiscreteIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/TetrahedronDiscreteIntersection.h
  Sofa/Component/Collision/Geometry/CMakeLists.txt
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TetrahedronModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TetrahedronModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleModelInRegularGrid.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleModelInRegularGrid.h
  Sofa/Component/Collision/Response/Contact/CMakeLists.txt
  Sofa/Component/Collision/Response/Contact/Sofa.Component.Collision.Response.ContactConfig.cmake.in
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/BarycentricStickContact.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/BarycentricStickContact.h
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/BarycentricStickContact.inl
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/RuleBasedContactManager.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/RuleBasedContactManager.h
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/TetrahedronBarycentricPenalityContact.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/TetrahedronFrictionContact.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/TetrahedronRayContact.cpp
  Sofa/Component/Collision/Response/Mapper/CMakeLists.txt
  Sofa/Component/Collision/Response/Mapper/src/sofa/component/collision/response/mapper/TetrahedronBarycentricContactMapper.cpp
  Sofa/Component/Collision/Response/Mapper/src/sofa/component/collision/response/mapper/TetrahedronBarycentricContactMapper.h
  Sofa/Component/Compat/Sofa.Component.Collision.Detection.Intersection.cmake
  Sofa/Component/Compat/Sofa.Component.Collision.Geometry.cmake
  Sofa/Component/Compat/Sofa.Component.Collision.Response.Contact.cmake
  Sofa/Component/Compat/src/SofaMiscCollision/BarycentricStickContact.h
  Sofa/Component/Compat/src/SofaMiscCollision/BarycentricStickContact.inl
  Sofa/Component/Compat/src/SofaMiscCollision/RuleBasedContactManager.h
  Sofa/Component/Compat/src/SofaMiscCollision/TetrahedronDiscreteIntersection.h
  Sofa/Component/Compat/src/SofaMiscCollision/TetrahedronModel.h
  Sofa/Component/Compat/src/SofaMiscCollision/TriangleModelInRegularGrid.h
  modules/SofaMiscCollision/CMakeLists.txt
  modules/SofaMiscCollision/SofaMiscCollisionConfig.cmake.in
  modules/SofaMiscCollision/src/SofaMiscCollision/initSofaMiscCollision.cpp
Labels: pr: status ready, pr: clean, NG3: new-archi

#2953 [CMake] FIX out-of-tree build (2)
  SofaKernel/modules/SofaDefaultType/SofaDefaultTypeConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status ready

#2875 [SofaMatrix] Eigen can be used to reorder a mesh in order to reduce fill-in
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolverImpl.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLUSolver.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLUSolver.inl
  applications/plugins/SofaMatrix/CMakeLists.txt
  applications/plugins/SofaMatrix/SofaMatrix.md
  applications/plugins/SofaMatrix/SofaMatrixConfig.cmake.in
  applications/plugins/SofaMatrix/examples/.scene-tests
  applications/plugins/SofaMatrix/examples/FillReducingOrdering.scn
  applications/plugins/SofaMatrix/src/SofaMatrix/FillReducingOrdering.h
  applications/plugins/SofaMatrix/src/SofaMatrix/FillReducingOrdering.inl
Labels: enhancement, pr: status ready

#2929 [defaulttype] Prevent division by zero
  Sofa/framework/DefaultType/src/sofa/defaulttype/RigidTypes.h
Labels: pr: status ready, pr: clean

#2958 [CMake] Update all deps to SofaFramework modules
  Sofa/Component/Collision/Testing/CMakeLists.txt
  Sofa/Component/Engine/Generate/Sofa.Component.Engine.GenerateConfig.cmake.in
  Sofa/Component/Engine/Testing/CMakeLists.txt
  Sofa/Component/Mapping/Testing/CMakeLists.txt
  Sofa/Component/SolidMechanics/Testing/CMakeLists.txt
  Sofa/GUI/Component/CMakeLists.txt
  Sofa/framework/Config/cmake/SofaMacrosInstall.cmake
  Sofa/framework/Core/CMakeLists.txt
  Sofa/framework/Helper/test/system/TestPlugin/CMakeLists.txt
  SofaKernel/modules/Sofa.GL/CMakeLists.txt
  SofaKernel/modules/Sofa.GL/Sofa.GLConfig.cmake.in
  SofaKernel/modules/SofaBaseCollision/CMakeLists.txt
  SofaKernel/modules/SofaBaseVisual/CMakeLists.txt
  SofaKernel/modules/SofaBaseVisual/SofaBaseVisualConfig.cmake.in
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/Sofa.SimulationCoreConfig.cmake.in
  applications/plugins/CImgPlugin/CImgPlugin_test/CMakeLists.txt
  applications/plugins/Geomagic/CMakeLists.txt
  applications/plugins/LeapMotion/CMakeLists.txt
  applications/plugins/MultiThreading/test/CMakeLists.txt
  applications/plugins/PSL/CMakeLists.txt
  applications/plugins/SofaEulerianFluid/CMakeLists.txt
  applications/plugins/SofaOpenCL/CMakeLists.txt
  applications/plugins/SofaPardisoSolver/CMakeLists.txt
  applications/plugins/VolumetricRendering/CMakeLists.txt
  applications/plugins/image/CMakeLists.txt
  applications/projects/getDeprecatedComponents/CMakeLists.txt
  applications/projects/xmlconvert-displayflags/CMakeLists.txt
  modules/SofaGraphComponent/CMakeLists.txt
  modules/SofaMiscForceField/CMakeLists.txt
  modules/SofaMiscSolver/CMakeLists.txt
Labels: pr: fast merge, pr: status ready, pr: clean

#2973 [Topology.Dynamic] Remove implicit conversion warnings
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetGeometryAlgorithms.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#2968 Update sofa launcher to use SofaPython3
  tools/sofa-launcher/launcher.py
Labels: pr: status ready

#2926 [LinearSolver] Introduce Eigen solvers
  Sofa/Component/LinearSolver/Direct/CMakeLists.txt
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenDirectSparseSolver.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenDirectSparseSolver.inl
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenSimplicialLDLT.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenSimplicialLDLT.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenSimplicialLLT.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenSimplicialLLT.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenSparseLU.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenSparseLU.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenSparseQR.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenSparseQR.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SimplicialLDLTTraits.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SimplicialLLTTraits.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLUTraits.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseQRTraits.h
  examples/Components/linearsolver/FEMBAR_EigenSimplicialLDLT.scn
  examples/Components/linearsolver/FEMBAR_EigenSimplicialLLT.scn
  examples/Components/linearsolver/FEMBAR_EigenSparseLU.scn
  examples/Components/linearsolver/FEMBAR_EigenSparseQR.scn
Labels: enhancement, pr: status ready, pr: highlighted in next release, pr: dev meeting topic

#2933 [mapping.linear] Fix some warnings
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMappers/BarycentricMapperMeshTopology.inl
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/IdentityMultiMapping.inl
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SkinningMapping.inl
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMultiMapping.inl
Labels: pr: status ready, pr: clean

#2961 [Helper] Deduce plugin name from path based on known extension
  Sofa/framework/Helper/src/sofa/helper/system/PluginManager.cpp
  Sofa/framework/Helper/src/sofa/helper/system/PluginManager.h
Labels: pr: fix, pr: status ready

#2989 [S.C.Mapping] Fix assertion in BarycentricMapper
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMappers/BarycentricMapperMeshTopology.inl
Labels: pr: fix, pr: fast merge, pr: status ready
