Repository sofa-framework/sofa, pull requests merged in 2022-12, with the labels that each got.

#3512 [LinearSolver.Direct] Fix crashing unit tests
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.inl
Labels: pr: fast merge, pr: status ready

#3514 [plugins] SofaCUDA does not require Sofa.GL
  applications/plugins/CMakeLists.txt
Labels: pr: fast merge, pr: status ready

#3508 [FEM.Elastic] Clean draw method
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedralFEMForceFieldAndMass.inl
  examples/Components/forcefield/HexahedralFEMForceFieldAndMass.scn
Labels: pr: status ready

#3529 [LinearSolver.Direct] Segfault in SparseLDLSolver due to empty system matrix
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.inl
Labels: pr: fix, pr: status ready

#3519 [SofaPhysicsAPI] Some small cleaning and add access to VisualModel*
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsAPI.h
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsOutputMesh.cpp
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsOutputMesh_impl.h
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsSimulation.cpp
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsSimulation.h
Labels: pr: status ready, pr: clean, pr: backport todo

#3491 [Simulation] Worker threads are no longer static
  Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultTaskScheduler.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultTaskScheduler.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/WorkerThread.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/WorkerThread.h
Labels: enhancement, pr: status ready

#3542 [Tests] Update required plugins in tests
  Sofa/Component/ODESolver/Backward/tests/EulerImplicitSolverStatic_test.cpp
  Sofa/Component/ODESolver/Backward/tests/scenes/EulerImplicitSpringDynamicTest.xml
  Sofa/Component/ODESolver/Forward/tests/CentralDifferenceExplicitSolverDynamic_test.cpp
  Sofa/Component/ODESolver/Testing/src/sofa/component/odesolver/testing/ODESolverSpringTest.h
Labels: pr: fix, pr: fast merge, pr: status ready

#3543 [Simulation.Core] Add the _API flag to Task::Status
  Sofa/framework/Simulation/Core/src/sofa/simulation/CpuTask.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/Task.h
Labels: pr: fix, pr: fast merge, pr: status ready

#3547 [Core] Missing include in SingleStateAccessor
  Sofa/framework/Core/src/sofa/core/behavior/SingleStateAccessor.h
Labels: pr: fix, pr: fast merge, pr: status ready

#3546 [Modeler] rename shadow variable
  applications/projects/Modeler/lib/GlobalModification.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3539 [SofaPhysicsAPI] Add C bindings to access C++ api
  applications/projects/SofaPhysicsAPI/CMakeLists.txt
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsAPI.h
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsBindings.cpp
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsBindings.h
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsOutputMesh.cpp
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsSimulation.cpp
Labels: pr: status ready, pr: new feature

#3540 [SofaPhysicsAPI] Add methods and C bindings to load SOFA ini file, plugins and messageHandler
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsAPI.h
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsBindings.cpp
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsBindings.h
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsOutputMesh.cpp
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsSimulation.cpp
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsSimulation.h
Labels: pr: status ready, pr: new feature

#3557 [SofaEulerianFluid] Fix: rename shadow variable in Fluid3D
  applications/plugins/SofaEulerianFluid/Fluid3D.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3549 [GUI.Common] Cmake: Fix message when searching for Sofa.GL
  Sofa/GUI/Common/CMakeLists.txt
Labels: pr: fix, pr: fast merge, pr: status ready
