Repository sofa-framework/sofa, pull requests merged in 2022-07, with the labels that each got.

#3067 [SensableEmulation][CMake] Clean Boost dep
  applications/plugins/SensableEmulation/CMakeLists.txt
Labels: pr: fast merge, pr: status ready, pr: clean

#3098 [Sofa.GL] Fix cmake config file for out-of-tree when trying to find glew on Windows
  SofaKernel/modules/Sofa.GL/Sofa.GLConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status to review

#3087 [SofaCUDA] Fail gracefully if no cuda device found
  applications/plugins/SofaCUDA/main.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/mycuda.cu
Labels: pr: fix, pr: fast merge, pr: status ready

#3084 [IO.Mesh] Fix binary loading in case of degenerated triangles
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshSTLLoader.cpp
Labels: pr: fix, pr: status ready

#3102 [CMake] Replace references of SofaNG codename to SOFA
  Sofa/Component/CMakeLists.txt
  Sofa/Component/Collision/CMakeLists.txt
  Sofa/Component/Collision/Detection/CMakeLists.txt
  Sofa/Component/Collision/Response/CMakeLists.txt
  Sofa/Component/Constraint/CMakeLists.txt
  Sofa/Component/Constraint/Lagrangian/CMakeLists.txt
  Sofa/Component/Engine/CMakeLists.txt
  Sofa/Component/IO/CMakeLists.txt
  Sofa/Component/LinearSolver/CMakeLists.txt
  Sofa/Component/Mapping/CMakeLists.txt
  Sofa/Component/ODESolver/CMakeLists.txt
  Sofa/Component/SolidMechanics/CMakeLists.txt
  Sofa/Component/SolidMechanics/FEM/CMakeLists.txt
  Sofa/Component/Topology/CMakeLists.txt
  Sofa/Component/Topology/Container/CMakeLists.txt
  Sofa/framework/Config/CMakeLists.txt
  Sofa/framework/Config/cmake/SofaMacros.cmake
  Sofa/framework/Config/cmake/SofaMacrosConfigure.cmake
  Sofa/framework/Config/cmake/SofaNGMacros.cmake
  SofaKernel/modules/Sofa.GL/CMakeLists.txt
  SofaKernel/modules/Sofa.GL/Component/CMakeLists.txt
Labels: pr: fast merge, pr: status to review, pr: clean

#3080 [Core] Dynamic control of the computation of the bounding box
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/ConstraintAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/FreeMotionAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/MultiStepAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/MultiTagAnimationLoop.cpp
  Sofa/framework/Core/src/sofa/core/behavior/BaseAnimationLoop.cpp
  Sofa/framework/Core/src/sofa/core/behavior/BaseAnimationLoop.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultAnimationLoop.cpp
  examples/Components/constraint/InextensiblePendulum.scn
Labels: pr: fix, pr: fast merge, pr: status ready

#3106 [runSofa] Clean up in case GUI init fails
  applications/projects/runSofa/Main.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3107 [CollisionOBBCapsule] Fix module name
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/config.h.in
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/init.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3101 [GUI.Qt] Redirect Qt messages to the SOFA output stream
  Sofa/GUI/Qt/src/sofa/gui/qt/init.cpp
Labels: enhancement, pr: status ready

#3112 [Sofa.Component] Put the initilization code in init() instead of the entrypoint initExternalPlugin()
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/init.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/init.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/init.cpp
  Sofa/Component/Collision/Detection/src/sofa/component/collision/detection/init.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/init.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/init.cpp
  Sofa/Component/Collision/Response/Mapper/src/sofa/component/collision/response/mapper/init.cpp
  Sofa/Component/Collision/Response/src/sofa/component/collision/response/init.cpp
  Sofa/Component/Collision/src/sofa/component/collision/init.cpp
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/init.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/init.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/init.cpp
  Sofa/Component/Constraint/Lagrangian/src/sofa/component/constraint/lagrangian/init.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/init.cpp
  Sofa/Component/Constraint/src/sofa/component/constraint/init.cpp
  Sofa/Component/Controller/src/sofa/component/controller/init.cpp
  Sofa/Component/Diffusion/src/sofa/component/diffusion/init.cpp
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/init.cpp
  Sofa/Component/Engine/Generate/src/sofa/component/engine/generate/init.cpp
  Sofa/Component/Engine/Select/src/sofa/component/engine/select/init.cpp
  Sofa/Component/Engine/Transform/src/sofa/component/engine/transform/init.cpp
  Sofa/Component/Engine/src/sofa/component/engine/init.cpp
  Sofa/Component/Haptics/src/sofa/component/haptics/init.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/init.cpp
  Sofa/Component/IO/src/sofa/component/io/init.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/init.cpp
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/init.cpp
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/init.cpp
  Sofa/Component/LinearSolver/src/sofa/component/linearsolver/init.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/init.cpp
  Sofa/Component/Mapping/MappedMatrix/src/sofa/component/mapping/mappedmatrix/init.cpp
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/init.cpp
  Sofa/Component/Mapping/src/sofa/component/mapping/init.cpp
  Sofa/Component/Mass/src/sofa/component/mass/init.cpp
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/init.cpp
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/init.cpp
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/init.cpp
  Sofa/Component/ODESolver/src/sofa/component/odesolver/init.cpp
  Sofa/Component/Playback/src/sofa/component/playback/init.cpp
  Sofa/Component/Setting/src/sofa/component/setting/init.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/init.cpp
  Sofa/Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/init.cpp
  Sofa/Component/SolidMechanics/FEM/src/sofa/component/solidmechanics/fem/init.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/init.cpp
  Sofa/Component/SolidMechanics/TensorMass/src/sofa/component/solidmechanics/tensormass/init.cpp
  Sofa/Component/SolidMechanics/src/sofa/component/solidmechanics/init.cpp
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/init.cpp
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/init.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/init.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/init.cpp
  Sofa/Component/Topology/Container/src/sofa/component/topology/container/init.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/init.cpp
  Sofa/Component/Topology/Utility/src/sofa/component/topology/utility/init.cpp
  Sofa/Component/Topology/src/sofa/component/topology/init.cpp
  Sofa/Component/Visual/src/sofa/component/visual/init.cpp
  Sofa/Component/src/sofa/component/init.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3119 [GUI.Qt] Save scene graph lock state persistently
  Sofa/GUI/Qt/src/sofa/gui/qt/GUI.ui
  Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.cpp
Labels: enhancement, pr: fast merge, pr: status ready

#3055 [Constraint.Lagrangian.Correction] Searching for Direct Linear Solver in LinearSolverConstraintCorrection
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.h
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.inl
Labels: enhancement, pr: status ready

#3135 [Lagrangian.Correction] LinearSolverConstraintCorrection: Trivial optimisations for MSVC
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.inl
  Sofa/framework/DefaultType/src/sofa/defaulttype/RigidTypes.h
  Sofa/framework/DefaultType/src/sofa/defaulttype/SolidTypes.h
  Sofa/framework/DefaultType/src/sofa/defaulttype/SolidTypes.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#3146 [examples] Last pass of plugin finder before the release
  examples/Benchmark/Performance/TorusFall.scn
  examples/Components/collision/RuleBasedContactManager.scn
  examples/Components/interactionforcefield/InteractionEllipsoidForceField.scn
  examples/Components/misc/MeshTetraStuffing.scn
  examples/Components/topology/Tetra2TriangleTopologicalMapping_with_TetrahedronModel.scn
  examples/Components/topology/TopologicalModifiers/RemovingTetraProcess_withCollisionModel.scn
  examples/Demos/liverConfiguration.scn
  examples/Tutorials/StepByStep/Dentistry_Haptics/dentalSurgery_Annex.scn
  examples/Tutorials/Topologies/TopologyVolumeDifferentMesh.scn
Labels: pr: fast merge, pr: status ready

#3109 [Helper] Make clearer from where plugins are loaded
  Sofa/GUI/Qt/src/sofa/gui/qt/SofaPluginManager.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/SofaPluginManager.h
  Sofa/framework/Helper/src/sofa/helper/system/PluginManager.cpp
  Sofa/framework/Helper/src/sofa/helper/system/PluginManager.h
  Sofa/framework/Helper/test/system/PluginManager_test.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/RequiredPlugin.cpp
  Sofa/framework/Simulation/Graph/src/sofa/simulation/graph/SimpleApi.cpp
  Sofa/framework/Testing/src/sofa/testing/BaseSimulationTest.cpp
  applications/projects/runSofa/Main.cpp
Labels: pr: status ready

#3140 Remove duplicate entry in clang-format
  .clang-format
Labels: pr: fix, pr: fast merge, pr: status ready

#3144 [SofaCUDA][SofaSphFluid] Remove some getTemplateName deprecated methods
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaVisualModel.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/OglFluidModel.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SpatialGridContainer.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3118 [All] Remove warnings
  Sofa/Component/Engine/Generate/src/sofa/component/engine/generate/GenerateGrid.inl
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/AsyncSparseLDLSolver.inl
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/SSORPreconditioner.cpp
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/WarpPreconditioner.inl
  Sofa/Component/Mass/src/sofa/component/mass/DiagonalMass.inl
  Sofa/Component/Mass/src/sofa/component/mass/MeshMatrixMass.cpp
  Sofa/Component/Mass/src/sofa/component/mass/MeshMatrixMass.inl
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/PlaneForceField.inl
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/SphereForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedronFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedronFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceFieldOptim.inl
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/SpringForceField.inl
  Sofa/GUI/Common/src/sofa/gui/common/ColourPickingVisitor.cpp
  Sofa/framework/Core/src/sofa/core/topology/TopologyData.inl
  Sofa/framework/DefaultType/src/sofa/defaulttype/RigidTypes.h
  Sofa/framework/DefaultType/src/sofa/defaulttype/VecTypes.h
  Sofa/framework/Type/src/sofa/type/DualQuat.h
  Sofa/framework/Type/src/sofa/type/Quat.h
  Sofa/framework/Type/src/sofa/type/Vec.h
Labels: pr: status ready, pr: clean

#3105 [GUI.Qt] Move default format setup before application creation
  Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.h
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qgl/QtGLViewer.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qgl/QtGLViewer.h
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qt/QtViewer.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qt/QtViewer.h
  applications/projects/runSofa/Main.cpp
Labels: pr: fix, pr: status ready

#3158 [GUI.Common] FIX unused variable
  Sofa/GUI/Common/src/sofa/gui/common/ColourPickingVisitor.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3160 [all] Minor changes to use new SOFA-NG includes
  Sofa/Component/Compat/src/SofaBaseMechanics/BarycentricMapping.h
  Sofa/Component/Compat/src/SofaBaseTopology/RegularGridTopology.h
  Sofa/Component/Compat/src/SofaMiscMapping/SubsetMultiMapping.h
  Sofa/Component/Mapping/Testing/src/sofa/component/mapping/testing/Multi2MappingTestCreation.h
  modules/SofaGraphComponent/src/SofaGraphComponent/InteractingBehaviorModel.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3077 [SofaCUDA] Fix CMake to compile plugin without legacy headers option
  applications/plugins/SofaCUDA/CMakeLists.txt
  applications/plugins/SofaCUDA/SofaCUDAConfig.cmake.in
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaExtraMonitor.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLinearForceField.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSpringForceField.cpp
Labels: pr: status ready, pr: clean

#3143 [Topology.Container] Fix save/restoreLastState in draw method were missing
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedConstraint.inl
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/MeshTopology.cpp
Labels: pr: fix, pr: status ready

#3174 [Sofa.Defaulttype] Name() should be compile-time evaluable
  Sofa/framework/DefaultType/src/sofa/defaulttype/RigidTypes.h
  Sofa/framework/DefaultType/src/sofa/defaulttype/SolidTypes.h
  Sofa/framework/DefaultType/src/sofa/defaulttype/VecTypes.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTypes.h
Labels: pr: status to review, pr: clean

#3142 [Core.Topology] Fix info message when Topology given to topologyHandler is not dynamic
  Sofa/framework/Core/src/sofa/core/topology/TopologyData.inl
  Sofa/framework/Core/src/sofa/core/topology/TopologyHandler.cpp
  Sofa/framework/Core/src/sofa/core/topology/TopologyHandler.h
Labels: pr: status ready, pr: clean

#3138 [Sofa.Type] Quat: Optimize rotate() (and inverseRotate())
  Sofa/framework/Type/src/sofa/type/Quat.h
  Sofa/framework/Type/src/sofa/type/Quat.inl
  Sofa/framework/Type/test/Quater_test.cpp
Labels: pr: status ready, pr: clean
