Repository sofa-framework/sofa, pull requests merged in 2022-02, with the labels that each got.

#2645 [SofaHelper] Reduce AdvancedTimer overhead
  SofaKernel/modules/SofaHelper/src/sofa/helper/AdvancedTimer.h
Labels: enhancement, pr: fast merge, pr: status ready

#2634 [SofaCUDA] Fix symbol definition at run time and compilation error
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaConstantForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTriangularFEMForceFieldOptim.h
Labels: pr: fix, pr: fast merge, pr: status ready

#2638 [SofaBaseTopology] Clearer error message
  SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TriangleSetTopologyContainer.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#2641 [SofaDefaultType] Speedup MapMapSparseMatrix
  SofaKernel/modules/SofaCore/src/sofa/core/MultiVecId.h
  SofaKernel/modules/SofaDefaultType/SofaDefaultType_test/MapMapSparseMatrixEigenUtils_test.cpp
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/MapMapSparseMatrix.h
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/MapMapSparseMatrixEigenUtils.h
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/DistanceGrid.h
Labels: enhancement, pr: fast merge, pr: status ready, pr: highlighted in next release

#2659 [SofaGeneralObjectInteraction] Fix dependencies in cmake
  modules/SofaGeneralObjectInteraction/SofaGeneralObjectInteractionConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status to review

#2646 [examples] Speed up the falling cubes
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.h
  applications/plugins/MultiThreading/examples/ParallelBruteForceBroadPhase.scn
  applications/plugins/MultiThreading/src/MultiThreading/ParallelBVHNarrowPhase.cpp
  examples/Benchmark/Performance/benchmark_cubes.pscn
  examples/Benchmark/Performance/benchmark_cubes.scn
Labels: enhancement, pr: fast merge, pr: status to review

#2640 [SofaConstraint] Clean timers in LCPConstraintSolver
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/mechanicalvisitor/MechanicalGetConstraintInfoVisitor.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/mechanicalvisitor/MechanicalGetConstraintInfoVisitor.h
  modules/SofaConstraint/src/SofaConstraint/BilateralInteractionConstraint.inl
  modules/SofaConstraint/src/SofaConstraint/LCPConstraintSolver.cpp
  modules/SofaConstraint/src/SofaConstraint/LCPConstraintSolver.h
  modules/SofaMiscCollision/src/SofaMiscCollision/SolverMerger.cpp
Labels: pr: fast merge, pr: status to review, pr: clean

#2669 [Sofa.LinearAlgebra] Fix SOFA_OPENMP
  SofaKernel/modules/Sofa.LinearAlgebra/CMakeLists.txt
Labels: pr: fix, pr: fast merge, pr: status ready

#2674 [SofaCUDA] harmless cleaning of namespace declaration and header inclusion
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaCollision.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaContactMapper.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaIdentityMapping.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaIdentityMapping.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaIdentityMapping.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSubsetMapping.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSubsetMapping.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSubsetMapping.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#2663 [image] Remove qt4 usage
  applications/plugins/image/image_gui/CMakeLists.txt
Labels: pr: status to review, pr: clean

#2693 [all] Fix missing #include config.h or invalid ordering that disturb the factory's getTarget() to operate properly.
  Component/IO/Mesh/src/sofa/component/io/mesh/GIDMeshLoader.cpp
  Component/IO/Mesh/src/sofa/component/io/mesh/GridMeshCreator.cpp
  Component/IO/Mesh/src/sofa/component/io/mesh/MeshGmshLoader.cpp
  Component/IO/Mesh/src/sofa/component/io/mesh/MeshOffLoader.cpp
  Component/IO/Mesh/src/sofa/component/io/mesh/MeshSTLLoader.cpp
  Component/IO/Mesh/src/sofa/component/io/mesh/MeshTrianLoader.cpp
  Component/IO/Mesh/src/sofa/component/io/mesh/StringMeshCreator.cpp
  Component/SceneUtility/src/sofa/component/sceneutility/APIVersion.cpp
  Component/SceneUtility/src/sofa/component/sceneutility/InfoComponent.cpp
  Component/SceneUtility/src/sofa/component/sceneutility/MakeAliasComponent.cpp
  Component/SceneUtility/src/sofa/component/sceneutility/MakeDataAliasComponent.cpp
  Component/SceneUtility/src/sofa/component/sceneutility/MessageHandlerComponent.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/DistanceGridCollisionModel.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/FFDDistanceGridDiscreteIntersection.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/RigidDistanceGridDiscreteIntersection.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/forcefield/DistanceGridForceField.cpp
  applications/plugins/SofaImplicitField/components/geometry/BottleField.cpp
  applications/plugins/SofaImplicitField/components/geometry/DiscreteGridField.cpp
  applications/plugins/SofaImplicitField/components/geometry/SphericalField.cpp
  applications/plugins/SofaImplicitField/components/geometry/StarShapedField.cpp
  applications/plugins/SofaImplicitField/components/mapping/ImplicitSurfaceMapping.cpp
  applications/plugins/SofaImplicitField/deprecated/InterpolatedImplicitSurface.cpp
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/AffineMovementConstraint.cpp
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/LinearForceField.cpp
  modules/SofaConstraint/src/SofaConstraint/MappingGeometricStiffnessForceField.cpp
  modules/SofaGeneralMeshCollision/src/SofaGeneralMeshCollision/IncrSAP.cpp
  modules/SofaNonUniformFem/src/SofaNonUniformFem/SparseGridRamificationTopology.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/DataDisplay.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/OglCylinderModel.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/OglSceneFrame.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/PointSplatModel.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/SlicedVolumetricModel.cpp
  modules/SofaSparseSolver/src/SofaSparseSolver/SparseLDLSolver.cpp
  modules/SofaSparseSolver/src/SofaSparseSolver/SparseLUSolver.cpp
  modules/SofaValidation/src/SofaValidation/ExtraMonitor.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#2549 [SofaKernel] More generic DefaultVisualManagerLoop
  SofaKernel/modules/SofaCore/src/sofa/core/fwd.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/DefaultVisualManagerLoop.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/DefaultVisualManagerLoop.h
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/Simulation.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/fwd.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/fwd.h
  modules/SofaGuiQt/src/sofa/gui/qt/ModifyObject.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/QDisplayPropertyWidget.cpp
  modules/SofaGuiQt/src/sofa/gui/qt/QSofaListView.h
  modules/SofaGuiQt/src/sofa/gui/qt/QTabulationModifyObject.cpp
  modules/SofaOpenglVisual/src/SofaOpenglVisual/CompositingVisualLoop.cpp
Labels: enhancement, pr: status ready

#2699 [Sofa.Defaulttype] Revert #2641 (changing unordered_map from map in MapMapSparseMatrix)
  SofaKernel/modules/SofaDefaultType/src/sofa/defaulttype/MapMapSparseMatrix.h
Labels: pr: fix, pr: fast merge, pr: status to review

#2647 [SofaSimpleFem][SofaGeneralSimpleFem][SofaMiscFem] Avoid vectors normalization
  SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/HexahedronFEMForceField.inl
  SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
  examples/Components/forcefield/FastTetrahedralCorotationalForceField.scn
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/HexahedralFEMForceField.inl
  modules/SofaGeneralSimpleFem/src/SofaGeneralSimpleFem/TetrahedralCorotationalFEMForceField.inl
  modules/SofaMiscFem/src/SofaMiscFem/FastTetrahedralCorotationalForceField.inl
  modules/SofaMiscFem/src/SofaMiscFem/TriangleFEMForceField.inl
  modules/SofaMiscFem/src/SofaMiscFem/TriangularFEMForceField.inl
Labels: enhancement, pr: status ready

#2652 [Sofa.Config][MSVC] Change SIMD cmake option and flags
  SofaKernel/modules/Sofa.Config/CMakeLists.txt
  SofaKernel/modules/Sofa.Config/cmake/Modules/find_avx.cmake
Labels: enhancement, pr: fix, pr: status ready, pr: clean

#2653 [SofaBaseTopology][SofaDeformable][SofaMiscTopology] Proper topological changes in SpringForceField
  Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetTopologyModifier.cpp
  Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetTopologyModifier.h
  Component/Topology/Utility/src/sofa/component/topology/utility/TopologicalChangeProcessor.cpp
  Component/Topology/Utility/src/sofa/component/topology/utility/TopologicalChangeProcessor.h
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/SpringForceField.h
  SofaKernel/modules/SofaDeformable/src/SofaDeformable/SpringForceField.inl
  examples/Components/topology/TopologicalModifiers/RemovingPointSprings.scn
Labels: pr: fix, pr: status ready

#2708 [SofaCuda] FIX linking error : needed the code of the destructor
  SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/IdentityMapping.h
Labels: pr: fix, pr: fast merge, pr: status ready

#2707 Fixed this error while trying to compile a plugin depending on SofaGuiQt
  modules/SofaMiscForceField/SofaMiscForceFieldConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status ready

#2705 [Component.Compat] Remove wrong mappings in compat layer
  Component/Compat/Sofa.Component.Topology.Mapping.cmake
  Component/Compat/src/SofaTopologyMapping/Mesh2PointTopologicalMapping.h
  Component/Compat/src/SofaTopologyMapping/SimpleTesselatedHexaTopologicalMapping.h
  Component/Compat/src/SofaTopologyMapping/SimpleTesselatedTetraTopologicalMapping.h
Labels: pr: fix, pr: fast merge, pr: status to review, NG3: new-archi

#2650 [Sofa.Component.ODESolver] Gather tests + create Sofa.Component.ODESolver.Testing
  Component/ODESolver/Backward/CMakeLists.txt
  Component/ODESolver/Backward/tests/CMakeLists.txt
  Component/ODESolver/Backward/tests/EulerImplicitSolverDynamic_test.cpp
  Component/ODESolver/Backward/tests/EulerImplicitSolverStatic_test.cpp
  Component/ODESolver/Backward/tests/NewmarkImplicitSolverDynamic_test.cpp
  Component/ODESolver/Backward/tests/SpringSolverDynamic_test.cpp
  Component/ODESolver/Backward/tests/StaticSolver_test.cpp
  Component/ODESolver/Backward/tests/VariationalSymplecticExplicitSolverDynamic_test.cpp
  Component/ODESolver/Backward/tests/VariationalSymplecticImplicitSolverDynamic_test.cpp
  Component/ODESolver/Backward/tests/VariationalSymplecticImplicitSolverNonLinearForceDynamic_test.cpp
  Component/ODESolver/Backward/tests/scenes/EulerImplicitSpringDynamicTest.xml
  Component/ODESolver/CMakeLists.txt
  Component/ODESolver/Forward/CMakeLists.txt
  Component/ODESolver/Forward/tests/CMakeLists.txt
  Component/ODESolver/Forward/tests/CentralDifferenceExplicitSolverDynamic_test.cpp
  Component/ODESolver/Forward/tests/EulerExplicitSolverDynamic_test.cpp
  Component/ODESolver/Forward/tests/RungeKutta2ExplicitSolverDynamic_test.cpp
  Component/ODESolver/Forward/tests/RungeKutta4ExplicitSolverDynamic_test.cpp
  Component/ODESolver/Testing/CMakeLists.txt
  Component/ODESolver/Testing/src/sofa/component/odesolver/testing/MassSpringSystemCreation.h
  Component/ODESolver/Testing/src/sofa/component/odesolver/testing/SunPlanetSystemCreation.h
  Component/ODESolver/Testing/src/sofa/component/odesolver/testing/empty.cpp
  Component/SceneUtility/src/sofa/component/sceneutility/init.cpp
  SofaKernel/modules/Sofa.Testing/CMakeLists.txt
  SofaKernel/modules/SofaExplicitOdeSolver/CMakeLists.txt
  SofaKernel/modules/SofaExplicitOdeSolver/SofaExplicitOdeSolver_test/CMakeLists.txt
  SofaKernel/modules/SofaImplicitOdeSolver/CMakeLists.txt
  SofaKernel/modules/SofaImplicitOdeSolver/SofaImplicitOdeSolver_test/CMakeLists.txt
  SofaKernel/modules/SofaImplicitOdeSolver/SofaImplicitOdeSolver_test/loadPlugins.cpp
  modules/SofaGeneralExplicitOdeSolver/CMakeLists.txt
  modules/SofaGeneralExplicitOdeSolver/SofaGeneralExplicitOdeSolver_test/CMakeLists.txt
  modules/SofaGeneralImplicitOdeSolver/CMakeLists.txt
  modules/SofaGeneralImplicitOdeSolver/SofaGeneralImplicitOdeSolver_test/CMakeLists.txt
  modules/SofaMiscSolver/CMakeLists.txt
  modules/SofaMiscSolver/SofaMiscSolver_test/CMakeLists.txt
Labels: pr: status ready, pr: clean, NG3: new-archi

#2676 [SofaBaseCollision] Fixed invalid vector bug in ContactListener
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/ContactListener.cpp
  SofaKernel/modules/SofaBaseCollision/src/SofaBaseCollision/ContactListener.h
Labels: pr: fix, pr: status ready

#2673 [SofaCUDA] Clean Cuda Collision models
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLineModel.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLineModel.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaPointModel.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaPointModel.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSphereModel.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSphereModel.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTriangleModel.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTriangleModel.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTypes.h
Labels: pr: status ready, pr: clean

#2678 [examples] An example showing a skybox
  CMakeLists.txt
  examples/Demos/skybox.scn
  modules/SofaOpenglVisual/src/SofaOpenglVisual/OglTexture.cpp
  share/shaders/CMakeLists.txt
  share/shaders/skybox.frag
  share/shaders/skybox.vert
  share/textures/skybox_back.jpg
  share/textures/skybox_bottom.jpg
  share/textures/skybox_front.jpg
  share/textures/skybox_left.jpg
  share/textures/skybox_right.jpg
  share/textures/skybox_top.jpg
Labels: pr: status ready

#2722 [image] remove shadow variable
  applications/plugins/image/imagetoolbox/imagetoolboxdata.h
Labels: pr: fast merge, pr: status ready, pr: clean

#2726 [example] Remove misplaced example file
  examples/Components/solver/ShewchukPCGLinearSolver.scn
Labels: pr: fast merge, pr: status ready, pr: clean

#2723 [SofaGeneralEngine] Fix some warnings
  modules/SofaGeneralEngine/src/SofaGeneralEngine/AverageCoord.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/GenerateRigidMass.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/GroupFilterYoungModulus.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/IndexValueMapper.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#2728 [Sofa.Core] Use forward declaration for BoundingBox in Base
  SofaKernel/modules/Sofa.Type/src/sofa/type/fwd.h
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.cpp
  SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.h
Labels: pr: fast merge, pr: status ready, pr: clean

#2725 [SofaSparseSolver] Disable matrix export in SparseLDLSolver
  modules/SofaSparseSolver/src/SofaSparseSolver/AsyncSparseLDLSolver.inl
  modules/SofaSparseSolver/src/SofaSparseSolver/SparseLDLSolver.h
  modules/SofaSparseSolver/src/SofaSparseSolver/SparseLDLSolver.inl
  modules/SofaSparseSolver/src/SofaSparseSolver/config.h.in
Labels: pr: fast merge, pr: status ready, pr: clean
