Repository sofa-framework/sofa, pull requests merged in 2022-04, with the labels that each got.

#2828 [LMConstraint] Remove LMConstraint folder as it is an external plugin
  applications/plugins/LMConstraint/src/LMConstraint/BaseLMConstraint.cpp
  applications/plugins/LMConstraint/src/LMConstraint/BaseLMConstraint.h
  applications/plugins/LMConstraint/src/LMConstraint/DOFBlockerLMConstraint.h
  applications/plugins/LMConstraint/src/LMConstraint/FixedLMConstraint.h
  applications/plugins/LMConstraint/src/LMConstraint/LMConstraintSolver.cpp
  applications/plugins/LMConstraint/src/LMConstraint/LMConstraintSolver.h
Labels: pr: fast merge, pr: status ready, pr: clean

#2831 [Scenes] Fix falling cubes scene
  examples/Benchmark/Performance/benchmark_cubes.pscn
  examples/Benchmark/Performance/benchmark_cubes.scn
Labels: pr: fix, pr: fast merge

#2827 [Scenes] Fix ProjectToPointconstraint scene by using MeshSpringForceField
  examples/Components/constraint/ProjectToPointConstraint.scn
Labels: pr: fix, pr: fast merge, pr: status ready

#2833 [SofaEulerianFluid] Move examples into plugin
  applications/plugins/SofaEulerianFluid/examples/Fluid2D.scn
  applications/plugins/SofaEulerianFluid/examples/Fluid2D.scn.view
  applications/plugins/SofaEulerianFluid/examples/Fluid3D.scn
  applications/plugins/SofaEulerianFluid/examples/Fluid3D.scn.view
Labels: pr: fast merge, pr: status ready, pr: clean

#2835 [Sofa.Core] Remove annoying 'unused' warning in StateAccessor
  SofaKernel/modules/SofaCore/src/sofa/core/behavior/StateAccessor.h
Labels: pr: fix, pr: fast merge, pr: status ready

#2837 [Component.IO.Mesh] Fix substring comparison
  Component/IO/Mesh/src/sofa/component/io/mesh/MeshGmshLoader.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#2830 [SofaBoundaryCondition] Remove duplicated code
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/PartialFixedConstraint.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#2834 [examples] Remove scene which should be in LMConstraint
  examples/Components/constraint/Compare_FixConstraints.scn
Labels: pr: fast merge, pr: status ready, pr: clean

#2798 [Sofa.Component.Diffusion][Sofa.Component.Mass] Fix diffusion
  Component/Diffusion/src/sofa/component/diffusion/TetrahedronDiffusionFEMForceField.h
  Component/Diffusion/src/sofa/component/diffusion/TetrahedronDiffusionFEMForceField.inl
  Component/Mass/src/sofa/component/mass/DiagonalMass.cpp
  Component/Mass/src/sofa/component/mass/DiagonalMass.h
  Component/Mass/src/sofa/component/mass/DiagonalMass.inl
  Component/Mass/src/sofa/component/mass/MeshMatrixMass.cpp
  Component/Mass/src/sofa/component/mass/MeshMatrixMass.h
  Component/Mass/src/sofa/component/mass/MeshMatrixMass.inl
  SofaKernel/modules/SofaSimpleFem/SofaSimpleFem_test/TetrahedronDiffusionFEMForceField_test.cpp
  SofaKernel/modules/SofaSimpleFem/SofaSimpleFem_test/scenes/TetrahedronDiffusionFEMForceField.scn
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaDiagonalMass.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMeshMatrixMass.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMeshMatrixMass.h
  examples/Components/forcefield/TetrahedronDiffusionFEMForceField.scn
Labels: pr: fix, pr: status ready, pr: clean

#2839 [Sofa.LinearAlgebra] Test CRS product compared to Eigen
  SofaKernel/modules/Sofa.LinearAlgebra/Sofa.LinearAlgebra_test/CMakeLists.txt
  SofaKernel/modules/Sofa.LinearAlgebra/Sofa.LinearAlgebra_test/CompressedRowSparseMatrix_test.cpp
Labels: pr: fast merge, pr: status ready

#2841 [Preconditioner] Fix missing find_package() in the cmake.in
  Component/LinearSolver/Preconditioner/Sofa.Component.LinearSolver.PreconditionerConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status to review

#2844 [applications] fix shadow variable
  applications/plugins/SofaAssimp/SceneColladaLoader.cpp
Labels: pr: status ready, pr: clean

#2847 [Scenes] Move PointSplatModel and SpatialGridPointModel scenes into Sph plugin
  applications/plugins/SofaSphFluid/examples/PointSplatModel.scn
  applications/plugins/SofaSphFluid/examples/PointSplatModel.scn.view
  applications/plugins/SofaSphFluid/examples/SpatialGridPointModel.scn
  applications/plugins/SofaSphFluid/examples/SpatialGridPointModel.scn.view
  examples/Components/visualmodel/PointSplatModel.scn.view
Labels: pr: fix, pr: fast merge, pr: status ready

#2845 [FEM.Elastic] Minor changes in TetraXX FEM at init and to be able to access Data
  Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.h
  Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.inl
  Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.inl
  Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.h
  Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#2829 [SofaNewMat] Fix compilation
  applications/plugins/SofaNewmat/src/SofaNewmat/NewMatCGLinearSolver.cpp
  applications/plugins/SofaNewmat/src/SofaNewmat/NewMatCholeskySolver.cpp
  applications/plugins/SofaNewmat/src/SofaNewmat/NewMatMatrix.h
Labels: pr: fix, pr: fast merge, pr: status ready

#2857 [HyperElastic] Introduce example scene for StandardTetrahedralFEMForceField
  examples/Components/forcefield/StandardTetrahedralFEMForceField.scn
Labels: pr: fast merge, pr: status ready

#2863 [SofaCUDA] Fix compilation for SOFA_GPU_CUDA_DOUBLE
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLinearVelocityConstraint.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#2855 [Sofa.GL.Component] Fix tangents/bitangents type set for OpenGL
  Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
  SofaKernel/modules/Sofa.GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglModel.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#2842 [SofaSimpleFEM_test] Add tests on Tetrahedron, CorotationalTetrahedral and FastTetrahedral FEM ForceField
  Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.h
  SofaKernel/modules/SofaSimpleFem/SofaSimpleFem_test/CMakeLists.txt
  SofaKernel/modules/SofaSimpleFem/SofaSimpleFem_test/TetrahedronFEMForceField_test.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#2803 [ArticulatedSystemPlugin] ArticulatedSystemMapping new features
  applications/plugins/ArticulatedSystemPlugin/src/ArticulatedSystemPlugin/ArticulatedHierarchyContainer.inl
  applications/plugins/ArticulatedSystemPlugin/src/ArticulatedSystemPlugin/ArticulatedSystemMapping.h
  applications/plugins/ArticulatedSystemPlugin/src/ArticulatedSystemPlugin/ArticulatedSystemMapping.inl
Labels: enhancement, pr: status ready

#2838 [HyperElastic] Add draw method to StandardTetrahedralFEMForceField
  Component/SolidMechanics/FEM/HyperElastic/CMakeLists.txt
  Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/StandardTetrahedralFEMForceField.inl
  Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/TetrahedronHyperelasticityFEMDrawing.h
  Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/TetrahedronHyperelasticityFEMForceField.inl
Labels: pr: status ready

#2849 [SceneUtility] Move RequiredPlugin to Sofa.SimulationCore
  Component/Compat/Sofa.Component.SceneUtility.cmake
  Component/SceneUtility/CMakeLists.txt
  SofaKernel/modules/Sofa.Compat/CMakeLists.txt
  SofaKernel/modules/Sofa.Compat/src/SofaBaseUtils/RequiredPlugin.h
  SofaKernel/modules/SofaBaseUtils/SofaBaseUtils_test/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/SofaSimulationCore_test/CMakeLists.txt
  SofaKernel/modules/SofaSimulationCore/SofaSimulationCore_test/RequiredPlugin_test.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/RequiredPlugin.cpp
  SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/RequiredPlugin.h
Labels: pr: status ready

#2859 [SofaBoundaryCondition] Remove optimization based on type of matrix
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/TorsionForceField.h
  modules/SofaBoundaryCondition/src/SofaBoundaryCondition/TorsionForceField.inl
Labels: pr: status ready, pr: clean

#2867 [StateContainer] Remove deprecated code for topologicalChanges in MechanicalObject.
  Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.h
  Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#2872 [StateContainer] Fix VecId names for != V_COORD
  Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#2825 [all] Move addInput/addOutput from init() to constructor
  SofaKernel/modules/Sofa.GL/Component/Engine/src/sofa/gl/component/engine/TextureInterpolation.inl
  SofaKernel/modules/SofaCore/SofaCore_test/DataEngine_test.cpp
  applications/plugins/SofaMatrix/src/SofaMatrix/FillReducingOrdering.inl
  modules/SofaGeneralEngine/SofaGeneralEngine_test/TestEngine.cpp
  modules/SofaGeneralEngine/src/SofaGeneralEngine/AverageCoord.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ClusteringEngine.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ComplementaryROI.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/DifferenceEngine.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/DilateEngine.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ExtrudeEdgesAndGenerateQuads.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ExtrudeQuadsAndGenerateHexas.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ExtrudeSurface.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/GenerateCylinder.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/GenerateGrid.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/GenerateRigidMass.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/GenerateSphere.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/GroupFilterYoungModulus.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/IndexValueMapper.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/Indices2ValuesMapper.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/IndicesFromValues.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/JoinPoints.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MapIndices.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MergePoints.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MergeSets.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MeshBarycentricMapperEngine.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MeshBoundaryROI.cpp
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MeshClosingEngine.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MeshROI.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MeshSampler.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MeshSubsetEngine.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/MeshSubsetEngine.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/NearestPointROI.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/NormEngine.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/NormalsFromPoints.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/PairBoxRoi.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/PlaneROI.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/PointsFromIndices.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ProximityROI.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/QuatToRigidEngine.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ROIValueMapper.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/RandomPointDistributionInSurface.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/RigidToQuatEngine.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/SelectConnectedLabelsROI.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/SelectLabelROI.h
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ShapeMatching.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/SmoothMeshEngine.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/SphereROI.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/Spiral.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/SumEngine.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/TransformMatrixEngine.cpp
  modules/SofaGeneralEngine/src/SofaGeneralEngine/TransformPosition.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ValuesFromIndices.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/ValuesFromPositions.inl
  modules/SofaGeneralEngine/src/SofaGeneralEngine/Vertex2Frame.inl
  modules/SofaMiscEngine/src/SofaMiscEngine/ProjectiveTransformEngine.inl
Labels: pr: fix, pr: status ready, pr: clean

#2832 [SceneUtility] MakeDataAliasComponent: Remove alias in destructor
  Component/SceneUtility/src/sofa/component/sceneutility/MakeDataAliasComponent.cpp
  Component/SceneUtility/src/sofa/component/sceneutility/MakeDataAliasComponent.h
Labels: pr: fix, pr: status ready

#2858 [FEM.HyperElastic] Remove optimization based on type of matrix in StandardTetrahedralFEMForceField
  Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/StandardTetrahedralFEMForceField.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#2874 [Metis] Disable compilation warnings
  Component/LinearSolver/Direct/extlibs/metis-5.1.0/CMakeLists.txt
Labels: pr: fast merge, pr: status to review, pr: clean

#2883 [S.C.LinearSolver]fix bug in linearsolvers and preconditioners
  Component/Compat/src/SofaConstraint/BilateralInteractionConstraint.inl
  Component/Compat/src/SofaPreconditioner/BlockJacobiPreconditioner.h
  Component/Compat/src/SofaPreconditioner/PrecomputedWarpPreconditioner.h
  Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/BlockJacobiPreconditioner.h
  Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/JacobiPreconditioner.h
  Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/PrecomputedWarpPreconditioner.inl
  Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/SSORPreconditioner.cpp
  Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/SSORPreconditioner.h
  Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/SSORPreconditioner.inl
Labels: pr: fix, pr: fast merge, pr: status to review

#2861 [FEM.Elastic] Simplify addkToMatrix in TriangularFEMForceFieldOptim
  Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceFieldOptim.h
  Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceFieldOptim.inl
Labels: pr: status ready, pr: clean

#2862 [LinearSolver.Direct] LU solver can be templated to CRSMat3x3
  Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLUSolver.cpp
  Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLUSolver.h
  Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLUSolver.inl
  examples/Components/linearsolver/FEMBAR_SparseLUSolver.scn
Labels: enhancement, pr: status ready

#2864 [SofaCUDA] Convert standard stream to msg_* API
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMechanicalObject.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#2865 [SofaCUDA] Resurrect CudaTetrahedronTLEDForceField
  applications/plugins/SofaCUDA/CMakeLists.txt
  applications/plugins/SofaCUDA/examples/CudaTetrahedronTLEDForceField.scn
  applications/plugins/SofaCUDA/scenes/benchmarks/CudaTetrahedronTLEDForceField_beam10x10x40_gpu.scn
  applications/plugins/SofaCUDA/scenes/benchmarks/CudaTetrahedronTLEDForceField_beam16x16x76_gpu.scn
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedronTLEDForceField.cpp
  examples/Benchmark/Accuracy/cylinder_TLEDTetraSolution.scn
Labels: pr: status ready, pr: clean

#2878 [SofaCUDA] Modernize CMake for CUDA
  applications/plugins/SofaCUDA/CMakeLists.txt
Labels: pr: status ready, pr: clean

#2884 Clean project files
  .clang-format
  .gitignore
Labels: pr: fast merge, pr: status ready, pr: clean

#2868 [SofaSphFluid] Fix ParticleSource topologicalChanges use new callbacks mechanism
  applications/plugins/SofaSphFluid/examples/ParticleSink.scn
  applications/plugins/SofaSphFluid/examples/ParticleSource.scn
  applications/plugins/SofaSphFluid/examples/SPHParticleSink.scn
  applications/plugins/SofaSphFluid/examples/SPHParticleSink_obstacle.scn
  applications/plugins/SofaSphFluid/examples/SPHParticleSource.scn
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSource.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSource.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#2891 [CMake] FIX out-of-tree configure
  Component/Collision/Response/Contact/Sofa.Component.Collision.Response.ContactConfig.cmake.in
  Component/Collision/Response/Mapper/Sofa.Component.Collision.Response.MapperConfig.cmake.in
  SofaKernel/modules/SofaSimpleFem/CMakeLists.txt
  SofaKernel/modules/SofaSimpleFem/SofaSimpleFemConfig.cmake.in
Labels: pr: fast merge, pr: status ready

#2893 [SofaCUDA] Ignore CudaTLED-related scene on the CI
  applications/plugins/SofaCUDA/scenes/.scene-tests
Labels: pr: fix, pr: fast merge, pr: status to review

#2885 [S.C.LinearSolver] Restore specialized functions in SSORPreconditioner
  Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/SSORPreconditioner.cpp
  Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/SSORPreconditioner.inl
Labels: pr: fast merge, pr: status to review, pr: clean

#2877 [FEM.elastic] Some optimisation to make FastTetrahedralCorotational even faster
  Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.h
  Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.inl
Labels: pr: fix, pr: status ready

#2804 [ArticulatedSystemPlugin] New example
  applications/plugins/ArticulatedSystemPlugin/examples/.scene-tests
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/README.md
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/data/RobotBase.stl
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/data/RobotPart1.stl
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/data/RobotPart10.stl
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/data/RobotPart2.stl
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/data/RobotPart3.stl
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/data/RobotPart4.stl
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/data/RobotPart5.stl
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/data/RobotPart6.stl
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/data/RobotPart7.stl
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/data/RobotPart8.stl
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/data/RobotPart9.stl
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/header.py
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/images/robot.png
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/robot.py
  applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/robotGUI.py
Labels: enhancement, pr: status ready

#2898 [examples] FIX benchmark_cubes.scn needs CollisionOBBCapsule
  examples/Benchmark/Performance/benchmark_cubes.scn
Labels: pr: fast merge, pr: status ready

#2869 [SofaCore.Topology] Depreciate method linked to topologyHandler create/destroy function
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologyData.inl
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologyDataHandler.h
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologyDataHandler.inl
  SofaKernel/modules/SofaCore/src/sofa/core/topology/TopologySubsetData.inl
Labels: pr: fix, pr: status ready

#2903 [CollisionOBBCapsule] Fix compat for mappers
  SofaKernel/modules/Sofa.Compat/src/SofaMiscCollision/CapsuleContactMapper.h
  SofaKernel/modules/Sofa.Compat/src/SofaMiscCollision/OBBContactMapper.h
Labels: pr: fix, pr: fast merge, pr: status ready

#2881 [LinearSolver.Direct] Minor clean up in SparseCholeskySolver
  Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseCholeskySolver.h
  Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseCholeskySolver.inl
  SofaKernel/modules/Sofa.Type/src/sofa/type/vector_Real.cpp
Labels: pr: fast merge, pr: status ready, pr: clean
