Repository sofa-framework/sofa, pull requests merged in 2022-08, with the labels that each got.

#3182 [Controller] Fix specialization issue in inline file
  Sofa/Component/Controller/src/sofa/component/controller/MechanicalStateController.cpp
  Sofa/Component/Controller/src/sofa/component/controller/MechanicalStateController.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#3198 [examples] FIX scenes with old CollisionGroupManager component
  applications/collections/deprecated/modules/SofaMiscCollision/examples/MultipleObjectsDynamicCollisionGroups.html
  applications/collections/deprecated/modules/SofaMiscCollision/examples/MultipleObjectsDynamicCollisionGroups.png
  applications/collections/deprecated/modules/SofaMiscCollision/examples/MultipleObjectsDynamicCollisionGroups.scn
  applications/collections/deprecated/modules/SofaMiscCollision/examples/MultipleObjectsDynamicCollisionGroups_init.png
  applications/collections/deprecated/modules/SofaMiscCollision/examples/MultipleObjectsStaticCollisionGroups.html
  applications/collections/deprecated/modules/SofaMiscCollision/examples/MultipleObjectsStaticCollisionGroups.png
  applications/collections/deprecated/modules/SofaMiscCollision/examples/MultipleObjectsStaticCollisionGroups.scn
  applications/collections/deprecated/modules/SofaMiscCollision/examples/MultipleObjectsStaticCollisionGroups_init.png
  examples/Tutorials/Mappings/TutorialMappingDragonBarycentric.scn
Labels: pr: fix, pr: fast merge, pr: status ready

#3197 [CMake] Clean packaging for v22.06
  CMakeLists.txt
  tools/postinstall-fixup/linux-postinstall-fixup.sh
  tools/postinstall-fixup/macos-postinstall-fixup.sh
  tools/postinstall-fixup/windows-postinstall-fixup.sh
Labels: pr: fast merge, pr: status ready, pr: clean

#3163 [all] Remove code disabled in v21.06
  Sofa/framework/Config/src/sofa/config.h.in
  Sofa/framework/Core/src/sofa/core/ExecParams.h
  Sofa/framework/Core/src/sofa/core/ObjectFactory.h
  Sofa/framework/Core/src/sofa/core/loader/MeshLoader.h
  Sofa/framework/Core/src/sofa/core/objectmodel/Base.h
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseClass.h
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseLink.h
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseObject.h
  Sofa/framework/Core/src/sofa/core/objectmodel/DDGNode.h
  Sofa/framework/Core/src/sofa/core/objectmodel/Data.h
  Sofa/framework/Core/src/sofa/core/objectmodel/Link.h
  Sofa/framework/Helper/src/sofa/helper/visual/DrawTool.h
Labels: pr: status ready, deprecated

#3173 [MappedMatrix] MechanicalMatrixMapper: adds option
  Sofa/Component/Mapping/MappedMatrix/src/sofa/component/mapping/mappedmatrix/MechanicalMatrixMapper.h
  Sofa/Component/Mapping/MappedMatrix/src/sofa/component/mapping/mappedmatrix/MechanicalMatrixMapper.inl
Labels: pr: status ready

#3190 [objectmodel] Remove redefinition of initData
  Sofa/framework/Core/src/sofa/core/objectmodel/Base.h
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseClass.h
Labels: pr: status ready, pr: clean

#3214 [Sofa.Config] Rename ide folder for libraries
  Sofa/framework/Config/cmake/SofaMacrosConfigure.cmake
Labels: pr: fix, pr: fast merge, pr: status to review

#3218 [Project] Start v22.12 dev phase
  CHANGELOG.md
  CMakeLists.txt
Labels: pr: fast merge, pr: status ready, pr: clean

#3209 [Plugins] Fix Cmake configuration w/o compat
  applications/plugins/MultiThreading/MultiThreadingConfig.cmake.in
  applications/plugins/SofaCUDA/CMakeLists.txt
  applications/plugins/image/CMakeLists.txt
  applications/plugins/image/imageConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status ready

#3220 [GUI.Qt] Fix MSAA sampling setup
  Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3212 [core] remove shadow variables
  Sofa/framework/Core/src/sofa/core/ObjectFactory.cpp
Labels: pr: status ready, pr: clean

#3164 [SofaCUDA] Make CudaConstantForceField compatible with CudaRigid types
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaConstantForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTypes.h
Labels: enhancement, pr: status ready

#3175 [Spring] RestSpringsForceField: Unify Vec/Rigid implementation
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/RestShapeSpringsForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/RestShapeSpringsForceField.inl
Labels: pr: status ready, refactoring, pr: clean

#3229 [CMake] FIX out-of-tree SofaGui and runSofa locations
  applications/collections/deprecated/SofaGui/CMakeLists.txt
  applications/collections/deprecated/modules/SofaGuiCommon/CMakeLists.txt
  applications/collections/deprecated/modules/SofaGuiQt/CMakeLists.txt
  applications/projects/runSofa/CMakeLists.txt
Labels: pr: fix, pr: fast merge, pr: status ready, pr: backport todo

#3217 [Type] Add NoInit constructor for Quat class
  Sofa/framework/Type/src/sofa/type/Quat.h
  Sofa/framework/Type/src/sofa/type/Quat.inl
Labels: pr: status ready, pr: new feature

#3233 [Geometry] Make global variables constexpr
  Sofa/framework/Geometry/src/sofa/geometry/Pentahedron.h
  Sofa/framework/Geometry/src/sofa/geometry/Point.h
  Sofa/framework/Geometry/src/sofa/geometry/Pyramid.h
  Sofa/framework/Geometry/src/sofa/geometry/Quad.h
  Sofa/framework/Geometry/src/sofa/geometry/Tetrahedron.h
  Sofa/framework/Geometry/src/sofa/geometry/Triangle.h
Labels: pr: fast merge, pr: status ready

#3232 [constraint.lagrangian.solver] fixes verbose GenericConstraintSolver
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.h
Labels: pr: status to review

#3183 [objectmodel] Remove memory leaks
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseClass.h
Labels: pr: breaking, pr: status ready, pr: clean

#3225 [CMake] FIX parent modules library consistency
  Sofa/Component/CMakeLists.txt
  Sofa/Component/Collision/CMakeLists.txt
  Sofa/Component/Collision/Detection/CMakeLists.txt
  Sofa/Component/Collision/Response/CMakeLists.txt
  Sofa/Component/Constraint/CMakeLists.txt
  Sofa/Component/Constraint/Lagrangian/CMakeLists.txt
  Sofa/Component/Engine/CMakeLists.txt
  Sofa/Component/IO/CMakeLists.txt
  Sofa/Component/LinearSolver/CMakeLists.txt
  Sofa/Component/Mapping/CMakeLists.txt
  Sofa/Component/ODESolver/CMakeLists.txt
  Sofa/Component/SolidMechanics/CMakeLists.txt
  Sofa/Component/Topology/CMakeLists.txt
  Sofa/Component/Topology/Container/CMakeLists.txt
  Sofa/GUI/CMakeLists.txt
  Sofa/framework/Config/cmake/SofaMacrosConfigure.cmake
Labels: pr: fix, pr: status ready, pr: backport todo

#3240 [Constraint.Lagrangian] Make class abstract and add key function
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/ConstraintSolverImpl.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/ConstraintSolverImpl.h
Labels: pr: fix, pr: fast merge, pr: status ready

#3226 [LinearSolver.Direct] BTDLinearSolver: Clean debug informations and rename data
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/BTDLinearSolver.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/BTDLinearSolver.inl
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/config.h.in
Labels: pr: status ready, pr: clean

#3243 [Sofa.Core] Remove compilation warning because of un-used argument in BaseClass.h
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseClass.h
Labels: pr: fast merge, pr: status ready

#3236 [All] Remove deprecation warnings while building the deprecated thing itself
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/GenericConstraintCorrection.h
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.h
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/config.h.in
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.h
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/config.h.in
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/ShewchukPCGLinearSolver.h
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/config.h.in
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/PrecomputedWarpPreconditioner.h
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/WarpPreconditioner.h
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/config.h.in
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetTopologyContainer.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/config.h.in
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/EigenMatrixManipulator.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/config.h.in
Labels: pr: fast merge, pr: status ready, pr: clean

#2935 [SofaCUDA] FIX namespaces
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping-3f1-f.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping-f.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaBarycentricMapping-old.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaCollision.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaIdentityMapping.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMultiMapping.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSubsetMapping.cpp
Labels: pr: fix, pr: status ready

#3251 [linearalgebra] Remove deprecated code
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/BTDMatrix.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/BlocFullMatrix.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/BlockDiagonalMatrix.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/BlockVector.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrix.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/config.h.in
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/matrix_bloc_traits.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3250 [Topology] Remove Disabled and Deprecated method <= 22.06
  Sofa/framework/Core/src/sofa/core/topology/BaseMeshTopology.h
  Sofa/framework/Core/src/sofa/core/topology/TopologyData.h
  Sofa/framework/Core/src/sofa/core/topology/TopologyDataHandler.h
  Sofa/framework/Core/src/sofa/core/topology/TopologyHandler.h
  Sofa/framework/Core/src/sofa/core/topology/TopologySubsetIndices.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3059 [Sofa.Core] Linear time getRoot() method in BaseNode and Node
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseNode.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseNode.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/Node.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/Node.h
Labels: pr: status ready

#3176 [Core] Minor cleaning
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseData.h
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseObject.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/Data.h
Labels: pr: status ready, pr: clean
