Repository sofa-framework/sofa, pull requests merged in 2022-09, with the labels that each got.

#3272 [SofaSphFluid] Fix required plugin in scenes
  applications/plugins/SofaSphFluid/examples/OglFluidModel_SPH.scn
  applications/plugins/SofaSphFluid/examples/OglFluidModel_SPHParticles.scn
  applications/plugins/SofaSphFluid/examples/ParticleSink.scn
  applications/plugins/SofaSphFluid/examples/ParticleSource.scn
  applications/plugins/SofaSphFluid/examples/ParticlesRepulsionForceField.scn
  applications/plugins/SofaSphFluid/examples/PointSplatModel.scn
  applications/plugins/SofaSphFluid/examples/SPHDemo.scn
  applications/plugins/SofaSphFluid/examples/SPHFluidForceField.scn
  applications/plugins/SofaSphFluid/examples/SPHFluidForceField_benchmarks.scn
  applications/plugins/SofaSphFluid/examples/SPHFluidSurfaceMapping.scn
  applications/plugins/SofaSphFluid/examples/SPHParticleSink.scn
  applications/plugins/SofaSphFluid/examples/SPHParticleSink_obstacle.scn
  applications/plugins/SofaSphFluid/examples/SPHParticleSource.scn
  applications/plugins/SofaSphFluid/examples/SpatialGridContainer.scn
  applications/plugins/SofaSphFluid/examples/SpatialGridPointModel.scn
Labels: pr: fix, pr: fast merge, pr: status ready

#3260 [DrawToolGL] Fix ill-formed drawLines with multiple colors
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/UnilateralInteractionConstraint.inl
  Sofa/GL/src/sofa/gl/DrawToolGL.cpp
Labels: pr: fix, pr: fast merge, pr: status ready, pr: clean, STC#10

#3264 [Core] Reduce calls to getValue in collisions
  Sofa/framework/Core/src/sofa/core/CollisionModel.cpp
  examples/Components/collision/CollisionGroups.scn
Labels: pr: fast merge, pr: status ready

#3285 [Test] Remove the output of a test from file versioning
  Sofa/framework/Helper/test/io/images/output_bw.png
Labels: pr: fast merge, pr: status ready, pr: clean

#3249 [SolidMechanics.Spring] RestShapeSpringForceField: Fix addKToMatrix
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/RestShapeSpringsForceField.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#3284 [StateContainer] Optimize vector operations
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.inl
  Sofa/framework/DefaultType/CMakeLists.txt
  Sofa/framework/DefaultType/src/sofa/defaulttype/DataTypeOperations.h
Labels: pr: fast merge, pr: status ready

#3283 [Core][Type] Minor warning fixes
  Sofa/framework/Core/src/sofa/core/objectmodel/Context.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/Context.h
  Sofa/framework/Type/src/sofa/type/Frame.h
  Sofa/framework/Type/src/sofa/type/Material.cpp
  Sofa/framework/Type/src/sofa/type/PrimitiveGroup.cpp
  Sofa/framework/Type/src/sofa/type/RGBAColor.cpp
  Sofa/framework/Type/src/sofa/type/RGBAColor.h
  Sofa/framework/Type/src/sofa/type/SVector.cpp
  Sofa/framework/Type/src/sofa/type/vector_Integral.cpp
  Sofa/framework/Type/src/sofa/type/vector_T.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3216 [Topology] Fix initTopology call chains for mesh without topology
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/HexahedronSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/QuadSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TetrahedronSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetTopologyContainer.cpp
  Sofa/Component/Topology/Utility/tests/TopologicalChangeProcessor_test.cpp
Labels: pr: fix, pr: status ready, pr: status postponed

#3276 [SofaCarving] Fix bug in CarvingManager when searching for target collision model
  applications/plugins/SofaCarving/CarvingManager.cpp
Labels: pr: fix, pr: status ready

#3239 [GUI.performer] Add remove elements function for LineCollisionModel
  Sofa/GUI/Component/src/sofa/gui/component/performer/TopologicalChangeManager.cpp
  Sofa/GUI/Component/src/sofa/gui/component/performer/TopologicalChangeManager.h
Labels: pr: status ready, pr: new feature

#3296 [SofaValidation] is a plugin, not a collection
  applications/collections/deprecated/CMakeLists.txt
  applications/collections/deprecated/modules/SofaValidation/CMakeLists.txt
Labels: pr: fast merge, pr: status ready, pr: clean

#3266 [tests] Fix remove SofaComponentAll plugin which doesn't exist anymore
  Sofa/Component/Mass/tests/DiagonalMass_test.cpp
  Sofa/Component/Mass/tests/MeshMatrixMass_test.cpp
  Sofa/Component/Mass/tests/UniformMass_test.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/TriangleFEMForceField_test.cpp
  Sofa/Component/SolidMechanics/Spring/tests/PolynomialRestShapeSpringsForceField_test.cpp
  Sofa/Component/SolidMechanics/Spring/tests/RestShapeSpringsForceField_test.cpp
  Sofa/Component/SolidMechanics/Spring/tests/TriangularBendingSprings_test.cpp
  Sofa/Component/Topology/Utility/tests/TopologyChecker_test.cpp
  Sofa/framework/Core/simutest/objectmodel/BaseContext_test.cpp
  Sofa/framework/Core/simutest/objectmodel/BaseLink_simutest.cpp
  Sofa/framework/Core/simutest/objectmodel/Base_test.cpp
  Sofa/framework/Core/simutest/objectmodel/PathResolver_simutest.cpp
  Sofa/framework/Simulation/Core/simutest/NodeContext_test.cpp
Labels: pr: status ready, pr: clean

#3281 [Sofa.Type] Fix compile-time Mat and Vec
  Sofa/framework/Type/src/sofa/type/Mat.h
  Sofa/framework/Type/src/sofa/type/Vec.h
Labels: pr: fix, pr: fast merge, pr: status ready

#3302 [ExternalBehaviorModel] Without compatibility layer
  applications/plugins/CMakeLists.txt
  applications/plugins/ExternalBehaviorModel/CMakeLists.txt
  applications/plugins/ExternalBehaviorModel/ExternalBehaviorModelConfig.cmake.in
  applications/plugins/ExternalBehaviorModel/FEMGridBehaviorModel.h
  applications/plugins/ExternalBehaviorModel/FEMGridBehaviorModel.inl
Labels: pr: status ready

#3306 Minor warning fixes
  Sofa/Component/Engine/Select/src/sofa/component/engine/select/BoxROI.inl
  Sofa/Component/Engine/Transform/src/sofa/component/engine/transform/MathOp.inl
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/ConstantForceField.inl
  Sofa/framework/Core/src/sofa/core/objectmodel/vectorData.h
  Sofa/framework/Helper/src/sofa/helper/OptionsGroup.cpp
  Sofa/framework/Helper/src/sofa/helper/OptionsGroup.h
Labels: pr: fast merge, pr: status ready

#3297 [Sofa.Core] Add missing #include
  Sofa/framework/Core/simutest/objectmodel/BaseLink_simutest.cpp
  Sofa/framework/Core/simutest/objectmodel/Base_test.cpp
  Sofa/framework/Core/simutest/objectmodel/PathResolver_simutest.cpp
  Sofa/framework/Core/src/sofa/core/State.h
  Sofa/framework/Core/src/sofa/core/behavior/BaseConstraintCorrection.h
  Sofa/framework/Core/src/sofa/core/behavior/MechanicalState.h
  Sofa/framework/Core/src/sofa/core/objectmodel/Base.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/Base.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3221 [Type] Constexpr Quaternion
  Sofa/framework/Type/src/sofa/type/Quat.h
  Sofa/framework/Type/src/sofa/type/Quat.inl
Labels: pr: status ready, pr: clean

#3231 [Constraint.Lagrangian.Correction] LinearSolverCC: use FullVector API if detected
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.h
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.inl
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/LCPConstraintSolver.cpp
Labels: enhancement, pr: status ready, pr: clean

#3322 [Simulation.Core] Fix import of required plugins
  Sofa/framework/Simulation/Core/simutest/NodeContext_test.cpp
Labels: pr: fast merge, pr: status ready

#3300 [Sofa.Core] Move operator<<(Data&) into operator<<(BaseData).
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseData.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseData.h
  Sofa/framework/Core/src/sofa/core/objectmodel/Data.h
Labels: pr: fast merge, pr: status ready

#3321 [Mapping.Linear] Add support for 2d in SubsetMultiMapping
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMultiMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMultiMapping.h
  Sofa/framework/Core/src/sofa/core/MultiMapping.cpp
  Sofa/framework/Core/src/sofa/core/MultiMapping.h
Labels: pr: fast merge, pr: status ready

#3316 [LinearSolver.Direct] Missing call to super init()
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenDirectSparseSolver.inl
Labels: pr: fast merge, pr: status ready

#3326 [Regression] Test Eigen solvers scenes for regression
  examples/RegressionStateScenes.regression-tests
Labels: pr: fast merge, pr: status ready

#3303 [Sofa.Core] Use pragma, single line namespaces and move forward declarations in fwd.h
  Sofa/framework/Core/src/sofa/core/BaseMapping.h
  Sofa/framework/Core/src/sofa/core/BaseState.h
  Sofa/framework/Core/src/sofa/core/fwd.h
  Sofa/framework/Core/src/sofa/core/loader/BaseLoader.h
  Sofa/framework/Core/src/sofa/core/objectmodel/Base.h
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseClass.h
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseLink.h
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseObject.h
  Sofa/framework/Core/src/sofa/core/objectmodel/ComponentState.h
  Sofa/framework/Core/src/sofa/core/objectmodel/Context.h
  Sofa/framework/Core/src/sofa/core/objectmodel/DataCallback.h
Labels: pr: fast merge, pr: status ready

#3270 [Sofa.Core] Add some const qualifier to collision methods & use SReal & nodiscard.
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BVHNarrowPhase.cpp
  Sofa/framework/Core/src/sofa/core/CollisionElement.h
  Sofa/framework/Core/src/sofa/core/CollisionModel.h
Labels: pr: breaking, pr: status ready, pr: clean

#3279 [Sofa.Core] Finally disable deprecated code in BaseData and ExectParam's Aspects.
  Sofa/framework/Config/src/sofa/config.h.in
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseData.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseData.h
  Sofa/framework/Core/src/sofa/core/objectmodel/Data.h
Labels: pr: breaking, pr: status ready

#3282 [Sofa.Defaulttype] Move Rigid{Coord, Deriv, Mass} from RigidTypes into their own headers
  Sofa/framework/DefaultType/CMakeLists.txt
  Sofa/framework/DefaultType/src/sofa/defaulttype/RigidCoord.h
  Sofa/framework/DefaultType/src/sofa/defaulttype/RigidDeriv.h
  Sofa/framework/DefaultType/src/sofa/defaulttype/RigidMass.h
  Sofa/framework/DefaultType/src/sofa/defaulttype/RigidTypes.h
Labels: pr: status ready, pr: clean

#3347 [Type] Deprecate Color.h
  Sofa/framework/Type/src/sofa/type/Color.h
Labels: pr: fast merge, pr: status ready

#3346 [Type] Disable deprecated methods
  Sofa/framework/Config/src/sofa/config.h.in
  Sofa/framework/Type/src/sofa/type/Quat.h
  Sofa/framework/Type/src/sofa/type/Quat.inl
Labels: pr: status ready, pr: clean

#3348 [Topology.Container.Grid] trivial optimization in GridTopology
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/GridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/GridTopology.h
Labels: pr: fast merge, pr: status to review, pr: clean

#3337 [Core.Collision] Fix memory leak in NarrowPhaseDetection and IntersectorFactory
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BVHNarrowPhase.cpp
  Sofa/framework/Core/src/sofa/core/collision/Intersection.h
  Sofa/framework/Core/src/sofa/core/collision/IntersectorFactory.h
  Sofa/framework/Core/src/sofa/core/collision/NarrowPhaseDetection.cpp
  Sofa/framework/Core/src/sofa/core/collision/NarrowPhaseDetection.h
Labels: pr: fix, pr: status ready

#3349 [Type] Remove explicit template instantiation to restore performances
  Sofa/framework/Type/CMakeLists.txt
  Sofa/framework/Type/src/sofa/type/Mat.cpp
  Sofa/framework/Type/src/sofa/type/Mat.h
Labels: pr: fix, pr: fast merge, pr: status ready

#3323 [GUI/runSofa] Cmake: tweaks and fixes
  Sofa/CMakeLists.txt
  Sofa/GUI/CMakeLists.txt
  Sofa/framework/Simulation/Core/CMakeLists.txt
  applications/projects/runSofa/CMakeLists.txt
  applications/projects/runSofa/Main.cpp
Labels: pr: fix, pr: status ready, pr: clean
