Repository sofa-framework/sofa, pull requests merged in 2022-10, with the labels that each got.

#3313 [Config] Option to set the number of MSVC processes
  Sofa/framework/Config/CMakeLists.txt
Labels: pr: status to review

#3245 [Topology_test] Add tests in EdgeSetTopology_test to check topological changes
  Sofa/Component/Topology/Container/Dynamic/tests/EdgeSetTopology_test.cpp
  Sofa/Component/Topology/Testing/src/sofa/component/topology/testing/fake_TopologyScene.h
Labels: pr: status ready, pr: new feature

#3304 [Sofa.Core] Remove the use of Link in MechanicalParams & ConstraintParams
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceFromTargetMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/RigidMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/RigidRigidMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/SquareDistanceMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/SquareMapping.inl
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/TaitSurfacePressureForceField.inl
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/NonUniformHexahedralFEMForceFieldAndMass.inl
  Sofa/framework/Config/src/sofa/config.h.in
  Sofa/framework/Core/src/sofa/core/ConstraintParams.h
  Sofa/framework/Core/src/sofa/core/MechanicalParams.h
  Sofa/framework/Core/src/sofa/core/behavior/ForceField.inl
  Sofa/framework/Core/src/sofa/core/behavior/Mass.inl
  Sofa/framework/Core/src/sofa/core/behavior/MixedInteractionConstraint.inl
  Sofa/framework/Core/src/sofa/core/behavior/MixedInteractionForceField.inl
  Sofa/framework/Core/src/sofa/core/behavior/PairInteractionConstraint.inl
  Sofa/framework/Core/src/sofa/core/behavior/PairInteractionForceField.inl
  Sofa/framework/Core/src/sofa/core/fwd.h
Labels: pr: status ready, refactoring

#3305 Introduce CMake presets
  .gitignore
  CMakePresets.json
Labels: pr: status ready, pr: highlighted in next release, pr: dev meeting topic

#3331 [Topology] Update getLastElementIndex in TopologySubsetIndices
  Sofa/framework/Core/src/sofa/core/topology/BaseTopologyData.h
  Sofa/framework/Core/src/sofa/core/topology/TopologySubsetData.inl
  Sofa/framework/Core/src/sofa/core/topology/TopologySubsetIndices.cpp
  Sofa/framework/Core/src/sofa/core/topology/TopologySubsetIndices.h
Labels: pr: fix, pr: status ready

#3314 [all] Type conversion cleaning (+ user-defined literal)
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/BaseProximityIntersection.cpp
  Sofa/Component/Collision/Response/Mapper/tests/BaryMapper_test.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/AttachConstraint.cpp
  Sofa/Component/Engine/Transform/src/sofa/component/engine/transform/TransformEngine.inl
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/GridMeshCreator.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/StringMeshCreator.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VoxelGridLoader.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMapping.inl
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMultiMapping.inl
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/InteractionEllipsoidForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/QuadBendingFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceFieldOptim.inl
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.cpp
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.inl
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/CubeTopology.cpp
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/SphereQuadTopology.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyContainer.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/CylinderGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/RegularGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridRamificationTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.h
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SphereGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/tests/RegularGridTopology_test.cpp
  Sofa/Component/Visual/src/sofa/component/visual/LineAxis.cpp
  Sofa/Component/Visual/src/sofa/component/visual/RecordedCamera.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/Light.cpp
  Sofa/GL/src/sofa/gl/Axis.cpp
  Sofa/GL/src/sofa/gl/Axis.h
  Sofa/GL/src/sofa/gl/Cylinder.cpp
  Sofa/GL/src/sofa/gl/Cylinder.h
  Sofa/GL/src/sofa/gl/DrawToolGL.cpp
  Sofa/GL/src/sofa/gl/TransformationGL.cpp
  Sofa/GUI/Component/src/sofa/gui/component/AttachBodyButtonSetting.cpp
  Sofa/GUI/Component/src/sofa/gui/component/FixPickedParticleButtonSetting.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qgl/QtGLViewer.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qt/QtViewer.cpp
  Sofa/framework/Config/src/sofa/config.h.in
  Sofa/framework/Core/src/sofa/core/CollisionModel.cpp
  Sofa/framework/Core/src/sofa/core/behavior/BaseMechanicalState.h
  Sofa/framework/Helper/src/sofa/helper/GenerateRigid.h
  Sofa/framework/Helper/src/sofa/helper/MarchingCubeUtility.cpp
  Sofa/framework/Helper/src/sofa/helper/MarchingCubeUtility.h
  Sofa/framework/Helper/src/sofa/helper/TriangleOctree.cpp
  Sofa/framework/Helper/src/sofa/helper/TriangleOctree.h
  Sofa/framework/Simulation/Common/src/sofa/simulation/common/TransformationVisitor.cpp
  Sofa/framework/Type/src/sofa/type/Frame.h
  Sofa/framework/Type/src/sofa/type/Quat.inl
  Sofa/framework/Type/test/MatTypes_test.cpp
Labels: pr: status ready, pr: highlighted in next release

#3332 [SofaCarving] Some cleaning in carvingManager to use link instead of string and clean warning in scenes
  applications/plugins/SofaCarving/CarvingManager.cpp
  applications/plugins/SofaCarving/CarvingManager.h
  applications/plugins/SofaCarving/SofaCarving_test/SofaCarving_test.cpp
  applications/plugins/SofaCarving/examples/CarvingTool.scn
  applications/plugins/SofaCarving/examples/SimpleCarving.scn
  applications/plugins/SofaCarving/examples/SimpleCarving_withPenetration.scn
Labels: pr: status ready, pr: clean

#3269 [SolidMechanics][Spring] Implement applyRemovedEdges for SpringForceField
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/SpringForceField.h
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/SpringForceField.inl
Labels: pr: status ready, pr: new feature

#3371 [Type] equalsZero returns bool, not a real
  Sofa/framework/Type/src/sofa/type/Mat.h
Labels: pr: fast merge, pr: status ready

#3287 [Collision] Cleaning pass on types
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/LocalMinDistance.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshDiscreteIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshMinProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshMinProximityIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshNewProximityIntersection.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/LineModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/LineModel.inl
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/PointModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/PointModel.inl
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/SphereModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/SphereModel.inl
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleModel.inl
Labels: pr: status ready, pr: clean

#3366 [SofaMatrix] Fix crash if init fails in FillReducingOrdering
  applications/plugins/SofaMatrix/examples/FillReducingOrdering.scn
  applications/plugins/SofaMatrix/src/SofaMatrix/FillReducingOrdering.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#3315 [S.C.MechanicalLoad] PlaneForcefield: Fix "potential divide by zero" warnings in msvc
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/PlaneForceField.inl
Labels: pr: status ready, pr: clean

#3344 [git] Add various temporary files to .gitignore
  .gitignore
Labels: pr: status ready

#3365 [CImgPlugin] Replace new keyword with creating unique pointers to properly clean up allocated memory.
  applications/plugins/CImgPlugin/src/CImgPlugin/ImageCImg.cpp
  applications/plugins/CImgPlugin/src/CImgPlugin/ImageCImg.h
Labels: pr: status ready

#3328 [Constraint.Lagrangian] Remove merge option from BilateralInteractionConstraint
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/BilateralInteractionConstraint.h
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/BilateralInteractionConstraint.inl
Labels: pr: breaking, pr: status ready, pr: clean

#3367 [Regression] Add HexahedronFEMForceFieldAndMass to regression tests
  examples/RegressionStateScenes.regression-tests
Labels: pr: fast merge, pr: status ready

#3381 [Config] Change type of CMake message when adding a module
  Sofa/framework/Config/cmake/SofaMacrosConfigure.cmake
Labels: pr: fast merge, pr: status ready

#3382 [CMake] Speed-up Configuration (again)
  Sofa/GUI/Common/CMakeLists.txt
  Sofa/GUI/Component/CMakeLists.txt
  Sofa/framework/Config/cmake/SofaMacrosConfigure.cmake
  Sofa/framework/Simulation/Common/CMakeLists.txt
  Sofa/framework/Simulation/Core/CMakeLists.txt
  Sofa/framework/Testing/CMakeLists.txt
  applications/collections/deprecated/CMakeLists.txt
  applications/plugins/CMakeLists.txt
  applications/projects/SceneChecking/CMakeLists.txt
Labels: enhancement, pr: status ready, pr: clean

#3359 [image] Fix CMake warning from deprecated function
  applications/plugins/image/image_gui/CMakeLists.txt
Labels: pr: fast merge, pr: status ready

#3390 [Lagrangian.Solver] Move MechanicalGetConstraintResolutionVisitor in its own files
  Sofa/Component/Constraint/Lagrangian/Solver/CMakeLists.txt
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.h
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/visitors/MechanicalGetConstraintResolutionVisitor.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/visitors/MechanicalGetConstraintResolutionVisitor.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3400 [SofaDistanceGrid] Set invalid state if cannot load mesh
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/forcefield/DistanceGridForceField.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#3383 [BarycentricMappers] Fix potential division by 0
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMappers/BarycentricMapperMeshTopology.inl
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/RegularGridTopology.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3396 [Lagrangian.Solver] Move GenericConstraintProblem in its own files
  Sofa/Component/Constraint/Lagrangian/Solver/CMakeLists.txt
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintProblem.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintProblem.h
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.h
Labels: pr: fast merge, pr: status ready

#3301 [SofaSimpleGUI] Without compatibility layer
  applications/plugins/SofaSimpleGUI/CMakeLists.txt
  applications/plugins/SofaSimpleGUI/SofaScene.cpp
  applications/plugins/SofaSimpleGUI/SofaSimpleGUIConfig.cmake.in
  applications/plugins/SofaSimpleGUI/SpringInteractor.cpp
  applications/plugins/SofaSimpleGUI/SpringInteractor.h
Labels: pr: status ready

#3345 [Config] Option to enable interprocedural optimization
  Sofa/framework/Config/CMakeLists.txt
Labels: pr: status ready

#3373 [Helper] Deprecate error-prone resize and add emplace_back
  Sofa/Component/Mass/src/sofa/component/mass/DiagonalMass.inl
  Sofa/framework/Helper/src/sofa/helper/accessor/WriteAccessorVector.h
  Sofa/framework/Helper/src/sofa/helper/config.h.in
  Sofa/framework/Helper/test/accessor/WriteAccessor.cpp
Labels: pr: status ready

#3376 [Simulation] Change LoadFromMemory signature to remove unused parameter Size
  Sofa/Component/Collision/Detection/Algorithm/tests/DefaultPipeline_test.cpp
  Sofa/Component/Collision/Detection/Intersection/tests/LocalMinDistance_test.cpp
  Sofa/Component/Collision/Geometry/tests/Sphere_test.cpp
  Sofa/Component/Engine/Select/tests/BoxROI_test.cpp
  Sofa/Component/Engine/Select/tests/MeshROI_test.cpp
  Sofa/Component/Engine/Select/tests/PlaneROI_test.cpp
  Sofa/Component/IO/Mesh/tests/MeshExporter_test.cpp
  Sofa/Component/IO/Mesh/tests/STLExporter_test.cpp
  Sofa/Component/IO/Mesh/tests/VisualModelOBJExporter_test.cpp
  Sofa/Component/Mass/tests/DiagonalMass_test.cpp
  Sofa/Component/Mass/tests/MeshMatrixMass_test.cpp
  Sofa/Component/Mass/tests/UniformMass_test.cpp
  Sofa/Component/MechanicalLoad/tests/ConstantForceField_test.cpp
  Sofa/Component/MechanicalLoad/tests/PlaneForceField_test.cpp
  Sofa/Component/SceneUtility/tests/AddResourceRepository_test.cpp
  Sofa/Component/SceneUtility/tests/MakeAliasComponent_test.cpp
  Sofa/Component/SceneUtility/tests/MakeDataAliasComponent_test.cpp
  Sofa/Component/SceneUtility/tests/MessageHandlerComponent_test.cpp
  Sofa/GL/Component/Rendering2D/tests/OglLabel_test.cpp
  Sofa/GL/Component/Rendering3D/tests/ClipPlane_test.cpp
  Sofa/GL/Component/Shader/tests/LightManager_test.cpp
  Sofa/GL/Component/Shader/tests/Light_test.cpp
  Sofa/framework/Helper/simutest/AdvancedTimer_test.cpp
  Sofa/framework/Simulation/Common/src/sofa/simulation/common/SceneLoaderPHP.cpp
  Sofa/framework/Simulation/Common/src/sofa/simulation/common/SceneLoaderXML.cpp
  Sofa/framework/Simulation/Common/src/sofa/simulation/common/SceneLoaderXML.h
  Sofa/framework/Simulation/Common/src/sofa/simulation/common/xml/XML.cpp
  Sofa/framework/Simulation/Common/src/sofa/simulation/common/xml/XML.h
  Sofa/framework/Simulation/Core/test/RequiredPlugin_test.cpp
  Sofa/framework/Testing/src/sofa/testing/BaseSimulationTest.cpp
  applications/projects/SceneChecking/tests/SceneChecker_test.cpp
Labels: pr: status ready, pr: clean

#3271 [Topology] Improve TopologyHandler registration
  Sofa/Component/Topology/Container/Dynamic/tests/EdgeSetTopology_test.cpp
  Sofa/framework/Core/src/sofa/core/topology/BaseTopology.cpp
  Sofa/framework/Core/src/sofa/core/topology/BaseTopology.h
  Sofa/framework/Core/src/sofa/core/topology/TopologyData.inl
  Sofa/framework/Core/src/sofa/core/topology/TopologyDataHandler.h
  Sofa/framework/Core/src/sofa/core/topology/TopologyDataHandler.inl
  Sofa/framework/Core/src/sofa/core/topology/TopologyHandler.cpp
  Sofa/framework/Core/src/sofa/core/topology/TopologyHandler.h
Labels: pr: breaking, pr: status ready, pr: clean

#3403 [Sofa.Core] TagSet: move method definitions in cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/TagSet.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/TagSet.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3356 [All] Reduce calls to getValue
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshMinProximityIntersection.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/LineModel.inl
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleModel.inl
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMappers/BarycentricMapperSparseGridTopology.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedronFEMForceField.inl
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/MeshTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/GridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/GridTopology.h
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/RegularGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SphereGridTopology.cpp
Labels: pr: status ready, pr: clean

#3406 [Tests] Update tests to new modules
  Sofa/Component/Engine/Select/tests/BoxROI_test.cpp
  Sofa/Component/IO/Mesh/tests/STLExporter_test.cpp
  Sofa/GL/Component/Shader/tests/LightManager_test.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3417 [GL.Rendering3D] OglModel: Minor cleanups
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglModel.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglModel.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3398 [Engine.Analyze] ClusteringEngine: set correct values in load()
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/PrecomputedConstraintCorrection.inl
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/ClusteringEngine.inl
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/PrecomputedWarpPreconditioner.inl
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/PlaneForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangleFEMForceField.inl
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetTopologyContainer.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/VisualManagerPass.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qt/QtViewer.cpp
Labels: pr: fix, pr: fast merge, pr: status ready, pr: clean

#3401 [Sofa.Core] VecId: move definition of VecTypeLabels in its own Translation Unit
  Sofa/framework/Core/CMakeLists.txt
  Sofa/framework/Core/src/sofa/core/VecId.cpp
  Sofa/framework/Core/src/sofa/core/VecId.h
Labels: pr: status ready, pr: clean

#3407 [SofaCarving] Update and add more tests in SofaCarving_test
  applications/plugins/SofaCarving/SofaCarving_test/SofaCarving_test.cpp
Labels: pr: fast merge, pr: status ready, pr: clean, pr: new feature

#3408 [Topology.mapping] Types cleaning in Edge2QuadTopologicalMapping
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Edge2QuadTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Edge2QuadTopologicalMapping.h
  examples/Components/topology/Edge2QuadTopologicalMapping.scn
Labels: pr: fast merge, pr: status ready, pr: clean

#3412 [TriangularFEMForceField] Avoid double write access to the TriangleInfo Data in TriangularFEMForceField
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceField.inl
Labels: pr: breaking, pr: fix, pr: status ready

#3420 [FEM.Elastic] Speedup hexa drawing in force field
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedronFEMForceField.inl
Labels: pr: fast merge, pr: status ready

#3423 [SofaMatrix] Update plugin CMakeLists to avoid strong dependency on Qt
  applications/plugins/SofaMatrix/CMakeLists.txt
  applications/plugins/SofaMatrix/SofaMatrixConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status ready, pr: backport todo

#3427 [SofaNewmat] Fix modules
  applications/plugins/SofaNewmat/CMakeLists.txt
  applications/plugins/SofaNewmat/SofaNewmatConfig.cmake.in
  applications/plugins/SofaNewmat/src/SofaNewmat/LULinearSolver.h
  applications/plugins/SofaNewmat/src/SofaNewmat/NewMatMatrix.h
  applications/plugins/SofaNewmat/src/SofaNewmat/initSofaNewmat.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3432 [Mapping.Linear] Fix assert
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMappers/BarycentricMapperSparseGridTopology.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#3429 [Topology.mapping] Replace all beginEdit by writeAccessor to access Loc2GlobMap
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Edge2QuadTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Hexa2QuadTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Hexa2TetraTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Quad2TriangleTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Tetra2TriangleTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Triangle2EdgeTopologicalMapping.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#3242 [Core] Make some functions non-virtual
  Sofa/Component/Engine/Transform/src/sofa/component/engine/transform/DisplacementMatrixEngine.h
  Sofa/Component/Engine/Transform/src/sofa/component/engine/transform/ProjectiveTransformEngine.h
  Sofa/Component/Engine/Transform/tests/TransformEngine_test.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/Base.h
  Sofa/framework/DefaultType/src/sofa/defaulttype/typeinfo/DataTypeInfo.h
  applications/plugins/MeshSTEPLoader/SingleComponent.h
  applications/plugins/MultiThreading/src/MultiThreading/DataExchange.h
  applications/plugins/MultiThreading/src/MultiThreading/MeanComputation.h
Labels: pr: breaking, pr: status ready

#3393 [Lagrangian.Solver] Deprecate MechanicalAccumulateConstraint
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/FreeMotionAnimationLoop.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.h
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/LCPConstraintSolver.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/LCPConstraintSolver.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/AnimateVisitor.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/config.h.in
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalAccumulateConstraint.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalIntegrationVisitor.cpp
Labels: pr: breaking, pr: status ready, pr: clean

#3447 [test] Fix mutiple component init calls in several tests
  Sofa/Component/MechanicalLoad/tests/QuadPressureForceField_test.cpp
  Sofa/Component/MechanicalLoad/tests/TrianglePressureForceField_test.cpp
  Sofa/Component/MechanicalLoad/tests/scenes/QuadPressureForceField.scn
  Sofa/Component/MechanicalLoad/tests/scenes/TrianglePressureForceField.scn
  Sofa/Component/SolidMechanics/Testing/src/sofa/component/solidmechanics/testing/ForceFieldTestCreation.h
  Sofa/Component/SolidMechanics/simutests/AffinePatch_test.cpp
  Sofa/Component/SolidMechanics/simutests/LinearElasticity_test.cpp
  Sofa/Component/Topology/Testing/src/sofa/component/topology/testing/RegularGridNodeCreation.h
Labels: pr: fix, pr: fast merge, pr: status to review
