Repository sofa-framework/sofa, pull requests merged in 2023-12, with the labels that each got.

#4332 [FEM.Elastic] Reference instead of a copy in TriangularFEMForceField
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceField.inl
  examples/Component/SolidMechanics/FEM/TriangularFEMForceField.scn
Labels: enhancement, pr: fast merge, pr: status ready

#4304 [SolidMechanics.Springs] Cleaning of QuadularBendingSprings
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/QuadularBendingSprings.h
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/QuadularBendingSprings.inl
  examples/Component/SolidMechanics/Spring/QuadularBendingSprings.scn
Labels: enhancement, pr: breaking, pr: status ready, refactoring, STC#16

#4263 [Type] RGBAColor: remove inheritance from type::fixed_array and use std::array to store its components
  Sofa/GL/src/sofa/gl/Axis.cpp
  Sofa/GL/src/sofa/gl/Axis.h
  Sofa/GL/src/sofa/gl/DrawToolGL.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/QRGBAColorPicker.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/QRGBAColorPicker.h
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qgl/QtGLViewer.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qt/QtViewer.cpp
  Sofa/framework/DefaultType/src/sofa/defaulttype/typeinfo/TypeInfo_RGBAColor.h
  Sofa/framework/Type/src/sofa/type/RGBAColor.cpp
  Sofa/framework/Type/src/sofa/type/RGBAColor.h
  Sofa/framework/Type/src/sofa/type/config.h.in
  Sofa/framework/Type/src/sofa/type/fixed_array_algorithms.h
  Sofa/framework/Type/test/Color_test.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mass/CudaUniformMass.inl
Labels: pr: breaking, pr: status to review, pr: clean

#4270 [All] ColorMap uses RGBAColor
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/DataDisplay.cpp
  Sofa/framework/Helper/src/sofa/helper/ColorMap.cpp
  Sofa/framework/Helper/src/sofa/helper/ColorMap.h
  Sofa/framework/Type/src/sofa/type/RGBAColor.cpp
  Sofa/framework/Type/src/sofa/type/RGBAColor.h
Labels: pr: breaking, pr: status to review, pr: clean

#4341 [ODESolver.Backward] Convert double to SReal in NewmarkImplicitSolver
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/NewmarkImplicitSolver.cpp
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/NewmarkImplicitSolver.h
Labels: pr: fast merge, pr: status ready, pr: clean

#4325 [ODESolver] Fix compilation with SOFA_NO_VMULTIOP
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/CentralDifferenceSolver.cpp
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/EulerSolver.cpp
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/RungeKutta2Solver.cpp
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/RungeKutta4Solver.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4330 [image] image_gui to compile with Qt6
  applications/plugins/image/image_gui/CMakeLists.txt
  applications/plugins/image/image_gui/HistogramWidget.h
  applications/plugins/image/image_gui/ImagePlaneWidget.h
  applications/plugins/image/imagetoolbox/imagetoolboxcentralwidget.h
Labels: pr: fix, pr: fast merge, pr: status ready

#4327 [Simulation.Core] Deprecate LocalStorage feature
  Sofa/framework/Simulation/Core/src/sofa/simulation/BaseMechanicalVisitor.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/CactusStackStorage.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/LocalStorage.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/Visitor.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/config.h.in
  Sofa/framework/Simulation/Core/src/sofa/simulation/fwd.h
Labels: pr: status ready, deprecated

#4338 [Haption] Partially fix the plugin
  applications/plugins/Haption/CMakeLists.txt
  applications/plugins/Haption/HaptionDriver.cpp
  applications/plugins/Haption/HaptionDriver.h
  applications/plugins/Haption/README.md
Labels: pr: fix, pr: status ready, pr: backport todo

#4242 [Topology] Check indices out-of-bound in TriangleSetTopologyContainer
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetTopologyContainer.cpp
Labels: pr: fix, pr: status ready, pr: backport todo

#4328 [Simulation.Core] Remove usage of ill-used nodeData in MechanicalGetNonDiagonalMassesCountVisitor and MechanicalVDotVisitor
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/EulerSolver.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalGetNonDiagonalMassesCountVisitor.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalGetNonDiagonalMassesCountVisitor.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalVDotVisitor.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalVDotVisitor.h
Labels: pr: status ready, pr: clean

#4351 [LinearAlgebra] Use class template argument deduction with MatrixExpr
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrixMechanical.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/DiagonalMatrix.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/MatrixExpr.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/SparseMatrix.h
Labels: pr: fast merge, pr: status ready, pr: clean

#4352 [LinearAlgebra] constexpr if statement when possible
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/BaseMatrix.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#4354 [GUI] Fix compilation using QDocBrowser
  Sofa/GUI/Qt/CMakeLists.txt
  Sofa/GUI/Qt/libQGLViewer/QGLViewer/CMakeLists.txt
Labels: pr: fix, pr: fast merge, pr: status ready, pr: backport todo

#4363 [Mapping.Linear] Replace a few beginEdit by accessors
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMappers/BarycentricMapperEdgeSetTopology.inl
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMappers/BarycentricMapperHexahedronSetTopology.inl
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMapping.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#4391 [Type] Remove test of a deprecated constructor
  Sofa/framework/Type/test/Color_test.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#4355 [LinearAlgebra] Factorize template specializations of filterValues in CRS matrix
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrixMechanical.cpp
  Sofa/framework/LinearAlgebra/test/CompressedRowSparseMatrix_test.cpp
Labels: pr: status ready, pr: clean

#4393 [Core] Remove pragma directive in cpp file
  Sofa/framework/Core/src/sofa/core/objectmodel/DeprecatedData.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#4392 [MultiThreading] Fix failing test on ParallelImplementationsRegistry
  applications/plugins/MultiThreading/src/MultiThreading/initMultiThreading.cpp
  applications/plugins/MultiThreading/test/ParallelImplementationsRegistry_test.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4350 [Simulation.Core] BaseMechanicalVisitor: Deprecate rootData
  Sofa/framework/Simulation/Core/src/sofa/simulation/BaseMechanicalVisitor.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/BaseMechanicalVisitor.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/config.h.in
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalGetNonDiagonalMassesCountVisitor.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalVDotVisitor.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalVMultiOpVisitor.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalVNormVisitor.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalVOpVisitor.h
Labels: pr: status ready, pr: clean, deprecated

#4309 [Constraint.Projective] Implement applyConstraint from new matrix assembly API
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/AttachConstraint.h
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/AttachProjectiveConstraint.h
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/AttachProjectiveConstraint.inl
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PartialLinearMovementConstraint.h
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PartialLinearMovementProjectiveConstraint.h
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PartialLinearMovementProjectiveConstraint.inl
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PointProjectiveConstraint.h
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PointProjectiveConstraint.inl
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/ProjectToPointConstraint.h
Labels: pr: status ready, refactoring, STC#16

#4356 [Config] CMake: support interface-type target for install macro
  Sofa/framework/Config/cmake/SofaMacrosInstall.cmake
Labels: enhancement, pr: status ready

#4360 [Core] BaseMapping: link mapConstraints to the "meta-alias" isMechanical
  Sofa/framework/Core/src/sofa/core/BaseMapping.cpp
Labels: enhancement, pr: status ready

#4390 [SofaSimpleGUI] Fix calls to deprecated functions
  applications/plugins/SofaSimpleGUI/SofaGL.cpp
  applications/plugins/SofaSimpleGUI/SofaScene.cpp
  applications/plugins/SofaSimpleGUI/SofaScene.h
Labels: pr: fast merge, pr: status ready, pr: clean, deprecated

#4408 [Helper] Fix Colormap when using HSV to RGB
  Sofa/framework/Helper/src/sofa/helper/ColorMap.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4361 [Topology.Mapping] Edge2QuadTopologicalMapping: use Links for required QuadSet components
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Edge2QuadTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Edge2QuadTopologicalMapping.h
Labels: pr: fix, pr: status ready, pr: clean

#4362 [Topology.Container.Dynamic] GeometryAlgorithms: support generic State
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Utility/src/sofa/component/topology/utility/TopologicalChangeProcessor.cpp
Labels: enhancement, pr: breaking, pr: status ready, pr: clean

#4388 [Topology.Mapping] Edge2QuadTopologicalMapping: use States directly
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Edge2QuadTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Edge2QuadTopologicalMapping.h
  examples/Component/Topology/Mapping/Edge2QuadTopologicalMapping.scn
Labels: enhancement, pr: status ready
