Repository sofa-framework/sofa, pull requests merged in 2023-07, with the labels that each got.

#3982 [tests] Restore commented unit tests
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/TetrahedronFEMForceField_test.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/scenes/TetrahedronFEMForceFieldRegularTetra.scn
Labels: pr: status ready, pr: clean

#3969 [FEM.Elastic] Implement buildStiffnessMatrix in HexahedralFEMForceField
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedralFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedralFEMForceField.inl
Labels: enhancement, pr: status ready

#3978 [Mapping.NonLinear] Fix assert in RigidMapping
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/RigidMapping.inl
Labels: pr: fix, pr: status ready

#3962 [Core.Topology] Restore invalid ids in invalid containers
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/RestShapeSpringsForceField.h
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/RestShapeSpringsForceField.inl
  Sofa/Component/Topology/Utility/src/sofa/component/topology/utility/TopologyChecker.cpp
  Sofa/Component/Topology/Utility/tests/TopologyChecker_test.cpp
  Sofa/framework/Core/src/sofa/core/topology/BaseMeshTopology.cpp
  Sofa/framework/Core/src/sofa/core/topology/BaseMeshTopology.h
  Sofa/framework/Core/test/CMakeLists.txt
  Sofa/framework/Core/test/topology/BaseMeshTopology_test.cpp
  Sofa/framework/Type/src/sofa/type/fixed_array.h
Labels: pr: fix, pr: status ready

#3993 [Spring] Implement buildStiffnessMatrix for AngularSpringForceField
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/AngularSpringForceField.h
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/AngularSpringForceField.inl
Labels: enhancement, pr: status ready

#3972 [MechanicalLoad] Implement buildStiffnessMatrix for PlaneForceField
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/PlaneForceField.h
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/PlaneForceField.inl
  Sofa/framework/Type/src/sofa/type/Mat.h
Labels: enhancement, pr: breaking, pr: status ready

#3997 [MechanicalLoad] Implement buildStiffnessMatrix for ConicalForceField
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/ConicalForceField.h
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/ConicalForceField.inl
Labels: enhancement, pr: status ready

#3931 [all] Use NVI design pattern for drawVisual
  Sofa/Component/Visual/src/sofa/component/visual/LineAxis.cpp
  Sofa/Component/Visual/src/sofa/component/visual/LineAxis.h
  Sofa/Component/Visual/src/sofa/component/visual/TrailRenderer.h
  Sofa/Component/Visual/src/sofa/component/visual/TrailRenderer.inl
  Sofa/Component/Visual/src/sofa/component/visual/Visual3DText.cpp
  Sofa/Component/Visual/src/sofa/component/visual/Visual3DText.h
  Sofa/Component/Visual/src/sofa/component/visual/VisualGrid.cpp
  Sofa/Component/Visual/src/sofa/component/visual/VisualGrid.h
  Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
  Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.h
  Sofa/Component/Visual/src/sofa/component/visual/VisualTransform.cpp
  Sofa/Component/Visual/src/sofa/component/visual/VisualTransform.h
  Sofa/GL/Component/Rendering2D/src/sofa/gl/component/rendering2d/OglColorMap.cpp
  Sofa/GL/Component/Rendering2D/src/sofa/gl/component/rendering2d/OglColorMap.h
  Sofa/GL/Component/Rendering2D/src/sofa/gl/component/rendering2d/OglLabel.cpp
  Sofa/GL/Component/Rendering2D/src/sofa/gl/component/rendering2d/OglLabel.h
  Sofa/GL/Component/Rendering2D/tests/OglLabel_test.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/DataDisplay.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/DataDisplay.h
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglCylinderModel.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglCylinderModel.h
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglModel.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglShader.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglShader.h
  Sofa/framework/Core/src/sofa/core/visual/VisualModel.cpp
  Sofa/framework/Core/src/sofa/core/visual/VisualModel.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/VisualVisitor.cpp
  applications/plugins/SensableEmulation/OmniDriverEmu.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/OglFluidModel.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/OglFluidModel.inl
Labels: enhancement, pr: status ready

#4013 Follow changes from SOFA #3889
  Sofa/Component/Constraint/Projective/tests/FixedPlaneConstraint_test.cpp
  Sofa/Component/MechanicalLoad/tests/SurfacePressureForceField_test.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#4004 [MechanicalLoad] Implement buildStiffnessMatrix in EdgePressureForceField
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/EdgePressureForceField.cpp
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/EdgePressureForceField.h
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/EdgePressureForceField.inl
  examples/Component/MechanicalLoad/EdgePressureForceField.scn
Labels: enhancement, pr: status ready

#4012 [Diffusion] Fix buildStiffnessMatrix in TetrahedronDiffusionFEMForceField
  Sofa/Component/Diffusion/src/sofa/component/diffusion/TetrahedronDiffusionFEMForceField.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#4018 [MechanicalLoad] Implement buildStiffnessMatrix for QuadPressureForceField
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/QuadPressureForceField.h
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/QuadPressureForceField.inl
Labels: enhancement, pr: fast merge, pr: status ready

#3989 [FEM.Linear] FIX & Minor refactor of buildStiffnessMatrix in TriangleFEMForceField
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangleFEMForceField.inl
Labels: pr: fix, pr: status ready, refactoring, pr: backport done

#4007 [MechanicalLoad] Implement buildStiffnessMatrix for OscillatingTorsionPressureForceField
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/OscillatingTorsionPressureForceField.h
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/OscillatingTorsionPressureForceField.inl
Labels: enhancement, pr: status ready

#4020 [LinearAlgebra] CompressedRowSparseMatrix: add virtual destructor
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrixGeneric.h
Labels: pr: fast merge, pr: status to review, pr: clean

#4006 [Spring] Implement buildStiffnessMatrix in FastTriangularBendingSprings
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/FastTriangularBendingSprings.h
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/FastTriangularBendingSprings.inl
Labels: enhancement, pr: status ready

#3994 [AnimationLoop] Change the default constraint solver in FreeMotionAnimationLoop
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/FreeMotionAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/FreeMotionAnimationLoop.h
Labels: enhancement, pr: breaking, pr: status ready

#4015 [SolidMechanics] Implement buildStiffnessMatrix for QuadBendingFEMForceField
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/QuadBendingFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/QuadBendingFEMForceField.inl
Labels: enhancement, pr: status ready

#4000 [SofaCUDA] Implement buildStiffnessMatrix and buildDampingMatrix in TLED
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaHexahedronTLEDForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaHexahedronTLEDForceField.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedronTLEDForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedronTLEDForceField.h
Labels: enhancement, pr: status ready

#3942 [Tests] Properly remove exported files
  Sofa/Component/IO/Mesh/tests/MeshExporter_test.cpp
  Sofa/Component/IO/Mesh/tests/STLExporter_test.cpp
  Sofa/Component/IO/Mesh/tests/VisualModelOBJExporter_test.cpp
  Sofa/framework/Helper/src/sofa/helper/system/FileSystem.cpp
  Sofa/framework/Helper/src/sofa/helper/system/FileSystem.h
  Sofa/framework/Helper/test/system/PluginManager_test.cpp
Labels: pr: status ready, pr: clean, pr: test

#4009 [Spring] Implement buildStiffnessMatrix in PolynomialRestShapeSpringsForceField
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/PolynomialRestShapeSpringsForceField.h
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/PolynomialRestShapeSpringsForceField.inl
  examples/Component/SolidMechanics/Spring/PolynomialRestShapeSpringsForceField.scn
Labels: enhancement, pr: breaking, pr: status ready

#3974 [Collision.Response.Contact] Implement buildStiffnessMatrix in PenalityContactForceField
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/PenalityContactForceField.h
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/PenalityContactForceField.inl
Labels: enhancement, pr: status ready

#4026 [constraint] Update PrecomputedConstraintCorrection logs when loading compliance file
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/PrecomputedConstraintCorrection.inl
Labels: pr: status ready, pr: clean

#4044 [Core] Fix drawing of Objects when hiding Visual Models
  Sofa/framework/Simulation/Core/src/sofa/simulation/VisualVisitor.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3981 [FEM.Elastic] Implement buildStiffnessMatrix for TetrahedralCorotationalFEMForceField
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.inl
Labels: enhancement, pr: status ready

#3882 [plugin] Add fetchable SoftRobots
  applications/plugins/CMakeLists.txt
  applications/plugins/STLIB/ExternalProjectConfig.cmake.in
  applications/plugins/SoftRobots/ExternalProjectConfig.cmake.in
Labels: enhancement, pr: status ready, pr: highlighted in next release

#4025 [GuiQt] Remove some unactivated code
  Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.h
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qt/QtViewer.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qt/QtViewer.h
Labels: pr: status ready, pr: clean

#3983 [FEM.Elastic] Minor refactor of buildStiffnessMatrix in TetrahedronFEMForceField
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
Labels: pr: status ready, refactoring

#3999 [MechanicalLoad] Restore computation of derivatives in DiagonalVelocityDampingForceField
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/DiagonalVelocityDampingForceField.h
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/DiagonalVelocityDampingForceField.inl
  Sofa/framework/Type/src/sofa/type/fixed_array_algorithms.h
Labels: enhancement, pr: status ready

#4055 [examples] Introduce falling beam example
  examples/Demos/fallingBeamLagrangianCollision.scn
  examples/RegressionStateScenes.regression-tests
Labels: pr: fast merge, pr: status to review

#4060 [LinearSolver.Direct] More details in error message
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.inl
Labels: pr: fast merge, pr: status ready

#4062 [FEM.Elastic] Fix typo in error message
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangleFEMUtils.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#4061 [FEM.Elastic] Compute BBox in triangle FEM
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangleFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangleFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceFieldOptim.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceFieldOptim.inl
Labels: pr: fix, pr: fast merge, pr: status to review

#3278 [Sofa.Core] minor refactoring for Data::read() to move into BaseData the reading code
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseData.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseData.h
  Sofa/framework/Core/src/sofa/core/objectmodel/Data.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/Data.h
  Sofa/framework/Core/test/objectmodel/BaseData_test.cpp
Labels: pr: status to review

#4068 Revert "[Sofa.Core] minor refactoring for Data::read() to move into BaseData the reading code"
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseData.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseData.h
  Sofa/framework/Core/src/sofa/core/objectmodel/Data.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/Data.h
  Sofa/framework/Core/test/objectmodel/BaseData_test.cpp
Labels: pr: fast merge, pr: status to review

#4041 [GUI.Qt] Remove unused recorder feature
  Sofa/Component/Setting/src/sofa/component/setting/SofaDefaultPathSetting.cpp
  Sofa/Component/Setting/src/sofa/component/setting/SofaDefaultPathSetting.h
  Sofa/GUI/Common/src/sofa/gui/common/BaseGUI.cpp
  Sofa/GUI/Common/src/sofa/gui/common/BaseGUI.h
  Sofa/GUI/Qt/src/sofa/gui/qt/QSofaRecorder.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/QSofaRecorder.h
  Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.h
Labels: pr: status ready, pr: clean

#4027 [fem] Add option to compute principal stress direction in TriangularFEMForceFieldOptim
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceFieldOptim.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceFieldOptim.inl
Labels: enhancement, pr: status ready

#4005 [MechanicalLoad] Implement buildStiffnessMatrix in EllipsoidForceField
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/EllipsoidForceField.h
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/EllipsoidForceField.inl
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/config.h.in
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mechanicalload/CudaEllipsoidForceField.inl
Labels: enhancement, pr: status ready

#3945 [all] Unify how Animation/Visual loops are handling their "targetNode"
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/ConstraintAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/ConstraintAnimationLoop.h
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/FreeMotionAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/FreeMotionAnimationLoop.h
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/MultiStepAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/MultiStepAnimationLoop.h
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/MultiTagAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/MultiTagAnimationLoop.h
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/CompositingVisualLoop.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/CompositingVisualLoop.h
  Sofa/framework/Core/src/sofa/core/behavior/BaseAnimationLoop.cpp
  Sofa/framework/Core/src/sofa/core/behavior/BaseAnimationLoop.h
  Sofa/framework/Core/src/sofa/core/behavior/MixedInteractionForceField.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/CollisionAnimationLoop.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/CollisionAnimationLoop.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultAnimationLoop.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultAnimationLoop.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultVisualManagerLoop.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultVisualManagerLoop.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/Simulation.cpp
Labels: pr: breaking, pr: status ready, pr: clean

#3986 [LinearSolver.Direct] Parallelization of H A^-1 H^T in SparseLDLSolver
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.inl
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolverImpl.h
  Sofa/framework/LinearAlgebra/CMakeLists.txt
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/DiagonalSystemSolver.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/TriangularSystemSolver.h
  Sofa/framework/LinearAlgebra/test/CMakeLists.txt
  Sofa/framework/LinearAlgebra/test/TriangularSystemSolver_test.cpp
  examples/RegressionStateScenes.regression-tests
Labels: enhancement, pr: status ready, pr: highlighted in next release

#3991 [FEM.Linear] Implement buildStiffnessMatrix and addKToMatrix for TriangularFEMForceField
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceField.inl
Labels: enhancement, pr: status to review
