Repository sofa-framework/sofa, pull requests merged in 2023-02, with the labels that each got.

#3596 [MultiThreading] Parallel springs
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/MeshSpringForceField.h
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/SpringForceField.h
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/SpringForceField.inl
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/StiffSpringForceField.h
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/StiffSpringForceField.inl
  applications/plugins/MultiThreading/CMakeLists.txt
  applications/plugins/MultiThreading/MultiThreadingConfig.cmake.in
  applications/plugins/MultiThreading/examples/ParallelMeshSpringForceField.scn
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/spring/ParallelMeshSpringForceField.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/spring/ParallelMeshSpringForceField.h
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/spring/ParallelMeshSpringForceField.inl
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/spring/ParallelStiffSpringForceField.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/spring/ParallelStiffSpringForceField.h
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/spring/ParallelStiffSpringForceField.inl
Labels: pr: status ready, pr: new feature

#3611 [Cmake] Update warning replacement message for deprecated macro sofa_add_XX
  Sofa/framework/Config/cmake/SofaMacrosConfigure.cmake
Labels: pr: fast merge, pr: status ready, pr: clean

#3612 [SofaPhysicsAPI] Fix compilation by replacing use of SofaGUI by sofa::GUI::common
  applications/projects/SofaPhysicsAPI/CMakeLists.txt
  applications/projects/SofaPhysicsAPI/SofaPhysicsAPIConfig.cmake.in
  applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsSimulation.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3622 [all] Update totalmass to totalMass
  applications/collections/deprecated/modules/SofaValidation/SofaValidation_test/Monitor_test.cpp
  applications/plugins/BulletCollisionDetection/examples/BulletConvexHullDemo.scn
  applications/plugins/BulletCollisionDetection/examples/BulletLMDragon.scn
  applications/plugins/Haption/exemple/haption1.scn
  applications/plugins/Haption/exemple/temp1.scn
  applications/plugins/LeapMotion/examples/Buffoon/obj-buffoon.xml
  applications/plugins/LeapMotion/examples/buffoon.scn
  applications/plugins/PSL/PSL_test/pyfiles/data/test_caduceus.psl
  applications/plugins/PSL/examples/livedemo1/mytemplates.psl
  applications/plugins/PersistentContact/examples/grasping.scn
  applications/plugins/SceneCreator/src/SceneCreator/SceneCreator.cpp
  applications/plugins/Sensable/examples/Dentistry/dentalSurgeryDistanceGrid.scn
  applications/plugins/Sensable/examples/Dentistry/dentalSurgeryDistanceGrid_teeth.scn
  applications/plugins/Sensable/examples/Dentistry/dentalSurgeryLCP.scn
  applications/plugins/Sensable/examples/Dentistry/dentalSurgeryLCPNewOmni.scn
  applications/plugins/Sensable/examples/Old Examples/flexibleRaptor.scn
  applications/plugins/Sensable/examples/Old Examples/omni1.scn
  applications/plugins/Sensable/examples/Old Examples/omni2.scn
  applications/plugins/Sensable/examples/Old Examples/raptor.scn
  applications/plugins/SixenseHydra/Scenes/Hydra_buffon.scn
  applications/plugins/SixenseHydra/Scenes/Hydra_test.scn
  applications/plugins/SixenseHydra/Scenes/OBJs/obj-buffoon.xml
  applications/plugins/SofaCUDA/examples/Bar16-spring-rk4-CudaVec3f.pscn
  applications/plugins/SofaCUDA/examples/CudaTetrahedronTLEDForceField.scn
  applications/plugins/SofaHAPI/examples/SofaHAPI1.scn
  applications/plugins/SofaSimpleGUI/examples/oneTet.scn
  applications/plugins/Xitact/examples/1xitact.scn
  applications/plugins/Xitact/examples/2xitact2.scn
  applications/plugins/image/examples/ImageTransform.scn
  applications/plugins/image/examples/sampler_meshSpring.scn
  examples/Benchmark/Performance/Bar16-fem-implicit-CudaVec3f.pscn
  examples/Benchmark/Performance/Bar16-fem-implicit-Vec3f.pscn
  examples/Benchmark/Performance/Bar16-spring-rk4-CudaVec3f.pscn
  examples/Benchmark/Performance/Bar16-spring-rk4-Vec3f.pscn
  examples/Component/Collision/Response/FrictionContact.scn
  examples/Objects/GridHexaFEM.xml
  examples/Objects/GridSpring.xml
  examples/Objects/GridTetraFEM.xml
  examples/Objects/MeshFEM.xml
  examples/Objects/MeshHexaFEM.xml
  examples/Objects/MeshSpring.xml
  examples/Objects/MeshTetraFEM.xml
  tools/sofa-launcher/example.py
Labels: pr: fix, pr: fast merge, pr: status ready

#3629 [Component.Engine] Replace some explicit instanciations on double with SReal
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/SumEngine.cpp
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/SumEngine.h
  Sofa/Component/Engine/Generate/src/sofa/component/engine/generate/MergeVectors.cpp
  Sofa/Component/Engine/Generate/src/sofa/component/engine/generate/MergeVectors.h
  Sofa/Component/Engine/Generate/src/sofa/component/engine/generate/NormEngine.cpp
  Sofa/Component/Engine/Generate/src/sofa/component/engine/generate/NormEngine.h
  Sofa/Component/Engine/Select/src/sofa/component/engine/select/IndicesFromValues.cpp
  Sofa/Component/Engine/Select/src/sofa/component/engine/select/IndicesFromValues.h
  Sofa/Component/Engine/Transform/src/sofa/component/engine/transform/DifferenceEngine.cpp
  Sofa/Component/Engine/Transform/src/sofa/component/engine/transform/DifferenceEngine.h
Labels: pr: fix, pr: fast merge, pr: status ready

#3620 [Simulation.Graph] SimpleAPI: Remove reference to Node argument in createChild()
  Sofa/framework/Simulation/Graph/src/sofa/simulation/graph/SimpleApi.cpp
  Sofa/framework/Simulation/Graph/src/sofa/simulation/graph/SimpleApi.h
Labels: pr: fix, pr: fast merge, pr: status ready

#3632 [SofaCUDA] Clean removed code and add useful one
  applications/plugins/SofaCUDA/CMakeLists.txt
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaExternalForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaExternalForceField.cu
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaExternalForceField.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaExternalForceField.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#3637 [GUI.Qt, Multithreading] Fix compilation when SReal=float
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qgl/QtGLViewer.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qgl/QtGLViewer.h
  applications/plugins/MultiThreading/src/MultiThreading/component/mapping/linear/BeamLinearMapping_mt.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#3636 [Topology.Container.Grid] RegularGrid: Fix rounding errors with SReal=float
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/RegularGridTopology.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3646 [defaulttype] Fix cuda template instantiation
  Sofa/framework/DefaultType/src/sofa/defaulttype/TemplatesAliases.cpp
Labels: pr: fix, pr: fast merge, pr: status to review

#3626 [Collision.Response.Contact] Implement addKToMatrix for PenalityContactForceField
  Sofa/Component/Collision/Response/Contact/CMakeLists.txt
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/PenalityContactForceField.h
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/PenalityContactForceField.inl
  Sofa/Component/Collision/Response/Contact/tests/CMakeLists.txt
  Sofa/Component/Collision/Response/Contact/tests/PenalityContactForceField_test.cpp
Labels: enhancement, pr: status ready

#3627 [Sofa] Remove warnings
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/FreeMotionTask.h
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/IncrSAP.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/CubeModel.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/BilateralInteractionConstraint.h
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/config.h.in
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/ProjectToLineConstraint.inl
  Sofa/Component/Engine/Generate/src/sofa/component/engine/generate/MeshBarycentricMapperEngine.inl
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshGmshLoader.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/SphereLoader.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/BTDLinearSolver.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMappingRigid.inl
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/PlaneForceField.inl
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/QuadPressureForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangleFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/QuadularBendingSprings.inl
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/SpringForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/SpringForceField.h
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.inl
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridMultipleTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridRamificationTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.cpp
  Sofa/framework/Core/src/sofa/core/visual/Data[DisplayFlags].cpp
  Sofa/framework/DefaultType/src/sofa/defaulttype/DataTypeOperations.h
  Sofa/framework/Helper/src/sofa/helper/io/MeshGmsh.cpp
  Sofa/framework/Helper/src/sofa/helper/io/MeshTopologyLoader.cpp
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/BlockFullMatrix.inl
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrix.h
  Sofa/framework/Simulation/Common/src/sofa/simulation/common/xml/AttributeElement.cpp
  Sofa/framework/Simulation/Common/src/sofa/simulation/common/xml/ObjectElement.cpp
Labels: pr: status ready, pr: clean

#3667 [MultiThreading] Remove obsolete documentation
  applications/plugins/MultiThreading/docs/MultiThreading.pdf
  applications/plugins/MultiThreading/docs/MultiThreading.tex
  applications/plugins/MultiThreading/docs/images/MultiThreading.docx
  applications/plugins/MultiThreading/docs/images/TaskSchedulerDesign.docx
  applications/plugins/MultiThreading/docs/images/TaskSchedulerDesign.jpg
  applications/plugins/MultiThreading/docs/images/multithreading.jpg
Labels: pr: fast merge, pr: status ready, pr: clean

#3658 [Collision.Geometry] Fix transparency while displaying the Bounding Collision Cubemodel
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/CubeModel.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3650 [SofaCUDA] No longer use deprecated texture references in TetraTLED
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedronTLEDForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedronTLEDForceField.cu
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedronTLEDForceField.h
Labels: pr: status ready

#3660 [SofaCUDA] Reorganize following SOFA structure (3/n)
  applications/plugins/SofaCUDA/CMakeLists.txt
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaDiagonalMass.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaDiagonalMass.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaHexahedronFEMForceField.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaHexahedronFEMForceField.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMeshMatrixMass.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMeshMatrixMass.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaStandardTetrahedralFEMForceField.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaStandardTetrahedralFEMForceField.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedralTensorMassForceField.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedralTensorMassForceField.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedronFEMForceField.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTetrahedronFEMForceField.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTriangularFEMForceFieldOptim.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTriangularFEMForceFieldOptim.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaUniformMass.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaUniformMass.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/linear/CudaBarycentricMappingRigid.h
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaHexahedronFEMForceField.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaHexahedronFEMForceField.cu
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaHexahedronFEMForceField.h
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaHexahedronFEMForceField.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTetrahedronFEMForceField.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTetrahedronFEMForceField.cu
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTetrahedronFEMForceField.h
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTetrahedronFEMForceField.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTriangularFEMForceFieldOptim.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTriangularFEMForceFieldOptim.cu
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTriangularFEMForceFieldOptim.h
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTriangularFEMForceFieldOptim.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/hyperelastic/CudaStandardTetrahedralFEMForceField.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/hyperelastic/CudaStandardTetrahedralFEMForceField.cu
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/hyperelastic/CudaStandardTetrahedralFEMForceField.h
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/hyperelastic/CudaStandardTetrahedralFEMForceField.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/tensormass/CudaTetrahedralTensorMassForceField.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/tensormass/CudaTetrahedralTensorMassForceField.cu
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/tensormass/CudaTetrahedralTensorMassForceField.h
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/tensormass/CudaTetrahedralTensorMassForceField.inl
Labels: pr: status ready, refactoring

#3672 [Helper] ArgumentParser: Fix map insertion when parsing more than once
  Sofa/GUI/Common/src/sofa/gui/common/ArgumentParser.cpp
Labels: pr: fix, pr: fast merge, pr: status to review

#3670 [MechanicalLoad] Fix ConstantForceField when no force given
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/ConstantForceField.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#3674 [CI, Scenes] Restore custom parameters for the scene-tests
  examples/.scene-tests
Labels: pr: fix, pr: fast merge, pr: status to review

#3675 [Defaulttype] Add generic precision aliases for Mat templates
  Sofa/framework/DefaultType/src/sofa/defaulttype/TemplatesAliases.cpp
Labels: pr: fix, pr: fast merge, pr: status to review

#3676 [Multithreading] Fix AnimationLoopParallelScheduler
  applications/plugins/MultiThreading/CMakeLists.txt
  applications/plugins/MultiThreading/examples/TriangularForceFieldComparison.scn
  applications/plugins/MultiThreading/examples/livers.scn
  applications/plugins/MultiThreading/examples/liversMeanPositions.scn
  applications/plugins/MultiThreading/src/MultiThreading/component/animationloop/AnimationLoopParallelScheduler.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/animationloop/AnimationLoopParallelScheduler.h
  applications/plugins/MultiThreading/src/MultiThreading/component/animationloop/StepTask.h
  applications/plugins/MultiThreading/src/MultiThreading/config.h.in
Labels: pr: fast merge, pr: status to review, pr: clean

#3686 [MultiThreading] Empty string instead of null pointer in DataExchange
  applications/plugins/MultiThreading/src/MultiThreading/DataExchange.h
Labels: pr: fix, pr: fast merge, pr: status ready

#3668 [MultiThreading] Implement addDForce in ParallelStiffSpringForceField
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/StiffSpringForceField.h
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/StiffSpringForceField.inl
  applications/plugins/MultiThreading/examples/ParallelMeshSpringForceField.scn
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/spring/ParallelStiffSpringForceField.h
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/spring/ParallelStiffSpringForceField.inl
Labels: enhancement, pr: status ready

#3664 [Core] Fix UB (misaligned address) when comparing string
  Sofa/framework/Core/src/sofa/core/objectmodel/Base.cpp
Labels: pr: fix, pr: fast merge, pr: status ready, pr: clean

#3671 [Helper, GL] Fix various memleaks
  Sofa/GL/src/sofa/gl/Axis.cpp
  Sofa/GL/src/sofa/gl/Axis.h
  Sofa/framework/Helper/src/sofa/helper/io/MeshTopologyLoader.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3688 [SofaCUDA] Add missing templates for Cuda MechanicalObject
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMechanicalObject.cpp
Labels: enhancement, pr: fast merge, pr: status ready

#3689 [IO.Mesh] Fix UB when filename is empty
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/OffSequenceLoader.cpp
  Sofa/Component/IO/Mesh/tests/CMakeLists.txt
  Sofa/Component/IO/Mesh/tests/OffSequenceLoader_test.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3694 [Testing] Fix CMake config after removal of compat
  Sofa/framework/Testing/CMakeLists.txt
Labels: pr: fix, pr: fast merge, pr: status to review
