Repository sofa-framework/sofa, pull requests merged in 2023-03, with the labels that each got.

#3678 [Config] Disable SOFA_EXTERN_TEMPLATE
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/PolynomialSpringsForceField.h
  Sofa/framework/Config/src/sofa/config.h.in
Labels: pr: fix, pr: fast merge, pr: status ready

#3682 [all] Give reason when component cannot be created
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/Distances.h
  Sofa/Component/Playback/src/sofa/component/playback/CompareTopology.h
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/CenterPointTopologicalMapping.h
  Sofa/framework/Core/src/sofa/core/Multi2Mapping.h
Labels: enhancement, pr: status ready

#3683 [Analyze] Raw pointers to Links
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/AverageCoord.h
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/AverageCoord.inl
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/ShapeMatching.h
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/ShapeMatching.inl
Labels: pr: breaking, pr: status ready

#3684 [SofaCUDA] Remove BeamLinearMapping<Rigid3fTypes,.>
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/linear/CudaBeamLinearMapping.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#3685 [all] Simple robustification
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PatchTestMovementConstraint.h
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PatchTestMovementConstraint.inl
  Sofa/Component/Engine/Select/src/sofa/component/engine/select/NearestPointROI.inl
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VoxelGridLoader.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/LineSetSkinningMapping.inl
  Sofa/Component/Mapping/MappedMatrix/src/sofa/component/mapping/mappedmatrix/MechanicalMatrixMapper.inl
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/InteractionEllipsoidForceField.inl
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/HexahedronCompositeFEMForceFieldAndMass.inl
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/NonUniformHexahedralFEMForceFieldAndMass.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TetrahedronSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridMultipleTopology.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/MergeVisualModels.h
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/SlicedVolumetricModel.cpp
  Sofa/GUI/Common/src/sofa/gui/common/PickHandler.cpp
  applications/plugins/MultiThreading/src/MultiThreading/TaskSchedulerUser.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaVisualModel.inl
Labels: pr: fix, pr: status ready

#3690 [FEM.Elastic] Check for nullptr in BeamFEMForceField
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/BeamFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/BeamFEMForceField_test.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3692 [MechanicalLoad] Stupid check for consistency between state and topology
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/OscillatingTorsionPressureForceField.h
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/OscillatingTorsionPressureForceField.inl
Labels: pr: breaking, pr: fix, pr: fast merge, pr: status ready

#3698 [Geomagic] Fix potential crash at exit when device has not been init
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3702 [IO.Mesh] Fix mesh creation if load called multiple times
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/StringMeshCreator.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3701 [SofaCUDA] Reorganize following SOFA structure (4/n)
  applications/plugins/SofaCUDA/CMakeLists.txt
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaFixedConstraint.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaFixedConstraint.inl
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLinearMovementConstraint.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLinearMovementConstraint.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaFixedConstraint.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaFixedConstraint.cu
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaFixedConstraint.h
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaFixedConstraint.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaFixedTranslationConstraint.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaLinearMovementConstraint.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaLinearMovementConstraint.cu
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaLinearMovementConstraint.h
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaLinearMovementConstraint.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaLinearVelocityConstraint.cpp
Labels: pr: status ready, refactoring

#3700 [LinearAlgebra] Fix crash when matrix has no nonzero values
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrix.h
  Sofa/framework/LinearAlgebra/test/CompressedRowSparseMatrix_test.cpp
Labels: pr: fix, pr: status ready

#3687 [Collision] Make the (CubeModel) BoundingTree deterministic
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/CubeModel.cpp
Labels: pr: fix, pr: status ready, pr: dev meeting topic

#3691 [Spring] Check for nullptr in RestShapeSpringsForceField
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/PolynomialRestShapeSpringsForceField.inl
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/RestShapeSpringsForceField.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#3693 [Helper] Fix FileRepository::relativeToPath
  Sofa/framework/Core/src/sofa/core/objectmodel/DataFileName.cpp
  Sofa/framework/Helper/src/sofa/helper/system/FileRepository.cpp
  Sofa/framework/Helper/src/sofa/helper/system/FileRepository.h
  Sofa/framework/Helper/test/system/FileRepository_test.cpp
Labels: pr: fix, pr: status ready

#3706 [LinearSolver.Direct] Make sure the matrix is factorized in SparseCholeskySolver
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseCholeskySolver.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#3713 [Sofa.GUI.Qt] Clean and fix in the "inspector" panel
  Sofa/GUI/Qt/src/sofa/gui/qt/ModifyObject.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/ModifyObject.h
  Sofa/GUI/Qt/src/sofa/gui/qt/QTabulationModifyObject.cpp
Labels: pr: status ready, issue: bug (minor)

#3727 [SofaCUDA] Fix includes pointing to compatibility layer
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaFixedConstraint.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaFixedConstraint.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaLinearMovementConstraint.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaLinearMovementConstraint.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/linear/CudaBarycentricMapping-3f.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/linear/CudaBarycentricMapping-3f1-3f.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/linear/CudaBarycentricMapping-3f1-d.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/linear/CudaBarycentricMapping-3f1-f.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/linear/CudaBarycentricMapping-3f1.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/linear/CudaBarycentricMapping-f.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/linear/CudaBarycentricMapping.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/nonlinear/CudaRigidMapping.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/nonlinear/CudaRigidMapping.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mass/CudaDiagonalMass.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mass/CudaDiagonalMass.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mass/CudaMeshMatrixMass.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mass/CudaUniformMass.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mass/CudaUniformMass.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaHexahedronFEMForceField.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaHexahedronFEMForceField.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTetrahedronFEMForceField.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTetrahedronFEMForceField.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/hyperelastic/CudaStandardTetrahedralFEMForceField.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/hyperelastic/CudaStandardTetrahedralFEMForceField.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/tensormass/CudaTetrahedralTensorMassForceField.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/tensormass/CudaTetrahedralTensorMassForceField.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#3711 [all] Remove a bunch of warnings
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/LinearVelocityConstraint.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/RigidRigidMapping.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceField.h
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/StiffSpringForceField.inl
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/TriangularBiquadraticSpringsForceField.h
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/TriangularQuadraticSpringsForceField.h
  Sofa/framework/Helper/src/sofa/helper/proximity.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3738 [applications] rename shadow variable
  applications/plugins/SofaAssimp/SceneColladaLoader.cpp
Labels: pr: fast merge, pr: status ready

#3742 [example] Introduce an example for DistanceMultiMapping
  examples/Component/Mapping/NonLinear/DistanceMultiMapping.scn
  examples/RegressionStateScenes.regression-tests
Labels: enhancement, pr: fast merge, pr: status ready

#3714 [Core] TLink: Fix warnings about comparisons between unnamed enums
  Sofa/framework/Core/src/sofa/core/objectmodel/Link.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3754 [Spring] Remove variable redefinitions
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/RestShapeSpringsForceField.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#3755 [Tests] S.Components tests compiles with SReal=float
  Sofa/Component/Engine/Select/tests/BoxROI_test.cpp
  Sofa/Component/Mapping/Linear/tests/BarycentricMapping_test.cpp
  Sofa/Component/Mass/tests/MeshMatrixMass_test.cpp
  Sofa/Component/MechanicalLoad/tests/PlaneForceField_test.cpp
  Sofa/Component/ODESolver/Backward/tests/StaticSolver_test.cpp
  applications/plugins/SceneCreator/src/SceneCreator/SceneUtils.h
Labels: pr: fix, pr: fast merge, pr: status ready

#3758 [SofaCUDA] Reorganize following SOFA structure (5/n)
  applications/plugins/SofaCUDA/CMakeLists.txt
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/lagrangian/correction/CudaLinearSolverConstraintCorrection.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/lagrangian/correction/CudaPrecomputedConstraintCorrection.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/lagrangian/correction/CudaUncoupledConstraintCorrection.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/lagrangian/model/CudaBilateralInteractionConstraint.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/engine/select/CudaBoxROI.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/engine/select/CudaNearestPointROI.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/engine/select/CudaSphereROI.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/engine/transform/CudaIndexValueMapper.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/linear/CudaSubsetMultiMapping.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mechanicalload/CudaConstantForceField.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/spring/CudaRestShapeSpringsForceField.cpp
Labels: pr: fast merge, pr: status ready, refactoring
