Repository sofa-framework/sofa, pull requests merged in 2023-01, with the labels that each got.

#3560 [Helper] Fix GenerateRigidMass redirection
  Sofa/framework/Helper/src/sofa/helper/ComponentChange.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3501 [Solver.Direct] Unit test on topological changes leading to empty system
  Sofa/Component/LinearSolver/Direct/tests/SparseLDLSolver_test.cpp
Labels: enhancement, pr: status ready

#3545 [FEM.Elastic] Fix unit tests warnings
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/BeamFEMForceField_test.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/HexahedronFEMForceField_test.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/TetrahedronFEMForceField_test.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/TriangleFEMForceField_test.cpp
  Sofa/Component/SolidMechanics/Testing/src/sofa/component/solidmechanics/testing/ForceFieldTestCreation.h
  Sofa/framework/Core/src/sofa/core/topology/TopologyData.inl
  Sofa/framework/Testing/src/sofa/testing/NumericTest.h
Labels: pr: status ready, pr: clean

#3551 [Core] Give threads a name on Windows
  Sofa/framework/Simulation/Core/src/sofa/simulation/WorkerThread.cpp
Labels: enhancement, pr: fast merge, pr: status ready

#3564 [FEM.Elastic] Minor refactoring and optimization in draw
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#3562 [GUI] Revert unexpected change of behavior introduced in #3299
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/SofaViewer.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qgl/QtGLViewer.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qt/QtViewer.cpp
Labels: pr: fix, pr: status ready, pr: backport todo

#3576 [CollisionOBBCapsule] Fix generation of configuration file for installation
  applications/plugins/CollisionOBBCapsule/CollisionOBBCapsuleConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status ready, pr: backport todo

#3548 [Core] Introduce parallel for each
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.h
  Sofa/framework/Simulation/Core/CMakeLists.txt
  Sofa/framework/Simulation/Core/src/sofa/simulation/ParallelForEach.h
  Sofa/framework/Simulation/Core/test/CMakeLists.txt
  Sofa/framework/Simulation/Core/test/ParallelForEach_test.cpp
  applications/plugins/MultiThreading/src/MultiThreading/ParallelHexahedronFEMForceField.h
  applications/plugins/MultiThreading/src/MultiThreading/ParallelHexahedronFEMForceField.inl
Labels: enhancement, pr: status ready, pr: highlighted in next release

#3541 [StateContainer] Avoid code duplication in MechanicalObject
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.h
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.inl
  Sofa/framework/Core/src/sofa/core/VecId.h
  Sofa/framework/Core/src/sofa/core/objectmodel/Data.h
Labels: pr: status ready, pr: clean

#3561 [SofaEulerianFluid] Fix: rename shadow variable in Fluid2D
  applications/plugins/SofaEulerianFluid/Fluid2D.cpp
Labels: pr: status ready

#3563 [FEM.Elastic] Consistent default values for poisson's ratio and Young's modulus
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/TetrahedronFEMForceField_test.cpp
Labels: pr: status ready, pr: clean

#3582 [LinearAlgebra] Remove wrong comment
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/RotationMatrix.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3585 [LinearAlgebra] Unit tests for RotationMatrix
  Sofa/framework/LinearAlgebra/test/CMakeLists.txt
  Sofa/framework/LinearAlgebra/test/RotationMatrix_test.cpp
Labels: pr: fast merge, pr: status ready

#3559 [Type] Quat: small optimization for axisToQuat()
  Sofa/framework/Type/src/sofa/type/Quat.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#3565 [Config] Remove unused SOFA_WITH_THREADING option
  Sofa/framework/Config/CMakeLists.txt
  Sofa/framework/Config/Sofa.ConfigConfig.cmake.in
  Sofa/framework/Config/src/sofa/config.h.in
  Sofa/framework/Config/src/sofa/config/build_option_threading.h.in
  Sofa/framework/Helper/test/logging/logging_test.cpp
Labels: pr: status ready, pr: clean

#3584 [Type] Construct matrices based on initializer-lists
  Sofa/framework/Type/src/sofa/type/Mat.h
  Sofa/framework/Type/test/MatTypes_test.cpp
Labels: pr: fast merge, pr: status ready

#3575 [Core] Display flags spelling suggestion
  Sofa/Component/Visual/src/sofa/component/visual/VisualStyle.h
  Sofa/framework/Core/CMakeLists.txt
  Sofa/framework/Core/src/sofa/core/objectmodel/Data.h
  Sofa/framework/Core/src/sofa/core/visual/Data[DisplayFlags].cpp
  Sofa/framework/Core/src/sofa/core/visual/Data[DisplayFlags].h
  Sofa/framework/Core/src/sofa/core/visual/DisplayFlags.cpp
  Sofa/framework/Core/src/sofa/core/visual/DisplayFlags.h
  Sofa/framework/Core/src/sofa/core/visual/FlagTreeItem.cpp
  Sofa/framework/Core/src/sofa/core/visual/FlagTreeItem.h
  Sofa/framework/Core/src/sofa/core/visual/Tristate.h
  Sofa/framework/Core/test/CMakeLists.txt
  Sofa/framework/Core/test/visual/DisplayFlags_test.cpp
Labels: enhancement, pr: status ready

#3574 [MultiThreading] ParallelBruteForceBroadPhase: Fix assertion error
  applications/plugins/MultiThreading/src/MultiThreading/ParallelBruteForceBroadPhase.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3591 [image] Fix Sofa.GUI dependency
  applications/plugins/image/image_gui/CMakeLists.txt
Labels: pr: fix, pr: fast merge, pr: status ready

#3593 [Mass] Remove empty loop in addForce
  Sofa/Component/Mass/src/sofa/component/mass/UniformMass.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#3572 [Multithreading] 2 steps to maximize coalescing memory access
  applications/plugins/MultiThreading/examples/ParallelHexahedronFEMForceField.scn
  applications/plugins/MultiThreading/src/MultiThreading/ParallelHexahedronFEMForceField.h
  applications/plugins/MultiThreading/src/MultiThreading/ParallelHexahedronFEMForceField.inl
Labels: enhancement, pr: status ready

#3594 [Spring] Remove duplicated code
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/StiffSpringForceField.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#3603 [SofaCUDA] Missing support for double precision floating-points
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaConstantForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLinearSolverConstraintCorrection.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMultiMapping.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaPenalityContactForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaPrecomputedConstraintCorrection.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSphereForceField.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSubsetMultiMapping.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaUncoupledConstraintCorrection.cpp
Labels: pr: fast merge, pr: status ready

#3586 [LinearAlgebra] Factorize rotateMatrix in RotationMatrix
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/RotationMatrix.cpp
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/RotationMatrix.h
Labels: pr: fast merge, pr: status ready, pr: clean

#3592 [defaulttype] Template aliases for CRS matrices
  Sofa/framework/DefaultType/src/sofa/defaulttype/TemplatesAliases.cpp
Labels: enhancement, pr: status ready

#3595 [GUI] Fix CMake Packaging
  Sofa/GUI/CMakeLists.txt
  Sofa/GUI/Sofa.GUIConfig.cmake.in
  Sofa/GUI/src/sofa/gui/config.h.in
  Sofa/GUI/src/sofa/gui/init.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#3599 [MultiThreading] Prepare data for rendering in parallel
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/fem/elastic/ParallelTetrahedronFEMForceField.h
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/fem/elastic/ParallelTetrahedronFEMForceField.inl
Labels: enhancement, pr: status ready

#3606 [Components] rename shadow variable
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/DefaultPipeline.cpp
Labels: pr: fast merge, pr: status to review, pr: clean
