Repository sofa-framework/sofa, pull requests merged in 2023-08, with the labels that each got.

#4028 [Geometry] Add method isPointOnEdge in Edge structure
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetGeometryAlgorithms.inl
  Sofa/framework/Geometry/src/sofa/geometry/Edge.h
  Sofa/framework/Geometry/test/Edge_test.cpp
Labels: pr: status ready, pr: new feature

#4001 [LinearSystem] Optim: Only account for affected DoFs
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.inl
Labels: enhancement, pr: status ready, pr: highlighted in next release

#4098 [MechanicalLoad] Fix plane force field buildStiffnessMatrix
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/PlaneForceField.inl
Labels: pr: fix, pr: status ready

#4097 [MechanicalLoad] Implement buildStiffnessMatrix in SurfacePressureForceField
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/SurfacePressureForceField.h
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/SurfacePressureForceField.inl
Labels: enhancement, pr: status ready

#3959 [Simulation.Core] Refactor DefaultAnimationLoop + multithreading
  Sofa/GUI/Component/src/sofa/gui/component/performer/MouseInteractor.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultAnimationLoop.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultAnimationLoop.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/SolveVisitor.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/SolveVisitor.h
Labels: enhancement, pr: status ready, pr: highlighted in next release

#4108 [Constraint.Lagrangian.Correction] Decrease the severity of not finding a file in PrecomputedConstraintCorrection
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/PrecomputedConstraintCorrection.inl
  Sofa/framework/Helper/src/sofa/helper/StringUtils.cpp
  Sofa/framework/Helper/src/sofa/helper/StringUtils.h
  Sofa/framework/Helper/test/CMakeLists.txt
  Sofa/framework/Helper/test/StringUtils_test.cpp
Labels: enhancement, pr: fast merge, pr: status ready

#4099 [MechanicalLoad] Implement buildStiffnessMatrix for SphereForceField
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/SphereForceField.h
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/SphereForceField.inl
Labels: enhancement, pr: status ready

#4111 [Helper] Fix wrong function called when writing jpg file
  Sofa/framework/Helper/src/sofa/helper/io/STBImage.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4102 [GUI.Qt] Fix crash if filename is null
  Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/panels/QDocBrowser.cpp
Labels: pr: fix, pr: status ready

#4118 [all] Replace deprecated wbloc function by its new function name
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrixMechanical.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTetrahedronFEMForceField.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#4120 [Core] VecId: set correct message for the deleted function holonomicC
  Sofa/framework/Core/src/sofa/core/VecId.h
Labels: pr: fast merge, pr: status ready, pr: clean

#4103 [Tutorials] Update and fix oneTetrahedron tutorial
  applications/tutorials/oneTetrahedron/oneTetrahedron.cpp
Labels: pr: fix, pr: status ready

#4112 [SofaMatrix] Remove CImgPlugin dependency
  applications/plugins/SofaMatrix/CMakeLists.txt
  applications/plugins/SofaMatrix/SofaMatrixConfig.cmake.in
  applications/plugins/SofaMatrix/src/SofaMatrix/MatrixImageExporter.cpp
Labels: pr: status ready, pr: clean

#4106 [plugins] Add fetchable ShapeMatchingPlugin
  applications/plugins/CMakeLists.txt
  applications/plugins/ShapeMatchingPlugin/ExternalProjectConfig.cmake.in
Labels: pr: status ready, pr: new feature

#4029 [Geometry] Add method intersectionWithEdge in Edge structure
  Sofa/framework/Geometry/src/sofa/geometry/Edge.h
  Sofa/framework/Geometry/test/Edge_test.cpp
Labels: pr: status ready, pr: new feature

#4110 [FEM.HyperElastic] Implement buildStiffnessMatrix for StandardTetrahedralFEMForceField
  Sofa/Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/StandardTetrahedralFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/StandardTetrahedralFEMForceField.inl
  examples/Component/SolidMechanics/FEM/StandardTetrahedralFEMForceField.scn
Labels: enhancement, pr: status ready

#4048 [Visual] ADD a visualization flag and draw method for NarrowPhaseDetection
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BVHNarrowPhase.h
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/DirectSAPNarrowPhase.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/DirectSAPNarrowPhase.h
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/IncrSAP.h
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/RayTraceNarrowPhase.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/RayTraceNarrowPhase.h
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/config.h.in
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/UnilateralInteractionConstraint.inl
  Sofa/GUI/Qt/src/sofa/gui/qt/DisplayFlagsDataWidget.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/DisplayFlagsDataWidget.h
  Sofa/framework/Core/src/sofa/core/collision/DetectionOutput.h
  Sofa/framework/Core/src/sofa/core/collision/NarrowPhaseDetection.cpp
  Sofa/framework/Core/src/sofa/core/collision/NarrowPhaseDetection.h
  Sofa/framework/Core/src/sofa/core/visual/DisplayFlags.cpp
  Sofa/framework/Core/src/sofa/core/visual/DisplayFlags.h
  Sofa/framework/Core/test/collision/NarrowPhaseDetection_test.cpp
  Sofa/framework/Core/test/visual/DisplayFlags_test.cpp
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaCollisionDetection.h
Labels: enhancement, pr: breaking, pr: status ready, pr: new feature
