Repository sofa-framework/sofa, pull requests merged in 2023-10, with the labels that each got.

#4195 [Constraint.Lagrangian.Solver] GenericConstraintSolver: avoid repeated allocation in loops
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintProblem.cpp
Labels: enhancement, pr: status ready

#4192 [Topology.Container] Remove method writeMSHfile in GeometryAlgorithms components
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/HexahedronSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/HexahedronSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/QuadSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/QuadSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TetrahedronSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TetrahedronSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.inl
Labels: pr: status ready, pr: clean

#4138 [MultiThreading] Introduce parallel CG
  applications/plugins/MultiThreading/CMakeLists.txt
  applications/plugins/MultiThreading/examples/ParallelCGLinearSolver.scn
  applications/plugins/MultiThreading/src/MultiThreading/component/linearsolver/iterative/ParallelCGLinearSolver.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/linearsolver/iterative/ParallelCGLinearSolver.h
  applications/plugins/MultiThreading/src/MultiThreading/component/linearsolver/iterative/ParallelCGLinearSolver.inl
  applications/plugins/MultiThreading/src/MultiThreading/component/linearsolver/iterative/ParallelCompressedRowSparseMatrixMechanical.h
  applications/plugins/RegressionStateScenes.regression-tests
Labels: pr: status ready, pr: new feature, pr: highlighted in next release

#4158 [LinearSystem] Introduce constant sparsity matrix assembly
  Sofa/Component/LinearSystem/CMakeLists.txt
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/ConstantSparsityPatternSystem.cpp
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/ConstantSparsityPatternSystem.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/ConstantSparsityPatternSystem.inl
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/CreateMatrixDispatcher.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/matrixaccumulators/ConstantLocalMappedMatrix.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/matrixaccumulators/ConstantLocalMatrix.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/matrixaccumulators/SparsityPatternLocalMappedMatrix.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/matrixaccumulators/SparsityPatternLocalMatrix.h
  Sofa/Component/LinearSystem/tests/MatrixLinearSystem_test.cpp
  examples/Component/LinearSystem/ConstantSparsityPatternSystem.scn
  examples/Demos/caduceus.scn
Labels: pr: status ready, pr: new feature, pr: highlighted in next release

#4172 [LinearSystem] Assemble non-mapped and mapped matrices in parallel
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
  Sofa/framework/Core/src/sofa/core/MechanicalStatesMatrixAccumulators.h
Labels: enhancement, pr: status ready

#4180 [LinearSolver.Direct] SparseLDL: Fix crash in addJMInvJtLocal
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.inl
Labels: pr: fix, pr: status ready

#4198 [GUI.Qt] Fix libQGLViewer cmake install
  Sofa/GUI/Qt/libQGLViewer/QGLViewer/CMakeLists.txt
Labels: pr: fix, pr: status ready

#4168 [BatchGUI] Show progress bar
  Sofa/GUI/Batch/CMakeLists.txt
  Sofa/GUI/Batch/src/sofa/gui/batch/BatchGUI.cpp
  Sofa/GUI/Batch/src/sofa/gui/batch/BatchGUI.h
  Sofa/GUI/Batch/src/sofa/gui/batch/ProgressBar.cpp
  Sofa/GUI/Batch/src/sofa/gui/batch/ProgressBar.h
  Sofa/GUI/Batch/src/sofa/gui/batch/indicators/LICENSE.txt
  Sofa/GUI/Batch/src/sofa/gui/batch/indicators/indicators.hpp
  Sofa/GUI/Common/CMakeLists.txt
  Sofa/GUI/Common/src/sofa/gui/common/ArgumentParser.cpp
  Sofa/GUI/Common/src/sofa/gui/common/ArgumentParser.h
Labels: enhancement, pr: breaking, pr: status ready

#4190 [Topology.Container] Update and rename methods in EdgeSetGeometryAlgorithms to compute barycentric coordinates
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TetrahedronSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.inl
Labels: pr: status ready, pr: clean

#4220 [LinearSolver.Direct] Better distribution of tasks among threads
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.inl
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/TriangularSystemSolver.h
  Sofa/framework/LinearAlgebra/test/TriangularSystemSolver_test.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/PipelineImpl.cpp
Labels: enhancement, pr: status ready

#4227 [SofaCUDA] Move cuda GUI dependent code
  applications/plugins/SofaCUDA/CMakeLists.txt
  applications/plugins/SofaCUDA/FindCUDASparse.cmake
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaCollision.cpp
  applications/plugins/SofaCUDA/sofa/gpu/gui/CudaMouseInteraction.cpp
Labels: pr: status ready, pr: clean

#4235 [Helper] Update ComponentChange for MechanicalMatrixMapper
  Sofa/framework/Helper/src/sofa/helper/ComponentChange.cpp
Labels: pr: fix, pr: fast merge, pr: status to review

#4237 [all] Forgotten scoped timers
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/FreeMotionAnimationLoop.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/CollisionPipeline.cpp
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/StaticSolver.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/collision/detection/algorithm/ParallelBVHNarrowPhase.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/collision/detection/algorithm/ParallelBruteForceBroadPhase.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#4245 [all] Add the folder sofa-launcher to the resources component
  CMakeLists.txt
Labels: pr: fast merge, pr: status to review, pr: new feature

#4244 [all] Remove TODO.md
  TODO.md
Labels: pr: fast merge, pr: status ready, pr: clean

#4247 [MatrixAccumulator] adds 6x6 matrix handling
  Sofa/framework/Core/src/sofa/core/DerivativeMatrix.h
  Sofa/framework/Core/src/sofa/core/MatrixAccumulator.cpp
  Sofa/framework/Core/src/sofa/core/MatrixAccumulator.h
Labels: enhancement, pr: status to review

#4236 [LinearAlgebra] Robustify accesses to empty matrices
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrixConstraint.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrixGeneric.h
  Sofa/framework/LinearAlgebra/test/CompressedRowSparseMatrix_test.cpp
Labels: pr: fix, pr: status ready

#4248 [LinearAlgebra] Speedup accumulation on BTDMatrix
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/BTDMatrix.h
Labels: enhancement, pr: status ready

#4253 [LinearAlgebra] Support 6x6 matrices accumulation in BaseMatrix
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/matrixaccumulators/AssemblingMatrixAccumulator.h
  Sofa/framework/Core/src/sofa/core/MatrixAccumulator.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/BaseMatrix.cpp
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/BaseMatrix.h
  Sofa/framework/Type/src/sofa/type/fwd.h
Labels: enhancement, pr: status ready

#4255 [LinearSolver] Implement parallel inverse product for all linear solvers
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.inl
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/MatrixLinearSolver.cpp
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/MatrixLinearSolver.h
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/MatrixLinearSolver.inl
Labels: enhancement, pr: status ready, pr: highlighted in next release

#4264 [GL] Remove deprecated (and incomplete) Color class
  Sofa/GL/CMakeLists.txt
  Sofa/GL/src/sofa/gl/Color.cpp
  Sofa/GL/src/sofa/gl/Color.h
Labels: pr: fast merge, pr: status ready, pr: clean

#4256 [example] Speedup TorusFall with parallel inverse product
  examples/Benchmark/Performance/TorusFall.scn
Labels: enhancement, pr: fast merge, pr: status ready
