Repository sofa-framework/sofa, pull requests merged in 2024-08, with the labels that each got.

#4869 [all] Fix type of renamed Data
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMapping.h
  Sofa/Component/SolidMechanics/TensorMass/src/sofa/component/solidmechanics/tensormass/TetrahedralTensorMassForceField.h
Labels: pr: fix, pr: fast merge, pr: status ready

#4842 [All] Add way to disable windeppack
  CMakeLists.txt
  Sofa/framework/Config/CMakeLists.txt
  Sofa/framework/Config/Sofa.ConfigConfig.cmake.in
  Sofa/framework/Helper/CMakeLists.txt
Labels: enhancement, pr: breaking, pr: status ready

#4879 [VolumetricRendering.CUDA] Fix compilation after SOFA changes
  applications/plugins/VolumetricRendering/extensions/CUDA/src/VolumetricRendering/CUDA/CudaTetrahedralVisualModel.h
  applications/plugins/VolumetricRendering/src/VolumetricRendering/config.h.in
Labels: pr: fix, pr: fast merge, pr: status ready

#4880 [GUI] Improve Error Handling in createPerformer
  Sofa/GUI/Common/src/sofa/gui/common/MouseOperations.cpp
Labels: enhancement, pr: fast merge, pr: status ready

#4859 [Plugin] Add Cosserat as a fetchable plugin
  applications/plugins/CMakeLists.txt
  applications/plugins/Cosserat/ExternalProjectConfig.cmake.in
Labels: pr: status ready, pr: new feature

#4872 [Qt] Register objects when loading from Qt
  Sofa/GUI/Qt/src/sofa/gui/qt/SofaPluginManager.cpp
Labels: pr: fix, pr: status ready

#4883 [FEM.Elastic] remove static variable
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/BaseLinearElasticityFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/BaseLinearElasticityFEMForceField.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#4863 [Helper, AnimationLoop] ComponentChange: add Dealiased state
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/ConstraintAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/FreeMotionAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/MultiStepAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/MultiTagAnimationLoop.cpp
  Sofa/framework/Core/src/sofa/core/ObjectFactory.cpp
  Sofa/framework/Helper/src/sofa/helper/ComponentChange.cpp
  Sofa/framework/Helper/src/sofa/helper/ComponentChange.h
Labels: pr: status ready, pr: clean

#4884 [Visual] BaseCamera: Fix return value when saving a view file
  Sofa/Component/Visual/src/sofa/component/visual/BaseCamera.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4885 [Core] Add filtering for unloaded plugins in ObjectFactory::getAllEntries
  Sofa/framework/Core/src/sofa/core/ObjectFactory.cpp
  Sofa/framework/Core/src/sofa/core/ObjectFactory.h
  Sofa/framework/Core/src/sofa/core/ObjectFactoryJson.cpp
  Sofa/framework/Helper/test/system/PluginManager_test.cpp
Labels: enhancement, pr: fast merge, pr: status ready

#4889 [Core] Fix compilation warnings with addClambda
  Sofa/framework/Core/src/sofa/core/behavior/ForceField.h
Labels: pr: fix, pr: fast merge, pr: status ready

#4890 [FEM] Remove duplicated Link to topology
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/NonUniformHexahedronFEMForceFieldAndMass.h
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/NonUniformHexahedronFEMForceFieldAndMass.inl
Labels: pr: fix, pr: fast merge, pr: status to review

#4894 [Core] Secure json dump
  Sofa/framework/Core/src/sofa/core/ObjectFactoryJson.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4868 [SofaCUDA] Add constructor based on initializer_list
  Sofa/framework/Helper/src/sofa/helper/MemoryManager.h
  Sofa/framework/Type/src/sofa/type/vector_device.h
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaMemoryManager.h
Labels: enhancement, pr: status ready

#4858 [AnimationLoop] Apply new factory registration mechanism
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/ConstraintAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/FreeMotionAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/MultiStepAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/MultiTagAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/init.cpp
  Sofa/Component/src/sofa/component/init.cpp
Labels: pr: status ready, pr: new feature

#4887 [Topology.Dynamic] GeometryAlgoritims: disable lighting when drawing topologies
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/HexahedronSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/QuadSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TetrahedronSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#4888 [Visual] Camera: do not export/import lookat info
  Sofa/Component/Visual/src/sofa/component/visual/BaseCamera.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4893 [VolumetricRendering] Fix target name in OglTetrahedralModel
  applications/plugins/VolumetricRendering/extensions/CUDA/src/VolumetricRendering/CUDA/CudaTetrahedralVisualModel.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4899 [SolidMechanics.FEM.Elastic] Fix compilation on clang{12, 13}
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/BeamFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangleFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceField.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#4903 [Type] Fix wrong use of std::empty
  Sofa/framework/Type/src/sofa/type/vector_device.h
Labels: pr: fix, pr: fast merge, pr: status to review

#4900 [Core] Replace non-utf8 chars by special char with error message
  Sofa/framework/Core/src/sofa/core/ObjectFactoryJson.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4904 [Core] pointer checking
  Sofa/framework/Core/src/sofa/core/behavior/PairInteractionConstraint.h
  Sofa/framework/Core/src/sofa/core/behavior/PairStateAccessor.h
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseObject.h
Labels: pr: fix, pr: fast merge, pr: status ready

#4901 [image] convert unsigned char to int when streaming
  applications/plugins/image/ImageTypes.h
Labels: pr: fix, pr: fast merge, pr: status to review

#4902 [Core] Revert thread local changes on exec params
  Sofa/framework/Core/src/sofa/core/ExecParams.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4908 [Core] ObjectFactory: fix typo when an object is not found
  Sofa/framework/Core/src/sofa/core/ObjectFactory.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#4875 [Helper] Retrieve the current user local configuration directory
  Sofa/framework/Helper/src/sofa/helper/Utils.cpp
  Sofa/framework/Helper/src/sofa/helper/Utils.h
  Sofa/framework/Helper/test/Utils_test.cpp
Labels: pr: status ready, pr: new feature

#4891 [Mapping.NonLinear] Fix rigid types in SquareDistanceMapping
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/SquareDistanceMapping.inl
Labels: pr: fix, pr: status ready

#4919 [Playback] Fix WriteStateCreator to pass period only if it has a value. Because WriteState use isSet value...
  Sofa/Component/Playback/src/sofa/component/playback/WriteState.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4828 [Helper] Added cleanup callback
  Sofa/framework/Helper/src/sofa/helper/init.cpp
  Sofa/framework/Helper/src/sofa/helper/system/PluginManager.cpp
  Sofa/framework/Helper/src/sofa/helper/system/PluginManager.h
  applications/projects/runSofa/Main.cpp
Labels: pr: status ready, pr: clean

#4848 [ODESOlver] Fix RHS computation of the backward Euler implicit solver
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/EulerImplicitSolver.cpp
  Sofa/Component/ODESolver/Backward/tests/CMakeLists.txt
  Sofa/Component/ODESolver/Backward/tests/EulerImplicitSolver_withDamping_test.cpp
Labels: pr: fix, pr: status ready, expert discussion required

#4897 [Test] Add generic test on buildGeometricStiffnessMatrix for mappings
  Sofa/Component/Mapping/Testing/src/sofa/component/mapping/testing/MappingTestCreation.h
  Sofa/framework/Core/src/sofa/core/behavior/BaseForceField.cpp
Labels: pr: status ready, pr: test

#4925 [runSofa] Removed obsolete options
  applications/projects/runSofa/Main.cpp
Labels: pr: status ready, pr: clean

#4947 [GUI.Common] ArgumentParser: catch exceptions when same options are added
  Sofa/GUI/Common/src/sofa/gui/common/ArgumentParser.cpp
Labels: pr: fix, pr: fast merge, pr: status to review

#4930 [Visual] Apply new factory registration mechanism
  Sofa/Component/Visual/src/sofa/component/visual/Camera.cpp
  Sofa/Component/Visual/src/sofa/component/visual/InteractiveCamera.cpp
  Sofa/Component/Visual/src/sofa/component/visual/LineAxis.cpp
  Sofa/Component/Visual/src/sofa/component/visual/RecordedCamera.cpp
  Sofa/Component/Visual/src/sofa/component/visual/TrailRenderer.cpp
  Sofa/Component/Visual/src/sofa/component/visual/Visual3DText.cpp
  Sofa/Component/Visual/src/sofa/component/visual/VisualGrid.cpp
  Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
  Sofa/Component/Visual/src/sofa/component/visual/VisualStyle.cpp
  Sofa/Component/Visual/src/sofa/component/visual/VisualTransform.cpp
  Sofa/Component/Visual/src/sofa/component/visual/init.cpp
  Sofa/Component/src/sofa/component/init.cpp
Labels: pr: status ready, pr: new feature

#4931 [Setting] Apply new factory registration mechanism
  Sofa/Component/Setting/src/sofa/component/setting/BackgroundSetting.cpp
  Sofa/Component/Setting/src/sofa/component/setting/SofaDefaultPathSetting.cpp
  Sofa/Component/Setting/src/sofa/component/setting/StatsSetting.cpp
  Sofa/Component/Setting/src/sofa/component/setting/ViewerSetting.cpp
  Sofa/Component/Setting/src/sofa/component/setting/init.cpp
  Sofa/Component/src/sofa/component/init.cpp
  Sofa/framework/Helper/src/sofa/helper/ComponentChange.cpp
Labels: pr: status ready, pr: new feature
