Repository sofa-framework/sofa, pull requests merged in 2024-05, with the labels that each got.

#4625 [LinearSystem] Cache mapped mass matrix
  Sofa/Component/LinearSystem/CMakeLists.txt
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/ConstantSparsityProjectionMethod.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/ConstantSparsityProjectionMethod.inl
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MappedMassMatrixObserver.cpp
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MappedMassMatrixObserver.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MappedMassMatrixObserver.inl
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixProjectionMethod.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixProjectionMethod.inl
  Sofa/Component/Mapping/Linear/CMakeLists.txt
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BeamLinearMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/CenterOfMassMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/CenterOfMassMulti2Mapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/CenterOfMassMultiMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/DeformableOnRigidFrameMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/IdentityMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/IdentityMultiMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/LineSetSkinningMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/LinearMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/Mesh2PointMechanicalMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SimpleTesselatedTetraMechanicalMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SkinningMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMapping.inl
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMultiMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/TubularMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/VoidMapping.h
  Sofa/framework/Core/src/sofa/core/BaseMapping.h
  Sofa/framework/Core/src/sofa/core/DataTracker.cpp
Labels: pr: status ready, pr: new feature, pr: highlighted in next release

#4650 [GUI.Qt] Add clickable link to online documentation
  CMakeLists.txt
  Sofa/GUI/Qt/src/sofa/gui/qt/QDataDescriptionWidget.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/QDataDescriptionWidget.h
  Sofa/framework/Config/CMakeLists.txt
  Sofa/framework/Config/src/sofa/url.h.in
  Sofa/framework/Core/src/sofa/core/ComponentLibrary.cpp
  Sofa/framework/Core/src/sofa/core/ObjectFactory.cpp
  Sofa/framework/Core/src/sofa/core/ObjectFactory.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultAnimationLoop.cpp
Labels: enhancement, pr: status ready

#4678 [Controller+Engine] Rename Data
  Sofa/Component/Controller/src/sofa/component/controller/Controller.cpp
  Sofa/Component/Controller/src/sofa/component/controller/Controller.h
  Sofa/Component/Controller/src/sofa/component/controller/MechanicalStateController.cpp
  Sofa/Component/Controller/src/sofa/component/controller/config.h.in
  Sofa/Component/Engine/Generate/src/sofa/component/engine/generate/MeshTetraStuffing.cpp
  Sofa/Component/Engine/Generate/src/sofa/component/engine/generate/MeshTetraStuffing.h
  Sofa/Component/Engine/Generate/src/sofa/component/engine/generate/config.h.in
Labels: pr: fast merge, pr: status ready, refactoring

#4708 [examples] Remove examples using DefaultCollisionGroupManager
  examples/Benchmark/Performance/CollisionGroupManager/1system_without_CollisionGroupManager.scn
  examples/Benchmark/Performance/CollisionGroupManager/2systems_with_CollisionGroupManager.scn
  examples/Benchmark/Performance/CollisionGroupManager/2systems_without_CollisionGroupManager.scn
Labels: pr: fast merge, pr: status ready, pr: clean

#4712 [SceneUtility] Initialize pointer to nullptr
  Sofa/Component/SceneUtility/src/sofa/component/sceneutility/MessageHandlerComponent.cpp
  Sofa/Component/SceneUtility/src/sofa/component/sceneutility/MessageHandlerComponent.h
Labels: pr: fix, pr: fast merge, pr: status to review

#4709 [CollisionOBBCapsule] Fix duplicated registration in the factory
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/geometry/CapsuleModel.cpp
Labels: pr: fix, pr: fast merge, pr: status to review

#4710 [Contact] Fix crash if collision models are not provided
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/ContactListener.h
Labels: pr: fix, pr: fast merge, pr: status to review

#4698 [all] Remove some warnings
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceFromTargetMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceMultiMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/SquareDistanceMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/SquareMapping.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.inl
  Sofa/GUI/Common/src/sofa/gui/common/PickHandler.cpp
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/SparseMatrixProduct.inl
  Sofa/framework/Simulation/Core/src/sofa/simulation/UpdateMappingVisitor.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#4711 [Engine.Analyze] Fix initialization of distance type
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/Distances.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#4721 [SensableEmulation] Fix module name
  applications/plugins/SensableEmulation/initSensableEmulation.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4674 [Collision.Detection.Algorithm] Rename Data
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BruteForceBroadPhase.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BruteForceBroadPhase.h
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/IncrSAP.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/IncrSAP.h
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/config.h.in
Labels: pr: status ready, refactoring

#4675 [Collision.Detection.Intersection] Rename Data
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/BaseProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/BaseProximityIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/LocalMinDistance.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/LocalMinDistance.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshMinProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshNewProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MinProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MinProximityIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/NewProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/NewProximityIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/config.h.in
Labels: pr: status to review, refactoring

#4646 [Constraint.Lagrangian] Add fixed lagrangian constraint
  Sofa/Component/Constraint/Lagrangian/Model/CMakeLists.txt
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/FixedLagrangianConstraint.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/FixedLagrangianConstraint.h
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/FixedLagrangianConstraint.inl
  Sofa/framework/Core/src/sofa/core/behavior/Constraint.cpp
  Sofa/framework/Core/src/sofa/core/behavior/Constraint.h
  Sofa/framework/Core/src/sofa/core/behavior/Constraint.inl
  Sofa/framework/Core/src/sofa/core/behavior/SingleStateAccessor.h
  examples/Component/Constraint/Lagrangian/FixedLagrangianConstaint_Rigid3.scn
  examples/Component/Constraint/Lagrangian/FixedLagrangianConstaint_Vec3.scn
Labels: pr: status ready, pr: new feature, pr: highlighted in next release

#4680 [ODESolver] Rename Data
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/EulerImplicitSolver.cpp
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/EulerImplicitSolver.h
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/VariationalSymplecticSolver.cpp
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/VariationalSymplecticSolver.h
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/config.h.in
  Sofa/Component/ODESolver/Backward/tests/VariationalSymplecticImplicitSolverDynamic_test.cpp
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/CentralDifferenceSolver.cpp
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/CentralDifferenceSolver.h
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/DampVelocitySolver.cpp
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/DampVelocitySolver.h
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/config.h.in
  Sofa/Component/Topology/Testing/src/sofa/component/topology/testing/RegularGridNodeCreation.h
  applications/collections/deprecated/modules/SofaMiscCollision/src/SofaMiscCollision/SolverMerger.cpp
Labels: pr: status ready, refactoring

#4681 [Playback] Rename Data
  Sofa/Component/Playback/src/sofa/component/playback/CompareTopology.cpp
  Sofa/Component/Playback/src/sofa/component/playback/InputEventReader.cpp
  Sofa/Component/Playback/src/sofa/component/playback/InputEventReader.h
  Sofa/Component/Playback/src/sofa/component/playback/ReadTopology.cpp
  Sofa/Component/Playback/src/sofa/component/playback/ReadTopology.h
  Sofa/Component/Playback/src/sofa/component/playback/ReadTopology.inl
  Sofa/Component/Playback/src/sofa/component/playback/WriteTopology.cpp
  Sofa/Component/Playback/src/sofa/component/playback/WriteTopology.h
  Sofa/Component/Playback/src/sofa/component/playback/WriteTopology.inl
  Sofa/Component/Playback/src/sofa/component/playback/config.h.in
Labels: pr: status ready, refactoring

#4720 [image] Fix module name
  applications/plugins/image/config.h.in
  applications/plugins/image/initImage.cpp
Labels: pr: fast merge, pr: status ready

#4715 [AnimationLoop] Remove duplicated Constraint Visitors
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/ConstraintAnimationLoop.cpp
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/ConstraintAnimationLoop.h
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/config.h.in
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/visitors/MechanicalGetConstraintResolutionVisitor.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/visitors/MechanicalGetConstraintResolutionVisitor.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalBuildConstraintMatrix.cpp
Labels: pr: breaking, pr: status ready, pr: clean

#4676 [Collision.Geometry+Response] Rename Data
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/LocalMinDistance.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/LineModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/LineModel.inl
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/PointModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/PointModel.inl
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/RayModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/RayModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/SphereModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/SphereModel.inl
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/config.h.in
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/BarycentricStickContact.h
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/BarycentricStickContact.inl
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/CollisionResponse.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/CollisionResponse.h
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/FrictionContact.h
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/FrictionContact.inl
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/RuleBasedContactManager.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/RuleBasedContactManager.h
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/StickContactConstraint.h
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/StickContactConstraint.inl
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/config.h.in
  Sofa/Component/Collision/Testing/src/sofa/component/collision/testing/SpherePrimitiveCreator.h
  Sofa/framework/Helper/src/sofa/helper/LCPcalc.cpp
  applications/projects/SceneChecking/src/SceneChecking/SceneCheckCollisionResponse.cpp
Labels: pr: status to review, refactoring

#4679 [IO] Rename Data
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/GridMeshCreator.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/GridMeshCreator.h
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshSTLLoader.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshSTLLoader.h
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshTrianLoader.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshTrianLoader.h
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/OffSequenceLoader.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/OffSequenceLoader.h
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/StringMeshCreator.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/StringMeshCreator.h
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VTKExporter.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VTKExporter.h
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VoxelGridLoader.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VoxelGridLoader.h
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/config.h.in
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/LineSetSkinningMapping.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetTopologyContainer.cpp
  Sofa/framework/Core/src/sofa/core/loader/VoxelLoader.h
Labels: pr: status to review, refactoring

#4682 [Setting] Rename Data
  Sofa/Component/Setting/src/sofa/component/setting/BackgroundSetting.cpp
  Sofa/Component/Setting/src/sofa/component/setting/BackgroundSetting.h
  Sofa/Component/Setting/src/sofa/component/setting/MouseButtonSetting.cpp
  Sofa/Component/Setting/src/sofa/component/setting/MouseButtonSetting.h
  Sofa/Component/Setting/src/sofa/component/setting/SofaDefaultPathSetting.cpp
  Sofa/Component/Setting/src/sofa/component/setting/SofaDefaultPathSetting.h
  Sofa/Component/Setting/src/sofa/component/setting/StatsSetting.cpp
  Sofa/Component/Setting/src/sofa/component/setting/StatsSetting.h
  Sofa/Component/Setting/src/sofa/component/setting/ViewerSetting.cpp
  Sofa/Component/Setting/src/sofa/component/setting/ViewerSetting.h
  Sofa/Component/Setting/src/sofa/component/setting/config.h.in
  Sofa/GL/Component/Rendering2D/src/sofa/gl/component/rendering2d/OglLabel.cpp
  Sofa/GUI/Common/src/sofa/gui/common/BaseGUI.cpp
  Sofa/GUI/Common/src/sofa/gui/common/BaseViewer.cpp
  Sofa/GUI/Common/src/sofa/gui/common/MouseOperations.h
  Sofa/GUI/Common/src/sofa/gui/common/PickHandler.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/QMouseOperations.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/GLBackend.cpp
Labels: pr: status ready, refactoring

#4726 [image,Mapping.NonLinear] Properly includes config.h before ObjectFactory.h
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceMultiMapping.cpp
  applications/plugins/image/ImageTypes.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4724 [tests] Adapt code to any Eigen version
  Sofa/Component/SolidMechanics/FEM/HyperElastic/tests/Material_test.cpp
Labels: pr: fix, pr: status ready

#4719 [image_gui] Make it a cleaner SOFA module
  applications/plugins/image/image_gui/CMakeLists.txt
  applications/plugins/image/image_gui/image_guiConfig.cmake.in
  applications/plugins/image/image_gui/src/image_gui/HistogramWidget.cpp
  applications/plugins/image/image_gui/src/image_gui/HistogramWidget.h
  applications/plugins/image/image_gui/src/image_gui/ImagePlaneWidget.cpp
  applications/plugins/image/image_gui/src/image_gui/ImagePlaneWidget.h
  applications/plugins/image/image_gui/src/image_gui/ImageTransformWidget.cpp
  applications/plugins/image/image_gui/src/image_gui/ImageTransformWidget.h
  applications/plugins/image/image_gui/src/image_gui/VectorVisualizationWidget.cpp
  applications/plugins/image/image_gui/src/image_gui/VectorVisualizationWidget.h
  applications/plugins/image/image_gui/src/image_gui/config.h.in
  applications/plugins/image/image_gui/src/image_gui/initImage_gui.cpp
  applications/plugins/image/imagetoolbox/contour/contourimagetoolbox.h
  applications/plugins/image/imagetoolbox/contour/contourimagetoolboxaction.h
  applications/plugins/image/imagetoolbox/depth/averagecatchallvector.h
  applications/plugins/image/imagetoolbox/depth/catchallvector.h
  applications/plugins/image/imagetoolbox/depth/depthimagetoolbox.h
  applications/plugins/image/imagetoolbox/depth/depthimagetoolboxaction.h
  applications/plugins/image/imagetoolbox/depth/mergedcatchallvector.cpp
  applications/plugins/image/imagetoolbox/depth/mergedcatchallvector.h
  applications/plugins/image/imagetoolbox/imagetoolbox.cpp
  applications/plugins/image/imagetoolbox/imagetoolbox.h
  applications/plugins/image/imagetoolbox/imagetoolboxbasicactionwidget.h
  applications/plugins/image/imagetoolbox/imagetoolboxcentralwidget.h
  applications/plugins/image/imagetoolbox/imagetoolboxdata.h
  applications/plugins/image/imagetoolbox/imagetoolboxlabelactionwidget.h
  applications/plugins/image/imagetoolbox/imagetoolboxwidget.h
  applications/plugins/image/imagetoolbox/labelbox/labelboximagetoolbox.h
  applications/plugins/image/imagetoolbox/labelbox/labelboximagetoolboxaction.h
  applications/plugins/image/imagetoolbox/labelgrid/labelgridimagetoolbox.h
  applications/plugins/image/imagetoolbox/labelgrid/labelgridimagetoolboxaction.h
  applications/plugins/image/imagetoolbox/labelimagetoolbox.h
  applications/plugins/image/imagetoolbox/labelimagetoolboxaction.h
  applications/plugins/image/imagetoolbox/labelpoint/labelpointimagetoolbox.h
  applications/plugins/image/imagetoolbox/labelpoint/labelpointimagetoolboxaction.h
  applications/plugins/image/imagetoolbox/labelpointsbysection/labelpointsbysectionimagetoolbox.h
  applications/plugins/image/imagetoolbox/labelpointsbysection/labelpointsbysectionimagetoolboxaction.h
  applications/plugins/image/imagetoolbox/zonegenerator/distancezoneimagetoolbox.h
  applications/plugins/image/imagetoolbox/zonegenerator/distancezoneimagetoolboxaction.h
  applications/plugins/image/imagetoolbox/zonegenerator/zonegeneratorimagetoolbox.h
  applications/plugins/image/imagetoolbox/zonegenerator/zonegeneratorimagetoolboxaction.h
Labels: pr: fix, pr: status ready

#4740 [MultiThreading] Fix module name in BeamLinearMapping_mt
  applications/plugins/MultiThreading/src/MultiThreading/component/mapping/linear/BeamLinearMapping_mt.cpp
  applications/plugins/MultiThreading/src/MultiThreading/config.h.in
Labels: pr: fix, pr: fast merge, pr: status ready

#4741 [image_gui] Fix module name
  applications/plugins/image/imagetoolbox/depth/depthimagetoolbox.cpp
  applications/plugins/image/imagetoolbox/labelgrid/labelgridimagetoolbox.cpp
  applications/plugins/image/imagetoolbox/zonegenerator/distancezoneimagetoolbox.cpp
  applications/plugins/image/imagetoolbox/zonegenerator/zonegeneratorimagetoolbox.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4744 [PlayBack] Add option to set period in the WriteStateCreator visitor
  Sofa/Component/Playback/src/sofa/component/playback/WriteState.cpp
  Sofa/Component/Playback/src/sofa/component/playback/WriteState.h
Labels: pr: fix, pr: fast merge, pr: status ready

#4732 [tests] Fix and test value type string of topology primitives
  Sofa/framework/Core/src/sofa/core/topology/Topology.h
  Sofa/framework/Core/test/objectmodel/Data_test.cpp
  Sofa/framework/Geometry/src/sofa/geometry/Edge.h
  Sofa/framework/Geometry/src/sofa/geometry/ElementInfo.cpp
  Sofa/framework/Geometry/src/sofa/geometry/ElementInfo.h
  Sofa/framework/Geometry/src/sofa/geometry/Hexahedron.h
  Sofa/framework/Geometry/src/sofa/geometry/Pentahedron.h
  Sofa/framework/Geometry/src/sofa/geometry/Point.h
  Sofa/framework/Geometry/src/sofa/geometry/Pyramid.h
  Sofa/framework/Geometry/src/sofa/geometry/Quad.h
  Sofa/framework/Geometry/src/sofa/geometry/Tetrahedron.h
  Sofa/framework/Geometry/src/sofa/geometry/Triangle.h
  Sofa/framework/Topology/src/sofa/topology/Element.h
Labels: pr: fix, pr: fast merge, pr: status ready, pr: test

#4753 [Core] Missing closing brace
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseObject.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4628 [ODESolver] Explicit link to linear solver
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/EulerImplicitSolver.cpp
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/EulerImplicitSolver.h
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/NewmarkImplicitSolver.cpp
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/NewmarkImplicitSolver.h
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/StaticSolver.cpp
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/StaticSolver.h
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/VariationalSymplecticSolver.cpp
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/VariationalSymplecticSolver.h
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/EulerSolver.cpp
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/EulerSolver.h
  Sofa/framework/Core/CMakeLists.txt
  Sofa/framework/Core/src/sofa/core/behavior/LinearSolverAccessor.cpp
  Sofa/framework/Core/src/sofa/core/behavior/LinearSolverAccessor.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/MechanicalOperations.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/MechanicalOperations.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/config.h.in
Labels: pr: status ready, refactoring

#4683 [Topology] Rename Data
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/IncrSAP.h
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/Distances.inl
  Sofa/Component/Engine/Transform/src/sofa/component/engine/transform/Vertex2Frame.h
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshSTLLoader.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/STLExporter.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SimpleTesselatedHexaTopologicalMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMapping.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMapping.inl
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/NonUniformHexahedronFEMForceFieldAndMass.h
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/NonUniformHexahedronFEMForceFieldAndMass.inl
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/CubeTopology.cpp
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/CubeTopology.h
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/MeshTopology.cpp
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/MeshTopology.h
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/SphereQuadTopology.cpp
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/SphereQuadTopology.h
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/config.h.in
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyContainer.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyModifier.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetTopologyContainer.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetTopologyContainer.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/config.h.in
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/GridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/RegularGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridMultipleTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridMultipleTopology.h
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridRamificationTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridRamificationTopology.h
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.h
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/config.h.in
  Sofa/Component/Topology/Container/Grid/tests/SparseGridTopology_test.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Hexa2QuadTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Hexa2QuadTopologicalMapping.h
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Hexa2TetraTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Hexa2TetraTopologicalMapping.h
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/SubsetTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/SubsetTopologicalMapping.h
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Tetra2TriangleTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Tetra2TriangleTopologicalMapping.h
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/config.h.in
  Sofa/Component/Topology/Utility/src/sofa/component/topology/utility/TopologicalChangeProcessor.cpp
  Sofa/Component/Topology/Utility/src/sofa/component/topology/utility/TopologicalChangeProcessor.h
  Sofa/Component/Topology/Utility/src/sofa/component/topology/utility/config.h.in
  Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.h
  Sofa/framework/Core/src/sofa/core/loader/SceneLoader.cpp
  Sofa/framework/Helper/src/sofa/helper/MarchingCubeUtility.cpp
  Sofa/framework/Helper/src/sofa/helper/MarchingCubeUtility.h
Labels: pr: status to review, refactoring

#4684 [Visual] Rename Data
  Sofa/Component/Visual/src/sofa/component/visual/BaseCamera.cpp
  Sofa/Component/Visual/src/sofa/component/visual/BaseCamera.h
  Sofa/Component/Visual/src/sofa/component/visual/Camera.cpp
  Sofa/Component/Visual/src/sofa/component/visual/InteractiveCamera.cpp
  Sofa/Component/Visual/src/sofa/component/visual/InteractiveCamera.h
  Sofa/Component/Visual/src/sofa/component/visual/RecordedCamera.cpp
  Sofa/Component/Visual/src/sofa/component/visual/RecordedCamera.h
  Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
  Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.h
  Sofa/Component/Visual/src/sofa/component/visual/VisualStyle.cpp
  Sofa/Component/Visual/src/sofa/component/visual/VisualStyle.h
  Sofa/Component/Visual/src/sofa/component/visual/VisualTransform.cpp
  Sofa/Component/Visual/src/sofa/component/visual/VisualTransform.h
  Sofa/Component/Visual/src/sofa/component/visual/config.h.in
  Sofa/Component/Visual/tests/VisualModelImpl_test.cpp
  Sofa/GL/Component/Rendering2D/src/sofa/gl/component/rendering2d/OglViewport.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/MergeVisualModels.h
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglModel.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/CompositingVisualLoop.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglShaderVisualModel.cpp
  Sofa/GUI/Common/src/sofa/gui/common/BaseViewer.cpp
  Sofa/GUI/Component/src/sofa/gui/component/performer/AddRecordedCameraPerformer.cpp
  Sofa/GUI/Component/src/sofa/gui/component/performer/StartNavigationPerformer.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/viewer/qt/QtViewer.cpp
Labels: pr: status ready, refactoring

#4754 [Helper] Fix dl open when path are not canonical
  Sofa/framework/Helper/src/sofa/helper/system/DynamicLibrary.cpp
  Sofa/framework/Helper/src/sofa/helper/system/PluginManager.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4748 [tools] Factorize and clean plugin list filtering
  tools/postinstall-fixup/CMakeLists.txt
  tools/postinstall-fixup/common.sh
  tools/postinstall-fixup/linux-postinstall-fixup.sh
  tools/postinstall-fixup/macos-postinstall-fixup.sh
  tools/postinstall-fixup/windows-postinstall-fixup.sh
Labels: pr: status ready, pr: clean, pr: dev meeting topic

#4759 [all] Fix typos in comments
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PartialLinearMovementProjectiveConstraint.h
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PositionBasedDynamicsProjectiveConstraint.inl
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridRamificationTopology.h
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.h
Labels: pr: fast merge, pr: status ready, refactoring, pr: clean, pr: backport todo

#4749 [tools] Add new dependency to fix in MacOS post-install-fixup
  applications/plugins/CImgPlugin/CMakeLists.txt
  cmake/Modules/FindZSTD.cmake
  tools/postinstall-fixup/macos-postinstall-fixup.sh
Labels: pr: fast merge, pr: status ready, pr: clean, pr: backport todo

#4738 [Core] Add topology subset indices test
  Sofa/framework/Core/src/sofa/core/topology/TopologySubsetData.h
  Sofa/framework/Core/src/sofa/core/topology/TopologySubsetData.inl
  Sofa/framework/Core/src/sofa/core/topology/TopologySubsetIndices.cpp
  Sofa/framework/Core/src/sofa/core/topology/TopologySubsetIndices.h
  Sofa/framework/Core/test/CMakeLists.txt
  Sofa/framework/Core/test/topology/TopologySubsetIndices_test.cpp
Labels: pr: fix, pr: status ready
