Repository sofa-framework/sofa, pull requests merged in 2024-12, with the labels that each got.

#5059 [workflow][Nix] initial packaging & flake
  .github/workflows/nix.yml
  Sofa/GUI/Qt/CMakeLists.txt
  cmake/Modules/FindQGLViewer.cmake
  flake.lock
  flake.nix
  package.nix
Labels: pr: status ready, pr: new feature, pr: highlighted in next release

#5087 [LinearAlgebra] CompressedRowSparseMatrixConstraint: make consistent the serialization/deserialization process
  Sofa/GUI/Qt/src/sofa/gui/qt/SimpleDataWidget.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/SimpleDataWidget.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrixConstraint.h
  Sofa/framework/LinearAlgebra/test/CompressedRowSparseMatrixConstraint_test.cpp
Labels: pr: fix, pr: status ready

#5136 [Spring] Add warning when user tries to override MeshSpringForcefield indices
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/MeshSpringForceField.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#5098 [Simulation.Core] Apply new factory registration mechanism
  Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultAnimationLoop.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultVisualManagerLoop.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/RequiredPlugin.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/init.cpp
  Sofa/framework/Simulation/Graph/src/sofa/simulation/graph/DAGSimulation.cpp
Labels: pr: status to review, pr: new feature

#5097 [GL, GUI] Apply new factory registration mechanism
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/GenericConstraintCorrection.cpp
  Sofa/GL/Component/Engine/src/sofa/gl/component/engine/TextureInterpolation.cpp
  Sofa/GL/Component/Engine/src/sofa/gl/component/engine/init.cpp
  Sofa/GL/Component/Rendering2D/src/sofa/gl/component/rendering2d/OglColorMap.cpp
  Sofa/GL/Component/Rendering2D/src/sofa/gl/component/rendering2d/OglLabel.cpp
  Sofa/GL/Component/Rendering2D/src/sofa/gl/component/rendering2d/OglViewport.cpp
  Sofa/GL/Component/Rendering2D/src/sofa/gl/component/rendering2d/init.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/ClipPlane.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/DataDisplay.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/MergeVisualModels.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglCylinderModel.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglModel.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglSceneFrame.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/PointSplatModel.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/SlicedVolumetricModel.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/init.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/CompositingVisualLoop.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/Light.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/LightManager.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglAttribute.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglOITShader.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglRenderingSRGB.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglShader.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglShaderMacro.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglShaderVisualModel.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglShadowShader.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglTexture.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglTexturePointer.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OglVariable.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/OrderIndependentTransparencyManager.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/PostProcessManager.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/VisualManagerPass.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/VisualManagerSecondaryPass.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/init.cpp
  Sofa/GL/Component/src/sofa/gl/component/init.cpp
  Sofa/GUI/Component/src/sofa/gui/component/AddFrameButtonSetting.cpp
  Sofa/GUI/Component/src/sofa/gui/component/AddFrameButtonSetting.h
  Sofa/GUI/Component/src/sofa/gui/component/AddRecordedCameraButtonSetting.cpp
  Sofa/GUI/Component/src/sofa/gui/component/AttachBodyButtonSetting.cpp
  Sofa/GUI/Component/src/sofa/gui/component/ConstraintAttachButtonSetting.cpp
  Sofa/GUI/Component/src/sofa/gui/component/FixPickedParticleButtonSetting.cpp
  Sofa/GUI/Component/src/sofa/gui/component/init.cpp
  Sofa/GUI/Component/src/sofa/gui/component/performer/MouseInteractor.cpp
  Sofa/framework/Helper/src/sofa/helper/ComponentChange.cpp
Labels: pr: status ready, pr: new feature

#5156 [All] Remove spam warnings
  Sofa/framework/Core/src/sofa/core/behavior/BaseMechanicalState.h
  Sofa/framework/Core/src/sofa/core/config.h.in
  Sofa/framework/Helper/src/sofa/helper/SelectableItem.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/MechanicalOperations.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/config.h.in
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalPropagateOnlyPositionAndVelocityVisitor.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalPropagateOnlyVelocityVisitor.h
Labels: pr: fast merge, pr: status to review, pr: clean

#5025 [Constraint.Projective] Make LinearVelocityProjectiveConstraint work with FreeMotionAL
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/LinearVelocityProjectiveConstraint.h
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/LinearVelocityProjectiveConstraint.inl
  examples/Component/Constraint/Projective/LinearVelocityProjectiveConstraint.scn
  examples/Demos/SofaWasher.scn
  examples/RegressionStateScenes.regression-tests
  share/mesh/SOFA_collision_center.obj
  share/mesh/SOFA_collision_no_face.obj
  share/mesh/SOFA_surface.obj
  share/mesh/SOFA_volume.vtk
Labels: pr: fix, pr: status ready

#5155 [Core, Simulation.Core] Registration: (re)enable deprecation warnings
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/AugmentedLagrangianConstraint.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/init.cpp
  Sofa/Component/IO/Mesh/tests/STLExporter_test.cpp
  Sofa/framework/Core/src/sofa/core/ObjectFactory.cpp
  Sofa/framework/Core/src/sofa/core/ObjectFactory.h
  Sofa/framework/Helper/test/system/PluginManager_test.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/RequiredPlugin.cpp
  Sofa/framework/Simulation/Core/test/RequiredPlugin_test.cpp
  Sofa/framework/Simulation/simutest/parallel_scenes_test.cpp
  applications/projects/SceneChecking/tests/SceneChecker_test.cpp
Labels: pr: status to review, pr: clean, deprecated, pr: backport todo

#5171 [SofaCUDA] Remove NO_CUDA condition
  applications/plugins/SofaCUDA/sofa/gpu/cuda/mycuda.cu
Labels: pr: fast merge, pr: status ready, pr: clean

#5175 [Plugins] Remove unsupported plugins: InvertibleFVM, SofaSimpleGUI and SensableEmulation
  applications/plugins/CMakeLists.txt
  applications/plugins/InvertibleFVM/ExternalProjectConfig.cmake.in
  applications/plugins/SensableEmulation/CMakeLists.txt
  applications/plugins/SensableEmulation/NewOmniDriverEmu.cpp
  applications/plugins/SensableEmulation/NewOmniDriverEmu.h
  applications/plugins/SensableEmulation/OmniDriverEmu.cpp
  applications/plugins/SensableEmulation/OmniDriverEmu.h
  applications/plugins/SensableEmulation/PluginSensableEmulation.txt
  applications/plugins/SensableEmulation/config.h
  applications/plugins/SensableEmulation/examples/SimpleBox-Method2.scn
  applications/plugins/SensableEmulation/examples/SimpleBox-Method2.scn.view
  applications/plugins/SensableEmulation/examples/data/mesh/box.obj
  applications/plugins/SensableEmulation/examples/data/mesh/dental_instrument.obj
  applications/plugins/SensableEmulation/examples/testOmniDriverEmu.scn
  applications/plugins/SensableEmulation/initSensableEmulation.cpp
  applications/plugins/SensableEmulation/pthread/pthread.h
  applications/plugins/SensableEmulation/pthread/pthreadVC2.dll
  applications/plugins/SensableEmulation/pthread/pthreadVC2.lib
  applications/plugins/SensableEmulation/pthread/sched.h
  applications/plugins/SensableEmulation/pthread/semaphore.h
  applications/plugins/SofaSimpleGUI/CMakeLists.txt
  applications/plugins/SofaSimpleGUI/Camera.cpp
  applications/plugins/SofaSimpleGUI/Camera.h
  applications/plugins/SofaSimpleGUI/Interactor.cpp
  applications/plugins/SofaSimpleGUI/Interactor.h
  applications/plugins/SofaSimpleGUI/PickedPoint.h
  applications/plugins/SofaSimpleGUI/README.txt
  applications/plugins/SofaSimpleGUI/SimpleGUI.dox
  applications/plugins/SofaSimpleGUI/SofaGL.cpp
  applications/plugins/SofaSimpleGUI/SofaGL.h
  applications/plugins/SofaSimpleGUI/SofaGlutAnt.zip
  applications/plugins/SofaSimpleGUI/SofaScene.cpp
  applications/plugins/SofaSimpleGUI/SofaScene.h
  applications/plugins/SofaSimpleGUI/SofaSimpleGUIConfig.cmake.in
  applications/plugins/SofaSimpleGUI/SpringInteractor.cpp
  applications/plugins/SofaSimpleGUI/SpringInteractor.h
  applications/plugins/SofaSimpleGUI/VisualPickVisitor.cpp
  applications/plugins/SofaSimpleGUI/VisualPickVisitor.h
  applications/plugins/SofaSimpleGUI/config.h.in
  applications/plugins/SofaSimpleGUI/doc/Doxyfile
  applications/plugins/SofaSimpleGUI/doc/DoxygenLayout.xml
  applications/plugins/SofaSimpleGUI/doc/SimpleGUI.png
  applications/plugins/SofaSimpleGUI/doc/index.html
  applications/plugins/SofaSimpleGUI/examples/liver.scn
  applications/plugins/SofaSimpleGUI/examples/oneTet.scn
  applications/plugins/SofaSimpleGUI/initSimpleGUI.cpp
Labels: enhancement, pr: status ready, pr: highlighted in next release

#5165 [SofaCUDA] Explicit the CUDA C++ standard version to 17
  applications/plugins/SofaCUDA/CMakeLists.txt
Labels: pr: status ready, pr: clean

#5133 [Helper] PluginManager: support loading from Non-MSVC Multi-Configuration Build
  Sofa/framework/Helper/CMakeLists.txt
  Sofa/framework/Helper/src/sofa/helper/system/FileRepository.cpp
  Sofa/framework/Helper/src/sofa/helper/system/PluginManager.cpp
Labels: pr: fix, pr: status ready

#5178 [Multithreading] Apply new factory registration mechanism
  applications/plugins/MultiThreading/src/MultiThreading/DataExchange.cpp
  applications/plugins/MultiThreading/src/MultiThreading/MeanComputation.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/animationloop/AnimationLoopParallelScheduler.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/collision/detection/algorithm/ParallelBVHNarrowPhase.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/collision/detection/algorithm/ParallelBruteForceBroadPhase.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/linearsolver/iterative/ParallelCGLinearSolver.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/mapping/linear/BeamLinearMapping_mt.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/fem/elastic/ParallelHexahedronFEMForceField.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/fem/elastic/ParallelTetrahedronFEMForceField.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/fem/elastic/ParallelTetrahedronFEMForceField.h
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/fem/elastic/ParallelTetrahedronFEMForceField.inl
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/spring/ParallelMeshSpringForceField.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/spring/ParallelSpringForceField.cpp
  applications/plugins/MultiThreading/src/MultiThreading/config.h.in
  applications/plugins/MultiThreading/src/MultiThreading/initMultiThreading.cpp
  applications/plugins/MultiThreading/test/ParallelImplementationsRegistry_test.cpp
Labels: pr: status ready, pr: clean
