Repository sofa-framework/sofa, pull requests merged in 2024-07, with the labels that each got.

#4786 [Core] Factorize two variables with the same meaning (constraint id)
  Sofa/framework/Core/src/sofa/core/behavior/BaseConstraintSet.h
  Sofa/framework/Core/src/sofa/core/config.h.in
Labels: pr: breaking, pr: status ready, pr: clean

#4804 [SofaTest] Rename deprecated data
  applications/plugins/SofaTest/Elasticity_test.inl
Labels: pr: fast merge, pr: status ready, refactoring

#4775 [Core] Dump ObjectFactory in json
  Sofa/framework/Core/CMakeLists.txt
  Sofa/framework/Core/src/sofa/core/ObjectFactory.cpp
  Sofa/framework/Core/src/sofa/core/ObjectFactory.h
  Sofa/framework/Core/src/sofa/core/ObjectFactoryJson.cpp
  Sofa/framework/Core/src/sofa/core/ObjectFactoryJson.h
  Sofa/framework/Core/test/CMakeLists.txt
  Sofa/framework/Core/test/ObjectFactoryJson_test.cpp
Labels: pr: status ready, pr: new feature

#4807 [SolidMechanics] Fix type declaration in deprecated data
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.h
Labels: pr: fix, pr: fast merge, pr: status ready

#4795 [All] Plugins: Deprecate entrypoint getModuleComponentList()
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/init.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/init.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/init.cpp
  Sofa/Component/Collision/Detection/src/sofa/component/collision/detection/init.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/init.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/init.cpp
  Sofa/Component/Collision/Response/Mapper/src/sofa/component/collision/response/mapper/init.cpp
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/init.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/init.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/init.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/init.cpp
  Sofa/Component/Controller/src/sofa/component/controller/init.cpp
  Sofa/Component/Diffusion/src/sofa/component/diffusion/init.cpp
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/init.cpp
  Sofa/Component/Engine/Generate/src/sofa/component/engine/generate/init.cpp
  Sofa/Component/Engine/Select/src/sofa/component/engine/select/init.cpp
  Sofa/Component/Engine/Transform/src/sofa/component/engine/transform/init.cpp
  Sofa/Component/Haptics/src/sofa/component/haptics/init.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/init.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/init.cpp
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/init.cpp
  Sofa/Component/LinearSolver/Ordering/src/sofa/component/linearsolver/ordering/init.cpp
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/init.cpp
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/init.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/init.cpp
  Sofa/Component/Mapping/MappedMatrix/src/sofa/component/mapping/mappedmatrix/init.cpp
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/init.cpp
  Sofa/Component/Mass/src/sofa/component/mass/init.cpp
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/init.cpp
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/init.cpp
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/init.cpp
  Sofa/Component/Playback/src/sofa/component/playback/init.cpp
  Sofa/Component/SceneUtility/src/sofa/component/sceneutility/init.cpp
  Sofa/Component/Setting/src/sofa/component/setting/init.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/init.cpp
  Sofa/Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/init.cpp
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/init.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/init.cpp
  Sofa/Component/SolidMechanics/TensorMass/src/sofa/component/solidmechanics/tensormass/init.cpp
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/init.cpp
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/init.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/init.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/init.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/init.cpp
  Sofa/Component/Topology/Utility/src/sofa/component/topology/utility/init.cpp
  Sofa/Component/Visual/src/sofa/component/visual/init.cpp
  Sofa/GL/Component/Rendering2D/src/sofa/gl/component/rendering2d/init.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/init.cpp
  Sofa/GL/Component/Shader/src/sofa/gl/component/shader/init.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/SofaPluginManager.cpp
  Sofa/framework/Helper/src/sofa/helper/config.h.in
  Sofa/framework/Helper/src/sofa/helper/system/PluginManager.h
  applications/plugins/MultiThreading/src/MultiThreading/initMultiThreading.cpp
Labels: pr: status ready, pr: clean

#4802 [All] Remove compat layer for Intersection methods
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/CollisionPM.h
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/DirectSAPNarrowPhase.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/MirrorIntersector.h
  Sofa/framework/Core/src/sofa/core/collision/Intersection.h
  Sofa/framework/Core/src/sofa/core/collision/Intersection.inl
  Sofa/framework/Core/src/sofa/core/config.h.in
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/detection/intersection/CapsuleIntersection.cpp
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/detection/intersection/CapsuleIntersection.h
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/detection/intersection/OBBIntersection.cpp
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/detection/intersection/OBBIntersection.h
  applications/plugins/MultiThreading/src/MultiThreading/component/collision/detection/algorithm/ParallelBruteForceBroadPhase.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/FFDDistanceGridDiscreteIntersection.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/FFDDistanceGridDiscreteIntersection.h
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/FFDDistanceGridDiscreteIntersection.inl
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/RigidDistanceGridDiscreteIntersection.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/RigidDistanceGridDiscreteIntersection.h
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/RigidDistanceGridDiscreteIntersection.inl
Labels: pr: status ready, pr: clean

#4812 [All] CMake: Remove deprecated settings
  CMakeLists.txt
  Sofa/framework/Config/CMakeLists.txt
  Sofa/framework/LinearAlgebra/CMakeLists.txt
  Sofa/framework/Type/CMakeLists.txt
Labels: pr: fast merge, pr: status ready, pr: clean

#4816 [Core] Explicit type instead of calling function with side effect
  Sofa/framework/Core/src/sofa/core/objectmodel/Data.h
Labels: pr: fix, pr: fast merge, pr: status to review

#4817 [Core] Deprecate typeName with parameter
  Sofa/framework/Core/src/sofa/core/config.h.in
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseData.h
Labels: pr: fast merge, pr: status ready, pr: clean

#4819 [Collision] Secure pointers dereferences
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/SphereModel.h
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/ContactListener.h
Labels: pr: fix, pr: fast merge, pr: status ready

#4831 [FEM.Elastic] Fix dynamic symbols
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/BaseLinearElasticityFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/BaseLinearElasticityFEMForceField.h
Labels: pr: fix, pr: fast merge, pr: status ready

#4763 [Lagrangian.Model] Use base class Data instead of protected class member for constraint id
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/SlidingLagrangianConstraint.h
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/SlidingLagrangianConstraint.inl
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/StopperLagrangianConstraint.h
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/StopperLagrangianConstraint.inl
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/UniformLagrangianConstraint.h
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/UniformLagrangianConstraint.inl
Labels: pr: status ready, pr: clean

#4780 [FEM.Elastic] Fix small deformation in TriangleFEMForceField
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangleFEMForceField.inl
Labels: pr: fix, pr: status ready

#4818 [Core] Test json dump on the main object factory
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BruteForceDetection.h
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/DirectSAP.h
  Sofa/framework/Core/test/ObjectFactoryJson_test.cpp
Labels: pr: status ready, pr: test

#4820 [All] Reduce includes to helper/set.h
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/LCPConstraintSolver.h
  Sofa/Component/Engine/Analyze/src/sofa/component/engine/analyze/Distances.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/NumericalIntegrationDescriptor.h
  Sofa/Component/Topology/Container/Dynamic/tests/TetrahedronNumericalIntegration_test.cpp
  Sofa/Component/Topology/Container/Dynamic/tests/TriangleNumericalIntegration_test.cpp
  Sofa/framework/Core/src/sofa/core/CollisionModel.h
  Sofa/framework/Core/src/sofa/core/collision/Pipeline.h
  Sofa/framework/Core/src/sofa/core/objectmodel/TagSet.cpp
  Sofa/framework/Core/src/sofa/core/objectmodel/TagSet.h
  Sofa/framework/Helper/src/sofa/helper/MarchingCubeUtility.h
  applications/plugins/MultiThreading/src/MultiThreading/MeanComputation.inl
Labels: pr: status ready, pr: clean

#4837 [Helper] Move string utils from Utils to StringUtils
  Sofa/framework/Core/src/sofa/core/ObjectFactory.h
  Sofa/framework/Helper/src/sofa/helper/StringUtils.cpp
  Sofa/framework/Helper/src/sofa/helper/StringUtils.h
  Sofa/framework/Helper/src/sofa/helper/Utils.cpp
  Sofa/framework/Helper/src/sofa/helper/Utils.h
  Sofa/framework/Helper/src/sofa/helper/config.h.in
  Sofa/framework/Helper/src/sofa/helper/system/FileSystem.cpp
  Sofa/framework/Helper/src/sofa/helper/system/PluginManager.cpp
  Sofa/framework/Helper/test/StringUtils_test.cpp
  Sofa/framework/Helper/test/Utils_test.cpp
Labels: pr: fast merge, pr: status to review, pr: clean

#4823 [Projective] FixedProjectiveConstraint: Remove draw specializations and compute bbox
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedProjectiveConstraint.h
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedProjectiveConstraint.inl
Labels: pr: status to review, pr: clean

#4824 [FEM.Elastic] Remove unused methods
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
Labels: pr: status ready, pr: clean

#4841 [CMake] Add QGLViewer2 name in FindQGLViewer.cmake
  cmake/Modules/FindQGLViewer.cmake
Labels: pr: fix, pr: fast merge, pr: status ready

#4814 [Core] Add RenamedData component for data symbol renaming
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
  Sofa/framework/Core/CMakeLists.txt
  Sofa/framework/Core/src/sofa/core/objectmodel/RenamedData.h
Labels: pr: fix, pr: status ready

#4832 [FEM.Elastic] Hexa FEM inherits from BaseLinearElasticityFEMForceField
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/BaseLinearElasticityFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/BaseLinearElasticityFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedralFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedralFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedralFEMForceFieldAndMass.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedronFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedronFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/HexahedronFEMForceField_test.cpp
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/HexahedronCompositeFEMForceFieldAndMass.inl
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/NonUniformHexahedralFEMForceFieldAndMass.inl
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/NonUniformHexahedronFEMForceFieldAndMass.inl
  applications/tutorials/compositeObject/compositeObject.cpp
Labels: pr: breaking, pr: status ready, pr: clean

#4835 [FEM.Elastic] Example of using structured binding
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/BeamFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangleFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceField.inl
Labels: pr: status ready, pr: clean

#4801 [GUI.Component] ConstraintAttachBodyPerformer: Add RigidType support
  Sofa/GUI/Component/src/sofa/gui/component/performer/ConstraintAttachBodyPerformer.cpp
  Sofa/GUI/Component/src/sofa/gui/component/performer/ConstraintAttachBodyPerformer.h
  Sofa/GUI/Component/src/sofa/gui/component/performer/ConstraintAttachBodyPerformer.inl
Labels: pr: status ready, pr: new feature

#4788 [Core] Proposition to reduce the number of alias declarations
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.h
  Sofa/framework/Core/CMakeLists.txt
  Sofa/framework/Core/src/sofa/core/Multi2Mapping.h
  Sofa/framework/Core/src/sofa/core/Multi2Mapping.inl
  Sofa/framework/Core/src/sofa/core/objectmodel/Data.h
  Sofa/framework/Core/src/sofa/core/trait/DataTypes.h
Labels: pr: status ready, pr: clean

#4822 [Sofa.GL] OglModel: Deprecate/Remove isEnabled Data
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglModel.cpp
  Sofa/GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglModel.h
Labels: pr: breaking, pr: status ready, pr: clean

#4843 [Topology.Dynamic] Fix wrong deprecation
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyContainer.h
Labels: pr: fix, pr: fast merge, pr: status ready

#4849 [CMake] Change CMake version in preset
  CMakePresets.json
Labels: pr: fast merge, pr: status to review, pr: clean

#4854 [Core] Fix string comparison in factory
  Sofa/framework/Core/src/sofa/core/ObjectFactory.h
Labels: pr: fix, pr: fast merge, pr: status to review

#4846 [Core] Remove m_cId deprecation warning spam
  Sofa/framework/Core/src/sofa/core/behavior/BaseConstraintSet.cpp
  Sofa/framework/Core/src/sofa/core/behavior/BaseConstraintSet.h
  Sofa/framework/Core/src/sofa/core/config.h.in
Labels: pr: fast merge, pr: status ready, pr: clean

#4847 [Config] Add CMake option for memory sanitizer
  Sofa/framework/Config/CMakeLists.txt
Labels: pr: fast merge, pr: status ready, pr: new feature

#4865 [Constraint.Projective] Fix internal data allocation
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedProjectiveConstraint.inl
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/LinearMovementProjectiveConstraint.inl
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PatchTestMovementProjectiveConstraint.inl
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PlaneProjectiveConstraint.inl
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PointProjectiveConstraint.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaFixedProjectiveConstraint.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaLinearMovementProjectiveConstraint.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#4866 [SofaCUDA] Apply rename of some Data
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaFixedTranslationProjectiveConstraint.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/constraint/projective/CudaLinearMovementProjectiveConstraint.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mapping/linear/CudaSubsetMapping.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/mechanicalload/CudaSphereForceField.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaHexahedronFEMForceField.h
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaHexahedronFEMForceField.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTetrahedronFEMForceField.h
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/fem/elastic/CudaTetrahedronFEMForceField.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/solidmechanics/tensormass/CudaTetrahedralTensorMassForceField.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#4864 [SofaCUDA] Simplify definition of CudaVector type
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTypes.h
Labels: pr: fast merge, pr: status ready, refactoring
