Repository sofa-framework/sofa, pull requests merged in 2024-06, with the labels that each got.

#4746 [Topology.Container] Various clean in TriangleSetGeometryAlgorithms
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.inl
Labels: pr: status ready, pr: clean

#4767 [tools] Add metis relocation in post install fixup
  tools/postinstall-fixup/common.sh
  tools/postinstall-fixup/linux-postinstall-fixup.sh
  tools/postinstall-fixup/macos-postinstall-fixup.sh
  tools/postinstall-fixup/windows-postinstall-fixup.sh
Labels: pr: fast merge, pr: status ready, pr: backport todo

#4769 [Constraints] Rename example scenes of constraints
  examples/Component/Constraint/Lagrangian/BilateralLagrangianConstraint_NNCG.scn
  examples/Component/Constraint/Lagrangian/BilateralLagrangianConstraint_PGS.scn
  examples/Component/Constraint/Lagrangian/BilateralLagrangianConstraint_Rigid.scn
  examples/Component/Constraint/Lagrangian/BilateralLagrangianConstraint_UGS.scn
  examples/Component/Constraint/Lagrangian/SlidingLagrangianConstraint.scn
  examples/Component/Constraint/Lagrangian/SlidingLagrangianConstraint.scn.view
  examples/Component/Constraint/Projective/AffineMovementProjectiveConstraint.scn
  examples/Component/Constraint/Projective/AffineMovementProjectiveConstraint3D.scn
  examples/Component/Constraint/Projective/AttachProjectiveConstraint.scn
  examples/Component/Constraint/Projective/AttachProjectiveConstraint.scn.view
  examples/Component/Constraint/Projective/AttachProjectiveConstraintMatrix.scn
  examples/Component/Constraint/Projective/DirectionProjectiveConstraint.scn
  examples/Component/Constraint/Projective/FixedPlaneProjectiveConstraint.scn
  examples/Component/Constraint/Projective/FixedRotationProjectiveConstraint.scn
  examples/Component/Constraint/Projective/HermiteSplineProjectiveConstraint.scn
  examples/Component/Constraint/Projective/LineProjectiveConstraint.scn
  examples/Component/Constraint/Projective/LinearMovementProjectiveConstraint.scn
  examples/Component/Constraint/Projective/OscillatorProjectiveConstraint.scn
  examples/Component/Constraint/Projective/OscillatorProjectiveConstraint_rigid.scn
  examples/Component/Constraint/Projective/ParabolicProjectiveConstraint.scn
  examples/Component/Constraint/Projective/ParabolicProjectiveConstraint.scn.view
  examples/Component/Constraint/Projective/PartialFixedProjectiveConstraint.scn
  examples/Component/Constraint/Projective/PlaneProjectiveConstraint.scn
  examples/Component/Constraint/Projective/PointProjectiveConstraint.scn
  examples/RegressionStateScenes.regression-tests
Labels: pr: fast merge, pr: status ready, pr: clean, pr: backport todo

#4743 [MechanicalLoad] Update TrianglePressureForceField to remove plan selection and add callback on Data pressure and triangleList
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/TrianglePressureForceField.h
  Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/TrianglePressureForceField.inl
  Sofa/Component/MechanicalLoad/tests/TrianglePressureForceField_test.cpp
  examples/Component/MechanicalLoad/TrianglePressureForceField.scn
  examples/Demos/simpleBoundaryConditions.scn
Labels: pr: fix, pr: status to review, pr: clean

#4779 [FEM.Elastic] Remove addKToMatrix override as it is duplicated from base class
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
Labels: pr: fast merge, pr: status ready, pr: clean

#4776 [Core] Deprecate Compliant API in force fields
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceMultiMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/SquareDistanceMapping.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/HexahedronFEMForceField_test.cpp
  Sofa/framework/Core/src/sofa/core/behavior/BaseForceField.cpp
  Sofa/framework/Core/src/sofa/core/behavior/BaseForceField.h
  Sofa/framework/Core/src/sofa/core/behavior/ForceField.h
  Sofa/framework/Core/src/sofa/core/behavior/ForceField.inl
  Sofa/framework/Core/src/sofa/core/config.h.in
  Sofa/framework/Simulation/Core/src/sofa/simulation/MechanicalOperations.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/MechanicalOperations.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalAddMBKdxVisitor.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalComputeDfVisitor.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalComputeForceVisitor.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalComputeForceVisitor.h
Labels: pr: breaking, pr: status ready, pr: clean, deprecated

#4785 [SofaAssump] Fix shadow variable in SceneColladaLoader
  applications/plugins/SofaAssimp/SceneColladaLoader.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#4784 [Core] Introduce category for LinearSystem
  Sofa/framework/Core/src/sofa/core/CategoryLibrary.cpp
  Sofa/framework/Core/src/sofa/core/CategoryLibrary.h
Labels: enhancement, pr: fast merge, pr: status ready

#4792 [Simulation.Core] Fix assert due to #4776
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalAddMBK_ToMatrixVisitor.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4777 [Mapping.NonLinear] Cleaning of DistanceMapping
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/LineProjectiveConstraint.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceFromTargetMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceMapping.cpp
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceMapping.h
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceMultiMapping.inl
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/NonLinearMappingData.h
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/SquareDistanceMapping.inl
  Sofa/framework/Helper/src/sofa/helper/decompose.inl
  examples/Component/Mapping/NonLinear/DistanceMapping.scn
Labels: pr: status ready, pr: clean

#4793 [GUI] initialize pointer to nullptr to avoid crash
  Sofa/GUI/Common/src/sofa/gui/common/PickHandler.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4781 [FEM.Elastic] Add test of TriangleFEMForceField
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangleFEMForceField.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangleFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/CMakeLists.txt
  Sofa/Component/SolidMechanics/FEM/Elastic/tests/TriangleFEMForceField_stepTest.cpp
  Sofa/Component/SolidMechanics/Testing/src/sofa/component/solidmechanics/testing/ForceFieldTestCreation.h
Labels: pr: status ready, pr: test

#4797 [GUI] Fix typo in comments
  Sofa/GUI/Component/src/sofa/gui/component/ConstraintAttachButtonSetting.h
Labels: pr: fast merge, pr: status ready, pr: clean
