Repository sofa-framework/sofa, pull requests merged in 2024-03, with the labels that each got.

#4555 [Visual] Fix cmake config
  Sofa/Component/Visual/Sofa.Component.VisualConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status to review

#4558 [GUI.qt] Set link to tinyxml2 to PRIVATE and fix config file
  Sofa/GUI/Qt/CMakeLists.txt
  Sofa/GUI/Qt/Sofa.GUI.QtConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status to review, pr: backport todo

#4554 [cmake] Remove error in Findcxxopt
  Sofa/framework/Config/cmake/Modules/Findcxxopts.cmake
Labels: pr: fix, pr: fast merge, pr: status ready, pr: backport todo

#4570 [Config] Fix Findmetis module when using config mode
  Sofa/framework/Config/cmake/Modules/Findmetis.cmake
Labels: pr: fix, pr: status to review, pr: backport todo

#4557 [Core] Update NarrowPhaseDetection.cpp use prefix
  Sofa/framework/Core/src/sofa/core/collision/NarrowPhaseDetection.cpp
Labels: pr: fast merge, pr: status to review, pr: clean

#4564 [Config] Fix findcxxopt when version is not specified
  Sofa/framework/Config/cmake/Modules/Findcxxopts.cmake
Labels: pr: fix, pr: fast merge, pr: status ready, pr: backport todo

#4552 [LinearSystem] Introduce ConstantSparsityProjectionMethod
  Sofa/Component/LinearSystem/CMakeLists.txt
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/ConstantSparsityProjectionMethod.cpp
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/ConstantSparsityProjectionMethod.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/ConstantSparsityProjectionMethod.inl
Labels: enhancement, pr: status ready, pr: highlighted in next release

#4590 [Core] Remove unused debug trace
  Sofa/framework/Core/src/sofa/core/objectmodel/BaseData.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#4596 [Core] cmake: Remove last traces of Sofa.Component.Compat
  CMakeLists.txt
  Sofa/framework/Core/CMakeLists.txt
  Sofa/framework/Core/Sofa.CoreConfig.cmake.in
Labels: pr: fast merge, pr: status to review, pr: clean

#4598 [LinearAlgebra] Fix compilation of assert
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/SparseMatrixProduct.inl
Labels: pr: fix, pr: fast merge, pr: status to review

#4599 [LinearAlgebra] Remove empty source file
  Sofa/framework/LinearAlgebra/CMakeLists.txt
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/SparseMatrixProduct.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#4576 [Geomagic] Update GeomagicDriver.cpp to fire error when hd.h is not found
  applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.cpp
Labels: pr: status ready, pr: clean

#4607 [tests] Use appropriate gtest macro
  Sofa/Component/Engine/Generate/tests/MergePoints_test.cpp
  Sofa/Component/SolidMechanics/Spring/tests/RestShapeSpringsForceField_test.cpp
  Sofa/Component/SolidMechanics/Spring/tests/StiffSpringForceField_test.cpp
  Sofa/Component/SolidMechanics/Testing/src/sofa/component/solidmechanics/testing/ForceFieldTestCreation.h
  Sofa/framework/Core/test/DataEngine_test.cpp
  Sofa/framework/Helper/test/system/thread/CircularQueue_test.cpp
  Sofa/framework/LinearAlgebra/test/Matrix_test.cpp
  Sofa/framework/LinearAlgebra/test/SparseMatrixStorageOrder_test.cpp
  Sofa/framework/Type/test/Quater_test.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#4619 [Multithreading] fix multithread packaging
  applications/plugins/MultiThreading/MultiThreadingConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status ready

#4591 [runsofa] Allowing multiple argv
  Sofa/GUI/Common/src/sofa/gui/common/ArgumentParser.cpp
  applications/projects/runSofa/Main.cpp
Labels: enhancement, pr: status to review

#4600 [Type] Clean and test MatSym
  Sofa/framework/Type/src/sofa/type/MatSym.h
  Sofa/framework/Type/test/CMakeLists.txt
  Sofa/framework/Type/test/MatSym_test.cpp
Labels: pr: status ready, pr: clean

#4581 [Constraint.Lagrangian.Solver] Make problemId counter id atomic
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/ConstraintSolverImpl.cpp
Labels: pr: fix, pr: status ready

#4580 [Simulation] Tests: introduce multiple parallel simulations
  Sofa/framework/Simulation/CMakeLists.txt
  Sofa/framework/Simulation/simutest/CMakeLists.txt
  Sofa/framework/Simulation/simutest/parallel_scenes_test.cpp
Labels: pr: status ready, pr: test

#4608 [plugins] Add fetchable ModelOrderReduction
  applications/plugins/CMakeLists.txt
  applications/plugins/ModelOrderReduction/ExternalProjectConfig.cmake.in
Labels: pr: status ready, pr: new feature

#4583 [Collision.Detection] Give current intersection methods as parameter to intersection functions
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BVHNarrowPhase.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BVHNarrowPhase.h
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BruteForceBroadPhase.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/MirrorIntersector.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/BaseProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/BaseProximityIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/DiscreteIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/DiscreteIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/LocalMinDistance.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/LocalMinDistance.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshDiscreteIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshDiscreteIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshDiscreteIntersection.inl
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshMinProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshMinProximityIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshNewProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshNewProximityIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MeshNewProximityIntersection.inl
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MinProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MinProximityIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/NewProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/NewProximityIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/NewProximityIntersection.inl
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/RayDiscreteIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/RayDiscreteIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/RayDiscreteIntersection.inl
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/RayNewProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/RayNewProximityIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/TetrahedronDiscreteIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/TetrahedronDiscreteIntersection.h
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/config.h.in
  Sofa/framework/Core/src/sofa/core/collision/Intersection.h
  Sofa/framework/Core/src/sofa/core/collision/Intersection.inl
  Sofa/framework/Core/src/sofa/core/collision/NarrowPhaseDetection.h
  Sofa/framework/Core/src/sofa/core/config.h.in
Labels: pr: fix, pr: status ready

#4620 [LinearSystem] Remove development artifact
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
Labels: pr: fast merge, pr: status ready, pr: clean
