Repository sofa-framework/sofa, pull requests merged in 2024-10, with the labels that each got.

#5034 [ODESolver] Rename files to match class name
  Sofa/Component/ODESolver/Forward/CMakeLists.txt
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/EulerExplicitSolver.cpp
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/EulerExplicitSolver.h
  Sofa/Component/ODESolver/Forward/src/sofa/component/odesolver/forward/EulerSolver.h
Labels: pr: fast merge, pr: status ready, refactoring, pr: clean

#5011 [LinearSolver] Apply new factory registration mechanism
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/AsyncSparseLDLSolver.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/BTDLinearSolver.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/CholeskySolver.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenSimplicialLDLT.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenSimplicialLLT.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenSparseLU.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/EigenSparseQR.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/MatrixLinearSystem[BTDMatrix].cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/PrecomputedLinearSolver.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SVDLinearSolver.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/TypedMatrixLinearSystem[BTDMatrix].cpp
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/init.cpp
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/CGLinearSolver.cpp
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/MatrixFreeSystem[GraphScattered].cpp
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/MinResLinearSolver.cpp
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/ShewchukPCGLinearSolver.cpp
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/init.cpp
  Sofa/Component/LinearSolver/Ordering/src/sofa/component/linearsolver/ordering/AMDOrderingMethod.cpp
  Sofa/Component/LinearSolver/Ordering/src/sofa/component/linearsolver/ordering/COLAMDOrderingMethod.cpp
  Sofa/Component/LinearSolver/Ordering/src/sofa/component/linearsolver/ordering/NaturalOrderingMethod.cpp
  Sofa/Component/LinearSolver/Ordering/src/sofa/component/linearsolver/ordering/init.cpp
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/BlockJacobiPreconditioner.cpp
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/JacobiPreconditioner.cpp
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/PrecomputedMatrixSystem.cpp
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/PrecomputedWarpPreconditioner.cpp
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/RotationMatrixSystem.cpp
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/SSORPreconditioner.cpp
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/WarpPreconditioner.cpp
  Sofa/Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/init.cpp
  Sofa/Component/LinearSolver/src/sofa/component/linearsolver/init.cpp
  Sofa/Component/MechanicalLoad/tests/ConstantForceField_test.cpp
  Sofa/Component/src/sofa/component/init.cpp
  Sofa/framework/Helper/src/sofa/helper/ComponentChange.cpp
  applications/plugins/MultiThreading/test/ParallelImplementationsRegistry_test.cpp
Labels: pr: status ready, pr: new feature

#5012 [Topology] Apply new factory registration mechanism
  Sofa/Component/Engine/Select/tests/MeshROI_test.cpp
  Sofa/Component/Mass/tests/DiagonalMass_test.cpp
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/CubeTopology.cpp
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/MeshTopology.cpp
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/SphereQuadTopology.cpp
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/init.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridGeometryAlgorithms.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyModifier.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetGeometryAlgorithms.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetTopologyModifier.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/HexahedronSetGeometryAlgorithms.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/HexahedronSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/HexahedronSetTopologyModifier.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/MultilevelHexahedronSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetGeometryAlgorithms.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetTopologyModifier.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/QuadSetGeometryAlgorithms.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/QuadSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/QuadSetTopologyModifier.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TetrahedronSetGeometryAlgorithms.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TetrahedronSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TetrahedronSetTopologyModifier.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetTopologyContainer.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetTopologyModifier.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/init.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/CylinderGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/GridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/RegularGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridMultipleTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridRamificationTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SphereGridTopology.cpp
  Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/init.cpp
  Sofa/Component/Topology/Container/src/sofa/component/topology/container/init.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/CenterPointTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Edge2QuadTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Hexa2QuadTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Hexa2TetraTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/IdentityTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Quad2TriangleTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/SubsetTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Tetra2TriangleTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/Triangle2EdgeTopologicalMapping.cpp
  Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/init.cpp
  Sofa/Component/Topology/Utility/src/sofa/component/topology/utility/TopologicalChangeProcessor.cpp
  Sofa/Component/Topology/Utility/src/sofa/component/topology/utility/TopologyBoundingTrasher.cpp
  Sofa/Component/Topology/Utility/src/sofa/component/topology/utility/TopologyChecker.cpp
  Sofa/Component/Topology/Utility/src/sofa/component/topology/utility/init.cpp
  Sofa/Component/Topology/src/sofa/component/topology/init.cpp
  Sofa/Component/src/sofa/component/init.cpp
  Sofa/framework/Helper/src/sofa/helper/ComponentChange.cpp
  applications/projects/SceneChecking/tests/SceneChecker_test.cpp
  examples/Component/Constraint/Lagrangian/FixedLagrangianConstaint_Vec3.scn
Labels: pr: status ready, pr: new feature

#5048 [Core.Collision] NarrowPhaseDetection: disable lighting when displaying detection outputs
  Sofa/framework/Core/src/sofa/core/collision/NarrowPhaseDetection.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#5027 [SolidMechanics] Apply new factory registration mechanism
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/BeamFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedralFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedralFEMForceFieldAndMass.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedronFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedronFEMForceFieldAndMass.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/QuadBendingFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangleFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularAnisotropicFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TriangularFEMForceFieldOptim.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/init.cpp
  Sofa/Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/StandardTetrahedralFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/TetrahedronHyperelasticityFEMForceField.cpp
  Sofa/Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/init.cpp
  Sofa/Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/material/PlasticMaterial.cpp
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/HexahedronCompositeFEMForceFieldAndMass.cpp
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/HexahedronCompositeFEMMapping.cpp
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/NonUniformHexahedralFEMForceFieldAndMass.cpp
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/NonUniformHexahedronFEMForceFieldAndMass.cpp
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/init.cpp
  Sofa/Component/SolidMechanics/FEM/src/sofa/component/solidmechanics/fem/init.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/AngularSpringForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/FastTriangularBendingSprings.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/FrameSpringForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/GearSpringForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/JointSpringForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/MeshSpringForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/PolynomialRestShapeSpringsForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/PolynomialSpringsForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/QuadBendingSprings.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/QuadularBendingSprings.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/RegularGridSpringForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/RepulsiveSpringForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/RestShapeSpringsForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/SpringForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/TriangleBendingSprings.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/TriangularBendingSprings.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/TriangularBiquadraticSpringsForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/TriangularQuadraticSpringsForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/VectorSpringForceField.cpp
  Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/init.cpp
  Sofa/Component/SolidMechanics/TensorMass/src/sofa/component/solidmechanics/tensormass/TetrahedralTensorMassForceField.cpp
  Sofa/Component/SolidMechanics/TensorMass/src/sofa/component/solidmechanics/tensormass/TriangularTensorMassForceField.cpp
  Sofa/Component/SolidMechanics/TensorMass/src/sofa/component/solidmechanics/tensormass/init.cpp
  Sofa/Component/SolidMechanics/src/sofa/component/solidmechanics/init.cpp
  Sofa/Component/src/sofa/component/init.cpp
  applications/plugins/MultiThreading/test/ParallelImplementationsRegistry_test.cpp
Labels: pr: status ready, pr: new feature

#5033 [Collision] Apply new factory registration mechanism
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BVHNarrowPhase.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BruteForceBroadPhase.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BruteForceDetection.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/CollisionPipeline.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/DirectSAP.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/DirectSAPNarrowPhase.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/IncrSAP.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/RayTraceDetection.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/RayTraceNarrowPhase.cpp
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/init.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/DiscreteIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/LocalMinDistance.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MinProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/NewProximityIntersection.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/init.cpp
  Sofa/Component/Collision/Detection/Intersection/tests/LocalMinDistance_test.cpp
  Sofa/Component/Collision/Detection/src/sofa/component/collision/detection/init.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/CubeModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/CylinderModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/LineModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/PointModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/RayModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/SphereModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TetrahedronModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleModelInRegularGrid.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleOctreeModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/init.cpp
  Sofa/Component/Collision/Geometry/tests/Sphere_test.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/CollisionResponse.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/ContactListener.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/PenalityContactForceField.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/RuleBasedContactManager.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/init.cpp
  Sofa/Component/Collision/Response/Mapper/src/sofa/component/collision/response/mapper/init.cpp
  Sofa/Component/Collision/Response/src/sofa/component/collision/response/init.cpp
  Sofa/Component/Collision/src/sofa/component/collision/init.cpp
  Sofa/Component/src/sofa/component/init.cpp
  Sofa/framework/Helper/src/sofa/helper/ComponentChange.cpp
  applications/plugins/MultiThreading/test/ParallelImplementationsRegistry_test.cpp
Labels: pr: status ready, pr: new feature

#5052 [Constraint] Apply new factory registration mechanism
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/GenericConstraintCorrection.cpp
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.cpp
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/PrecomputedConstraintCorrection.cpp
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/UncoupledConstraintCorrection.cpp
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/init.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/BilateralLagrangianConstraint.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/FixedLagrangianConstraint.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/SlidingLagrangianConstraint.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/StopperLagrangianConstraint.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/UniformLagrangianConstraint.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/UnilateralLagrangianConstraint.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/init.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/LCPConstraintSolver.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/init.cpp
  Sofa/Component/Constraint/Lagrangian/src/sofa/component/constraint/lagrangian/init.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/AffineMovementProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/AttachProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/DirectionProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedPlaneProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedRotationProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedTranslationProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/HermiteSplineProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/LineProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/LinearMovementProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/LinearVelocityProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/OscillatorProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/ParabolicProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PartialFixedProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PartialLinearMovementProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PatchTestMovementProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PlaneProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PointProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/PositionBasedDynamicsProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/SkeletalMotionProjectiveConstraint.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/init.cpp
  Sofa/Component/Constraint/src/sofa/component/constraint/init.cpp
  Sofa/Component/src/sofa/component/init.cpp
Labels: pr: status to review, pr: new feature

#5053 [Mapping] Apply new factory registration mechanism
  Sofa/Component/LinearSystem/tests/MappingGraph_test.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMappingRigid.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BeamLinearMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/CenterOfMassMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/CenterOfMassMulti2Mapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/CenterOfMassMultiMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/DeformableOnRigidFrameMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/IdentityMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/IdentityMultiMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/LineSetSkinningMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/Mesh2PointMechanicalMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/Mesh2PointTopologicalMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SimpleTesselatedHexaTopologicalMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SimpleTesselatedTetraMechanicalMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SimpleTesselatedTetraTopologicalMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SkinningMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SubsetMultiMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/TubularMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/VoidMapping.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/init.cpp
  Sofa/Component/Mapping/MappedMatrix/src/sofa/component/mapping/mappedmatrix/init.cpp
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/AreaMapping.cpp
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceFromTargetMapping.cpp
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceMapping.cpp
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/DistanceMultiMapping.cpp
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/RigidMapping.cpp
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/SquareDistanceMapping.cpp
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/SquareMapping.cpp
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/VolumeMapping.cpp
  Sofa/Component/Mapping/NonLinear/src/sofa/component/mapping/nonlinear/init.cpp
  Sofa/Component/Mapping/src/sofa/component/mapping/init.cpp
  Sofa/Component/src/sofa/component/init.cpp
  Sofa/framework/Helper/src/sofa/helper/ComponentChange.cpp
  applications/plugins/MultiThreading/test/ParallelImplementationsRegistry_test.cpp
Labels: pr: status ready, pr: new feature

#5055 [Mass] Apply new factory registration mechanism
  Sofa/Component/Engine/Transform/src/sofa/component/engine/transform/DisplacementMatrixEngine.cpp
  Sofa/Component/Engine/Transform/src/sofa/component/engine/transform/init.cpp
  Sofa/Component/Mass/src/sofa/component/mass/DiagonalMass.cpp
  Sofa/Component/Mass/src/sofa/component/mass/MeshMatrixMass.cpp
  Sofa/Component/Mass/src/sofa/component/mass/UniformMass.cpp
  Sofa/Component/Mass/src/sofa/component/mass/init.cpp
  Sofa/Component/Mass/tests/DiagonalMass_test.cpp
  Sofa/Component/Mass/tests/MeshMatrixMass_test.cpp
  Sofa/Component/Mass/tests/UniformMass_test.cpp
  Sofa/Component/MechanicalLoad/tests/ConstantForceField_test.cpp
  Sofa/Component/SceneUtility/src/sofa/component/sceneutility/InfoComponent.cpp
  Sofa/Component/SceneUtility/src/sofa/component/sceneutility/MakeAliasComponent.cpp
  Sofa/Component/SceneUtility/src/sofa/component/sceneutility/MakeDataAliasComponent.cpp
  Sofa/Component/SceneUtility/src/sofa/component/sceneutility/MessageHandlerComponent.cpp
  Sofa/Component/SceneUtility/src/sofa/component/sceneutility/init.cpp
  Sofa/Component/src/sofa/component/init.cpp
Labels: pr: status ready, pr: new feature

#5072 [examples] Run PluginFinder
  examples/Benchmark/Analysis/constantMomentum.scn
  examples/Component/Constraint/Lagrangian/FixedLagrangianConstaint_Rigid3.scn
  examples/Component/Constraint/Lagrangian/FixedLagrangianConstaint_Vec3.scn
  examples/Component/IO/Mesh/STLExporter.scn
  examples/Component/LinearSolver/FEMBAR-common.xml
  examples/Component/LinearSystem/MatrixLinearSystem.scn
  examples/Component/Mapping/NonLinear/DistanceMultiMapping.scn
  examples/Component/Mass/UniformMass.scn
  examples/Component/MechanicalLoad/EdgePressureForceField.scn
  examples/Component/MechanicalLoad/TrianglePressureForceField.scn
  examples/Component/ODESolver/Forward/RungeKutta4Solver.scn
  examples/Component/Playback/CompareState.scn
  examples/Component/Playback/ReadState.scn
  examples/Component/Playback/WriteState.scn
  examples/Demos/2d.scn
  examples/Tutorials/Basic/TutorialBasicPendulum.scn
Labels: pr: status ready, pr: clean

#5037 [LinearAlgebra] Add CompressedRowSparseMatrixConstraint tests
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrixConstraint.h
  Sofa/framework/LinearAlgebra/test/CMakeLists.txt
  Sofa/framework/LinearAlgebra/test/CompressedRowSparseMatrixConstraint_test.cpp
  Sofa/framework/LinearAlgebra/test/CompressedRowSparseMatrix_test.cpp
Labels: pr: fix, pr: status ready, pr: test
