Repository sofa-framework/sofa, pull requests merged in 2024-01, with the labels that each got.

#4389 [Constraint.Lagrangian.Solver] Fix assert in GenericConstraintSolver
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.h
Labels: pr: breaking, pr: fix, pr: status ready

#4420 [All] Fix subplugin regression tests
  applications/plugins/RegressionStateScenes.regression-tests
  examples/RegressionStateScenes.regression-tests
  examples/RegressionTopologyScenes.regression-tests
Labels: pr: fix, pr: status ready, pr: dev meeting topic

#4396 [Type] Refactor Mat
  Sofa/framework/Type/src/sofa/type/Mat.h
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/fem/elastic/ParallelTetrahedronFEMForceField.inl
Labels: pr: breaking, pr: status ready, pr: clean

#4422 [sofaInfo] Fix compilation and behavior
  applications/projects/CMakeLists.txt
  applications/projects/sofaInfo/CMakeLists.txt
  applications/projects/sofaInfo/sofaInfo.cpp
Labels: pr: fix, pr: fast merge, pr: status ready, pr: clean

#4431 [Core] Add documentation for the method BaseMapping::buildGeometricStiffnessMatrix
  Sofa/framework/Core/src/sofa/core/BaseMapping.h
Labels: pr: fast merge, pr: status ready, pr: clean

#4432 [Core] Call super init() in MultiMapping and Multi2Mapping
  Sofa/framework/Core/src/sofa/core/Multi2Mapping.inl
  Sofa/framework/Core/src/sofa/core/MultiMapping.inl
Labels: pr: fix, pr: fast merge, pr: status ready

#4436 [VolumetricRendering] Fix crashes in batch mode
  applications/plugins/VolumetricRendering/src/VolumetricRendering/OglTetrahedralModel.inl
  applications/plugins/VolumetricRendering/src/VolumetricRendering/OglVolumetricModel.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4410 [All] Rename license file into LICENSE-LGPL.md to follow github repository rules
  LICENSE-LGPL.md
Labels: pr: status ready, pr: clean

#4447 [Helper] Fix new[]/delete mismatch
  Sofa/framework/Helper/src/sofa/helper/logging/FileInfo.h
Labels: pr: fix, pr: fast merge, pr: status ready

#4453 [SofaCUDA] Initialize module from another module
  applications/plugins/SofaCUDA/CMakeLists.txt
  applications/plugins/SofaCUDA/init.cpp
  applications/plugins/SofaCUDA/init.h
Labels: pr: fast merge, pr: status ready, pr: clean

#4370 [LinearSolver.Direct] Introduce other ordering methods in SparseLDL through Eigen
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseCommon.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolverImpl.h
  Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/config.h.in
  examples/Component/LinearSolver/Direct/FEMBAR_SparseLDLSolver.scn
Labels: pr: breaking, pr: status ready, pr: new feature

#4442 [LinearAlgebra] Factorize value filtering
  Sofa/framework/DefaultType/src/sofa/defaulttype/RigidDeriv.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrixMechanical.cpp
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrixMechanical.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/matrix_bloc_traits.h
  Sofa/framework/LinearAlgebra/test/CompressedRowSparseMatrix_test.cpp
  Sofa/framework/Type/src/sofa/type/Mat.h
  Sofa/framework/Type/src/sofa/type/Vec.h
Labels: pr: status ready, refactoring, pr: clean

#4443 [StateContainer] Accelerate copy of MatrixDeriv for CRS matrices
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.inl
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrixMechanical.h
Labels: enhancement, pr: status ready

#4465 [Defaulttype, LinearAlgera] Fix warnings
  Sofa/framework/DefaultType/src/sofa/defaulttype/RigidDeriv.h
  Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/matrix_bloc_traits.h
Labels: pr: fast merge, pr: status to review, pr: clean

#4469 [All] CMake: Remove deprecation warnings
  Sofa/Component/Haptics/tests/CMakeLists.txt
  Sofa/framework/Config/cmake/Modules/FindDiffLib.cmake
  Sofa/framework/Config/cmake/Modules/FindJson.cmake
  extlibs/CMakeLists.txt
Labels: pr: fast merge, pr: status ready, pr: clean
