Repository sofa-framework/sofa, pull requests merged in 2024-02, with the labels that each got.

#4478 [SofaCUDA] Fix spatial grid compilation with double
  applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaSpatialGridContainer.inl
Labels: pr: fix, pr: fast merge, pr: status to review

#4464 [Helper] PluginManager: testing loading a plugin with a dependency on an other plugin
  Sofa/framework/Helper/test/CMakeLists.txt
  Sofa/framework/Helper/test/system/PluginManager_test.cpp
  Sofa/framework/Helper/test/system/TestPluginA/CMakeLists.txt
  Sofa/framework/Helper/test/system/TestPluginA/ComponentA.cpp
  Sofa/framework/Helper/test/system/TestPluginA/ComponentA.h
  Sofa/framework/Helper/test/system/TestPluginA/ComponentB.cpp
  Sofa/framework/Helper/test/system/TestPluginA/ComponentB.h
  Sofa/framework/Helper/test/system/TestPluginA/ComponentC.cpp
  Sofa/framework/Helper/test/system/TestPluginA/ComponentC.h
  Sofa/framework/Helper/test/system/TestPluginA/TestPluginA.h
  Sofa/framework/Helper/test/system/TestPluginA/TestPluginAConfig.cmake.in
  Sofa/framework/Helper/test/system/TestPluginA/initTestPluginA.cpp
  Sofa/framework/Helper/test/system/TestPluginB/CMakeLists.txt
  Sofa/framework/Helper/test/system/TestPluginB/TestPluginB.h
  Sofa/framework/Helper/test/system/TestPluginB/TestPluginBConfig.cmake.in
  Sofa/framework/Helper/test/system/TestPluginB/initTestPluginB.cpp
  applications/projects/runSofa/runSofa_test/runSofa_test.cpp
Labels: pr: status ready, pr: test

#4483 [all] Missing override keyword
  Sofa/Component/Collision/Detection/Intersection/tests/LocalMinDistance_test.cpp
  Sofa/Component/SolidMechanics/simutests/AffinePatch_test.cpp
  Sofa/Component/SolidMechanics/simutests/LinearElasticity_test.cpp
  Sofa/GL/src/sofa/gl/GLSLShader.cpp
  Sofa/framework/Simulation/Graph/test/Simulation_test.cpp
Labels: pr: fast merge, pr: status ready, pr: clean

#4489 [Testing] Fix installation of gtest headers
  Sofa/framework/Testing/CMakeLists.txt
Labels: pr: fix, pr: fast merge, pr: status to review

#4428 [LinearSystem] Detect changes in sparsity pattern when using ConstantSparsityPatternSystem
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/ConstantSparsityPatternSystem.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/ConstantSparsityPatternSystem.inl
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/matrixaccumulators/ConstantLocalMappedMatrix.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/matrixaccumulators/ConstantLocalMatrix.h
  Sofa/framework/Core/src/sofa/core/MatrixAccumulator.cpp
  Sofa/framework/Core/src/sofa/core/MatrixAccumulator.h
  Sofa/framework/Core/test/MatrixAccumulator_test.cpp
  examples/Component/LinearSystem/ConstantSparsityPatternSystem.scn
Labels: enhancement, pr: breaking, pr: status ready

#4316 [SofaSPHFluid] Add option in ParticleSource to add/remove random values in the particles generation. Remove noise for CI scenes
  applications/plugins/RegressionStateScenes.regression-tests
  applications/plugins/SofaSphFluid/examples/SPHParticleSink.scn
  applications/plugins/SofaSphFluid/examples/SPHParticleSource.scn
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSource.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSource.inl
Labels: pr: fix, pr: status ready

#4484 [image] Fix compilation on Windows
  applications/plugins/image/ImageFilter.h
Labels: pr: fix, pr: status ready

#4486 [Config] CMake: fix warning about upper/lowercase for Difflib
  Sofa/framework/Config/cmake/Modules/FindDiffLib.cmake
  Sofa/framework/Helper/CMakeLists.txt
Labels: pr: fast merge, pr: status ready, pr: clean

#4487 [VolumetricRendering][SofaCUDA] Move CUDA files related to VolumetricRendering
  applications/plugins/CMakeLists.txt
  applications/plugins/SofaCUDA/CMakeLists.txt
  applications/plugins/SofaCUDA/SofaCUDAConfig.cmake.in
  applications/plugins/VolumetricRendering/CMakeLists.txt
  applications/plugins/VolumetricRendering/extensions/CUDA/CMakeLists.txt
  applications/plugins/VolumetricRendering/extensions/CUDA/VolumetricRendering.CUDAConfig.cmake.in
  applications/plugins/VolumetricRendering/extensions/CUDA/src/VolumetricRendering/CUDA/CudaTetrahedralVisualModel.cpp
  applications/plugins/VolumetricRendering/extensions/CUDA/src/VolumetricRendering/CUDA/CudaTetrahedralVisualModel.h
  applications/plugins/VolumetricRendering/extensions/CUDA/src/VolumetricRendering/CUDA/CudaTetrahedralVisualModel.inl
  applications/plugins/VolumetricRendering/extensions/CUDA/src/VolumetricRendering/CUDA/config.h.in
  applications/plugins/VolumetricRendering/extensions/CUDA/src/VolumetricRendering/CUDA/init.cpp
  applications/plugins/VolumetricRendering/extensions/CUDA/src/VolumetricRendering/CUDA/init.h
Labels: pr: fast merge, pr: status ready, refactoring

#4240 [all] Replace tinyxml by external tinyxml2
  Sofa/Component/IO/Mesh/CMakeLists.txt
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshVTKLoader.cpp
  Sofa/Component/Mass/tests/UniformMass_test.cpp
  Sofa/Component/Visual/CMakeLists.txt
  Sofa/Component/Visual/Sofa.Component.VisualConfig.cmake.in
  Sofa/Component/Visual/src/sofa/component/visual/BaseCamera.cpp
  Sofa/GUI/Qt/CMakeLists.txt
  Sofa/GUI/Qt/Sofa.GUI.QtConfig.cmake.in
  Sofa/GUI/Qt/src/sofa/gui/qt/GraphVisitor.cpp
  Sofa/GUI/Qt/src/sofa/gui/qt/GraphVisitor.h
  Sofa/framework/Config/cmake/Modules/FindSOFA.cmake
  Sofa/framework/Simulation/Common/CMakeLists.txt
  Sofa/framework/Simulation/Common/Sofa.Simulation.CommonConfig.cmake.in
  Sofa/framework/Simulation/Common/src/sofa/simulation/common/xml/XML.cpp
  Sofa/framework/Simulation/Common/src/sofa/simulation/common/xml/XML.h
  applications/projects/Modeler/lib/CMakeLists.txt
  applications/projects/Modeler/lib/SofaModelerConfig.cmake.in
  applications/projects/Modeler/lib/TutorialSelector.cpp
  applications/projects/Modeler/lib/TutorialSelector.h
  applications/projects/xmlconvert-displayflags/CMakeLists.txt
  applications/projects/xmlconvert-displayflags/main.cpp
  applications/projects/xmlconvert-displayflags/xmlvisitor.cpp
  applications/projects/xmlconvert-displayflags/xmlvisitor.h
  cmake/Modules/FindTinyXML2.cmake
  examples/Component/Constraint/Lagrangian/BilateralInteractionConstraint_Rigid.scn
  examples/Component/IO/Mesh/GIDMeshLoader.scn
  extlibs/CMakeLists.txt
  extlibs/tinyxml/CMakeLists.txt
  extlibs/tinyxml/TinyXMLConfig.cmake.in
  extlibs/tinyxml/changes.txt
  extlibs/tinyxml/readme.txt
  extlibs/tinyxml/tinystr.cpp
  extlibs/tinyxml/tinystr.h
  extlibs/tinyxml/tinyxml.cpp
  extlibs/tinyxml/tinyxml.h
  extlibs/tinyxml/tinyxmlerror.cpp
  extlibs/tinyxml/tinyxmlparser.cpp
Labels: pr: breaking, pr: status to review, pr: clean, pr: status postponed, pr: backport todo

#4506 [Simulation.Common] Fix downstream project compilation with tinyXML2
  Sofa/framework/Simulation/Common/Sofa.Simulation.CommonConfig.cmake.in
Labels: pr: fast merge, pr: status to review, pr: clean, pr: backport todo

#4485 [all] Convert some loops to range-based
  Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/IncrSAP.cpp
  Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/LocalMinDistance.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleModelInRegularGrid.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleOctreeModel.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/CollisionResponse.cpp
  Sofa/Component/Collision/Response/Contact/src/sofa/component/collision/response/contact/RuleBasedContactManager.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/LCPConstraintSolver.cpp
  Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedProjectiveConstraint.cpp
  Sofa/Component/Engine/Generate/src/sofa/component/engine/generate/MeshTetraStuffing.cpp
  Sofa/Component/Engine/Select/src/sofa/component/engine/select/MeshBoundaryROI.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/GridMeshCreator.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshGmshLoader.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshOBJLoader.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshVTKLoader.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/STLExporter.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VTKExporter.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VoxelGridLoader.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/BarycentricMappingRigid.cpp
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/SimpleTesselatedTetraTopologicalMapping.cpp
  Sofa/Component/Mass/src/sofa/component/mass/UniformMass.cpp
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/EulerImplicitSolver.cpp
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/VariationalSymplecticSolver.cpp
  Sofa/Component/Playback/src/sofa/component/playback/ReadState.cpp
  Sofa/Component/Playback/src/sofa/component/playback/ReadTopology.cpp
  Sofa/Component/Playback/src/sofa/component/playback/WriteState.cpp
  Sofa/Component/Playback/src/sofa/component/playback/WriteTopology.cpp
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedralFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedralFEMForceFieldAndMass.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedronFEMForceField.inl
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/HexahedronFEMForceFieldAndMass.inl
  Sofa/Component/SolidMechanics/FEM/NonUniform/src/sofa/component/solidmechanics/fem/nonuniform/NonUniformHexahedralFEMForceFieldAndMass.inl
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.cpp
  Sofa/Component/Topology/Container/Constant/src/sofa/component/topology/container/constant/MeshTopology.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyContainer.cpp
  applications/plugins/MultiThreading/src/MultiThreading/component/solidmechanics/fem/elastic/ParallelHexahedronFEMForceField.inl
  applications/projects/runSofa/Main.cpp
Labels: pr: status ready, pr: clean

#4509 [Simulation.Core] RequiredPlugin: Avoid calling loadPlugin() twice on start-up
  Sofa/framework/Simulation/Core/src/sofa/simulation/RequiredPlugin.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#4507 [All] Display reference name when pulling external plugins
  Sofa/framework/Config/cmake/SofaMacrosConfigure.cmake
Labels: enhancement, pr: fast merge, pr: status ready

#4490 [LinearSystem] Introduce components to map matrices
  Sofa/Component/LinearSystem/CMakeLists.txt
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/BaseMatrixProjectionMethod.cpp
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/BaseMatrixProjectionMethod.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/BaseMatrixProjectionMethod.inl
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixMapping.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixProjectionMethod.cpp
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixProjectionMethod.h
  Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixProjectionMethod.inl
  examples/Component/LinearSystem/MatrixLinearSystem.scn
Labels: enhancement, pr: status ready, pr: highlighted in next release

#4494 [Topology] Fix method isQuadDeulaunayOriented and its use in splitAlongPath
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Utility/tests/TopologicalChangeProcessor_test.cpp
  examples/Component/Topology/Container/Dynamic/IncisionTrianglesProcess.txt
Labels: pr: fix, pr: status ready

#4517 [image] Fix scene test
  applications/plugins/image/examples/ImageTransform.scn
Labels: pr: fast merge, pr: status ready, pr: clean

#4521 [Share] Remove DefaultCollisionGroupManager in the default scenes
  share/config/default/newScene.scn
  share/config/newScene.scn
Labels: pr: fix, pr: fast merge, pr: status ready

#4525 [Simulation.Common] Fix tinyXML2 install for windows
  Sofa/framework/Simulation/Common/CMakeLists.txt
Labels: pr: fix, pr: fast merge, pr: status to review, pr: backport todo

#4526 [SofaSphFluid] Externalize SofaSphFluid
  applications/plugins/CMakeLists.txt
  applications/plugins/RegressionStateScenes.regression-tests
  applications/plugins/SofaSphFluid/CMakeLists.txt
  applications/plugins/SofaSphFluid/ExternalProjectConfig.cmake.in
  applications/plugins/SofaSphFluid/README.md
  applications/plugins/SofaSphFluid/SofaSphFluidConfig.cmake.in
  applications/plugins/SofaSphFluid/examples/.scene-tests
  applications/plugins/SofaSphFluid/examples/OglFluidModel_SPH.scn
  applications/plugins/SofaSphFluid/examples/OglFluidModel_SPH.scn.view
  applications/plugins/SofaSphFluid/examples/OglFluidModel_SPHParticles.scn
  applications/plugins/SofaSphFluid/examples/ParticleSink.scn
  applications/plugins/SofaSphFluid/examples/ParticleSource.scn
  applications/plugins/SofaSphFluid/examples/ParticlesRepulsionForceField.scn
  applications/plugins/SofaSphFluid/examples/ParticlesRepulsionForceField.scn.view
  applications/plugins/SofaSphFluid/examples/PointSplatModel.scn
  applications/plugins/SofaSphFluid/examples/PointSplatModel.scn.view
  applications/plugins/SofaSphFluid/examples/SPHDemo.scn
  applications/plugins/SofaSphFluid/examples/SPHFluidForceField.scn
  applications/plugins/SofaSphFluid/examples/SPHFluidForceField.scn.view
  applications/plugins/SofaSphFluid/examples/SPHFluidForceField_benchmarks.scn
  applications/plugins/SofaSphFluid/examples/SPHFluidSurfaceMapping.scn
  applications/plugins/SofaSphFluid/examples/SPHParticleSink.scn
  applications/plugins/SofaSphFluid/examples/SPHParticleSink_obstacle.scn
  applications/plugins/SofaSphFluid/examples/SPHParticleSource.scn
  applications/plugins/SofaSphFluid/examples/SpatialGridContainer.scn
  applications/plugins/SofaSphFluid/examples/SpatialGridPointModel.scn
  applications/plugins/SofaSphFluid/examples/SpatialGridPointModel.scn.view
  applications/plugins/SofaSphFluid/src/SofaSphFluid/OglFluidModel.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/OglFluidModel.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/OglFluidModel.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSink.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSink.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSink.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSource.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSource.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticleSource.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticlesRepulsionForceField.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticlesRepulsionForceField.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/ParticlesRepulsionForceField.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidForceField.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidForceField.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidForceField.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidSurfaceMapping.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidSurfaceMapping.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHFluidSurfaceMapping.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SPHKernel.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SpatialGridContainer.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SpatialGridContainer.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SpatialGridContainer.inl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SpatialGridPointModel.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/SpatialGridPointModel.h
  applications/plugins/SofaSphFluid/src/SofaSphFluid/config.h.in
  applications/plugins/SofaSphFluid/src/SofaSphFluid/initSPHFluid.cpp
  applications/plugins/SofaSphFluid/src/SofaSphFluid/shaders/pointToSprite.cppglsl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/shaders/spriteBlurDepth.cppglsl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/shaders/spriteBlurThickness.cppglsl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/shaders/spriteBlurThickness.glsl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/shaders/spriteFinalPass.cppglsl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/shaders/spriteShade.cppglsl
  applications/plugins/SofaSphFluid/src/SofaSphFluid/shaders/spriteToSpriteNormal.cppglsl
Labels: enhancement, pr: status ready, pr: highlighted in next release

#4538 [Config] Add cxxopts cmake find module
  Sofa/GUI/Common/CMakeLists.txt
  Sofa/framework/Config/cmake/Modules/Findcxxopts.cmake
Labels: pr: fix, pr: fast merge, pr: status ready, pr: backport todo

#4534 [Config] Add TSAN option
  Sofa/framework/Config/CMakeLists.txt
Labels: pr: status ready, pr: new feature

#4542 [Sofa.Testing] Add SimpleApi in Config.cmake.in
  Sofa/framework/Testing/Sofa.TestingConfig.cmake.in
Labels: pr: fix, pr: fast merge, pr: status to review

#4545 [all] Install FindTinyXML2
  CMakeLists.txt
Labels: pr: fast merge, pr: status ready, pr: backport todo
