Repository sofa-framework/sofa, pull requests merged in 2025-07, with the labels that each got.

#5576 [Core,StateContainer] Remove unused aliases
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.h
  Sofa/framework/Core/src/sofa/core/State.h
  Sofa/framework/Core/src/sofa/core/behavior/MechanicalState.h
Labels: pr: breaking, pr: status ready, pr: clean

#5222 [tools] generate stubfiles during packaging
  CMakeLists.txt
  tools/postinstall-fixup/generate-stubfiles.cmake
  tools/postinstall-fixup/generate-stubfiles.sh
  tools/postinstall-fixup/linux-postinstall-fixup.sh
  tools/postinstall-fixup/macos-postinstall-fixup.sh
Labels: enhancement, pr: status ready

#5621 [All] Fix last use of Sofa.GUI.Qt
  applications/plugins/SofaCUDA/SofaCUDAConfig.cmake.in
  applications/plugins/SofaMatrix/extensions/Qt/CMakeLists.txt
  applications/plugins/SofaMatrix/extensions/Qt/SofaMatrix.QtConfig.cmake.in
  applications/plugins/image/CMakeLists.txt
  applications/plugins/image/imageConfig.cmake.in
  applications/plugins/image/image_gui/CMakeLists.txt
  applications/plugins/image/image_gui/image_guiConfig.cmake.in
  cmake/Modules/FindQGLViewer.cmake
  tools/postinstall-fixup/CMakeLists.txt
Labels: pr: fix, pr: fast merge, pr: status ready, pr: backport todo

#5622 [Helper] Add path to icons to fix release error not finding icons
  Sofa/framework/Helper/src/sofa/helper/system/FileRepository.cpp
Labels: pr: status ready, pr: backport todo, pr: project-ci-infrastructure
