Repository sofa-framework/sofa, pull requests merged in 2025-03, with the labels that each got.

#5299 [Lagrangian] Add regularization term in lagrangian constraints
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/GenericConstraintCorrection.cpp
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/GenericConstraintCorrection.h
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.h
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.inl
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/PrecomputedConstraintCorrection.h
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/PrecomputedConstraintCorrection.inl
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.h
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/LCPConstraintSolver.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/LCPConstraintSolver.h
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/MatrixLinearSolver.h
  Sofa/Component/LinearSolver/Iterative/src/sofa/component/linearsolver/iterative/MatrixLinearSolver.inl
  Sofa/framework/Core/src/sofa/core/behavior/LinearSolver.h
  examples/Component/Constraint/Lagrangian/BilateralLagrangianConstraint_with_regularization_solvable.scn
  examples/Component/Constraint/Lagrangian/BilateralLagrangianConstraint_with_regularization_unsolvable.scn
Labels: pr: status ready, pr: new feature, pr: highlighted in next release

#5272 [CMake] Modify presets to generalize its use
  CMakeLists.txt
  CMakePresets.json
  Sofa/CMakeLists.txt
  Sofa/framework/Config/CMakeLists.txt
  applications/plugins/CMakeLists.txt
  applications/projects/CMakeLists.txt
Labels: enhancement, pr: status to review, pr: highlighted in next release

#5260 [Topology.dynamic] Add new method computeSegmentTriangulationIntersections in TriangleSetGeometryAlgorithm to replace old versions
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.inl
  Sofa/Component/Topology/Container/Dynamic/tests/TriangleSetTopology_test.cpp
Labels: pr: status ready, pr: new feature

#5296 [Topology.container] Remove TopologyAlgorithms compatibility headers and some disabled methods
  Sofa/Component/Topology/Container/Dynamic/CMakeLists.txt
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/EdgeSetTopologyAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/HexahedronSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/HexahedronSetTopologyAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointSetTopologyAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/QuadSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/QuadSetTopologyAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TetrahedronSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TetrahedronSetTopologyAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.cpp
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetTopologyAlgorithms.h
  Sofa/framework/Helper/src/sofa/helper/ComponentChange.cpp
Labels: pr: status ready, pr: clean

#5319 [examples] Fix F letter collision in SofaScene
  examples/Demos/SofaScene.scn
Labels: pr: fast merge, pr: status ready

#5322 [Mapping] Fix assertion error in debug
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/DistanceToPlaneMapping.inl
Labels: pr: fix, pr: fast merge, pr: status to review

#5323 [Nix] Fix Nix CI
  flake.lock
  flake.nix
  package.nix
Labels: pr: fix, pr: fast merge, pr: status ready

#5333 [all] Copy Data description as comments
  Sofa/Component/Engine/Select/src/sofa/component/engine/select/NearestPointROI.h
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/DistanceToPlaneMapping.h
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/EulerImplicitSolver.h
  Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.h
Labels: pr: fast merge, pr: status ready, pr: clean

#5318 [Haptics.tests] Fix LCPForceFeedback blinking tests on ci
  Sofa/Component/Haptics/tests/LCPForceFeedback_test.cpp
Labels: pr: status ready, pr: test

#5342 [Type] Add tests on Vec default constructor
  Sofa/framework/Type/test/VecTypes_test.cpp
Labels: pr: fast merge, pr: status ready, pr: test

#5321 [IO.Mesh.VTKExporter] Inherit from BaseSimulationExporter
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VTKExporter.cpp
  Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VTKExporter.h
  examples/Component/IO/Mesh/VTKExporter.scn
Labels: pr: status ready, pr: clean

#5324 [examples] Propose a new default scene
  applications/projects/runSofa/Main.cpp
  examples/Demos/fallingSOFA.scn
  examples/Demos/fallingSOFA.scn.view
  examples/RegressionStateScenes.regression-tests
Labels: pr: fast merge, pr: status ready, pr: new feature, pr: highlighted in next release, topic for next dev-meeting

#5325 [All] Spring cleaning 1: clean main & tools directories
  CMakeLists.txt
  config.sh
  custom.cmake.example
  package.cmake
  tools/astyle/sofa.astyle
  tools/sofa-launcher/README.md
  tools/sofa-launcher/example.json
  tools/sofa-launcher/example.py
  tools/sofa-launcher/example.scn
  tools/sofa-launcher/integration_example.py
  tools/sofa-launcher/launcher.py
  tools/sofa-launcher/results.html
  tools/sofa-launcher/results.thtml
  tools/sofa-launcher/sofa-launcher.py
  tools/stylechecker/CMakeLists.txt
  tools/stylechecker/README
  tools/stylechecker/fileutils.cpp
  tools/stylechecker/fileutils.h
  tools/stylechecker/myclass.h
  tools/stylechecker/stylecheck.cpp
  tools/stylechecker/stylecheck.files
  tools/stylechecker/stylechecker.config
  tools/stylechecker/stylechecker.creator
  tools/stylechecker/stylechecker.files
  tools/stylechecker/stylechecker.includes
  tools/stylechecker/test1.cpp
  tools/stylechecker/test1.h
  tools/stylechecker/utilsllvm.cpp
  tools/stylechecker/utilsllvm.h
  tools/tips.txt
Labels: pr: breaking, pr: status ready, pr: clean

#5349 [CMake] Remove compatibility layer in macro
  Sofa/framework/Config/cmake/SofaMacrosInstall.cmake
Labels: pr: status ready, pr: clean

#5363 [CMake] Fix install process with default option SOFA_INSTALL_RESOURCES_FILES
  CMakeLists.txt
Labels: pr: fix, pr: fast merge, pr: status ready

#5361 [CMake] Remove references to deleted projects/option
  CMakeLists.txt
  CMakePresets.json
  applications/projects/CMakeLists.txt
Labels: pr: fast merge, pr: status to review, pr: clean

#5369 [All] Fix warnings
  Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/DistanceToPlaneMapping.inl
  Sofa/Component/Mapping/MappedMatrix/src/sofa/component/mapping/mappedmatrix/init.cpp
  Sofa/Component/StateContainer/src/sofa/component/statecontainer/MechanicalObject.inl
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/PointModifiers.h
  Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSubdividers.h
  Sofa/framework/Testing/src/sofa/testing/BaseTest.cpp
  Sofa/framework/Testing/src/sofa/testing/BaseTest.h
Labels: pr: fast merge, pr: status ready, pr: clean

#5362 [Examples] Add an option to (not) build SimpleAPI examples
  CMakeLists.txt
  CMakePresets.json
  examples/SimpleAPI/CMakeLists.txt
Labels: pr: fast merge, pr: status ready, pr: clean
