Repository sofa-framework/sofa, pull requests merged in 2025-04, with the labels that each got.

#5332 [CMake] Fetch in build dir instead of source to avoid lots of cmake errors
  Sofa/framework/Config/cmake/SofaMacrosConfigure.cmake
  applications/plugins/BeamAdapter/ExternalProjectConfig.cmake.in
  applications/plugins/CGALPlugin/ExternalProjectConfig.cmake.in
  applications/plugins/CMakeLists.txt
  applications/plugins/CSparseSolvers/ExternalProjectConfig.cmake.in
  applications/plugins/CollisionAlgorithm/ExternalProjectConfig.cmake.in
  applications/plugins/ConstraintGeometry/ExternalProjectConfig.cmake.in
  applications/plugins/Cosserat/ExternalProjectConfig.cmake.in
  applications/plugins/ManifoldTopologies/ExternalProjectConfig.cmake.in
  applications/plugins/MeshSTEPLoader/ExternalProjectConfig.cmake.in
  applications/plugins/ModelOrderReduction/ExternalProjectConfig.cmake.in
  applications/plugins/PSL/ExternalProjectConfig.cmake.in
  applications/plugins/PluginExample/ExternalPluginExample.md
  applications/plugins/PluginExample/ExternalProjectConfig.cmake.in
  applications/plugins/Registration/ExternalProjectConfig.cmake.in
  applications/plugins/RegressionStateScenes.regression-tests
  applications/plugins/STLIB/ExternalProjectConfig.cmake.in
  applications/plugins/ShapeMatchingPlugin/ExternalProjectConfig.cmake.in
  applications/plugins/Sofa.Metis/ExternalProjectConfig.cmake.in
  applications/plugins/SofaHighOrder/ExternalProjectConfig.cmake.in
  applications/plugins/SofaPython3/ExternalProjectConfig.cmake.in
  applications/plugins/SofaSphFluid/ExternalProjectConfig.cmake.in
  applications/plugins/SofaValidation/ExternalProjectConfig.cmake.in
  applications/plugins/SoftRobots/ExternalProjectConfig.cmake.in
  applications/projects/CMakeLists.txt
  applications/projects/Regression/ExternalProjectConfig.cmake.in
  applications/projects/Sofa.Qt/ExternalProjectConfig.cmake.in
  applications/projects/SofaGLFW/ExternalProjectConfig.cmake.in
  examples/RegressionStateScenes.regression-tests
  examples/RegressionTopologyScenes.regression-tests
Labels: enhancement, pr: breaking, pr: status ready

#5376 [ODESolver.Backward] BDFOdeSolver: Fix assertions
  Sofa/Component/ODESolver/Backward/src/sofa/component/odesolver/backward/BDFOdeSolver.cpp
Labels: pr: fix, pr: fast merge, pr: status to review

#5388 [Defaulttype, Helper] Return empty string instead of zero
  Sofa/framework/DefaultType/src/sofa/defaulttype/typeinfo/NoTypeInfo.h
  Sofa/framework/Helper/src/sofa/helper/AdvancedTimer.cpp
Labels: pr: fix, pr: fast merge, pr: status ready

#5401 [CI] Nix: Fix CI
  package.nix
Labels: pr: fix, pr: fast merge, pr: status to review

#5419 [SofaImplicitField] A bit of cleaning in the plugin
  applications/plugins/CMakeLists.txt
  applications/plugins/SofaImplicitField/CMakeLists.txt
  applications/plugins/SofaImplicitField/examples/README.md
  applications/plugins/SofaImplicitField/initSofaImplicitField.cpp
Labels: pr: status ready, pr: clean
