Repository sofa-framework/sofa, pull requests merged in 2025-05, with the labels that each got.

#5423 [Core] Rename BaseConstraint to BaseLagrangianConstraint
  Sofa/Component/AnimationLoop/src/sofa/component/animationloop/ConstraintAnimationLoop.cpp
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/BaseContactLagrangianConstraint.h
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/BilateralConstraintResolution.h
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/BilateralLagrangianConstraint.h
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/GenericConstraintSolver.h
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/LCPConstraintSolver.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/LCPConstraintSolver.h
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/visitors/ConstraintStoreLambdaVisitor.cpp
  Sofa/Component/Constraint/Lagrangian/Solver/src/sofa/component/constraint/lagrangian/solver/visitors/MechanicalGetConstraintResolutionVisitor.cpp
  Sofa/framework/Core/CMakeLists.txt
  Sofa/framework/Core/src/sofa/core/behavior/BaseConstraint.h
  Sofa/framework/Core/src/sofa/core/behavior/BaseInteractionConstraint.h
  Sofa/framework/Core/src/sofa/core/behavior/BaseLagrangianConstraint.cpp
  Sofa/framework/Core/src/sofa/core/behavior/BaseLagrangianConstraint.h
  Sofa/framework/Core/src/sofa/core/behavior/Constraint.h
  Sofa/framework/Core/src/sofa/core/behavior/Mass.inl
  Sofa/framework/Core/src/sofa/core/behavior/fwd.h
  Sofa/framework/Core/src/sofa/core/config.h.in
  Sofa/framework/Core/src/sofa/core/fwd.cpp
  Sofa/framework/Core/src/sofa/core/fwd.h
  Sofa/framework/Core/src/sofa/core/objectmodel/Base.h
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalGetConstraintInfoVisitor.cpp
  Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalGetConstraintInfoVisitor.h
Labels: pr: breaking, pr: status ready, refactoring

#5411 [SofaDistanceGrid] New scenes and regression tests for the plugin
  applications/plugins/RegressionStateScenes.regression-tests
  applications/plugins/SofaDistanceGrid/CMakeLists.txt
  applications/plugins/SofaDistanceGrid/examples/DistanceGridForceField_liver.scn
  applications/plugins/SofaDistanceGrid/examples/FFDDistanceGridCollisionModel_liver_DefaultAnimationLoop.scn
  applications/plugins/SofaDistanceGrid/examples/FFDDistanceGridCollisionModel_liver_FreeMotionAnimationLoop.scn
  applications/plugins/SofaDistanceGrid/examples/RigidDistanceGridCollisionModel_liver_DefaultAnimationLoop.scn
  applications/plugins/SofaDistanceGrid/examples/RigidDistanceGridCollisionModel_liver_FreeMotionAnimationLoop.scn
Labels: pr: status to review, pr: clean

#5425 [SOFADistanceGrid] Replace pointer to the mstate with a link in the collision models of the plugin
  applications/plugins/SofaDistanceGrid/examples/FFDDistanceGridCollisionModel_liver_DefaultAnimationLoop.scn
  applications/plugins/SofaDistanceGrid/examples/FFDDistanceGridCollisionModel_liver_FreeMotionAnimationLoop.scn
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/DistanceGridCollisionModel.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/DistanceGridCollisionModel.h
Labels: pr: status ready, pr: clean

#5499 [Core] Replace raw pointer by SingleStateAccessor
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.inl
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/PrecomputedConstraintCorrection.inl
  Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/UncoupledConstraintCorrection.inl
  Sofa/framework/Core/src/sofa/core/behavior/ConstraintCorrection.h
  Sofa/framework/Core/src/sofa/core/behavior/ConstraintCorrection.inl
Labels: pr: breaking, pr: status ready, pr: clean

#5490 [Core] Apply template method design pattern to CollisionModel::draw
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/CubeModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/CubeModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/CylinderModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/CylinderModel.inl
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/LineModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/LineModel.inl
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/PointModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/PointModel.inl
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/RayModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/RayModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/SphereModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/SphereModel.inl
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TetrahedronModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TetrahedronModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleModel.h
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleModel.inl
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleOctreeModel.cpp
  Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleOctreeModel.h
  Sofa/framework/Core/src/sofa/core/CollisionModel.cpp
  Sofa/framework/Core/src/sofa/core/CollisionModel.h
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/geometry/CapsuleModel.h
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/geometry/CapsuleModel.inl
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/geometry/OBBModel.h
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/geometry/OBBModel.inl
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/geometry/RigidCapsuleModel.h
  applications/plugins/CollisionOBBCapsule/src/CollisionOBBCapsule/geometry/RigidCapsuleModel.inl
  applications/plugins/SofaCUDA/src/SofaCUDA/component/collision/geometry/CudaPointModel.cpp
  applications/plugins/SofaCUDA/src/SofaCUDA/component/collision/geometry/CudaPointModel.h
  applications/plugins/SofaDistanceGrid/extensions/CUDA/src/SofaDistanceGrid/CUDA/CudaDistanceGridCollisionModel.cpp
  applications/plugins/SofaDistanceGrid/extensions/CUDA/src/SofaDistanceGrid/CUDA/CudaDistanceGridCollisionModel.h
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/DistanceGridCollisionModel.cpp
  applications/plugins/SofaDistanceGrid/src/SofaDistanceGrid/components/collision/DistanceGridCollisionModel.h
Labels: enhancement, pr: breaking, pr: status ready, pr: clean

#5507 [Lagrangian.Model] Redundant reading of free position
  Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/FixedLagrangianConstraint.inl
Labels: pr: fast merge, pr: status ready, pr: clean
